### ISSUE TITLE
Please allow Osara to interact with the master track

### ISSUE THREAD

**Issue by marioloreti** [jcsteh/osara#1]
It will be cool if Osara could interact with the master track as Rea Access does. Specifically Rea Access allows to insert fx and it can provide access to the master track related parameters by pressing shift+tab.

**Comment by jcsteh** [comment]
Sadly, REAPER won't actually let you focus the master track in the normal way tracks get focus.

From what I recall, ReaAccess has a separate action for viewing fx parameters on the master track; i.e. it isn't the same command you use for fx parameters on normal tracks. Is that correct? I'll probably have to do the same in OSARA.

Regarding shift+tab, I assume that too is different to accessing parameters on normal tracks? Or is there some ReaAccess specific way of "focusing" the master track?

**Comment by marioloreti** [comment]
Hi,

with Rea Access I focus the master track with shift+tab and I am  on the 
volume parameter. with shift+tab again I can explore all the other 
parameters.

About FX, yes, I can add these with a separated action, assigned to shift+f.
Il 05/02/2015 13:44, jcsteh ha scritto:
>
> Sadly, REAPER won't actually let you focus the master track in the 
> normal way tracks get focus.
>
> From what I recall, ReaAccess has a separate action for viewing fx 
> parameters on the master track; i.e. it isn't the same command you use 
> for fx parameters on normal tracks. Is that correct? I'll probably 
> have to do the same in OSARA.
>
> Regarding shift+tab, I assume that too is different to accessing 
> parameters on normal tracks? Or is there some ReaAccess specific way 
> of "focusing" the master track?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jcsteh/osara/issues/1#issuecomment-73040247>.
>

-- 
Mario Loreti

Iscriviti a Dropbox, il servizio per condividere i tuoi file gratis con uno spazio pari a 3500mb. Clicca:
http://db.tt/W6C56gy

**Comment by marioloreti** [comment]
Hi,
I wanted to let you know that it is already possible to add an fx to the 
master track using the action called view fx chain for master track. 
What rea-access did is the possibility to adjust the parameters for 
those fx, the same way it can be done for the current track. The key 
rea-access assigned to that action is CtrlShiftP and the action is 
called "parameter plugin for master track". The tab thing that we have 
on rea-access is a virtual mode that allows us to control volume, pan, 
and it can be useful when checking where things are, for example, when 
we normalize one item we can check at what volume it gets. In 
rea-access, the tab key lets you control the current track whereas 
shiftTab let you access the master track.
Il 05/02/2015 14:01, Mario Loreti ha scritto:
> Hi,
>
> with Rea Access I focus the master track with shift+tab and I am on 
> the volume parameter. with shift+tab again I can explore all the other 
> parameters.
>
> About FX, yes, I can add these with a separated action, assigned to 
> shift+f.
> Il 05/02/2015 13:44, jcsteh ha scritto:
>>
>> Sadly, REAPER won't actually let you focus the master track in the 
>> normal way tracks get focus.
>>
>> From what I recall, ReaAccess has a separate action for viewing fx 
>> parameters on the master track; i.e. it isn't the same command you 
>> use for fx parameters on normal tracks. Is that correct? I'll 
>> probably have to do the same in OSARA.
>>
>> Regarding shift+tab, I assume that too is different to accessing 
>> parameters on normal tracks? Or is there some ReaAccess specific way 
>> of "focusing" the master track?
>>
>> —
>> Reply to this email directly or view it on GitHub 
>> <https://github.com/jcsteh/osara/issues/1#issuecomment-73040247>.
>>
>
> -- 
> Mario Loreti
>
> Iscriviti a Dropbox, il servizio per condividere i tuoi file gratis con uno spazio pari a 3500mb. Clicca:
> http://db.tt/W6C56gy

-- 
Mario Loreti

Iscriviti a Dropbox, il servizio per condividere i tuoi file gratis con uno spazio pari a 3500mb. Clicca:
http://db.tt/W6C56gy

**Comment by jcsteh** [comment]
I've just added the ability to view the I/O dialog for the master track. Does this solve this issue?

Virtual parameter navigation (i.e. tab/shift+tab in ReaAccess) is a request that should be addressed separately, but I think you should be able to do most of what you need with what is now implemented.

**Comment by marioloreti** [comment]
tried, it works!

Thanks.
Il 09/02/2015 20:35, jcsteh ha scritto:
>
> I've just added the ability to view the I/O dialog for the master 
> track. Does this solve this issue?
>
> Virtual parameter navigation (i.e. tab/shift+tab in ReaAccess) is a 
> request that should be addressed separately, but I think you should be 
> able to do most of what you need with what is now implemented.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jcsteh/osara/issues/1#issuecomment-73574361>.
>

-- 
Mario Loreti

Iscriviti a Dropbox, il servizio per condividere i tuoi file gratis con uno spazio pari a 3500mb. Clicca:
http://db.tt/W6C56gy

**Comment by jcsteh** [comment]
I found a way to actually focus the master track for real. I'd like to get rid of OSARA's master track specific actions. Instead, the user would focus the master track and then use the same actions as for normal tracks.

The question is: what should the user experience for navigating to the master track be? We could either:

1. Have the user press up arrow from track 1 to get to it; or
2. Have a separate action to focus the master track.

With either approach, note that down arrow would always take you to track 1, since the master track is always before all other tracks. I can't really override this without major hackery. Personally, I think I'd prefer option 1.

Thoughts? cc @GianlucaApollaro @ScottChesworth @dgl1984 @cmdfv

**Comment by dgl1984** [comment]
As things stand now, we can adjust hardware outputs, volume, pan, and 
the width of the stereo image.
We would lose some of these abilities by limiting to volume and pan 
adjustments by removing the focus.

**Comment by dgl1984** [comment]
I also thought of another problem.
As it stands, one can look at levels on the currently touched track, and 
the master at the same time.  However, if ony 1 track can be 
manipulated/focused etc. that wouldn't be possible.

**Comment by jcsteh** [comment]
I don't see how we lose anything. There'd need to be an action to open 
the I/O dialog for the current track, which would include the master.

I guess we could keep the separate action to open the I/O dialog for the 
master. I'm also happy to keep feedback for any master specific actions.

The advantage of this approach is that it makes things more consistent 
for the user and doesn't require heaps of duplicate actions. While I 
understand the desire to have immediate access to, say, volume and pan 
for the master, it seems redundant to have separate actions for the FX 
Parameters dialog, virtual navigation, etc. Those aren't simply quick 
checks.

**Comment by ScottChesworth** [comment]
I vote for option 1. Most consistent with a sighted users ux and good consistency across platforms. Would like to keep a specific separate action to examine meters on the master without touching that track though if possible.

**Comment by marioloreti** [comment]
Option 1 for me!

Inviato da iPhone

**Comment by GianlucaApollaro** [comment]
Hi,
What would happen if the master track is not visible? My guess is we 
can't focus it either. Then, another comment. If I have to lose the 
ability to instantly get to the fx parameter for the master, I'd rather 
go for option two
This is my opinion
Il 07/04/2015 07:51, marioloreti ha scritto:

**Comment by jcsteh** [comment]
You can't focus the master if it isn't visible, but I can easily make it 
visible before focusing.

What makes FX parameters on the master more special than FX parameters 
on any other track? I understand why volume, pan and meters are special 
for the master, but can't think of a use case for FX parameters on the 
master. You obviously have one in mind; I'd just like to understand it.

**Comment by dgl1984** [comment]
It is useful with effects though.

Some times, adding a master effect changes a mix to the point of then needing to change another effect.
Having a separate action for master effects can let me quickly go between the 2, quickly changing parameters until the interaction is to my liking.

  ----- Original Message -----

**Comment by GianlucaApollaro** [comment]
Well, if you have a submix of things, and you're controlling how the EQ 
you've applied on the master is affecting it. Or, sometines some master 
effects make a reverb more obvious and I may want to turn it down, and 
now it's easily done by going between track and master effects
Il 07/04/2015 11:26, jcsteh ha scritto:

**Comment by jcsteh** [comment]
Fair enough. I'll leave that action. I guess that defeats the point of making master focusable. This still leaves us with a steep learning curve, though, which kinda sucks.

**Comment by dgl1984** [comment]
So would a keyboard training mode, but that has nothing to do with this issue. 


  ----- Original Message -----

**Comment by jcsteh** [comment]
As I've noted before, a keyboard training mode does not make an 
intuitive interface. It just gives users the ability to monkey push 
there way around until they happen to stumble on something useful, 
which, while admittedly helpful sometimes, is a very poor excuse for an 
intuitive UX.

On further reflection, perhaps there's merit in having both focus and 
separate actions. That means there are multiple ways to do things, but 
it also allows users to graduate to more efficient actions as required. 
5000 ways to do a single task does tend to be REAPER's philosophy, so 
who are we to buck the trend? :)

**Comment by chrisbelle2015** [comment]
A keyboard training mode still allows one to quickly check if you are 
using the right key combo for an action you don't do all the time.

Clunky or not, they are popular.

Put that request on the would like but not the most important thing, 
actual functionallity is more important, but if a keyboard training mode 
comes at some point, wouldn't hurt my feelings at all.

**Comment by cmdfv** [comment]
Think we all decided that while a keyboard help mode isn't sighted
congruent, I agree here with Chris. Having a mode to go into to double
check something I don't use all the time is a lot faster than opening
up the manual and hunting through it. I don't have to leave Reaper to
hit 1 key and then start jamming key commands, then toggle help mode
off again. We can argue until 2340 and this won't ever change.

I dig option one for the master track, but with master track actions.
Keeps things open to do things in whatever way the user wants. They
can always focus master by hitting upArrow to get there, and do track
actions if they so desire and feel that it's more appropriate. The
other guys can be on track 17 and hit ctrl+shift+P for master track
effects and be happy.

**Comment by ScottChesworth** [comment]
Chaps, this isn't the place to debate the keyboard training mode. Jamie has already agreed to implement the feature once the project is actually compensating for development time. A solid bid for funding has been placed, and the feature was on the roadmap that was submitted as part of that bid. Moreover, there's a separate GitHub issue for the feature, so if you have something to say (beyond wanting something that's already been agreed to), that'd be the place to talk about it. Cheers.

**Comment by jcsteh** [comment]
It's already been decided that there'll eventually be a training mode. That's covered in a separate issue. My only point in response to Derek is that having a training mode does not magically mean having thousands of actions suddenly becomes intuitive.
