### ISSUE TITLE
bug in "Toggle record arming for current (last touched) track"

### ISSUE THREAD

**Issue by dgl1984** [jcsteh/osara#10]
the armed state of the currently touched track is not reported when it's changed.  The armed status of a track can be ascertained by going through a track list, but the lack of verbal feedback could lend itself to accidents on the part of the user.

**Comment by jcsteh** [comment]
Are you definitely using the exact action "Toggle record arming for current (last touched) track"? For some weird reason, REAPER has quite a few track arm actions and the others don't notify via the API correctly. I hear "armed" or "unarmed" if I use the correct action.

**Comment by dgl1984** [comment]
That did it.
I'll update the keymap, and have it sent to the list.


to
