### ISSUE TITLE
Can we include channel choices for sends/receives in the OSARA track parameters dialog?

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#1003]
We've had a bunch of requests over the years to simplify the routing around sends and receives, the main thing people seem to want to avoid is repetitive diving in and out of menus. If we can improve this in some way, ideally I'd like to move away from the context menu on the Delete button being a necessary step while we're at it, have seen a lot of learners forget that's what to do.
Instead, could we add channel configuration choices to the track params dialog? Looks like it might be possible via the API but I don't think I'm smart enough to code it yet.
Thoughts?

**Comment by jcsteh** [comment]
As someone that uses a lot of NI drum synths and has to route a single track to multiple instances to work around NI's continual unwillingness to make core functionality accessible, you have no idea how much I'd love this. Unfortunately, while I concur that the API probably does allow for this, I think it's going to be a complete pain in the posterior to implement. That said, I'll look into it at some point, since it seems it's not just me this annoys. :)

**Comment by jcsteh** [comment]
The reason it's harder than other send/receive parameters is that MIDI sends and receives seem to be managed completely separately and differently from audio sends/receives, so I can't use any common code.

**Comment by jcsteh** [comment]
Oh wait, looks like they are managed with the same function. It's hardware outputs I'm thinking of that are different.

**Comment by jcsteh** [comment]
This does not support MIDI buses at this stage. That's possible with REAPER 7, but it's a bit more work and I figure it's a rare case right now that shouldn't block support for basic channels.

**Comment by Lo-lo78** [comment]
if we were to also insert the audio in the sends and receives, the entries per track will be many.
Why don't we think of a system like Cockos developed for envelopes with submenus?
In this way we could think about inserting other parameters in the future for the tracks.

**Comment by ScottChesworth** [comment]
> Why don't we think of a system like Cockos developed for envelopes with submenus?
> 
Because all of the feedback we've had is that people want to avoid menu diving. If you've got a strong idea for how submenus could make things more productive, let's here about it in as much detail as you can describe.

**Comment by Lo-lo78** [comment]
> Because all of the feedback we've had is that people want to avoid menu diving. If you've got a strong idea for how submenus could make things more productive, let's here about it in as much detail as you can describe.

I thought about it after the last message and thought that there is already a filter that can help.
This actually helps a lot.
If you need to search for the guitar track do alt+f and you have everything related to the guitar track.
I also include track controls among the parameters.
If the API supports audio that's great!
If the parameters of the Track Parameters window increase there are no problems. In fact I think it's great to have quick controls over track parameters. The filter is already an excellent solution in OSARA and nothing else is needed.

**Comment by ScottChesworth** [comment]
@jcsteh, I wanna try to get source and destination audio channels done here. Looking at what you added for MIDI though, seems like some pretty complex stuff, working with lower 5 bits of MIDI bus etc. Will I need to understand that stuff to add audio channels or are they handled in a way that I might be able to comprehend?

**Comment by jcsteh** [comment]
There is some bit manipulation involved for audio channels. For both source and destination, the starting channel is stored in the lower 10 bits. For source, the higher 10 bits contains the channel count. For destination, 1024 (bit 11) being set means mix to mono. (Not sure what the difference is between that and the separate B_MONO flag, but anyway...)

More concerning for me is mapping out the values for specifying source channels. If you have a multi-channel track, you need to be able to select from multiple types of sources. That's not so bad for a 2 channel track; you go 1/2, 2/3, 3/4, then 1, 2, 3, 4. Even a 4 channel track isn't too bad: 1/2, 2/3, 3/4, 1, 2, 3, 4, 1-4. But once you get to 6 channel or above, you have to go something like: 1/2, 2/3, 3/4, 4/5, 5/6, 1, 2, 3, 4, 5, 6, 1-4, 2-5, 3-6, 1-6. It's a bit of a nightmare. REAPER's channel menus take that a step further by letting you create new channels if they don't exist yet, but I'm inclined to say we just shouldn't support that; the user can easily increase the number of channels in the I/O dialog if they really want to do that.

**Comment by ScottChesworth** [comment]
Ugh, I hadn't considered tracks with more than two channels. That's gonna need some thinking about isn't it.
