### ISSUE TITLE
OSARA Update Dialog not behaving as it should

### ISSUE THREAD

**Issue by jennykbrennan** [jcsteh/osara#1013]
The OSARA Update dialog opens at startup on top of the startup prompt. Focus is in the text box. I don't bother reading any of it because I'm lazy so the text is selected. When I hit tab to go to the Go to download button, NVDA says: "Selection replaced.
 
The text box now says "tab" and nothing more. Tab key doesn't move me out of the text box. I get more written tab symbols or whatever I fancy writing. In other words, the text box is editable.  NVDA object nav let's me see the Go to download page button (Alt D), the Close button (Alt C), and the window title: (OSARA update Dialog).
Alt gives me system menu move or close. Alt F4 closes the window. Alt D and Alt C give me error sounds but does nothing.
NVDA Enter on the button takes me to the download page and closes the dialog.
From what I recall from the first time this happen a day ago, control tab did nothing either, but I'm more unsure about that. 

Cheers

**Comment by ScottChesworth** [comment]
REAPER Prefs, General category, "Open project(s) on startup" needs to be set to Prompt to reproduce this.

**Comment by jcsteh** [comment]
When you say the startup dialog, do you mean the configure optimal thing?

I think that's the key point here. That configure optimal dialog is modal, which means nothing should really open on top of it. I need to prevent that somehow.

**Comment by jcsteh** [comment]
Never mind, ignore last comment.

**Comment by ScottChesworth** [comment]
Reopening because I think there's still a gotcha here. Tab doesn't replace the commits being displayed any more, but pressing any alphanumeric key while focus is in the multiline edit field still does.
