### ISSUE TITLE
Is it possible to update the old OSARA FX Bypassed/active functionality?

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#1016]
Hello with the new versions of Reaper we now have feedback of the status of the plugin in the FX chain.
Now if you bypass a plugin it will be repeated twice.
I believe one from OSARA and the second from Reaper.
In this case I would give precedence to Reaper.
When it is activated I think it says OSARA.
In this case we can decide if it is good or not good.
when it is active it is reported by OSARA and not by Reaper. We might as well leave it.
In my opinion, a choice needs to be made here.
There is also a second problem.
When you open the menus there is a bit of confusion:
Add container  3 di 39. bypassed 
And this is even stranger:
Run selected FX in parallel with previous FX,  activated3 di 39. active
In my opinion it needs to be fixed up a bit. 🙂

**Comment by ScottChesworth** [comment]
Yep, I'm already planning to remove the OSARA hack that reports bypass. Just waiting a while to make sure we don't require a very recent release as our minimum supported version.

**Comment by jcsteh** [comment]
Strictly speaking, we could sniff the version of REAPER and disable that hack only for recent versions which make this accessible properly. That would allow us to avoid bumping the minimum requirement. It probably wouldn't be that hard to implement, but it does raise the question again of how long we intend to support old versions. Still, I don't like the idea of having a subpar experience for some as yet undetermined period of time. :)

**Comment by ScottChesworth** [comment]
That would be neat.
