### ISSUE TITLE
It is possible to prioritize action feedback: OSARA: Report track/item/time/MIDI selection (depending on focus) and other OSARA actions?

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#1022]
Custom actions are often created where this action has very important feedback for the track.
We're getting a lot better at navigating TCP right now.
It may happen that the main Reaper window is the last feedback overlapping the OSARA feedback.
Is it possible to prioritize feedback on this and other OSARA actions?

Thank you!

**Comment by jcsteh** [comment]
Not really. These actions already interrupt anything that is currently being spoken. If something else is being spoken over the top, that is almost certainly happening later, not earlier. The only speech prioritisation we can access is the one we're already using.
