### ISSUE TITLE
About updates

### ISSUE THREAD

**Issue by piano777wzy** [jcsteh/osara#1024]
Hello, now that osara is getting more and more powerful, it has a function of automatically updating and displaying update logs.
I have a suggestion whether you can add the update history function to display all the latest update logs from the beginning. It can be a document.
For example, there is a whatsnew.txt in reaper who has all the update logs from the old version to the latest version.

**Comment by ScottChesworth** [comment]
That's already available online. Hit the "Change log" link on the snapshots page.
