### ISSUE TITLE
Like the filter on Reaper: is it possible to switch to OSARA window parameters with the down arrow key?

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#1035]
Hi, I understand the strangeness but I often make mistakes when I'm in the workflow and don't do the alt+p shortcut after using the filter in the OSARA window.
I sometimes use the down arrow like an idiot out of habit when using OSARA windows.
obviously it doesn't work! (lol)
alt+p doesn't immediately come to mind if I'm in a hurry.
The tab key is too slow and slows me down.
Using the down arrow in Reaper filters sometimes confuses me if I'm in a hurry in OSARA windows.
This functionality is also available in the ReaPack browser.
The down arrow seems very instinctive.
Is it possible to use the down arrow after entering a text in the filter in the OSARA windows?
Thank you!
N.B.
In Reaper's envelope manager window the filter behaves differently. But the window doesn't disappear if you press the enter key.
Could we not close the OSARA window if we are in the filter and accidentally hit the Enter key?

**Comment by ScottChesworth** [comment]
I understand that you've become used to REAPER's ways of doing things, but all of those deviate from convention, so I don't think we should be emulating those. We also wouldn't be able to provide a consistent experience on both platforms.
