### ISSUE TITLE
Allow Updates checking to be toggled off

### ISSUE THREAD

**Issue by Nick6489** [jcsteh/osara#1039]
While there are very few use cases where that should even be a thing, it would be nice to allow OSARA to not check for updates. I use Reaper on one machine where it strictly acts as a Sonobus client and thus, OSARA updates are less consequential to me and just get in the way. Might someone please implement that?

**Comment by ScottChesworth** [comment]
Already done. Go to REAPER Prefs, General category, make sure that "Automatically check for new versions of REAPER on startup" is off, OSARA respects that choice.

**Comment by Nick6489** [comment]
Well, I'll be damned! Thanks! Sorry for wasting your time.

**Comment by ScottChesworth** [comment]
NO worries. Just realised I'm not 100% sure it's been documented yet. Will check.
