### ISSUE TITLE
When REAPER's jump dialog closes, can OSARA report the new edit cursor position?

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#1041]
If possible, it would be excellent to hear the new edit cursor position as validation. At the moment we hear REAPER's title bar being reported, which confirms that the dialog has been closed, but doesn't confirm where the user has jumped to.

**Comment by jcsteh** [comment]
The open question is whether that action blocks until the dialog closes or whether it just opens the dialog and returns. I suspect the former based on the fact that the parent window gets disabled. However, if it's the latter, that will be much harder and probably Windows specific.

**Comment by jcsteh** [comment]
Also, what do we do if the cursor doesn't move; e.g. if the user pressed escape or (don't know why anyone would do this, but...) pressed enter without changing the value?

**Comment by ScottChesworth** [comment]
> if it's the latter, that will be much harder and probably Windows specific.
> 
How would you recommend I investigate the difference?
I reckon suppressing the title bar would be fine as a Windows specific hack in this case, there's not a splurge of title bar on Mac when the jump dialog closes.

**Comment by ScottChesworth** [comment]
> what do we do if the cursor doesn't move;
> 
Run OSARA: Report edit/play cursor position and transport state whenever the dialog is dismissed? That breaks our usual convention of if we don't move then we don't speak, but arguably I reckon it's still more useful feedback than what we get right now, and like... is anyone gonna know? :)
