### ISSUE TITLE
Keystrokes not working for non-English keyboard layouts

### ISSUE THREAD

**Issue by tbdalgaard** [jcsteh/osara#106]
When trying to follow along the Reaper and OSARA keystrokes many of them aren't working because the keystrokes I use is different than the English keyboard. A good example is the bracket keys. On English keyboards these are easy to find.
On Non-English keyboard they can require aditional keystrokes. So on my Danish keyboard I have to press option (alt) and the number 8 on the number row to get the left bracket. However Reaper or OSARA does not allow this command, so I might end up having to change a huge amount of actions to fit my keyboard.
This was tested on my Mac, I haven't tested on Windows yet.

**Comment by jcsteh** [comment]
I don't think there's anything I can do about this. The key codes REAPER uses are just different for different operating systems and languages. See [this REAPER forum post](http://forums.cockos.com/showthread.php?p=1748438) for more details.

The only solution here would be for you to provide a key map for your language and maintain it going forward. However, that would also likely require some change to the installer to detect which language you're using. That's probably possible, but I don't know how at this point.
