### ISSUE TITLE
Configure REAPER for optimal screen reader accessibility question

### ISSUE THREAD

**Issue by reaperaccessible** [jcsteh/osara#1061]
Is disabling the following action part of parameters list of Configure REAPER for optimal screen reader accessibility?
In media explorer action list: Options: Close Media Explorer on escape key
If so, is it possible not to disable this action?
If it doesn't, there is something disabling this action and I don't know where it comes from
Thanks.

**Comment by ScottChesworth** [comment]
No that's not a setting OSARA changes, Pretty sure it's disabled by default. Should we consider enabling that as part of the optimal config?

**Comment by reaperaccessible** [comment]
Ok, I just completely removed Reaper on a machine and reinstalled and indeed, this action is disabled by default.
It's been enabled on my system for so long that I didn't know it was disabled by default.
I wonder if Cockos should enable this default action directly.
I think it would be interesting to activate this option because when inserting a .xp/.RfxChain via the Media Explorer, once loaded, the escap key takes us back to the Media Explorer, this currently works. But to return to the TCP, if this action is activated, another press on escape closes the media explorer and takes us to the TCP. So no need to use 2 hands to close media browser.
Another solution is the Close Media Explorer window action but for some reason this action does not work everywhere in the Media Explorer. So, we need to move to a specific location for this action to work.

**Comment by ScottChesworth** [comment]
Gotcha. Pretty sure I can get this one done. Thanks for checking with the fresh install.

**Comment by ranetto** [comment]
as regards the escape key to exit media explorer, an option has been added in the menu of that window which says whether escape should still be used to exit the window or not
