### ISSUE TITLE
Include nearest markers in report from "OSARA: Report edit/play cursor position and transport state"

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#1062]
We provide feedback when users navigate to the nearest project marker before or after their cursor position by pressing Semicolon or Apostrophe, running "Markers: Go to previous marker/project start" or "Markers: Go to next marker/project end".
However, these actions move cursor position, it would be useful to be able to hear where the closest markers are without changing that.
Can information about closest markers be appended to what we report when users hit Control+Shift+J to run "OSARA: Report edit/play cursor position and transport state" (ID _OSARA_CURSORPOS), avoiding any extra keystrokes?
- If cursor is before the first project marker, OSARA says "before marker" name of first marker, or its number if unnamed.
- If cursor is after the last project marker, OSARA says "after marker" name of last marker, or its number if unnamed.
- If cursor is between project markers, OSARA says "between markers" name of closest marker before cursor, Comma, name of closest marker after cursor, or numbers if unnamed.
- If there aren't any project markers, OSARA says nothing.
To make these longer reports easy to digest, I'd like to add a Comma between position and transport state. Here are some examples:
"bar 5 beat 2 0%, stopped before marker whistling intro"
"bar 250 beat 4 75%, paused after marker kazoo"
"bar 193 beat 3 27%, recording between markers bongo break, saucepan solo"

I reckon it would shore up the functionality gap discussed recently on RWP in this thread:
https://groups.io/g/rwp/topic/feature_request/105745527

Your thoughts?

**Comment by jprykiel** [comment]
@ScottChesworth I like that. Just hope it can be made optional if implemented, if not, implement anyway.
JPR

**Comment by ScottChesworth** [comment]
Why does it need to be optional?

**Comment by jprykiel** [comment]
Not for me, but I am anticipating users finding it too verbose. Well you can always escape the dialogue before it finishes so that's fine.

**Comment by ScottChesworth** [comment]
It's not a dialog.

**Comment by jprykiel** [comment]
My wrong Scott. I was thinking of the jump to dialogue. Anyway, one can hit control to make speech stop so just ignore what I said and hit control on me. 😆

**Comment by ScottChesworth** [comment]
Hahah! Thanks for clarifying.
