### ISSUE TITLE
speech feedback to these actions in main and midi editor

### ISSUE THREAD

**Issue by GianlucaApollaro** [jcsteh/osara#107]
I whould like to see speech feedback added to these actions if possible.
Midi editor:
Activate previous MIDI media item on this track, clearing the editor first
Activate next 	MIDI media item on this track, clearing the editor first
Activate previous MIDI track
Activate next MIDI track
All the "set grid" actions with a message like grid set to 1/4th or 1/4th t
All the "Set length for next inserted note" actions with a message like length set to 1/4th, including the "Set length for next inserted note: grid".
Main actions that I would like to have announced:
Pre-roll: toggle pre-roll on record
SWS/AW: Toggle count-in before recording

Lower priority actions:
Record: Set record mode to normal
Record: Set record mode to time selection auto-punch

**Comment by jcsteh** [comment]
We'll cover the grid actions in #142, since that's narrower in scope and provides more detail.

**Comment by RDMurray** [comment]
partly implemented in #222 , #223  and  #228

**Comment by ScottChesworth** [comment]
So far as I can tell, everything requested in the OP now reports feedback in one form or another. Closing for now. Feel free to reopen if I missed anything @GianlucaApollaro
