### ISSUE TITLE
The inconvenience and thoughts caused by using the method of inserting notes to input notes in the MIDI editor

### ISSUE THREAD

**Issue by XHG20033** [jcsteh/osara#1091]
In the MIDI editor, press I or Shift+I to insert a note. The newly inserted note will be added to the selection, resulting in more and more notes in selection. As a result, changing the pitch immediately after inserting a note will affect the previously existing notes.

  My English is not good, so I use Google Translate for the entire text. If you have any questions about grammar, politeness, etc., please forgive me!

  #### Ways to reproduce:

1. Create an empty MIDI item and open the MIDI editor. There are no notes in the item .

2. Sets the length of inserted notes (such as eighth note).

3. Move the pitch cursor where you want to insert (Alt + Up Arrow or Alt + Down Arrow).

4. Press Shift + I to insert a note.

  Now, the two Actions "Edit: Move notes up one semitone" and "Edit: Move notes down one semitone" will act on the notes just inserted.

  However, if there are some notes in the item, after you perform steps 2 to 4 in the above steps. You may hear screen reader speaks "2 notes semitone up" or "2 notes semitone down" when execute "Edit: Move notes up one semitone" or "Edit: Move notes down one semitone". This means that more than one note has been changed in pitch.

#### Analyze the reasons for this phenomenon:

  Go to "action list" and find "Custom: Insert note, maintaining current position of edit cursor" or "Custom: Insert note, advancing edit cursor". Click "Edit action..." to see that the custom action consists of the following actions:

* OSARA: Mute next message from OSARA

* View: Show events as rectangles (normal mode)

* Edit: Insert note at edit cursor

  The action of inserting a note will add the new note to the selection. But the selection is not cleared before inserting. So changing the new note will affect the existing notes.

#### solution:

  Adding "Edit: Unselect all" to these two actions can solve the problem.

* OSARA: Mute next message from OSARA

* View: Show events as rectangles (normal mode)

* Edit: Unselect all

* Edit: Insert note at edit cursor

**Comment by ScottChesworth** [comment]
> My English is not good, so I use Google Translate for the entire text. If you have any questions about grammar, politeness, etc., please forgive me!
> 
Nothing to worry about, that was an excellent report. Thanks!
> Adding "Edit: Unselect all" to these two actions can solve the problem.
> 
Sort of, but there's a trade-off, that will clutter the undo history. Make that change on your machine if you need this fixed immediately. I'm going to take a shot at handling this action in OSARA, however it might take a little time to figure out.

**Comment by ScottChesworth** [comment]
Derp, forgot we can combine undo points in the custom action. Will get this fixed today, just gotta wait until @jennykbrennan is awake so she can update the custom action on the Mac key map.
