### ISSUE TITLE
Feedback for volume and pan when automating

### ISSUE THREAD

**Issue by Justinmac84** [jcsteh/osara#112]
Hi, 

As we've discussed privately, this might be more something to address to Cockos, but would it be possible for some or all of the following three things. Either to have a way to input exact values when automating volume and pan in in say latch preview. Currently, one can enter exact values for send volume in the routing dialogue but not track volume and pan. this would be the most preferable step for me. 

Or could Osara somehow provide feedback when nudging track volume and pan in latch preview. Currently, because of the way latch preview works, feedback stays locked on what the parameter value was before you changed automation modes. This makes changing volume from 0 to -inf very tedious though, which brings me to my third possibility. 

It's true that, while there's currently no feedback when controls are nudged, you can hear where things are going by ear, even if they move very slowly. Especially if the first method isn't possible, either by you or by Cockos, could we at least have a means to move automatable volume and pan straight to the extremes or to the middle, 0 db in volume's case, since I'm not sure if that is the precise middle of the slider, probably not. 

Hope this makes sense, 

justin

**Comment by jcsteh** [comment]
I think all of these options would require changes from Cockos for a decent experience.

**Comment by jcsteh** [comment]
Discussed this with Cockos and it seems what we need is already in the API. Implementation note:

* Get the value with GetTrackUIVolPan
* Set it with CSurf_OnVolumeChangeEx

**Comment by RDMurray** [comment]
I have changed postChangeTrackVol() and postChangeTrackPan() to use GetTrackUIVolPan().
[My branch is here.](https://github.com/rdmurray/osara)
[You can get a test build here.](http://haylott.plus.com/osara_test.exe)
