### ISSUE TITLE
有关cc 动作的报告反馈

### ISSUE THREAD

**Issue by cn-peter** [jcsteh/osara#1121]
hello everyone
I have a few friends who arrange music. They have a need to edit CC
Can the following actions be reported?

Edit: Move CC events right 1 pixel; ID:40673
 Edit: Move CC events left 1 pixel; ID:40672
Edit: Move CC events right by grid; ID:40675
Edit: Move CC events left by grid; ID:40674

I am speaking here using a translator
Thank you

**Comment by ScottChesworth** [comment]
I think we have a guy who can do that. :)

**Comment by MatejGolian** [comment]
Indeed... 🙂
From my understanding we'd have to write a function like postMidiMoveStart, just for CCs. I'm sure that Jamie would be able to get all MIDI event movement feedback working even from a single function, but perhaps having a dedicated function for CCs could be better for function separation/clarity?
