### ISSUE TITLE
Configure REAPER for optimal screen reader accessibility: Hide mixer

### ISSUE THREAD

**Issue by reaperaccessible** [jcsteh/osara#1131]
I noticed that the Mixer is not unchecked in the View menu after applying the settings.
Would it be possible to add that?
Additionally, I was wondering if it would be possible to apply the necessary settings so that Reaper is preconfigured for file management.
I regularly have beginner users who have problems with file loss due to the fact that Reaper does not have basic configuration for file management.
It would be good to ensure that if the user saves his project, a folder with the name of the project is placed in the REAPER Media folder with the .rpp file in it and that the media is saved in a folder named Media 
and a Peaks folder.
But I don't know if it's possible.
Thanks.

**Comment by jcsteh** [comment]
I'll need to look into the mixer. It's probably possible. Have you specifically encountered screen reader trouble when the mixer is showing?

I think file management configuration is out of scope. While I understand the reasoning for this, it is not at all related to usage of a screen reader user or accessibility. It is something that applies equally for all users. I'd suggest you may want to try to convince Cockos to change REAPER's defaults here.

**Comment by reaperaccessible** [comment]
I systematically hide the mixer because I have already encountered problems with the media explorer if the mixer is activated.
But the mixer has been disabled on my machines since the beginning so I don't know if it can cause any other problem.
Personally I have never had to use the mixer.

**Comment by ScottChesworth** [comment]
Mixer visibility shouldn't be an  issue now that we undock Media Explorer in optimal config.

**Comment by jcsteh** [comment]
Closing this for now because there doesn't appear to be a need to do this now that we undock the Media Explorer. Please feel to reopen if you have a specific real world use case where mixer visibility causes problems.
