### ISSUE TITLE
Help keyboard shortcuts no longer speak in event list mode

### ISSUE THREAD

**Issue by reaperaccessible** [jcsteh/osara#1135]
As mentioned in the text, F12 in event list editor mode no longer speaks on my machine.
I see that the keyboard help is activated since I can no longer change mode or start playback project but nothing is spoken anymore.
On the other hand, I can select the MIDI events in the list and this is correctly stated.
If I press F12 again, everything returns to normal.
But F12 works perfectly in all other modes in the MIDI editor.
I only have this problem on one machine.
I tried to set Reaper to English with the OSARA keymap and I get the same behavior.
I have no idea how to solve this problem.
Someone would have any idea?
Thanks.

**Comment by ScottChesworth** [comment]
Sounds like MSAA is being used to deliver the reports. That being the case, shortcut help won't be able to speak when focus is in a listbox control. Which OS and screen reader is on the effected machine?

**Comment by ScottChesworth** [comment]
Can you go to your REAPER resource path, find this file:
reaper-extstate.ini
Post it or copy the contents here so I can have a look?

**Comment by reaperaccessible** [comment]
[osara]
reportScrub=0
reportFx=1
reportTransport=0
reportNotes=1
reportTimeMovementWhilePlaying=1
reportSurfaceChanges=0
paramsDialogPos=-7 0 974 1047
moveFromPlayCursor=1
reportMarkersWhilePlaying=1
reportTrackNumbers=1
editCursorFollowsEventListFocus=1
reportFullTimeMovement=0
reportPositionMIDI=1
reaperOptimalConfigVersion=2
lastUpdateCheck=1720433621
[ArcDntAll2]
All2=31
[MPLVFpurch]
ES_key=MPLVFpurch
dock=0.0
mb_title=MPL Various Function package Purchasing
vrs=1.0
wind_h=500.0
wind_w=500.0
wind_x=152.0
wind_y=396.0
PRESET0=
[MPL_Scripts]
sysID=26227C118E3041AEBD38B592F7449F32
counttotal=2
[Archie_Gui; Grid switch.lua]
PositionDock=0.0
PositionWind=150.0&100.0
SizeWindow=700.0&35.0
SaveDock=NULL
[TOGGLE BYPASS ALL FX ALL TRACKS EXCEPT INSTRUMENTS - SAVE RESTORE PREVIOUS]
STATE=0
[spk77_velocity_tool]
mode=0
w=280
h=320
x=0
y=0
target=22
weight=140
[amagalma_Grid Settings]
x=400.0
y=400.0
size=50
dock=0.0
[PeloReaper_MediaFolderWindow_01]
WindowLastVisible=False
WindowTitleName=
WindowGroup=1
WindowTopMost=True
MESync=False
MEPlay=False
LastCurrentPath=C:\
FListViewType=Details
WindowBounds=0,0,383,398
WindowColor=128,128,128
[PeloReaper_MediaFolderWindow_02]
WindowLastVisible=False
WindowTitleName=
WindowGroup=2
WindowTopMost=True
MESync=False
MEPlay=False
LastCurrentPath=C:\
FListViewType=Details
WindowBounds=0,0,383,398
WindowColor=128,128,128
[PeloReaper_MediaFolderWindow_03]
WindowLastVisible=False
WindowTitleName=
WindowGroup=3
WindowTopMost=True
MESync=False
MEPlay=False
LastCurrentPath=C:\
FListViewType=Details
WindowBounds=0,0,383,398
WindowColor=128,128,128
[PeloReaper_MediaFolderWindow_04]
WindowLastVisible=False
WindowTitleName=
WindowGroup=4
WindowTopMost=True
MESync=False
MEPlay=False
LastCurrentPath=C:\
FListViewType=Details
WindowBounds=0,0,383,398
WindowColor=128,128,128
[PeloReaper_MediaFolderWindow_05]
WindowLastVisible=False
WindowTitleName=
WindowGroup=5
WindowTopMost=True
MESync=False
MEPlay=False
LastCurrentPath=C:\
FListViewType=Details
WindowBounds=0,0,383,398
WindowColor=128,128,128
[PeloReaper_MediaFolderWindow_06]
WindowLastVisible=False
WindowTitleName=
WindowGroup=6
WindowTopMost=True
MESync=False
MEPlay=False
LastCurrentPath=C:\
FListViewType=Details
WindowBounds=0,0,383,398
WindowColor=128,128,128
[PeloReaper_MediaFolderWindow_07]
WindowLastVisible=False
WindowTitleName=
WindowGroup=7
WindowTopMost=True
MESync=False
MEPlay=False
LastCurrentPath=C:\
FListViewType=Details
WindowBounds=0,0,383,398
WindowColor=128,128,128
[PeloReaper_MediaFolderWindow_08]
WindowLastVisible=False
WindowTitleName=
WindowGroup=8
WindowTopMost=True
MESync=False
MEPlay=False
LastCurrentPath=C:\
FListViewType=Details
WindowBounds=0,0,383,398
WindowColor=128,128,128
[PeloReaper_MediaFolderWindow_09]
WindowLastVisible=False
WindowTitleName=
WindowGroup=9
WindowTopMost=True
MESync=False
MEPlay=False
LastCurrentPath=C:\
FListViewType=Details
WindowBounds=0,0,383,398
WindowColor=128,128,128
[PeloReaper_MediaFolderWindow_10]
WindowLastVisible=False
WindowTitleName=
WindowGroup=10
WindowTopMost=True
MESync=False
MEPlay=False
LastCurrentPath=C:\
FListViewType=Details
WindowBounds=0,0,383,398
WindowColor=128,128,128
[XR_InsertEmptySpacePopup]
unit=bt
value=1
[kawa_EnvelopeFunc2]
envelope_AutoTimeSelection_DetectionMODE=false
[PeloReaper_MediaFolderWindow_Global]
UseMEInsertActionOnSingleSelection=True
MEPlayCursorMoveSpeed=10
[PR_GameSynthRenderWindow]
WindowPlacement=0,0,526,420
WindowTopMost=False
[ak5k]
reablink_init=1

**Comment by ScottChesworth** [comment]
Try closing REAPER, then add this line to the OSARA section:
UiaNotificationEvents=2
Now restart REAPER and check whether Shortcut Help reports with focus in the event list.

**Comment by reaperaccessible** [comment]
Yessssss! you got it.
Is the problem only on my machine or is it an OSARA bug?
Thanks.

**Comment by ScottChesworth** [comment]
Dunno. I haven't seen it anywhere else yet and our code for reporting hasn't changed in a long time, so I guess it's just gonna be on that machine. If you hear about anyone else with the same situation, please let us know.
