### ISSUE TITLE
grouping of tracks

### ISSUE THREAD

**Issue by ranetto** [jcsteh/osara#1147]
Hi, when I group tracks, putting one as a guide and the others as slaves, I am always only informed of the grouping of the volume and not of the pan, mute, solo, record or any other grouped parameter. Does this happen to you too? Can anything be done to fix this?

**Comment by jcsteh** [comment]
I don't think I can reproduce this. Can you please provide the exact steps you're taking (keys or actions), what you expected and what happened instead? Thanks.

**Comment by ranetto** [comment]
Hi, sorry I couldn't play it anymore either, but it only tells me that the tracks are grouped, while last time it also told me volume: maybe it was a coincidence? Maybe then we could make it say which parameters have been grouped when it informs us of the grouping? Sorry again for wasting your time!

**Comment by jcsteh** [comment]
The track reports are already very long, which is why we only report "grouped" there. However, you can use the action OSARA: Report groups for current track to get the full information.
