### ISSUE TITLE
Osara FX parameters search filter

### ISSUE THREAD

**Issue by ranetto** [jcsteh/osara#1149]
good morning, sorry I don't know if I had already asked this question or if it had already been closed: I would like there to be a way to save the search filter in the list of osara parameters for an fx or for a synthesizer: maybe using a contextual one on the search box to do this: I'll give you an example: when I adjust the frequency of a filter of a synth, or the resonance, then I exit the parameters maybe to compare it with another synthesizer, I would like that when I return to the list of parameters the search was still set so that I can immediately see the parameter that I had previously searched for and be able to re-edit it. This would be very useful when a synth has hundreds of parameters and maybe you have to search for the name that you don't remember: is it possible? What do you think? Thanks in advance

**Comment by jcsteh** [comment]
You already filed #911 for this, which was itself a duplicate of #571.
