### ISSUE TITLE
Translation not showing and question on Media Explorer

### ISSUE THREAD

**Issue by reaperaccessible** [jcsteh/osara#1161]
1. Report time selection start and end while playing is not translated in the OSARA settings menu, is this normal?

2. I was doing support for a new user yesterday and noticed different behavior when navigating in Media Explorer.
If I select a directory and press Tab, normally it doesn't have a stop at the top and bottom of the list.
But on the machine I put together yesterday, there is one.
So, I was wondering how I can enable this behavior.
Is it in Reaper or in OSARA.
Thanks.

**Comment by ScottChesworth** [comment]
Whoops, I added that option in config, thought that it would be translatable but I guess there's something I haven't done properly yet. I'll learn what that is and get it fixed ASAP.
Re the Media Explorer question, OSARA doesn't have any influence over that behaviour. Must be a REAPER setting, probably best asked about on one of the groups.

**Comment by ScottChesworth** [comment]
Hey @jcsteh, whenever you have a sec can you spot what I've missed here? Adding an option to the OSARA Config dialog, we put this in settings.h:
BoolSetting(reportTimeSelectionWhilePlaying, MAIN_SECTION,
	"Report time se&lection start and end while playing",
	false)
Best I can tell that matches the formatting of other entries and it does show up in the dialog as expected, but it isn't in the translation template yet. I've searched the entire codebase for one of the other bools that I know is already translatable and can't see anywhere else the new one needs to be declared.
Heeeeeelp?

**Comment by reaperaccessible** [comment]
Okay, I found it. The problem comes from the ReaperAccessible KeyMap. Up arrow and down arrow was assigned to 2 action, "select next and previous file.
In the OSARA KeyMap, the up and down arrow keys are not assigned.
The user had already installed OSARA with default settings and installed the ReaperAccessible KeyMap without resetting all shortcuts in all sections before loading the ReaperAccessible KeyMap.
There you go, problem solved and corrected in the KeyMap. Really nicer with a stopper.

**Comment by jcsteh** [comment]
It's definitely showing up in the translation template:

```
msgctxt "OSARA Configuration"
msgid "Report time se&lection start and end while playing"
msgstr ""
```

Where are you downloading the .po file from?

**Comment by reaperaccessible** [comment]
I don't download a file, I translate directly online. I found the string:
Report time se&lection start and end while playing
Translation:
Énoncer le début et la fin de la sélection temporelle pendant la lecture
This is for the FRC translation.
Yet this did not translate into Reaper.
I use osara_2024.10.10.1613,3303c8e3

**Comment by jcsteh** [comment]
Ah, I thought you meant you couldn't find the message. I have to sync translations into OSARA manually and I haven't done that for a while. I'm triggering that now, so it should appear in a build soon.
