### ISSUE TITLE
Prompting there is an update when there isn't

### ISSUE THREAD

**Issue by alimoosa19** [jcsteh/osara#1163]
On MacOS 15.0.1, Reaper keeps prompting there is an OSARA update when I have installed the latest build.

How I know this, when I go to the page, it says October 18 for Mac.

Here are my steps:

1. Download the Upgrade file.
Allow it from Privacy and Security.
What I am expecting to happen, is it only prompt when a change to OSARA has been uploaded.

**Comment by jcsteh** [comment]
The problem was that the last build for Mac failed for some temporary reason. That meant the Windows and Mac versions were mismatched. I've forced a rebuild for Mac now. Once you update to that, this problem should go away.

**Comment by alimoosa19** [comment]
Hello,

Thank you so much!

I will check for OSARA update.
Kind Regards,
Ali Moosa

Host, Broadcast Map 

Check out the show on Youtube:

***@***.***

Website:

https://alitechgroup.wordpress.com

Listen to the show on all of your favourite platforms:

https://podcasters.spotify.com/pod/show/ali-moosa

Co-Host Spicy Techy
Producer, SienaT Radio
https://sienat.wordpress.com/sienat-radio/
https://podcasters.spotify.com/pod/show/sienatradio

Co-Facilitator, Techstravaganza. Focusing on providing tutorials to help people get the most out of their favourite devices.

Let’s connect!

Book some time with me using the following link: 

Zoom:

https://scheduler.zoom.us/ali-moosa
