### ISSUE TITLE
report wrap around when going to start of loop via repeat 

### ISSUE THREAD

**Issue by Binary-solo1** [jcsteh/osara#1164]
I've been recording a bunch with autopunch time selection lately. Just thought that it would be nice if there was some kind of cuing when the loop starts again. I can think of a number of ways to implement this but don't know what would be plausible or useful to others. 
1. some kind of audio marker set by Osara. If it wwere possible to hit a key and drop an audible marker like a short beep one could use that to get notified when you pass a specific point on the time line. 
2. a count of the recording passes when auto punching.

**Comment by ScottChesworth** [comment]
If you want to hear when the repeat has happened, try enabling "Report time selection start and end while playing" in OSARA Config. Or if you want a queue before it happens, drop a project marker wherever you want to be notified, call it something short like "in 2" if it's 2 bars before the end of your time selection, then record with "Report markers and regions during playback" enabled in OSARA Config. Yeah I know, it says during playback, but they both work during recording.

**Comment by ScottChesworth** [comment]
Related tasks:
- { } Clarify that both of those config options work during recording.
- - [ ] Add same feedback for loop points.

**Comment by Binary-solo1** [comment]
Both of these work, @ScottChesworth rest my case, I really thought I'd thought of something first.  Just to knit pick because I can, I do think that the marker reporting could be streamlined by not announcing marker unless its name is just the number. If you've placed and named a marker, just its' name should be enough. Feel free to close.
