### ISSUE TITLE
Improve feedback for action: Item: Select all items in track

### ISSUE THREAD

**Issue by ptorpey** [jcsteh/osara#1165]
I often find the help and feedback confusing for the action:
Item: Select all items in track

I think this is because when it says "select all items in track" it implies that it only selects items on a single track.

Compare this to the related action:
Item: Select all items on selected tracks in current time selection

which is more explicit about selecting items on "selected" tracks.

perhaps the wording for the first action can be modified to explicitly state that it applies to "selected" tracks and not just a single track.

--Pete

**Comment by ScottChesworth** [comment]
That's a REAPER action, OSARA can't rename it. I'll pass this along to Cockos.

**Comment by ptorpey** [comment]
Thanks.

 

--Pete
