### ISSUE TITLE
behavior when engaging scrubbing from playback creating time selection seems weird

### ISSUE THREAD

**Issue by Binary-solo1** [jcsteh/osara#1170]
When pressing left or right arrow while playing, provided you have the correct settings set in prefs and Osara prefs scrubbing is engaged at the play cursor position. However, if I hold down shift while pressing the arrows to create a time selection, Osara reports stop and jumps me to the original edit cursor position before starting scrub and creating time selection.  Seems to me that this should work the same as when you're not trying to create time selection.

**Comment by ScottChesworth** [comment]
Hmm I can't reproduce reporting sstop or moving cursor yet. Can you describe the sequence of keystrokes step by step and tell us how you've got things set in OSARA Config?

**Comment by ScottChesworth** [comment]
Note to self: Shift+Arrows doesn't speak with "Report position when scrubbing" checked. To fix, make "Time selection: Move cursor left, creating time selection and "Time selection: Move cursor right, creating time selection" actions call postCursorMovementScrub.

**Comment by Binary-solo1** [comment]
Osara prefs
move relative to play cursor for time movement commands during
playback checked.
Steps
1. press play
2. at desired spot press shift left arrow to create time selection
backwards
When I do this, playback stops and time selection starts being created from
the point where i pressed play.
Note that when i just press the arrows during playback scrubbing is engaged
like I expect from play cursor position. Its just when creating selection
that this doesn't behave as expected.

**Comment by ScottChesworth** [comment]
Thanks. Fixes incoming.
