### ISSUE TITLE
OSARA cannot report when list controls have focus, seems to be caused by something in reaper.ini

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#1173]
OSARA can't report when focus is in list boxes at the moment, I'm aware of at least 5 machines where this is the case, they're spread across Win 10/11, NVDA JAWS and Narrator. It's almost like OSARA has reverted to MSAA instead of UIA, but I don't think that's it, because the problem persists with a fresh reaper-extstate.ini, whereas reverting reaper.ini to defaults brings the functionality back.

To reproduce:
1. Move keyboard focus into either the MIDI Event List editor or file list in Media Explorer.
2. Try making OSARA speak by hitting ShortCut Help. If unsuccessful...
3. Revert reaper.ini to stock, it works again.
4. Configure for optimal accessibility. It'll still work, so this isn't caused by any of the values we're setting when starting from stock.

How do we chase this down? I don't even know when it broke as a starting point.

**Comment by ScottChesworth** [comment]
I've started trying to chase this down in reaper.ini. Notes coming up.

The issue is caused by something in the [reaper] section. Unfortunately that is by far the biggest section of the file.

At factory settings there are 23 lines written to the reaper section. Configuring my preserved broken ini to match all of those settings doesn't fix the problem, ergo I guess it's something outside of those default keys. In my ini file that could be 900 other lines *gulp*.

I've confirmed that resetting the [reaper] section also works on another machine.

Jen has an unafflicted ini. Comparing, there are 40-something lines which are unique to mine, so I've tried removing those. No dice.

There were 83 settings that are present in both but configured differently, I've tried reconfiguring mine to match those. Also no dice.

So, is it a combination of settings? Did I miss a different test worth trying? Not sure where to go from here.

**Comment by jcsteh** [comment]
Can you please attach an afflicted ini?

**Comment by ScottChesworth** [comment]
[reaper.ini.txt](https://github.com/user-attachments/files/17999724/reaper.ini.txt)

Had to append txt extension to get it attached.

**Comment by ScottChesworth** [comment]
I can round up other inis if needed.

**Comment by ScottChesworth** [comment]
I've learned another symptom of this. Using the afflicted ini attached above, speech interrupt doesn't work when "Report changes made via control surfaces" is enabled in OSARA Config. Using an unafflicted ini or reverting to stock resolves that. I've started collecting broken configs, not sure what to do with them yet, just seems like it might be useful. Any advice appreciated.

**Comment by jcsteh** [comment]
With your broken ini file, OSARA UIA fails to initialise. I don't know why yet, but that explains both the symptoms.

**Comment by jcsteh** [comment]
The offending setting is full screen. If you have full screen enabled when REAPER starts:

1. REAPER actually runs that command early during startup.
2. OSARA intercepts the command and tries to speak "full screen".
3. But UIA initialisation hasn't happened yet!
4. Therefore, when OSARA tries to speak, it sees that we can't use UIA and it caches that forever.
5. UIA initialisation happens very soon after, but we've already cached that we're not allowed to use it in 4), so no UIA after that.

Irritating.

**Comment by jcsteh** [comment]
Hmm, full screen doesn't seem to be enough. I can't reproduce this even with full screen enabled with my own reaper.ini. But either way, the temporary workaround is to turn off full screen. I'm still working out how to fix this correctly.
