### ISSUE TITLE
How do I intercept an SWS action and call a cmd function?

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#1179]
I'd like to intercept an SWS action. I've found a bunch of them listed in POST_CUSTOM_COMMANDS, they all call post functions, but I need to call a cmd instead because I want to compare some item properties before and after this action runs, aiming to make a more accurate report.

So I tried adding this line to the COMMANDS lookup table:
`{MAIN_SECTION, {DEFACCEL, nullptr}, "_SWS_DEFAULTFADES", cmdResetItemFadesToDefault},`
It builds, but REAPER crashes instantly with that build installed. DOH!

Using an SWS action ID in COMMANDS seems to be what causes REAPER to crash. I verified that by switching to a stock action instead. REAPER opens fine and my function seems to work as well, but there isn't a stock action that has the exact behaviour of this SWS one.

Any advice on how to wangle it appreciated.

**Comment by jcsteh** [comment]
It's not currently possible. I can make it possible, but it'll require a new map and a bit of new code in delayedInit().
