### ISSUE TITLE
some confusion regarding the development builds

### ISSUE THREAD

**Issue by zersiax** [jcsteh/osara#120]
At the moment, the snapshots have filenames starting with 2016.1 and only two snapshots are available, one for Windows and one for Mac OS X.
These snapshots don't seem to have a date associated with them either, so I have no idea if this is actually the latest version. I would say it isn't judging by the filename, but I'd also doubt that a snapshot thats more than a year old would still be offered.
I tried to build from source to compare, but I'm having a lot of trouble getting scons to find the windows SDK files on Win10 so that ship isn't sailing for now.

**Comment by jcsteh** [comment]
[**@jcsteh**](https://github.com/jcsteh) commented on [Aug 18, 2017, 11:27 PM GMT+10](https://github.com/jcsteh/osara/issues/120#issuecomment-323353294 "2017-08-18T13:27:47Z - Replied by Github Reply Comments"):
> Having dates on snapshots would still be useful, so I'm leaving this open to deal with that.

Done.
