### ISSUE TITLE
Requesting action feedback for Options: Toggle auto-crossfade on/off

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#130]
Discussion on the Whatsapp group indicates a consensus that action feedback for Options: Toggle auto-crossfade on/off would be a useful addition.

**Comment by jcsteh** [comment]
For future reference, it'd be super helpful when requesting anything specific to certain actions if people could include:

1. The exact name of the action (as you did here);
2. The key bound to that option in the key map; and
3. The id of the action (see the context menu for the item in the Actions list).

If you see other issues where this isn't included, providing this information for them is also a way you can help. I can obviously get these myself, but it saves me some time if they're just included, especially as looking these up sometimes takes longer than the tiny code change in the really simple cases like this one.
