### ISSUE TITLE
Request: action feedback for playrate adjustments

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#131]
Feedback for the following actions is a popular request, particularly in light of how readily accessible and easy to knock by mistake these are in the keymap.

Transport: Increase playrate by ~6% (one semitone)
Key: Shift+=
ID: 40522

Transport: Decrease playrate by ~6% (one semitone)
Key: Shift+-
ID: 40523

Transport: Increase playrate by ~0.6% (10 cents)
Key: =
ID: 40524

Transport: Decrease playrate by ~0.6% (10 cents)
Key: -
ID: 40525

If there's anything else I can do to streamline requests, just shout.

**Comment by jcsteh** [comment]
As per discussion in #153, when implementing this, it should not be reported while audio is playing.
