### ISSUE TITLE
Suggestion to change which editor action is bound to e.

### ISSUE THREAD

**Issue by kara-louise** [jcsteh/osara#132]
As you are aware, e is bound to the action "Item: Open item inline editors" ID 40847 by default.
However, since the inline editor is currently not accessible, I suggest that you bind it to "Item: Open in built-in MIDI editor (set default behavior in preferences)" ID 40153.
This will potentially alleviate frustration for new and experienced users alike, as accidentally opening the inline editor can cause navigation issues and lack of speech feedback.

**Comment by kara-louise** [comment]
I saw there's discussion regarding improving the keymap, so thought I'd bump this issue up.

**Comment by ScottChesworth** [comment]
Good shout @kara-louise , I'd totally missed this. Seems sensible to me. Floating in the key map group now.

**Comment by kara-louise** [comment]
Brilliant.
Thanks @ScottChesworth.
