### ISSUE TITLE
Automation Items

### ISSUE THREAD

**Issue by Justinmac84** [jcsteh/osara#133]
Hi, 

Thanks for all the excellent work you've done on automation items so far. I've been using them a bit and have some feedback, which I did post to the RWP list, thinking that I wouldn't be able to find the Github page here without the web address, but I figured here would be the better place. 

1. Would it be possible to alter how the focus moves away from automation items so that it's less easily lost? When you have an envelope selected for example and you click insert automation item, it will do it, but you can't select the item you've just inserted without reselecting the track and then the envelope. 

Likewise, if you move along the time-line, you have to reestablish focus. This makes other issues I've noticed more problematic. 

2. Would it be possible to make it so that, when an automation item is selected, pressing alt shift end will take you to the end of it just as it does with a regular item? Here's a use-case. 

I had one file from which I was cropping monster sounds to render by time selection. I wanted a tiny little fade in and out at the top and tail of each file. It wasn't possible to do this with item fades because it was a multi-track project. I created automation items with my fades and pasted them along the time-line in the desired places. Obviously though, I wanted to set the end of my time selection at the  end of the second automation item in each pair, where the fade-out would finish. I found that pressing alt shift end took me to the end of the project, since it just contained two copies of the same media item on different tracks. 

3. As I think used to be the case with envelope point navigation, often Osara will get stuck on a certain automation item. You'll be control cursor keying through and it will refes refuse to go  further than a certain item in one direction, so that, if I want automation item 5 and I'm on 15, if I'm lucky I'll be able to get there by pressing control home and going that way and if not, I'll have to press control home, control cursor right til it gets tuck, then go a bar forward to clear the item boundary, then refocus the automation item by the process I described before. 

4. This could be something to do with the way automation items work under the hood, but as I was pasting the same items along the time-line, Osara kept reporting that more and more envelope points were being added. I don't remember the exact numbers now, but it went from something like 15 to 18 to 23 to 26 etc. Thing is, I'm not certain it went in jumps of three, but regardless, the item I was creating should, I believe, only have been a three envelope point item. 

5. Again, I'm not sure how automation items work, this could be a desired behaviour, but once you've incorporated envelope points into an automation item, you can no longer navigate between them with alt j and k, not even if you use the action to delete the automation item but preserve the underlying envelope. Is there a way we could get at the envelope points the item has created or encapsulates in case we need to do fine tweeking? 

6. Would it be possible to label the sliders in the automation items properties dialogue as they don't speak for me? Perhaps this is only something that could be done natively. 

7. This could well be caused by a fault in my understanding of how automation items behave, but, once I had all my takes deliniated, I wanted to glue the pairs of automation items that comprised their fade in and fade out so that one would do both. I glued them, having used control shift cursor right to select the pair, would it be possible by the way to have control shift space report the selection of automation items, so I should only have glued the first two, but doing so changed the behaviour of the third automation item. It caused things to play at a different volume than they should have. 

I appreciate you are very busy with other more important things and that it's Christmas, so I'm not expecting a super fast response or anything, but if anyone could have a look at these things I would be very grateful. 

Hope you enjoyed the holidays, 

Regards, 

Justin

**Comment by jcsteh** [comment]
These all sound like valid requests (albeit with varying priorities and some of which probably need to be fixed in REAPER itself). Please file each separate issue as a separate GitHub issue, as each will have a different solution and priority. This also makes it easier to keep track of questions, answers, comments, etc. associated with each specific issue. While these are certainly related, there's a very clear distinction between them. Thanks.

**Comment by jcsteh** [comment]
Closing, as separate issues have been filed as requested. Thanks!
