### ISSUE TITLE
Labelling Automation Items Sliders

### ISSUE THREAD

**Issue by Justinmac84** [jcsteh/osara#135]
Hi, 

Is there a way, from within Osara, to label the sliders within the automation item properties dialogue? At the moment neither the sliders nor edit boxes are labelled. 

I imagine that labelling the sliders within the actual dialogue would be a Reaper native thing, but perhaps control shift p could also open an automation items parameters dialogue when the context was right? 

Thanks, 

Justin

**Comment by jcsteh** [comment]
I don't think having an OSARA parameters diaog for this makes sense, since the native dialog would be just fine if it had labels. Rather, I think this is something that should be fixed in REAPER.

**Comment by jcsteh** [comment]
I've reported this to Cockos.

**Comment by jcsteh** [comment]
Fixed in REAPER 5.91. Haven't verified myself.
