### ISSUE TITLE
Automation items: Focus and Context

### ISSUE THREAD

**Issue by Justinmac84** [jcsteh/osara#136]
I'm not sure how a solution to this would be implemented, but the current way in which automation items are focussed can make workflows quite cumbersome.

For example, if you highlight an automation item and so much as move down the timeline by bar for example you will lose focus so that you have to rehighlight the track, reselect the relevant envelope and then reselect the automation item you want, which, of course, moves your cursor from where you moved it to on the timeline. 

With envelope points, you are able to navigate the timeline without focus on the envelope breaking. I appreciate that, specially if you're working on multiple automation items on multiple envelopes across multiple tracks, the focus rules would need to be quite strict, but I wonder if there's a better way?

**Comment by jcsteh** [comment]
Can you please clarify what you mean by losing focus? What actions are you
trying after moving down the timeline? If I move to next/previous envelope
point after moving through the timeline, it still moves between points in
the automation item I last selected.
