### ISSUE TITLE
Unextpected Behaviour When Gluing Automation Items 

### ISSUE THREAD

**Issue by Justinmac84** [jcsteh/osara#139]
I'm not sure if this is an Osara issue or more to do with my understanding of automation items, but I was creating pairs of automation items as I described, one to fade things in and one to fade them out and then I wanted to turn each pair into one item. 

I selected a pair of items using control shift cursor right, then I glued the items, but, for some reason, this affected the way automation item three behaved, causing it to have a different volume. 

I don't know whether you can suggest anything or whether this is Reaper native behaviour or not.

**Comment by jcsteh** [comment]
I don't see how this could be an OSARA issue. OSARA just selects the items, but it doesn't override the glue action in any way. You'd need to discuss this with REAPER people, perhaps on the forums.
