### ISSUE TITLE
Keymap: slight inconsistency when setting grid in MIDI editor

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#143]
Just noticed that the following action is mapped to 0, but not duplicated on CTRL+Shift+0 which would be the expected ux from the current keymap.

Grid: Set to 1/48 (1/32 triplet)
40189

Not the end of the world, just filing for next time there are keymap updates.

**Comment by iBlindTech** [comment]
Issue exists on Mac key map as well in both Main and Midi Editor 

This is corrected in the Mac version of proposed revisions now for next update.  

On 16 Jan 2018, at 5:03 pm, ScottChesworth <notifications@github.com> wrote:

Just noticed that the following action is mapped to 0, but not duplicated on CTRL+Shift+0 which would be the expected ux from the current keymap.

Grid: Set to 1/48 (1/32 triplet)
40189

Not the end of the world, just filing for next time there are keymap updates.

**Comment by GianlucaApollaro** [comment]
Hi, the reason of this is my machine didn't let me assign that action to CtrlShift0, don't know why

**Comment by jcsteh** [comment]
This is fixed by the key map updates in 4c13dfb2.
