### ISSUE TITLE
Request: action feedback for setting grid in TCP

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#144]
This hasn't specifically been requested yet, but if action feedback for grid settings gets implemented for the MIDI editor, the most consistent ux would be for those actions to talk in the TCP too. Actions, assignments and IDs follow:

Grid: Set to 1
CTRL+Shift+1
40781

Grid: Set to 1/2
CTRL+Shift+2
40780

Grid: Set to 1/32
CTRL+Shift+3
40775

Grid: Set to 1/4
CTRL+Shift+4
40779

Grid: Set to 1/6 (1/4 triplet)
CTRL+Shift+5
41214

Grid: Set to 1/16
CTRL+Shift+6
40776

Grid: Set to 1/24 (1/16 triplet)
CTRL+Shift+7
41213

Grid: Set to 1/8
CTRL+Shift+8
40778

Grid: Set to 1/12 (1/8 triplet)
CTRL+Shift+9
40777

**Comment by chrisbelle2015** [comment]
Seems like  this used to talk sometimes, then I couldn't get it to work, 
but I know those control shift top number row keys did speak the grid 
settings to me before.
I don't remember which build of Osara, but I know they were work,ing, so 
who knows if it was a happy accident or what, I do know they report on 
the training mode.
