### ISSUE TITLE
cuestion: Can bars and or beats be spoken while recording or playing?

### ISSUE THREAD

**Issue by aefren** [jcsteh/osara#147]
Sometimes when i'm recording or just listening a recorded audio i need to know where i am.
When i'm just playing is simple to check the time line, but not when recording because both my hands are playing my instrument.

How can i set a toggle to say or not the bars or both bars and beats?

**Comment by aefren** [comment]
that's right. but i can't press any button when i'm playing my guitar for example.

i need a feedback of position for each bar or beat while i play.

**Comment by jcsteh** [comment]
I don't think this is feasible. In many cases, the speech will end up behind the count because it will take longer for the speech to speak the info in some cases than it will for the time to pass. Good use of a metronome is a far better option here.

**Comment by chrisbelle2015** [comment]
Why don't you assign a foot controler midi device to trigger the action 
to read the time to you?

**Comment by aefren** [comment]
i could be great, but i don't have that controller.

**Comment by ScottChesworth** [comment]
You could use an action marker. For example, if you wanted a heads up
that you're one bar away from the end of a 16 bar passage, you could
move to bar 15, insert a marker (Shift+M), and type !_OSARA_CURSORPOS
in the name field. The exclamation mark tells Reaper to call another
action, and the _OSARA_CURSORPOS string is the action ID of "OSARA:
Report edit/play cursor position". End result is that when you get to
bar 15, Reaper will tell you about it. I guess for this to be most
pleasant on the ears from a ux point of view we'd need an OSARA action
that speaks a custom string, so you could leave messages for yourself
at specific points on the timeline. For what it's worth, I'd make use
of that functionality here too, although in a different context. Mine
would be for short comping notes.
