### ISSUE TITLE
Report Number of Items when Navigating to a Track

### ISSUE THREAD

**Issue by MatejGolian** [jcsteh/osara#15]
It would be great if Osara reported the number of items for the current (touched) track - ideally when navigating to it. Sorry... I just can't be more eloquent. Hopefully it's self-understanding. :D

**Comment by jcsteh** [comment]
It's very quick for a sighted user to get a rough idea of this, so I'm happy to add it. However, I'm curious as to how this is useful; i.e. how it improves your workflow. It'd be great if you can provide such justification/explanation when requesting future features. Thanks.

**Comment by MatejGolian** [comment]
Sorry about that, I'll make sure to provide more info next time.
I think that the main reason to have this feature is that one would instantaneously know whether a particular track contains data or not. This would definitely speed up work because one wouldn't need to check for items manually. Of course, there are empty items too, but the point is that one would know that it has already been worked on the track in question.
