### ISSUE TITLE
Space and Shift+Space stopped working on checkboxes

### ISSUE THREAD

**Issue by GianlucaApollaro** [jcsteh/osara#150]
In the changelog for the new version or reaper we can see
  + Keyboard: pass through spacebar in various windows to main window
This caused the spacebar or shift+spacebar not to toggle checkboxes anymore in the item property window. In fact, when pressing the spacebar we actually play our project, but now, also shift+spacebar, which was our work around to toggle a check box, does not work anymore because it turns the multiselection on.
NVDA users can press NVDA key + numpad enter, but in jaws the thing is actually a bit more complicated, you either have to use the jaws or the touch cursor.

**Comment by jcsteh** [comment]
That's kinda annoying. IMO, this needs to be fixed in REAPER. For now, you can work around this by pressing = (equals) to check the check box and - (dash) to uncheck it. These are lesser known ways of working with standard Win32 check boxes using the keyboard.

**Comment by chrisbelle2015** [comment]
Nice tip, that also insures when the check state isn't known maybe it 
will define for sure the checked and unchecked state.

**Comment by Christianlm** [comment]
Yes, very useful. For those who use the  Spanish  keyboard, or italian keyboard, the corresponding commands for the check boxez are: + (plus) to check and - (Dash) to uncheck.

**Comment by ScottChesworth** [comment]
I've reported the bug in the Reaper forum here:
https://forum.cockos.com/showthread.php?t=205757

**Comment by ScottChesworth** [comment]
Fixed in 5.80 prerelease. Guess this is safe to close. Happy days.

**Comment by jcsteh** [comment]
Thanks for getting it reported, @ScottChesworth!
