### ISSUE TITLE
Requesting check box in preferences dialog to toggle feedback for custom OSARA actions when editing using the piano roll

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#154]
I know you're not keen on over complicating verbosity options, but bear with me, I'm pretty sure there's a strong case for this request.

There is currently no action feedback when editing in the piano roll using actions bound to the numpad. These actions adjust velocities, note lengths, nudge notes by grid unit etc, and they're popular among advanced MIDI users. A decent number of users have come to me making the case that there's some disparity between using those actions (where you're editing based on note playback) and the current ux when navigating events with the arrow keys (where you'll receive action feedback about grid position, note length and the number of notes in a chord each time you move to a new event (whether its required or not)). Additionally, there's currently a significant difference between the ux of editing audio (where a user can disable feedback for transport and scrubbing for a less verbose ux), and editing MIDI (where a fairly high level of verbosity is non-optional).

I've previously been of the opinion that muting the screen reader when action feedback isn't required in the piano roll was a viable workaround, but having recently tackled a few songs containing complex MIDI data where I needed to be as speedy as possible when navigating the piano roll, but also frequently needed to refer to control changes in the event list and input specific values into the note properties dialog, I can vouch that this check box being present would've been massively beneficial to productivity.

FYI, the actions that would be silenced by the proposed new check box are as follows:
OSARA: Move to previous chord (_OSARA_PREVCHORD)
OSARA: Move to previous chord and add to selection (_OSARA_PREVCHORDKEEPSEL)
OSARA: Move to next chord (_OSARA_NEXTCHORD)
OSARA: Move to next chord and add to selection (_OSARA_NEXTCHORDKEEPSEL)
OSARA: Move to previous note in chord (_OSARA_PREVNOTE)
OSARA: Move to previous note in chord and add to selection (_OSARA_PREVNOTEKEEPSEL)
OSARA: Move to next note in chord (_OSARA_NEXTNOTE)
OSARA: Move to next note in chord and add to selection (_OSARA_NEXTNOTEKEEPSEL)

Thanks for considering.

**Comment by jcsteh** [comment]
I think this is reasonable, especially because you can hear the notes/cords
as they are played. It's somewhat akin to scrubbing in that sense. Here's a
question, though: would it be acceptable to link this to the scrubbing
check box or does it need a new one? I don't really care that much, but
thought it worth asking.

**Comment by ScottChesworth** [comment]
I reckon it should be two separate check boxes. Based on observing
people as they learn to reap, the ux I'm seeing here is that the audio
feedback they're getting as they navigate between notes and make
changes with the numpad is informative enough that a relatively new
user might want to decrease the level of spoken feedback before they'd
have put in enough hours to be scrubbing with the same level of
confidence. Also, many newbies seem to tackle learning how to work
with audio and MIDI separately, so I think there's a strong likelihood
that a separate setting would be welcome if they're mixing and
matching their sound sources (MIDI drums and vocals, for example).

**Comment by jcsteh** [comment]
Is this request addressed by the Report MIDI notes in MIDI editor checkbox added in #251?

**Comment by ScottChesworth** [comment]
It is for me, and nobody's moaned at me about it for a while, so closing as part of today's effort to tidy up and prioritize open issues.
