### ISSUE TITLE
requesting action feedback for two widely used MIDI record modes

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#157]
Now that feedback is being provided when cycling through the record modes pertaining to audio by #156, it would be helpful if the most widely used MIDI record modes also spoke. The goal here is for users to be 100% confident about how Reaper is going to behave when they hit record, and consolidate the bread and butter of record mode functionality onto a single key..

The actions we use for this are:
Track: Set track record mode to MIDI overdub (40503)
Track: Set track record mode to MIDI replace (40504)

Thanks in advance, as ever.

**Comment by jcsteh** [comment]
This one doesn't have a cycle though, right? So there's nothing to report except the name of the single mode bound to the action.

**Comment by ScottChesworth** [comment]
Yep, that's correct.

**Comment by ScottChesworth** [comment]
We no longer map the actions mentioned in the OP and feedback has already been implemented for the replacement action "OSARA: Cycle through midi recording modes of selected tracks". Resolved.
