### ISSUE TITLE
Bug: OSARA sometimes loses track of stretch markers

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#161]
Here's how to reproduce:
1. Insert an audio item, and drop a few stretch markers throughout the audio. The amount and position of stretch markers doesn't seem to matter, so long as there's more than one.
2. Navigate between your stretch markers (this is just to verify that OSARA reports them as expected).
3. Go to Media Item Properties, modify the playback rate, and uncheck "Preserve item pitch". I haven't included a specific value for the play rate field because any modification will reproduce the bug here.
4. After clicking "OK" to submit those changes and returning to the TCP, add another stretch marker. As before, any position will do.
5. Now try navigating between stretch markers again, and OSARA fails to report/delete/move them. You'll only be able to work with them again once the item play rate has been returned to 1.0.

Shout if there's anything else I can provide to help diagnose, and thanks in advance for anything you can do.

**Comment by ScottChesworth** [comment]
I've just been made aware that there's still some buggy behaviour to squash here. Commenting instead of starting a new issue because it seems likely that it'll be the same section of code that'll need to be poked. Here are steps to reproduce the unexpected behaviour with Reaper 5.94-1 and OSARA 2018.1pre-116,07bf2c94 for Windows:

1. Insert an audio item, and drop a few stretch markers throughout. The project BPM, amount and positioning of stretch markers doesn't seem to matter.
2. Navigate between your stretch markers (this is just to verify that OSARA reports them as expected), and it does here.
3. Now, go to Media Item Properties and modify item rate,. The state of the "Preserve item pitch" check box no longer seems to have any impact on what'll happen next.
4. Try navigating between stretch markers again. You should find that OSARA will fail to report some of them as stretch markers. When this happens, it's possible to delete them, but not possible to move them using Alt+M "OSARA: move last focused stretch marker to current edit cursor position". You'll only be able to move them again once the item play rate has been returned to 1.0.

As ever, shout if there's anything else I can provide.

**Comment by jcsteh** [comment]
@ScottChesworth, I've seen this myself, but I can't seem to reproduce it at present. Could you possibly reproduce this with a very small project (single track with a single short item), save the project, close and re-open it, confirm that the stretch markers are still broken, and finally, send it to me? Thanks.
