### ISSUE TITLE
requesting action feedback when setting take channel mode

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#162]
It would be useful if action feedback could be provided when setting take channel mode using Shift+F5 through Shift+F8. The actions and IDs we're using are as follows:

Item properties: Set take channel mode to normal (40176)
Item properties: Set take channel mode to mono (left) (40179)
Item properties: Set take channel mode to mono (downmix) (40178)
Item properties: Set take channel mode to mono (right) (40180)

Additionally, I noticed when using this feature earlier on that the setting isn't reported with the usual "checked" feedback by NVDA or JAWS in the item settings application menu for some reason. Only tested on Reaper X64 5.90 so far, but if anyone else can reproduce, might be one for either a "needs Reaper fix" label or one to report in the Cockos bugs forum.

**Comment by ScottChesworth** [comment]
Just got visual confirmation. The current take mode setting is reflected with both visual and speech feedback when accessed from the Items top menu, but not reflected at all when entering the same menu via the Applications key.

**Comment by jcsteh** [comment]
That'll be the weird hacky way OSARA brings up those context menus. Hopefully, the request I've made of Cockos (and which will apparently be implemented soon) will fix that.

**Comment by ScottChesworth** [comment]
Aha, good to know.

**Comment by iBlindTech** [comment]
Will the requested change of Cockos make any difference to The potential of context menus on the Mac?   


On 27 May 2018, at 6:56 am, James Teh <notifications@github.com> wrote:

That'll be the weird hacky way OSARA brings up those context menus. Hopefully, the request I've made of Cockos (and which will apparently be implemented soon) will fix that.

**Comment by jcsteh** [comment]
Hopefully, yes. However, this is somewhat off-topic for this issue. :)

**Comment by ScottChesworth** [comment]
Long since resolved. Closing.
