### ISSUE TITLE
requesting speak next attempted action command

### ISSUE THREAD

**Issue by dgl1984** [jcsteh/osara#164]
This action would speak the name of an action which would immediately follow it.  The idea being that one could create a custom action to add feedback where osara would otherwise have nothing to say.  An example use case would be if someone wanted to add action feedback to an action such as "toggle take reverse," which is currently mapped to v,.  Hearing "toggle take reverse," would give the user no feedback as to the takes playback direction, but if someone accidentally pressed v, they would be alerted.

**Comment by jcsteh** [comment]
My concern is that this could result in a lot of custom actions being
created for this purpose, which could become pretty unwieldy in the
long-run. I guess I'd be fine if this were to be used in personal
configurations, but I wouldn't want to see custom actions like this in the
OSARA key map. I think we'd be better off maintaining a list of actions in
the code which should just get their action names reported. I could
probably split this into a separate file to make it easier for non-coders
to contribute to. Thoughts?

**Comment by ScottChesworth** [comment]
That seems like a great solution here.

**Comment by GarthHum** [comment]
This sounds like an excellent solution. 
So am I understanding this correctly? You would have a text file that resided in the extensions folder, users could, for example put an action ID into the file and this would tell OSARA to speak this action name when it was pressed? So the information would not be as meaningful as the current actions coded to speak, however it would give end users the ability to get some feedback on desired actions. 
On 30 May 2018, at 8:33 am, James Teh <notifications@github.com> wrote:

My concern is that this could result in a lot of custom actions being
created for this purpose, which could become pretty unwieldy in the
long-run. I guess I'd be fine if this were to be used in personal
configurations, but I wouldn't want to see custom actions like this in the
OSARA key map. I think we'd be better off maintaining a list of actions in
the code which should just get their action names reported. I could
probably split this into a separate file to make it easier for non-coders
to contribute to. Thoughts?

**Comment by jcsteh** [comment]
I was imagining a list hard-coded into OSARA that people like you, Scott,
etc. could contribute to, not a user editable file. If we wanted this to be
user configurable, I'd go with the original custom action idea, since we
can leverage REAPER's custom action user interface that way. It all depends
whether this is meant for distribution with OSARA or configuration by
users. If the former, I don't want to use custom actions. If the latter,
custom actions make sense.

**Comment by ScottChesworth** [comment]
Seems like the hard coded list option would definitely generate less
additional support requests whilst still enabling us to get some stuff
done without extra gruntwork for Jamie. I'd vote for that one.

**Comment by jcsteh** [comment]
The OSARA source includes a list of commands which just speak simple messages. Given that we now have other people who are set up to build the source code (even @ScottChesworth!), I think we should just edit that list. All you need is a text editor. Search for POST_COMMAND_MESSAGES (or MIDI_POST_COMMAND_MESSAGES) in src/reaper_osara.cpp and just copy the format for the lines inside that. For example:
`	{40491, "all tracks unarmed"}, // Track: Unarm all tracks for recording`
The first bit of text is the action id. The second is the message to speak. The third is just a comment so we know what action it's for when looking back at the code. You just make the change and then rebuild the source.

**Comment by ScottChesworth** [comment]
Following those instructions, I've just gotten OSARA to insult my mother when I run an action. Bingo! If even @scottchesworth can do it on the first attempt, it's gotta be easy. 👍 

@jcsteh, am I right in thinking that if any useful feedback gets added this way, we'd just submit the modified reaper_osara.cpp to you via a pull request?

**Comment by jcsteh** [comment]
Correctamundo.

**Comment by ScottChesworth** [comment]
Goodly to know. Thankings.

**Comment by ScottChesworth** [comment]
One question whenever you've got time @jcsteh: tinkering with POST_COMMAND_MESSAGES in reaper_osara.cpp, I'm not seeing a line for 40626 "Time selection: Set end point", and yet, it speaks. How?

**Comment by ScottChesworth** [comment]
Oh, just found it in PostCommand POST_COMMANDS[] = { by searching the action ID. I don't get the difference between those two functions yet, but I'll keep poking about.

**Comment by jcsteh** [comment]
POST_COMMANDS is for actions where we want to run some code after the action, rather than just speaking a simple message. I'm not in front of the code right now, but I think the reason the selection commands aren't just messages is that we want to also set OSARA's fake focus to the ruler as well as speaking the message.

**Comment by ScottChesworth** [comment]
Gotcha. Cheers.
