### ISSUE TITLE
Key map error in build 2018.1pre-109,e72fc973

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#168]
I'm getting reports from users with MIDI sustain pedals that in the most recent build, MIDI chan 1 CC64 is bound to the action "Transport: record". The upshot is that anyone who uses a sustain pedal is toggling record every time they use it. Really sorry that this slipped through the net man, I don't have a sustain pedal here so it went unnoticed until just now.

**Comment by jcsteh** [comment]
Any idea whether this is true in the Mac key map? Are you able to send me updated key maps ASAP? I should be able to add them pretty quickly.

**Comment by ScottChesworth** [comment]
It's not a problem in the Mac key map. I'll remove the dodgy
assignment and email you an updated Windows map in a sec.
