### ISSUE TITLE
SWS actions not speaking under Mac

### ISSUE THREAD

**Issue by GarthHum** [jcsteh/osara#169]
The SWS actions listed below which have voice feed back under Windows, don't speak under Mac.
*  SWS/BR: Options - Cycle through record modes
*  Xenakios/SWS: Nudge active take volume up
*  Xenakios/SWS: Nudge active take volume down

Not sure if this is all of the SWS actions which have been coded to speak, or indeed if it is related to them being SWS or not. 
Action command IDs. 
Record Cycle: _BR_CYCLE_RECORD_MODES
Nudge Up: _XENAKIOS_NUDGETAKEVOLUP
Nudge Down: _XENAKIOS_NUDGETAKEVOLDOWN

**Comment by jcsteh** [comment]
The two take volume actions don't speak in Windows either. I'm not sure why the record modes one wouldn't work, though.

**Comment by ScottChesworth** [comment]
I think Garth meant to inquire about the actions bound to
CTRL+Shift+UpArrow and CTRL+Shift+DownArrow which nudge track volume
in DB increments. These do provide feedback for Windows users, but not
for the Mac folk. I'm following up to check that you're aware of this
variation in UX more than anything, although if this is new news and a
fix can happen, the action feedback when cycling record mode Garth
mentioned is the one Mac users are missing the most.

Actions and IDs are:
Xenakios/SWS: Nudge volume of selected tracks up (_XENAKIOS_NUDGSELTKVOLUP)
Xenakios/SWS: Nudge volume of selected tracks down (_XENAKIOS_NUDGSELTKVOLDOWN)

**Comment by jcsteh** [comment]
Oh, actually, I totally see why that is. The SWS stuff has to be registered
later than anything else, but the delayed registration code is currently
Windows specific. The Cockos documentation suggests the timer mechanism I'm
using won't work on the Mac, but now that I think about it, I use the same
mechanism for watching peaks with Peak Watcher. Does Peak Watcher correctly
report peaks on the Mac?

**Comment by jcsteh** [comment]
I think I've fixed this, but I don't have time to actually test this on a Mac. It's in the [latest Mac snapshot](https://osara.reaperaccessibility.com/snapshots/osara_2018.1pre-76,1aa7fb8d.dmg) if you want to give it a try.

**Comment by GarthHum** [comment]
That’s right Scot. It is really only the cycle rec one that is a concern. Apologies   

Sent from my iPhone

On 7 Jun 2018, at 10:28 am, ScottChesworth <notifications@github.com> wrote:

I think Garth meant to inquire about the actions bound to
CTRL+Shift+UpArrow and CTRL+Shift+DownArrow which nudge track volume
in DB increments. These do provide feedback for Windows users, but not
for the Mac folk. I'm following up to check that you're aware of this
variation in UX more than anything, although if this is new news and a
fix can happen, the action feedback when cycling record mode Garth
mentioned is the one Mac users are missing the most.

Actions and IDs are:
Xenakios/SWS: Nudge volume of selected tracks up (_XENAKIOS_NUDGSELTKVOLUP)
Xenakios/SWS: Nudge volume of selected tracks down (_XENAKIOS_NUDGSELTKVOLDOWN)

**Comment by GarthHum** [comment]
Excellent, thanks Sir. 
Works perfectly now. 
Garth 

On 7 Jun 2018, at 11:44 am, James Teh <notifications@github.com> wrote:

I think I've fixed this, but I don't have time to actually test this on a Mac. It's in the latest Mac snapshot <https://osara.reaperaccessibility.com/snapshots/osara_2018.1pre-76,1aa7fb8d.dmg> if you want to give it a try.

**Comment by GarthHum** [comment]
Oh, and yes Peak watcher works just fine on the Mac


On 7 Jun 2018, at 11:20 am, James Teh <notifications@github.com> wrote:

Oh, actually, I totally see why that is. The SWS stuff has to be registered
later than anything else, but the delayed registration code is currently
Windows specific. The Cockos documentation suggests the timer mechanism I'm
using won't work on the Mac, but now that I think about it, I use the same
mechanism for watching peaks with Peak Watcher. Does Peak Watcher correctly
report peaks on the Mac?
