### ISSUE TITLE
request for solo defeat support

### ISSUE THREAD

**Issue by ns-studios** [jcsteh/osara#171]
As it is a feature I use often, I'd love to see Osara support the solo defeat feature if possible; particularly the action feedback for Track: Toggle track solo defeat, and a way to see if a track has solo defeat on (probably by either arrowing around the track list (where it currently says soloed/muted/armed/etc.), or by an action which would say the names of all tracks that have solo defeat on).

**Comment by ScottChesworth** [comment]
I'm about to add solo defeat actions to the next revision of the keymap, so yes, if there's any way defeat can be included in what OSARA reports when moving to a track and in the report from "OSARA: Report soloed tracks", that would be fantabulous. One for @RDMurray , perhaps?
