### ISSUE TITLE
Opening the presets combo box in the FX window for faster scrolling

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#173]
When scrolling through the presets combo box in the FX window using Up or Down arrows, the default behaviour is that the combo box remains closed, and as a consequence, plugins will load each preset as the user scrolls. With most EQs and compressors and the like this isn't a problem because plugin settings update almost instantaneously, but with many synth libraries and more resource intensive plugins, it decreases efficiency when searching through presets.

The UX for sighted users is different, and a lot more productive. They single click on the combo box to open it, then scroll through presets without the plugin updating presets as they pass while the combo box is open. A double click on the desired preset closes the combo box, and only then does the plugin load those settings.

Poking at this with object nav, I can replicate the behaviour that my sightling reported, but it involves more button bashing than is practical.

Part of the problem seems to be that Alt+DownArrow and Alt+UpArrow don't get passed through to the FX window, so it's not currently possible to open the presets combo box without object nav.

Is there anything that can be done to improve the UX here, either by OSARA or Cockos?

Thanks in advance for any thoughts.

**Comment by jcsteh** [comment]
I could probably hack around this, but it'd be far less ugly and less prone to breakage if Cockos dealt with this. I'll see about asking them at some point.

**Comment by jcsteh** [comment]
@ScottChesworth, you seem to be having some impact communicating such requests to Cockos. I don't think this request requires any technical input from me to be actionable, so do you want to give this a try?

**Comment by ScottChesworth** [comment]
Happy to give it a go. I'm slightly concerned that I don't know the technicalities involved in what I'm asking for though. Would it be possible to pass through Alt+Up and Alt+Down only when focus is on that combo box, for instance?

**Comment by jcsteh** [comment]
That would be my suggestion, yes.

**Comment by ScottChesworth** [comment]
Oki doke, I've asked. Let's see how we go. The post is here FYI:
https://forum.cockos.com/showthread.php?p=2062589

**Comment by ScottChesworth** [comment]
I've raised this a fair few times with Cockos since opening, both via the forum and prodding via email. No sign of a fix forthcoming and it's really starting to burn as synth VSTIs get more resource hungry. Also, the more large RPL files are being created and shared within the community, the more often this becomes an issue that impedes creative flow.

Is it time to start hacking at it with a digital spade yet, @jcsteh ? :)

**Comment by jcsteh** [comment]
@ScottChesworth, I'm still unclear on one thing here. For me, even if I use NVDA object nav to open the combo box, using up/down arrows still changes the preset as I move despite the combo box being open. Does that match your experience? If not, I'd like to figure out what we're doing differently. If so, we need something more than just a keystroke to open the combo box.

**Comment by ScottChesworth** [comment]
That matches my experience yep, but I have a cloogy workaround.
Interact with the combo box using object nav, NVDA+Enter on the Open thingy (I forget what type of element it is and I'm not in front of Reaper right now), then interact with the list box. You still can't use Up/Down arrows, but at that point you'll be able to scroll through the list using previous/next object without the plug-in loading presets on the fly. NVDA+Enter on the next preset you want to load.
Does that help any?

**Comment by jcsteh** [comment]
Okay, that matches my understanding. Good good, just wanted to make sure we
were on the same page.
