### ISSUE TITLE
Requesting an option in the OSARA dialog to silence track numbers

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#175]
Had a user request for this that I said I'd pass along. Imagining it to be a toggle controlled with an additional check box in the OSARA dialog.

Penny for your thoughts?

**Comment by jcsteh** [comment]
It's also not particularly useful. What if you have 6 unnamed tracks? now
you can't tell them apart. My inclination is to report the track number
when there's no name, but the reason I asked is that users really need to
be thinking about the full consequences of anything they request, including
all the possible edge cases. :)

**Comment by ScottChesworth** [comment]
@GianlucaApollaro, did you manage to collect feedback about this from whoever requested it?

**Comment by betov75** [comment]
An option like : "Report track's number after track's name" (in better english than mine :) )
When unchecked, it's as usual.
When checked: Violins 1 - Track 1 - (if fx is reported: Fx BBC Symphony Orchestra) etc..
It can be helpful I think. Thanks!

**Comment by ranetto** [comment]
I would say like this:
when the check is unchecked everything remains normal, when it is selected the track number is not announced.
In case the name field were to be empty, osara could still either vocalize the track number or say no name.
How about James?
I would love to!

**Comment by ScottChesworth** [comment]
How about a prompt like "Report track numbers", then two radio buttons, "Before track name" and "after track name". Before is default.

If a track doesn't have a name, revert to current behaviour (report its number, irrespective of radio button state).

Tbh I'm still not thrilled with the difference in UX that will be present once this is introduced, but if we're doing it, I reckon that'd be the intuitive GUI for it in OSARA Config.

**Comment by ranetto** [comment]
YES scott, I would say yes, default checked before the name of the track, so as now, the second is not checked after the name of the track, or if you also uncheck the first and clearly the second does not report any number.
How about Scott?
So even beginners would have no problems before it is explained to them how much the behavior would remain the current one.

**Comment by betov75** [comment]
Under 100 tracks, it's no big deal. But over that, the number is slow to pronounce. I think it's a good suggestion but I don't know the best way to implement it. It'll really help my workflow but it's not a tragic loss of productivity either. I use a regex entry in my NVDA speech dictionary to remove them and it doesn't seem to affect the whole experience. I don't use much enumerations.

My two cents.

**Comment by ranetto** [comment]
Cheo James, as you have heard, there are several solutions, but giving additional work to NVDA seems absurd to me.
It would be nice to implement Scott's proposed solution:
what do you think about it?

**Comment by ranetto** [comment]
Hi everyone, sorry James yes I was aware that there was an open problem but I thought I had to present it in a different way.
Anyway, if you think not to do it in osara do you have any idea how I can get this in NVDA?
Is there a script I can implement for this?
Is there a way to put a regular expression in the NVDA dictionary to eliminate the trace number in reaper?
I saw some comments from sighted people in the reaper forum who solved this problem by changing one of the themes:
if someone has an answer can you help me?
Thanks in advance for this!

**Comment by ScottChesworth** [comment]
Bump. This has come up again on RWP. @jcsteh, any thoughts on the most recent proposal for what it might look like?

**Comment by jcsteh** [comment]
> How about a prompt like "Report track numbers", then two radio buttons, "Before track name" and "after track name". Before is default.

Is there a reason we went from silencing track numbers to having an option to reorder this? I can understand if you don't care about track numbers, but in that case, you probably want them turned off altogether, no?

I'm really reluctant to go down the slippery slope of configuration to reorder things.

**Comment by jcsteh** [comment]
Should this option impact other commands which report tracks (e.g. report selection, report muted tracks) or just navigation?

**Comment by ScottChesworth** [comment]
My bad, slipped down a rabbit hole. Here's what would take care of the majority of requests that I've seen:
1. Add a check box to OSARA Config labeled "Report track numbers", checked by default to preserve current behaviour.
2. When that check box is un-checked, OSARA no longer reports track number.
3. If tracks are unnamed, OSARA reverts to reporting track number as per current behaviour.
Is that doable?

**Comment by jcsteh** [comment]
Yes, that's doable, though implementation motivation will be a struggle due to the tedium of adding anything to the GUI. I wish Win32 GUI resource files weren't so tragically bad to work with.

Should this be a combined option for tracks and items (#381)? Also, see my previous question.

**Comment by ScottChesworth** [comment]
> Should this option impact other commands which report tracks (e.g. report selection, report muted tracks) or just navigation?
> 
Ooh, that's a good thought. I'd like to see the change reflected in reports here, but then, I always name tracks. Suppose a mixture of names and sometimes just numbers could make the reports kinda difficult to follow, but is naming tracks something that we can reasonably expect all users to be doing? In larger projects (hence potentially lengthier reports), I reckon that's a reasonable expectation.

**Comment by ScottChesworth** [comment]
> Yes, that's doable, though implementation motivation will be a struggle due to the tedium of adding anything to the GUI.
> 
Do you reckon I'm at a point where I could tackle this, perhaps with a few pointers to get me going? Would be happy to help carry the weight if so.
> Should this be a combined option for tracks and items (#381)?
> 
Given that their are still unresolved questions in #381, and item navigation is silenced by the "Report time movement during playback/recording" nowadays, I'd say you've already done enough to make item navigation productive.

**Comment by jcsteh** [comment]
That has to be one of the most tedious, boring, unrewarding OSARA features I've ever implemented. The GUI actually wasn't the worst bit. It turned out there were other things that made this less than trivial.

**Comment by jcsteh** [comment]
As a side note, I guess I found it hard to see the benefit in this because I have my speech rate so damned high (somewhere between 800 and 960 wpm depending on what I'm doing).

**Comment by ScottChesworth** [comment]
> The GUI actually wasn't the worst bit. It turned out there were other things that made this less than trivial.
> 
Thanks for slogging through man.
Most people don't get anywhere near that speech rate, so they'll feel more of a benefit, for what it's worth.

**Comment by jcsteh** [comment]
Oh, I realise that. It was more of an idle thought than anything.
