### ISSUE TITLE
Request: action to speak current tempo

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#179]
Would it be possible to add an action that announces the current tempo? Sighted folk have this info readily available to the right of the transport bar in the TCP.

Obviously not a high priority request, but it came to me through WhatsApp and seemed worth cataloging.

**Comment by ranetto** [comment]
I would say that this action could pronounce the tempo if pressed once, like "tempo 110", and the time if pressed twice, like "4 quarters" what do you think?
Scott, It doesn't seem like a good method to decrease and increase the time to know what it is in real time.
This could lead to problems if perhaps at that moment something slows down and an increase or decrease is missing.

**Comment by ScottChesworth** [comment]
I like the idea of one press for tempo, two presses for time sig. Not so keen on the idea of trying to interpret time sigs in words though, that language could get super weird super fast with more complex time signatures. Just report what's in Project Settings I guess, like "4/4".

**Comment by jcsteh** [comment]
What's the advantage of the double press here? Would you ever need to know
the time signature in a hurry such that hearing the tempo first would be
too verbose? I'm thinking a single press could say, for example, "120, 5/8".

The double press isn't too hard to implement, but I also don't want to make
this more complicated than it needs to be from a UX perspective.

Definitely agree that we shouldn't try to interpret the time signature.

**Comment by ranetto** [comment]
Hi James and Scott, no, maybe you were misled by the fact that I wrote the numbers in words, but I absolutely did not intend to translate the numbers into words:
I think 3/4 and the like is fine.
james, if you think that the double pressure can create problems, the single pressure is also fine where it is said first 120 and then 4/4.
I had given the indication of the single pressure for the time and the double pressure for the 4/4 only for the fact that the user could have chosen whether he wanted to hear only the time or only the time.
However, it is also fine with a single push to say both.
Thanks James and Thanks Scott.

**Comment by ScottChesworth** [comment]
There's a new action - "OSARA: Report tempo and time signature at play cursor; press twice to add/edit tempo markers" - that addresses everything here. Guess we forgot to close when merging. Doh!
