### ISSUE TITLE
Request: feedback for two new SWS actions ("Select nearest previous folder" and "Select nearest next folder")

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#187]
I requested some additional actions from SWS which improve the UX of folder navigation a while ago, and they've just gone live in SWS version 2.10.0.1. It would be wonderful if you could implement action feedback for these and add them to the key map. The suggested key map assignments below were a consensus on the Reaper Access WhatsApp group.

Action: SWS: Select nearest previous folder
ID: _SWS_SELNEARESTPREVFOLDER
Key: CTRL+Alt+Shift+UpArrow

Action: SWS: Select nearest next folder
ID: _SWS_SELNEARESTNEXTFOLDER
Key: CTRL+Alt+Shift+DownArrow

As ever, shout if there's anything I can do to be more useful.

**Comment by RDMurray** [comment]
implemented in pr  #229
