### ISSUE TITLE
Request: feedback and key map assignment for new SWS action "SWS/NF: Cycle through MIDI recording modes"

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#188]
In SWS 2.10.0.1, they've also added an action to cycle through MIDI record modes as per my request. Can we get feedback for this and have it added to the key map?

Action: SWS/NF: Cycle through MIDI recording modes
ID: _NF_CYCLE_MIDI_RECORD_MODES
Key: Shift+\

Note: This key map assignment will overwrite "Track: Set track record mode to MIDI replace". once it's assigned, "Track: Set "track record mode to MIDI overdub" will no longer be needed (currently bound to the Backslash key).

Cheers.

**Comment by RDMurray** [comment]
Unfortunately this action has the same problem as "SWS/NF: Cycle through track automation modes" where in the mode is cycled for each track individually.  I suggest making it the same as to the action I created for automation in #217 where all selected tracks are set to the same mode starting from the last touched track.
