### ISSUE TITLE
Action feedback for "SWS/NF: Cycle through track automation modes"

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#190]
Also added in the newest public build of SWS as per my request is an action to cycle track automation modes. It would be great if you could implement feedback for it and shove it on the key map.

Action: SWS/NF: Cycle through track automation modes
ID: _NF_CYCLE_TRACK_AUTOMATION_MODES
Key: CTRL+Alt+\

Cheers :)

**Comment by RDMurray** [comment]
fix in PR #217 which implements a new action with more predictable behaviour.
