### ISSUE TITLE
Add check box in OSARA Config dialog to silence feedback when navigating by bar/beat

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#192]
I know you're not typically keen on adding check boxes to the OSARA configuration dialog, but wanted to run this request by you because - to me - there does seem to be a solid justification.

We have some OSARA users who are editing longform audio content for podcasts and such. These users typically work with their time unit for ruler set to either Minutes:Seconds or Hours:Minutes:Seconds:Frames, and they set their project BPM and time signature to values which make navigating by bars and beats skip in useful increments of time. However, when navigating using the actions and keystrokes listed below, they currently receive non-optional feedback in bars/beats, even though their project and workflows are based on time.

One solution (most often requested) to address this would be a check box in the OSARA Configuration dialog which toggles feedback for the following actions:

Action: Move edit cursor forward one measure
ID: 41042
Key: PgDown

Action: Move edit cursor back one measure
ID: 41043
Key: PgUp

Action: Move edit cursor forward one beat
ID: 41044
Key: CTRL+PgDown

Action: Move edit cursor back one beat
ID: 41045
Key: CTRL+PgUp

Penny for your thoughts?

**Comment by jcsteh** [comment]
I wonder: do sighted users see bars and beats at all when their ruler is set to just HMSF? I originally thought it always made sense to report bars and beats when moving by that unit, regardless of the ruler. However, if sighted users don't see this, there's an argument for reporting the ruler unit instead. Note that we'd still report bars and beats if the ruler is set to MB/MS. This feels less hacky to me than having an option to silence this and more consistent with the visual UX. Thoughts?

**Comment by ScottChesworth** [comment]
Sorry about the slow reply, only just remembered I was meant to collar my light slave for some observation.

Yes, sighted folk are able to gather different info from the ruler depending on the setting specified in View -> Time unit for ruler.

For example, when set to Measures.Beats / Minutes:Seconds (the most frequently adopted setting by OSARA users), measures and beats are displayed along the top of the ruler, with visual lines that connect the start of each measure to the equivalent reading in minutes and seconds along the bottom. Essentially, these settings that sound like they'd provide info in multiple measurements do exactly what you'd think. Sightlings can gather both measurements at a glance. I think "OSARA: Report edit/play cursor position" is already doing a good job of covering this when it comes to reporting the user's current position, but it does seem like we're missing the ability to choose which units of measurement we'd like to hear when moving.

When I switch to a singular unit such as minutes:Seconds or Measures/Beats, the pertinent info is displayed along the top of the ruler, and the other info disappears. Seems like the same deal in this scenario, with "OSARA: Report edit/play cursor position" nailing it, but reporting movement being more problematic.

The horizontal zoom level effects the granularity of what's displayed on the ruler with all of the time units I tested, but I don't think we need to worry about replicating that.

**Comment by ScottChesworth** [comment]
Jamie, you're a bloomin' legend! Thanks man.
