### ISSUE TITLE
Custom action to report current transport state

### ISSUE THREAD

**Issue by leonardder** [jcsteh/osara#197]
This is a request I got from my brother, who uses Reaper a lot and would like to have an Osara action that does no more than simply report the current transport, i.e. especially to distinguish between the recording and the stopped state.

**Comment by ScottChesworth** [comment]
Now that we have a function to speak strings, probably best implemented as a script.

**Comment by Christianlm** [comment]
I probably searched in the wrong place, but have not found a script that report playing state.
In the meantime i have written this LUA- script which uses reaper.GetPlayState() function.
I'm not an expert on lua scripting, if it is useful please review and see if it can be improved.

[christianLM_reportCurrentTransportState.zip](https://github.com/jcsteh/osara/files/5697323/christianLM_reportCurrentTransportState.zip)

**Comment by Lo-lo78** [comment]
Uau! Very nice, if OSARA integrates it it is an extra useful action. I 
have put the action in the keymap and it works very well. Thanks!
Il 15/12/2020 17:51, Chris ha scritto:
