### ISSUE TITLE
Media Explore No Longer Usable

### ISSUE THREAD

**Issue by ironcross32** [jcsteh/osara#199]
In the media explore, enter now tries to press record, rather than navigating folders or inserting an audio file onto a track. This is as of the latest version on the appveyor page.

**Comment by jcsteh** [comment]
I don't know of any changes in OSARA recently that should have affected Media Explorer. Can you verify with an older version of REAPER? Trying to determine whether this was a change in REAPER, in which case it needs to be reported to Cockos.

**Comment by ironcross32** [comment]
@jcsteh After these tests, it seems like it is Osara. I installed a portable version of one version older of Reaper that I currently use (specifically 5.96). I then installed the current version of Osara into it (osara_2019.1pre-123,b22e8acd). The issue carried across. I then removed that version of Osara and installed the previous version into the portable reaper wherein the issue vanished, and the media explorer worked as per normal.

**Comment by jcsteh** [comment]
Thanks. When you say you tested a previous build, what was the build number? Was it 2019.1pre-122,f05abab0? if not, could you please test [this build](https://ci.appveyor.com/api/buildjobs/r1vxhh5if3d8j53m/artifacts/installer%2Fosara_2019.1pre-122%2Cf05abab0.exe) and report your findings?

**Comment by ironcross32** [comment]
The build: 2019.1pre-122,f05abab0, does not have the issue, and the media explorer works normally. That is indeed the one I tested with after confirming that an older Reaper didn't fix the problem. The build: 2019.1pre-123,b22e8acd, is the build which is currently installed in my main Reaper, and was directly upgraded to from 2019.1pre-122,f05abab0; which was the previous version I had been using.

**Comment by jcsteh** [comment]
Okay. Thanks.

@leonardder, looks like this might be caused by #194. Would you mind taking a look?

**Comment by leonardder** [comment]
I'm certainly going to give this a try.

@ironcross32: Just to make sure, could you provide exact steps to reproduce this issue?
