### ISSUE TITLE
Weird interference between osara and midi editor

### ISSUE THREAD

**Issue by GianlucaApollaro** [jcsteh/osara#20]
Here's what happens and how to reproduce it.
1. Insert or record a midi item on a track.
2. Select and open that item in either the built in midi editor or the in line midi editor.
3. Try to select all events either through the edit menu or by pressing CtrlA.
The item gets removed for no apparent reason and this happens only when Osara is loaded

**Comment by jcsteh** [comment]
Confirmed.

Technical: Apparently, action ids are only unique to a section; i.e. 
commands in different sections can have the same id. The MIDI Editor's 
select all action has the same id as remove items. OSARA needs to check 
the section.
