### ISSUE TITLE
Automatic reporting need information when moving and changing notes lenght.

### ISSUE THREAD

**Issue by grishakonzalaev** [jcsteh/osara#201]
I would like to hear automatic Osara reportings when I move note by pixels or by grid unit.
For example^ my note set in bar 1 beat 1 5%. If I move note Osara must report me new place of my note. moving right: bar 1 beat 1 25%. All reports should be automatic or optional.
lenght of note should report new note lenght in %bars/beats during changing.

**Comment by jcsteh** [comment]
Feedback for the length changing actions was added in #255.

**Comment by jcsteh** [comment]
Fixed in #392.
