### ISSUE TITLE
Switching MIDI Editor Modes Broken (Win7 x64)

### ISSUE THREAD

**Issue by MatejGolian** [jcsteh/osara#203]
I and fellow REAPER user Yukio Nozawa have come across a fairly odd issue. I don't know what system he is running, but mine is Windows 7 x64. Since others (for example @ScottChesworth ) haven't been able to reproduce this issue, it may be limited to specific system configurations or OS versions.

It§s impossible to switch to the other MIDI editor modes from the MIDI event list. In other words, pressing alt+1 or alt+2 does not do anything. It's possible to switch to the notation editor using alt+4, but from my experience the only other view one can switch to from there is once again just the event list.

It seems that the keyboard shortcuts themselves work properly - instead it looks like something is preventing REAPER from switching to the desired mode. The reason why I believe that there's nothing wrong with the keyboard shortcuts is that a) they are assigned correctly; and b) it's not even possible to switch to the other modes via the action list or menu commands - neither of which require key assignments.

At this point it appears to me that unfortunately, this is an Osara issue.
Build Pre-123 is the first one with this problem, as least as far I can tell. Pre-122 responds properly all the time. As far as REAPER and system configurations go, I have been switching back and forth between the latest and previous Osara DLLs while testing, but everything else on my system remained absolutely untouched (exact same REAPER and OS settings).

**Comment by ironcross32** [comment]
I can confirm this, was here to file issue, already existed. Issue was resolved when uninstalled 2019.1pre-123,b22e8acd and installed 2019.1pre-122,f05abab0. Cannot switch with either the keyboard shortcut or the view menu in the midi editor. Previous version fixes problem.

I'm on windows 10 X64 1809 build 17763.

**Comment by MatejGolian** [comment]
@ironcross32, interesting. So it's not just limited to one OS then. This could be good in a way, because it could potentially help the smart folks here trace down the bug more easily.

**Comment by ironcross32** [comment]
I'm pretty sure this might stem from that recent PR that @leonardder contributed, as we have never had any troubles before that one :). Ah well, he can be forgiven, he does a lot of good work over on NVDA 👍 

This is the risk we take in using the snapshot versions, I'm cool with it, I did revert because this plus another issue I'm having with the current version kind of hamper my work flow a bit.

**Comment by MatejGolian** [comment]
@ironcross32, I have the same suspicion. :-)
And BTW, do you have the installer for 2019.1.Pre-122? If so, could you, please, put it somewhere for download? I have the DLL files, but I have lost the installer and it would be nice to get it back as I will be archiving all Windows builds from now on.

**Comment by jcsteh** [comment]
This should be fixed by #200, which I just merged. Please test the latest snapshot (2019.1pre-124,a2e7d7dc) and close this issue if it's fixed.

**Comment by yncat** [comment]
Thank you for the fix. I confirmed that the latest snapshot perfectly solved the issue. For your information. I'm using Win7 x64, Reaper 5.974.

**Comment by MatejGolian** [comment]
Yes, it works perfect.
