### ISSUE TITLE
Need Clarifications on Windows Build Instructions

### ISSUE THREAD

**Issue by mulcahy1000** [jcsteh/osara#204]
Attempting to setup a clean Windows 10 build environment, and we need a few build environment clarifications.

* Current version of sconstruct requires Python 2.7.
* Xcode 9 is required to build on Mac.
* Need to specifically call out the requirement for NSIS to build on Windows, although I haven't found the right version yet. Scons can't find mmakensis for some reason. It's looking for the path in a registry key that doesn't seem to exist anymore.

**Comment by jcsteh** [comment]
I've hopefully updated and clarified all of the dependencies now in 709826b4 and cbe5ab38.

Detection of NSIS with 64 bit Python should hopefully be fixed in d632de29.

Please confirm and close if everything is good. Thanks.

**Comment by mulcahy1000** [comment]
Instructions work perfectly. Setup a VM from scratch following them and now have a working build.

Haven't had a chance to test the 64-bit fix yet. Will spin a new VM tomorrow night and give that a try.

**Comment by mulcahy1000** [comment]
Confirmed that it also works great with Python 2.7 64 bit as well.

Incidentally, this VM also had Visual Studio 2019 installed instead of Visual Studio 2017, and a quick install and check of the built Osara speaks when navigating through tracks, so I suspect Visual Studio 2019 works as well, although it's not near as seamless. When using VS 2019, you need to launch  the x64 native command line tools setup script as per Microsoft's recommendation for building from the command line. Otherwise, the compiler(s) aren't on the path.
