### ISSUE TITLE
Bug: when using DXi plugins with OSARA 2019.1pre-129,eddf2ffe, sliders in the FX Parameters dialog report value of zero, no matter what they're set to.

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#208]
Reproduction steps:
1. In a fresh project, create a new track and instantiate a DXi plugin on it.
2. In the FX Parameters dialog for said DXi effect, attempt to move the slider associated with any parameter. You'll find that the only value that gets reported by screen readers is "zero" irrespective of what the slider is actually set to. Arrows, PgUp, PGDown, Home and End do move the sliders as expected, but the value is only readable using the edit field associated with each parameter.
3. Now revert to the previous public build of OSARA, and retest the sliders in the FX Parameters dialog for the same plugin you instantiated in step 1. You should find that the sliders behave as expected.

Pradip (the chap who reported this) has reproduced this behaviour with multiple screen readers, with or without scripts. The build of OSARA seems to be the variable.

Thanks in advance for anything that can be done to tighten up the UX here.

Scott

**Comment by jcsteh** [comment]
Oh. I think i see what's going on here; didn't understand it when it was
originally reported. It'd be great if someone could confirm the following:
In an unaffected (previous) version of OSARA, did these plugins only report
percentages; e.g. 0%, 1%, etc.? Also, when you move with the right arrow
key, did the same value get reported 10 times; e.g. 10 presses of right
arrow to get from 0% to 1%, 10 presses of right arrow to get from 1% to 2%,
etc.?
