### ISSUE TITLE
Bug: when change a switcher parameter in FX parameters via osara, some plugins does crash Reaper.

### ISSUE THREAD

**Issue by outsidepro-arts** [jcsteh/osara#210]
Osara build: 2019.1pre-129,eddf2ffe
For example, let use plugin "Proximity" by TDR Labs.
1. Add this plugin to a track/item FX chain.
2. Open the FX parameter window.
3. Choose parameter Mode (1).
4. Try to switch the parameter slider to any different value from Stereo using page up/down keys.
5. We've got a crash.

I had not this bug at the previous versions of Osara.

**Comment by jcsteh** [comment]
This is going to be tricky to debug, as I don't have this plugin.

Can you still reproduce this with OSARA 2019.1pre-132,c1d2f9c4?

**Comment by outsidepro-arts** [comment]
Osara build 2019.1pre-132,c1d2f9c4 got rid this bug. I think this issue may be closed. I think this problem was related to problem 209 somehow .
