### ISSUE TITLE
make visible plugin effects parameters on TCP able to be adjusted via OSARA: View parameters for current track/item (depending on focus)

### ISSUE THREAD

**Issue by dgl1984** [jcsteh/osara#214]
When pressing control+shift+p, to adjust track parameters, it would be nice to have effects parameters added to the track control panel be adjustable as well.
This would increase productivity because the user could edit multiple plugins in 1 dialog.

For example, you could take a reaeq, and just add the gain of each band to the tcp, then add a reacomp to the track, but only add its threshold parameter to the TCP.
Naturally, one would adjust the frequency, cue, etc. of each of the reaeq bands, and the compressors ratio, attack, release, etc. in the plugin parameters list itself.

**Comment by jcsteh** [comment]
Implementation note: REAPER API functions CountTCPFXParms and GetTCPFXParm.
This is going to require redesigning the paramsUi class model a bit to
support FxParams inside TrackParams. No idea how to manage that yet.
