### ISSUE TITLE
"OSARA: View I/O for master track" is broken in Reaper 6.0

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#232]
@AZSlow3 noted on RWP that this action clicks a spot which is no longer used in the new default theme. Perhaps he can fix it?

**Comment by jcsteh** [comment]
[Tweet from Cockos indicating they're fixing this](https://twitter.com/Cockos/status/1202590164905873408)

Technical: Alt key doesn't focus menu bar and alt+f4 doesn't close app when "REAPERTCPDisplay" HWND has focus. Don't really know why exactly, but this new HWND is what changed things.

**Comment by jcsteh** [comment]
As I [tweeted](https://twitter.com/jcsteh/status/1202683877124276225):

> That OSARA command depends on the accessibility info exposed for each track, but that seems to be gone now. Each track used to have its own HWND; now it doesn't. I think easiest fix will be for @Cockos to add an builtin action to open master i/o routing.
