### ISSUE TITLE
Current Jaws patch breaks after closing an OSARA dialog

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#238]
Below is a post Snowman made on RWP. CC-ing it here to make sure Jamie sees it.

"Sadly,  the patch that Jamie so graciously shoved into Osara for us, to fix Reaper's bug where they are not notifying us of a focus change, using the channel that JAWS is listening too, stops working after you close an Osara Dialog.  But, if you alt tab away from reaper,  and then back in,  it recovers.
But, until we get a solid fix for this,  we're kind of stuck."

**Comment by jcsteh** [comment]
Snowman and I are corresponding via email. Since REAPER fixed the bug on their side already, I'm hoping that will just deal with whatever the issue is here.
