### ISSUE TITLE
fx parameters slider always reports 0% with JAWS and automatic (default) MSAA mode

### ISSUE THREAD

**Issue by ns-studios** [jcsteh/osara#240]
Hi,

Often times I'll just use the slider in fx parameters dialog in the default mode, and rely on the state of the slider instead of enabling the classic mode and hearing the real values.
This, however, seems to be broken in the latest snapshot, because the slider always reports 0% with automatic mode, while the classic mode reports correct values.

**Comment by ScottChesworth** [comment]
Are you using Jim Snowbarger's scripts?

**Comment by ns-studios** [comment]
Nope.
I'm using my own that just passes certain keys through in specific windows like main window and midi editor.
This has worked just fine before, so it's an issue with either the latest snapshot, or one of the newer ones.
I believe the one I was using before I upgrated to the latest (and which worked fine) was 2019.1pre-142,430402cc.

**Comment by jcsteh** [comment]
The slider implementation was changed in April 2019 to make the code simpler and to allow it to work on Mac. OSARA does set the accessibility value for the slider, but JAWS chooses to ignore this by default (without scripts). This is not something that can reasonably be worked around without introducing a lot of complexity or breaking Mac.
