### ISSUE TITLE
Feature request: make CC lane accessible in piano roll view of MIDI editor

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#242]
In the piano roll view of the MIDI editor, CC data is displayed in a separate lane visually, but isn't currently navigable from the keyboard so far as I can tell. Is it possible to make the CC lane accessible through the API?

The UX springing to mind here is a layered approach. I'm imagining being able to move to a note, then hit modifier+UpArrow or modifier+DownArrow to move to corresponding data in the CC lane.

Thanks in advance. Shout if I can clarify anything.

**Comment by leonardder** [comment]
There are actions for this, there's just no feedback. I will address this in the near future.

**Comment by ScottChesworth** [comment]
Just seen your pr. Exciting stuff, thanks man!

**Comment by jcsteh** [comment]
is this fixed now that #260, #261 and #262 are merged? Or is there more to do here?

**Comment by ScottChesworth** [comment]
Seems fixed to me so closing. Feel free to re-open if that's incorrect.
