### ISSUE TITLE
osara_2019.1pre-158,7075c9aa causing a shortcut to fail

### ISSUE THREAD

**Issue by jprykiel** [jcsteh/osara#244]
Hello Osara team.
I had found a way to toggle record on or off with a midi foot switch. This is very convenient if you're a keyboard player and want to keep Both hands on the keys, and don't want to use auto punch.
It's as easy as assigning a midi foot switch to the record action, 1013, and tweaking a setting in the dialogue.
This has always worked until I installed Osara's current version, and reinstalling its previous version cures the problem.

Action attached.

Steps taken:

1, Select the transport/record action (1013)
2, The letter r is already assigned to this action as a shortcut, I want to add a new one, which is a 
[footpunch.zip](https://github.com/jcsteh/osara/files/4144217/footpunch.zip)
midi foot switch sending CC65, so I click the add
button.
3, press the foot switch, and noticed that CC65 is now displayed in the shortcut window.
4, at this point, if I leave the action shortcut dialogue in this state and press okay, the foot switch will work as a momentary foot switch, i.e., pressing
the foot switch will start recording, releasing the foot switch will stop recording and continue playback, this is normal and has always been this way,
as the foot switch sends a value of 127 when pressed, and a value of zero when released.
5, so, with the shortcut dialogue still opened, I choose "MIDI CC:
Relative 2 (63=-1, 65=+1)
" in the selector that appeared just after pressing the foot switch, which used to solve my problem before the bug started, i.e. made the foot switch a
toggle instead of a momentary switch.
6, press okay and realise that the foot switch still behaves as a momentary switch.

All the best,
JPR

**Comment by ScottChesworth** [comment]
Just chiming in here to say that I've now heard @jprykiel demo this issue on WhatsApp. It does indeed seem to be specific to OSARA. With OSARA active, the foot switch is momentary, and when he removes OSARA, the foot switch behaves as a toggle.

I had him temporarily revert his Reaper.ini back to factory settings just to check it wasn't some obscure setting, but nope, with OSARA installed the foot switch is always momentary, without OSARA it's a toggle.

Anyone got a clue what's going on?

**Comment by jcsteh** [comment]
OSARA responds to actions by hooking them; i.e. OSARA intercepts the action, does any stuff it needs to before the action, asks REAPER to execute the action, then does stuff after the action if necessary. My guess is that some data is lost when we ask REAPER to execute the action. That kinda makes sense, but I don't know how to fix it. The API call we use (Main_OnCommand) does have a "flag" argument which might be useful somehow, but in far too frequent REAPER API fashion, it's not documented anywhere, so I don't know how to use it.

**Comment by jcsteh** [comment]
It's also possible the REAPER API just doesn't provide us with a way to handle this properly.

**Comment by ScottChesworth** [comment]
Hi @jcsteh, do you have any thoughts on why this used to work up to OSARA 157 and has been exhibiting different behaviour since build 158 though? @jprykiel has also checked that Reaper 5 versus Reaper 6 isn't a variable in the interim. It does seem to be behaviour that's only present in OSARA builds 158 onward, irrespective of which version of Reaper is being used.

I have dialogue in progress with Justin at the mo. Can ask for info on how that Main_OnCommand flag works if it'd be useful?

**Comment by jprykiel** [comment]
Hello @jcsteh, @ScottChesworth suggested I should test the same MIDI message on a different action, and he suggested "SWS:TRANSPORT:RECORD/STOP". On this one, the foot switch does behave as a toggle indeed. Even though this action is not my favourite one as it will stop playback instead of letting it go after recording, I thought that might give you a clue.
So it appears it is specific to the combination between the record action and any MIDI message. As @ScottChesworth said in his previous message,Osara builds prior to Reaper six do not show this issue, even with Reaper six.
Thanks for your help,
Cheers,
JPR

**Comment by jcsteh** [comment]
It used to work because OSARA previously used the postcommand hook, which
notifies us after the command has executed, rather than intercepting the
command. However, that doesn't support anything other than the main section
(i.e. didn't allow us to support post actions for MIDI editor commands) and
was also problematic for control surface support.

**Comment by jprykiel** [comment]
Hi @jcsteh, it's becoming clearer now. Have you an idea why this issue is only affecting the record action? And do you think I could create a new action to fulfil my needs?
Thanks.

**Comment by ScottChesworth** [comment]
FYI, I've just emailed Cockos with a condensed summary of the above. Also  asked for info on the Main_OnCommand flag in case that turns out to be useful.

**Comment by jprykiel** [comment]
Thanks a lot @ScottChesworth. Hope this request reaches its goal.
All the best,
JP

**Comment by ScottChesworth** [comment]
Hi @jcsteh, I got the following reply from Justin in response to my query about data being dropped since OSARA has started hooking the "Transport: Record" action using Main_OnCommand:

"I think the API that is probably needed is the very poorly-named KBD_OnMainActionEx(), which allows passing the CC info along with the command ID... Hope that helps! (let me know if that's a dead end, or ask the OSARA devs to email...)"

I'll forward the email exchange along to ya now in case you want to hop on that for further clarification.

**Comment by jcsteh** [comment]
Ah, thanks. That makes sense, though switching to that is going to require some non-trivial, tedious refactor. :(

**Comment by ScottChesworth** [comment]
Suspected as much. If it's any consolation, I believe in you. #PrayForJamie

**Comment by jprykiel** [comment]
Wow! This is getting too technical for me. But I wonder why is the record action the only one that seems to be affected by this issue.
Is there any other way I can achieve the same foot switch behaviour, without Jamie having to do all this work?
Cheers,
JPR

**Comment by jcsteh** [comment]
The challenge is that given limited spare time, I'm not super motivated to work on tedious refactor outside of  my day job. :( I'll try to get to it at some point, though.

**Comment by ScottChesworth** [comment]
Well if this change is something that'll future-proof OSARA better, I could throw in something to help cover the time it'll take. Just suggesting that because sometimes, tedious work is easier to schedule here if I know I'm gonna be able to treat myself to a decent bottle of scotch as a result of doing it...

**Comment by jprykiel** [comment]
@ScottChesworth, no! It's up to me to treat @jcsteh.  After all, I seem to be the only one to request for this update. So, how should I proceed ?
Cheers,
JPR

**Comment by jcsteh** [comment]
Honestly, I can't promise any time frame on this, so I don't want to take
anyone's money. :) Plus, given current world events, I'm sure there are
people who need it far more than me. I appreciate the offer and your
respect for my work, though.

**Comment by jcsteh** [comment]
I'm a goose. I realised this was really easy to fix for post commands. If we ever want to do it for non-post commands (i.e. commands where we need to check the state of something before execution), that will be the trickier part. However, that never worked even before the change which broke this.

Note that I haven't tested this change with a pedal, but I'm fairly sure it should work. If it doesn't, please reopen.

**Comment by jprykiel** [comment]
No luck @jcsteh.
I made sure I was running the latest build but no change.
May I ask once again, why the record action (1013) is affected, while the action SWS: Transport: Record/stop; Command ID: _SWS_RECTOGGLE toggles as expected ?
Cheers,
JPR

**Comment by jcsteh** [comment]
Oh. That's disappointing. I'm doing as Cockos suggested, so I don't know
why it doesn't work. :(

OSARA does intercept the normal record command, but it doesn't intercept
the SWS record command. That's why there's a difference.

**Comment by jprykiel** [comment]
Could I create an alternative action then?

**Comment by jprykiel** [comment]
Hi friends,
I just fixed the issue. I'm gonna tell you how, but it makes no sense to me.
I created a custom action, in which I dragged the record action and nothing else. On this one, I could assign my foot switch and it togglesnow .
I'm so happy it works, even though I don't know why.
All the best,
JPR

**Comment by ScottChesworth** [comment]
Dammit, how did I miss that idea!

I'm guessing that works because OSARA doesn't hook user-created custom actions, @jcsteh?

**Comment by jcsteh** [comment]
OSARA is supposed to (and has code to) handle custom actions; see #29.
However, the way REAPER's action hooks work has always been a bit obscure
and quirky/buggy. My guess is that this discrepancy is a REAPER bug/quirk.

Still, I'm glad you've found a solution which works. Unless this starts
causing other problems, I'm inclined to let it go for now.

**Comment by jprykiel** [comment]
Hello.
The cure I found for my foot punch issue is now broken to with last Osara version.
It was still working in the previous version I was using which was 2022.1pre-867,0969c08e
it now shows the same symptoms as when I started this issue.
I would like to draw your attention to a particular point. The shortcut actually works, but what seems to be broken is this, quoted from my first post in this issue
" With the shortcut dialogue still opened, I choose "MIDI CC:
Relative 2 (63=-1, 65=+1)
" in the selector that appeared just after pressing the foot switch ..."
Osara seems to bypass this selector, as no matter how I set it, the switch behaves the same. Please, focus on this point if you can, as it may cause other problems to anyone who wants to use a MIDI controller to control any transport action.
I hope a solution can be found.
Thanks,
JPR

**Comment by jcsteh** [comment]
Is this still with action 1013 in your custom action? There were some changes to the way unknown toggle actions are handled, but OSARA already intercepted 1013, so there shouldn't have been any change there.

Unfortunately, I really don't know how to fix this properly. As I noted above, OSARA is already doing what it's supposed to do, but it still isn't working.

**Comment by RDMurray** [comment]
I think I've finally got to the bottom of this. handlePostCommand only passes the midi data to Reaper if hwnd is non-zero, which is the wrong way round.  hwnd is zero for actions initiated by midi, and for keyboard input it is non-zero.  I think we could remove the if statement and always use KBD_OnMainActionEx.  The parameter defaults would just need to be changed so that calling HandlePostCommand from handleMainCommandFallback still works.  Reaper sets val=63 valHW=-1 and relmode=0 when the command does not come from midi.

The reason @jprykiel's custom action stopped working is that it is handled by handleToggleCommand, which doesn't pass the midi data.

**Comment by jcsteh** [comment]
Blah. I was using hwnd 0 as a way of saying "REAPER didn't give us this info", not realising it would be 0 for MIDI.

But one question still remains for me. Why is JPR's custom action handled by handleToggleCommand? It's not a toggle itself; it runs a toggle, 1013, which should get handled by handlePostCommand.

Thanks for debugging this.

**Comment by jprykiel** [comment]
@jcsteh , could this be the reason?
Quoted from my first post on this issue,

**Comment by jprykiel** [comment]
5, so, with the shortcut dialogue still opened, I choose "MIDI CC:
Relative 2 (63=-1, 65=+1)
" in the selector that appeared just after pressing the foot switch, which used to solve my problem before the bug started, i.e. made the foot switch a
toggle instead of a momentary switch.

**Comment by jprykiel** [comment]
Thanks for reopening this issue anyway.
JP

**Comment by RDMurray** [comment]
Custom actions by default have a toggle state that depends on the state of the contained actions, so the custom action is a toggle action.

handleToggleCommand should probably pass midi data as well.

We are still left with the problem that midi data will only be passed back to reaper for post commands, and then only in the main section.  It would be good if Cockos would provide a function like KBD_OnMainActionEx that worked for any section.

**Comment by jprykiel** [comment]
@ So what has changed between version 2022.1pre-867,0969c08e and current version that broke this custom action. Maybe I missed something and it has already been stated in this issue, but maybe in terms too technical for me to understand. I still think this is the key to the issue.
All the best,
JPR

**Comment by RDMurray** [comment]
@jprykiel when this is fixed there will be no need for a custom action, you can assign the midi cc to action 1013 directly.

**Comment by RDMurray** [comment]
@jprykiel This should be fixed in the latest Osara snapshot.  There should be no need for the custom action, but I would appreciate it if you could test both the action directly and the custom action as both cases should be fixed.

**Comment by RDMurray** [comment]
@ScottChesworth Could you ask Cockos to add an API function similar to KBD_OnMainActionEx that works for any section?  This would mean that we could intercept any action without side affects like this.

**Comment by ScottChesworth** [comment]
Yep, will do.

**Comment by jprykiel** [comment]
> Hi guys,
> 
> Hi guys,
> 
>  
> 
Thanks a lot for the fix. Both actions now work. I still prefer my custom action because when record is assigned to my foot switch, Jaws will say record at foot press and release, and play at Foot press and release alternatively. My custom action seems a little less verbose.
Thanks again,
JPR

**Comment by jcsteh** [comment]
> I still prefer my custom action because when record is assigned to my foot switch, Jaws will say record at foot press and release, and play at Foot press and release alternatively.

You can prevent that by disabling "Report transport state" in OSARA's Configuration dialog (control+f12).

> My custom action seems a little less verbose.

So... @RDMurray , this really confuses me. If this custom action was indeed being handled by handleToggleCommand, why was it not being reported as a generic, unknown toggle action?

**Comment by RDMurray** [comment]
@jcsteh  It was definitely handled by handleToggleAction when I tested it here.  @jprykiel  did you uncheck the "Show as active if all component actions are:" checkbox in the custom action dialog?

**Comment by jcsteh** [comment]
Or perhaps @jprykiel used OSARA: Mute next message in the custom action?

**Comment by RDMurray** [comment]
If it is the action in dropbox unchanged, then it should be handled by handleToggleCommand and therefore say "enabled Custom: FootPunch".  @jprykiel is your custom action not speaking?

with the checkbox unchecked in the custom action dialog the transport state is still spoken, so I don't know how it could be silent.

**Comment by jprykiel** [comment]
hello. 
I just did some tests and there is indeed a verbosity difference between both actions. 
When a foot switch is assigned to the record action, Jaws or NVDA will say "record" When I press the foot switch, and record" again when I release it.
Then "play" when I press the foot switch, and "play" again when I release it. 
If I assign the same foot switch to my custom foot punch action, the screenreader will say "unable custom action foot punch" when pressed, nothing at release,
and "disable custom action foot punch" when pressed  again, nothing at release. The best would be if the record action could say "record" and "play" only
once. But really, I'm so grateful that your fixed the foot switch behaviour, that this Little Over verbosity thing does not Bother me at all. 
Thanks again, 
JPR

**Comment by jcsteh** [comment]
What custom action do you want to include exactly? This would be a case fairly specific to one user, no?

**Comment by jcsteh** [comment]
Also, there shouldn't be any code in OSARA which handles specific custom actions... but I'm really not sure what you had in mind.

**Comment by ScottChesworth** [comment]
I was thinking maybe to include JP's FootPunch custom action, which only contains "Transport: record". Right now it's reported as a generic toggle, but if I add one line to the main section toggles (sorry, forgetting the proper name for that section of code) it'll report "Record" and "Play" when he presses his pedal. It's not just for one user, JP is here talking about it, but I know other folks have been using his FootPunch custom.

**Comment by ScottChesworth** [comment]
Wouldn't the ID stay stable if we included the custom action in the OSARA map, unbound by default?

**Comment by ScottChesworth** [comment]
Oh, it's still not a numeric ID though is it. Hmm, ok, scratch this.

**Comment by ScottChesworth** [comment]
Yah, it was the tedious refactor that I was trying to avoid.

**Comment by RDMurray** [comment]
There's one more possibility I thought of: don't call the post command function if relmode==2 and val==0.  I don't know if actions always do nothing in that case, it's just a guess based on the ones I've tested.

**Comment by jprykiel** [comment]
Hey @ScottChesworth, I didn't know a mute next message action existed. I'll try it and tell you how it goes. That's fun.
JPR

**Comment by jprykiel** [comment]
Oh no. I'm afraid it won't work, because if this is a custom action, Osara will say unable custom action and the actions name, and nothing at foot switch release. You see, I already experimented with a custom action, but it somehow changes the way Osara reports it.
Listen. leave it like it is, it's okay.

**Comment by ScottChesworth** [comment]
Yeah, we can't change how the custom action is reported in OSARA because of how Reaper does ID's for those, that's why I think it might work better as a script instead. Think I'll be able to control the verbosity that way. It'll be useful to have in the Dropbox anyway if it works, I'll take a shot at it next time I get a spare minute.

**Comment by RDMurray** [comment]
If you uncheck the box that says "Show as active if all component actions are", it shouldn't be announced as a toggle action.  I have know idea if that will affect the way it interacts with midi.  I suspect it will do what you want @jprykiel .  

Mute next message wouldn't really help in this case.

Btw for testing this I used MIDI-OX and loopMIDI.

**Comment by jprykiel** [comment]
Hey @ScottChesworth , I did as you said, and it's working like a dream. First record, then mute next Osara Message. You made my day. So here is the action in question, I could throw that into our dropbox and replace the old one  maybe.
Cheers!
[footpunch2.zip](https://github.com/jcsteh/osara/files/8902816/footpunch2.zip)

**Comment by ScottChesworth** [comment]
Cool! I've updated Dropbox, and also fleshed out the accompanying text file with a bit more detail.

**Comment by jprykiel** [comment]
Great Scot! And many thanks to @jcsteh and @RDMurray for their help.
JP
