### ISSUE TITLE
Adding better feedback to the install scripts on MacOS

### ISSUE THREAD

**Issue by kyleman** [jcsteh/osara#246]
I have made two commits to my fork to add better feedback to the MacOS installer scripts. see fcddf39363361e31e8b3acf36d8964275b804776 and 8da4e86dfd2a5cb5e6ab25253a2a69574bef1e3c

I like the more verbose nature of this because in the original commands you get one word "Done." in a whole big mess of other terminal output. Now it clearly says what's being done, what is being moved where, and finally that it finishes.

**Comment by jcsteh** [comment]
Two things:

While I understand that a single word can be missed, especially given the other output above, I worry that most users (without technical knowledge) aren't going to care or understand the messages about files being moved. There's a possibility that those messages will confuse them more. Have you seen confusion from users that you think this would resolve?

**Comment by tbdalgaard** [comment]
@kyleman  I like your idea, but would it be possible to make a pkg-installer or simply one script which opens the terminal and guides the user through the OSARA installation? Perhaps if this installer prompted for the user/admin password we could go around the context menu thing where Mac OS warns the user about executing these scripts.
A use case for this would be that many users in general aren't using the terminal that much, and perhaps there is a possibility (like on Windows) to make some kind of installer for OSARA.
I don't mind going into the terminal myself, but I do understand if a new user with almost no experience with the Terminal gets lost once or twice, especially if the security pops up before the execution of the scripts.
