### ISSUE TITLE
Bug: moving by beat is inconsistent when project BPM is 118 or lower

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#247]
Not sure whether this is OSARA specific or not because it doesn't happen with all projects, but I've procured and attached an example project where it's reproducible.

Reproduction steps:
1. Download and open this example project. https://www.dropbox.com/s/sbsz5wcayjd3o77/Skipping%20beats%20%20after%20alt%20home.rpp?dl=1
2. Use the jump dialog to move to bar 8, beat 2, then hit Alt+Home to return to the start of bar 8.
3. Use Control+PageDown to navigate forward by beat, and observe how some beats get skipped for the next couple of bars.
4. Now go to Project Settings, change the project BPM to anything higher than 118, and repeat steps 2 and 3. The BPM having been changed, you should find that no beats get skipped.

I can't get it to happen with any of the projects I'm creating here irrespective of their tempo, but it's been flagged by a couple of users. I'm guessing it's something that's been saved as part of their default templates that's causing it, but I'm clueless about what that might be.

Any thoughts welcome.

**Comment by jcsteh** [comment]
I tried this without OSARA and was still able to reproduce, so this is a REAPER bug.

**Comment by ScottChesworth** [comment]
thanks @jcsteh, I’ll take it to the Cockos forum tomorrow.

**Comment by ScottChesworth** [comment]
For completeness, I've reported this to Cockos here: https://forum.cockos.com/showthread.php?p=2248770#post2248770

**Comment by ScottChesworth** [comment]
Fixed in v6.04+dev0224. I still can't quite believe how quickly Cockos move.
