### ISSUE TITLE
Midi editor: make note preview length reflect the length of the actual note

### ISSUE THREAD

**Issue by leonardder** [jcsteh/osara#250]
The osara note preview is now around 300ms. It would be helpful if the preview is equal to the actual length. Should be possible to calculate that based on bpm and note length.

Of course, chord previews would be more difficult, as notes in chords could have multiple lengths. I assume using the shortest length here would be fine. Alternatively, we need a done timer per note that turns off that particular note, but that adds much complexity with minimal effort.

Related to #249

**Comment by pitermach** [comment]
I think the current behavior is also confusing for new users. I've used Reaper for a while but mainly deal with audio. Recently I had to do something in the midi editor for a sound design project and assumed the note preview was matching the note length. So, I thought the commands I was giving to make the note shorter and longer weren't working. Fortunately I was talking to someone who spends most of their job working with Midi in Reaper and he explained how it actually works, but I don't think it's very obvious.
