### ISSUE TITLE
Add feedback to several midi editor note parameter actions

### ISSUE THREAD

**Issue by leonardder** [jcsteh/osara#252]
I propose adding feedback to the following actions:

* Edit: Lengthen/Shorten notes one grid unit
* Edit: Move notes up/down one semitone/octave
* Edit: Note velocity +-01/10

The problem with these actions is that we need to know the note to which the action was applied. As far as I know, there is no reliable way to find out the current note, especially when the cursor is at a chord. @jcsteh: any ideas how to handle this?
Note that some of these commands already have note preview, therefore I propose additional reporting feedback for them that can be toggled with the new report note feedback option.

**Comment by jcsteh** [comment]
I think those commands operate on selected notes and OSARA selects notes
when you move to a chord or note. So, you should be able to report based on
selected notes.

**Comment by ScottChesworth** [comment]
This seems to have been implemented already, so closing the issue. Feel free to reopen if that's incorrect.
