### ISSUE TITLE
Bug: OSARA reports note length as 60% if you use "Edit: Shorten notes one grid unit" action one too many times

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#256]
Reproduction steps:
1. Insert an empty MIDI item onto a track.
2. Open the piano roll and insert an eighth note (the length doesn't matter per se, just setting up the next steps).
3. Set your grid to 32nd notes, then repeatedly hit NumPad 1 and DownArrow in succession. You should find that OSARA reports the length being shortened correctly until...
4. After the final press of NumPad 1 (IE, when the note can't be shortened any further), OSARA will start announcing the length as 60%. I've no clue what that 60% relates to, as the length field in the Event Properties dialogue appears to be blank at this point.

The behaviour holds up across all of the grid divisions that we have mapped to the numeric row here.

Not a huge priority obviously, but figured I'd get it written down while @leonardder is breathing new life into the MIDI UX.

Thanks in advance for your fixage.

**Comment by leonardder** [comment]
Ugh, this is definitely my fault. I will take this.
