### ISSUE TITLE
Midi editor: Support navigate: select next/previous note actions

### ISSUE THREAD

**Issue by leonardder** [jcsteh/osara#258]
These actions select the next/previous note (with optional filtering), note preview is implemented as well. OSARA can add support for these as follows:

1. OSARA should update information about position in chord
2. OSARA should optionally announce information about the note.

**Comment by ScottChesworth** [comment]
Is this still on your radar @leonardder ?

**Comment by leonardder** [comment]
I thought I played with this, not sure what the status is now. I'll have a look, since apparently I will probably need this somewhere in the near future.

**Comment by leonardder** [comment]
I started working on this, hoping to finalize it somewhere this week.

**Comment by leonardder** [comment]
Played a bit with this, but it seems that selecting notes like this doesn't change the cursor position. Also, when you first select all notes with ctrl+a, behaviour with these actions is pretty weird in that the selection is preserved, whereas it discards the previous selection when only one note was selected.
I think this makes these actions pretty unintuitive and therefore I'm tempted to close this, as it is my own request. Unless others really want it, I can pr what I have now.

**Comment by ScottChesworth** [comment]
It's safe to close, don't think I've seen the request anywhere else except here. Thanks for putting in the time anyway man.
