### ISSUE TITLE
Request: rename "OSARA: Select next track/take envelope (depending on focus)" and "OSARA: Select previous track/take envelope (depending on focus)" for UX clarity?

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#263]
It's been pointed out on the ReaperAccess WhatsApp channel that perhaps the names of these two OSARA actions could use a bit of clarification. Currently, arming isn't mentioned in the action names, so it's possible to fall down a hole when using Shortcut Help to locate the appropriate keystroke to arm visible envelopes.

Seems like starting each action name with "Select and arm..." would clear this up?

Relevant actions:
Action: OSARA: Select next track/take envelope (depending on focus)
ID: _OSARA_SELECTNEXTENV
Action: OSARA: Select previous track/take envelope (depending on focus)
ID: _OSARA_SELECTPREVENV

Not a high priority obvs, but figured I'd raise it for consideration.

**Comment by jcsteh** [comment]
But... these actions *don't* arm the envelope:

1. Create new track.
2. Press control+alt+v.
3. Press control+l. OSARA reports the envelope is armed.
4. Execute "Automation: Unarm all envelopes".
5. Just to be sure you're unselecting the envelope, create a new track,
move to that track, then move back to the first track.
6. Press control+l. OSARA doesn't report the envelope is armed (so it
isn't).

Conclusion: REAPER is arming the envelope when you press control+alt+v.
OSARA isn't arming it when you press control+l.

**Comment by ScottChesworth** [comment]
Aha, so my understanding of when the envelope gets armed was wrong!

I think what feels off here then is that selection is mentioned in the action name, but not mentioned in the action feedback. I know it'd be longer to here, but would it be worth modifying the action feedback to be something like "volume envelope selected and armed" when armed, or just "volume envelope selected" if unarmed? Slightly longer to hear, but clearer UX I think.

No worries if this doesn't get a green light. I'll keep it in mind when recording future tutorials and explain things in such a way that the current UX can work.

**Comment by jcsteh** [comment]
1. You can only select one envelope at a time. When you select an item in a simple list or menu, screen readers don't report "selected"; it's redundant.
2. This would be inconsistent with the way other selection is reported by OSARA. If you press down arrow or control+rightArrow, we don't report "selected" for the track or item, even though one definitely gets selected. We only start reporting "selected" when multiple selection is happening.
3. I don't follow how this addresses the initial problem here, which was the misunderstanding about what action was arming the envelope. Can you clarify your thinking here?

**Comment by ScottChesworth** [comment]
Fair point re consistency. The initial gripe was that I thought terminology was being mixed, but that's not the case. Seems that this is a flaw in how automation has been explained in existing tutorials more than anything. All good, I'm recording knew tutorial content anyway, it can be taken care of here.
