### ISSUE TITLE
Can OSARA report if notes are muted in the piano roll?

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#278]
Just had a befuddling 5 minutes in the MIDI Editor, and this feature would've avoided most of the head scratching. I reckon muted would be reported after note name and length, in keeping with the current format.

Thanks in advance if this is possible.

**Comment by leonardder** [comment]
With a muted note, you mean a note with velocity 0?

**Comment by ScottChesworth** [comment]
That wasn't what I meant when I requested this nope, although considering that basically equates to the same thing, velocity being set to 0 might also be a useful thing to report. Poking at this afresh, here's some more detail that might help.
I mute notes by selecting them and hitting Alt+M, which runs the action "Edit: Mute events (toggle)", ID "40055" in the MIDI Editor category. There's not yet any action feedback for this toggle. That would also be a useful addition.
Once muted, note previews still play when arrowing over the note. The velocity doesn't change in the Event Properties dialog either. These were the combination of things that caused the confusion that lead me to open the issue.
I've got two thoughts on how the UX could be clarified.
1. Could note previews be silenced if the mute toggle is active?
2. Could OSARA report "muted" after the note info its already reporting?
Either of those would work a treat here, so whichever is easiest. :)

**Comment by ranetto** [comment]
I completely agree with Scott:
when the notes are muted with the action cited by Scott, passing over it osara should say mute and not play that note.
Velocity 0 is a different thing I would say, as you could use a note with velocity 0 to drive some action etc and then I would leave it out.
For the rest I completely agree with Scott.

**Comment by jcsteh** [comment]
@leonardder , do you still plan to work on this in the near term or should we reassign/unassign it?

**Comment by ScottChesworth** [comment]
Contrary to what I said above, could we have "muted" reported before other information? Our reporting style has changed since this was opened. It would also be superb if previews could respect muted notes. Thanks in advance.

**Comment by leonardder** [comment]
I might have time next weekend.

**Comment by jcsteh** [comment]
Happy for you to push it to master. Please reference this PR.

**Comment by leonardder** [comment]
Done.

**Comment by ElCrackLoko** [comment]
Hello guys, sorry to open this here but I think, according to me, it is better to comment here than to create an issue just for this, you will tell me
It is not distinguishing between one or more notes/chords when muting in the translation, everything is mentioned in the singular. #2 notas muteada", for example
