### ISSUE TITLE
Finding out the mute, solo, record monitor and phase status of tracks in a project

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#28]
At the moment it's possible to get a list of the armed tracks in a project spoken using the action "OSARA: report record armed tracks". Can more actions along this line be created to report which tracks are muted, soloed, have record monitor set to anything other than off, and have phase flipped? I'd ideally like if this info was given as track numbers and names, but understand if you'd want to hold off on adding track names to the announcement until we have some OSARA verbosity settings in place

**Comment by jcsteh** [comment]
I ended up just including names always. I can make this configurable later if needed, but I figure if you've bothered to name your tracks, it's probably useful to hear them.
