### ISSUE TITLE
Bug: OSARA loses focus of selected envelope type when navigating by bar or beat

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#280]
Here are reproduction steps with Reaper 6.12C:

1. Create a track (Control+T).
2. Show the volume envelope (Control+Alt+V).
3. Select the volume envelope (Control+L).
4. Now move a bar forward (PageDown), and try to drop an envelope point. You'll find that OSARA has lost focus and you'll need to re-select the track and re-select the envelope you want to work with before you'll be able to drop a point.

I noticed that if I hit Control+Shift+Space to have OSARA report selection after selecting the envelope, I get told "no selection". Could that be something to do with it?

**Comment by jcsteh** [comment]
How are you dropping a point in this instance? I'm using an outdated
version of REAPER (6.01, shows how rarely I get to play with this stuff,
heh). However, if I do control+t, control+alt+v, control+l, page down,
control+shift+i, it inserts a point as expected.

**Comment by ScottChesworth** [comment]
Ah, there's a difference in our workflows. Control+Shift+I inserts an automation item. I'm hitting Alt+Shift+E instead, which runs the action "Envelope: Edit envelope point value at cursor" (ID 41987). The same behaviour holds up here when using Shift+E, "Envelope: Insert new point at current position" (ID 40915). These are the two keystrokes that are being used most often so far as I know. I tend to use those over automation items because OSARA sometimes gets stuck when navigating between automation items. I believe we've already got an issue about that.

**Comment by jcsteh** [comment]
I'm using control+shift+i (Envelope: Insert new point at current position),
not control+alt+shift+i. Note that I'm using the keymap currently bundled
with OSARA, not the new one you are working on, so control+shift+i might be
remapped in yours. For me, Envelope: Insert new point at current position
works after pressing page down.

**Comment by RDMurray** [comment]
I also have been unable to reproduce this on Reaper 6.12c.

**Comment by jcsteh** [comment]
Anyone mind testing this with older versions (6.01 and later)? I'm thinking
this might be a regression in REAPER.

Even though OSARA does change its "fake focus" when you press page down (or
use any other ruler command), OSARA doesn't change anything in REAPER for
ruler commands. Furthermore, OSARA doesn't care about its "fake focus" when
you use an envelope specific command like insert envelope point; it just
asks REAPER which envelope is selected. That suggests that ruler commands
now cause REAPER to de-select the envelope.

**Comment by RDMurray** [comment]
It works fine here with the latest version of Reaper, so if it is a regression in Reaper it must be config specific.  

Scott, can you test with a fresh portable install to see if the configuration makes a difference?

**Comment by ScottChesworth** [comment]
Default Reaper config does cure the problem as outlined at the start of this thread yeah. Not sure why yet. However, it's still pretty easy to get OSARA to lose focus with default settings. Try this:
1. Create a track, show the volume envelope and select it.
2. Navigate by bar or beat.
3. Now also show the pan envelope and try to select that. Here, it's not possible. I'm stuck working with the volume envelope, and if I want to select a different envelope type, I have to start the workflow over from track selection.

Skipping step two, everything behaves as expected here when I show the additional envelope type. Hence, navigating still causes unanticipated behaviour at default settings.

**Comment by ScottChesworth** [comment]
CC-ing @Justinmac84 who uses this stuff more often than me.

**Comment by RDMurray** [comment]
@ScottChesworth  I can reproduce that problem, except after step 3 I cannot work with the volume envelope.  Even "envelope: insert new point at current position" doesn't work, so it looks like a Reaper problem.  

I'll try some older versions to see where this regression was introduced.

**Comment by ScottChesworth** [comment]
Well spotted, forgot to check that! I've already got dialog in progress with Cockos re weird behaviour when envelope points are placed in close proximity, so let me know if you narrow it down and I'll harangue them for a fix.

**Comment by RDMurray** [comment]
I can also reproduce the second problem @ScottChesworth  mentioned with Reaper 6.01.

**Comment by jcsteh** [comment]
>     1. Create a track, show the volume envelope and select it.
> 
>     2. Navigate by bar or beat.
> 
>     3. Now also show the pan envelope and try to select that. Here, it's not possible. I'm stuck working with the volume envelope, and if I want to select a different envelope type, I have to start the workflow over from track selection.

That's a different issue. Those commands must rely on OSARA's notion of fake focus because once you focus the envelope (step 1), the envelope has focus as far as REAPER is concerned; focus no longer refers to the track or item. Unfortunately, when you move by bar/beat in step 2, OSARA's notion of focus moves to the ruler. So, in step 3, OSARA doesn't know whether to select envelopes for the current track or the current item, since neither has focus. Thus, it does nothing.

**Comment by jcsteh** [comment]
> That's a different issue. Those commands must rely on OSARA's notion of fake focus because once you focus the envelope (step 1), the envelope has focus as far as REAPER is concerned; focus no longer refers to the track or item. Unfortunately, when you move by bar/beat in step 2, OSARA's notion of focus moves to the ruler. So, in step 3, OSARA doesn't know whether to select envelopes for the current track or the current item, since neither has focus. Thus, it does nothing.

OSARA already does have to keep track of whether the last envelope selected was for a track or an item. So, I can fix this by just using the last state when the focus isn't on a track or item. There's a catch, though. If I do that, those commands will have an counter-intuitive result if you press them in some cases. For example, if you move to a track, select an envelope, move on the ruler, select an item, move on the ruler and finally select an envelope, OSARA will select a track envelope, since the last selected envelope was a track envelope.

**Comment by jcsteh** [comment]
> So, I can fix this ...
> There's a catch, though. If I do that, those commands will have an counter-intuitive result if you press them in some cases.

I managed to figure out a way around this.
