### ISSUE TITLE
Can context sensitivity be improved when moving to beginning or end of time selection?

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#285]
Context sensitivity doesn't currently track moving to the beginning or end of a time selection.

1. Open a blank project and create a track.
2. Set start of time selection at the beginning of bar 2, end of time selection a bar later. Hit Control+Shift+Space at this point and OSARA will report the time selection.
3. Move anywhere outside of the time selection, select the track, and verify that OSARA reports the selection change.
4. Now hit Home to move back to the start of the time selection. At this point I'd expect Control+Shift+Space to report time selection again. Right now, it doesn't. It still reports track selection.

Could context sensitivity be tightened up here? Is this a Reaper thing or an OSARA thing?

**Comment by jcsteh** [comment]
When you move to start of time selection, I assume OSARA doesn't say
anything? From what I can see, OSARA doesn't know about that action at all.

We'd need to teach OSARA about those actions. Just to verify, are you
talking about actions: Go to start/end of time selection, 40630/40631?

**Comment by ScottChesworth** [comment]
Them's the ones, yep. Re action feedback for these, can we have them following Robbie's rules as per the adjustment of time selection edges? Ideally they'd provide action feedback when the transport is stopped and do their thing silently if transport is rolling. I know some people who use time selection when cuing stuff, should think they'd be pretty miffed by a bunch of extra speech. I think it does make sense to report the new timeline position when transport is stopped though.

**Comment by jcsteh** [comment]
Tricky. Should we also only report go to previous/next marker if playback is stopped? Or ruler commands (next bar, next beat, ...)? And if not, why is go to start/end of selection special?

**Comment by ScottChesworth** [comment]
Answering that question definitively is tricky enough, I can't imagine coding it lol.
My vote would be yes to all of the above propositions because I like minimal verbosity when the transport is rolling, but let me put it to the key map consortium for a short debate and I'll report back.

**Comment by ScottChesworth** [comment]
Hey @jcsteh , a thought occurred while I was relaying the question to the WhatsApp group. Instead of us trying to anticipate what's necessary here, would adding one more check box to the OSARA Configuration dialog labeled something like "report action feedback when transport is rolling" be a better solution? That way, people can decide when they need speech and when they don't. Seems better than us trying to anticipate, but I dunno what it would look like in terms of implementation. Thoughts?

**Comment by jcsteh** [comment]
I'm not a fan of adding a checkbox for all action feedback while playing.
However, I could probably get behind a checkbox for feedback from actions
which deal with time movement.

**Comment by ScottChesworth** [comment]
Apologies for the slow reply (thought I'd already done it). Your above suggestion of an additional check box to toggle time-based action feedback would be marvelous.

**Comment by tbdalgaard** [comment]
Hi!

I would clearly vote for more configuration options in OSARA any time. :)
Just wanted to comment on #1: In fact this context sensitivity gets even worse if you do the following:

1. Load a project with with two tracks.
2. Make a time selection that starts at bar 2 and ends at bar 3.
3. Press shift-space to verify the selection.
4. Now go to start of project with ctrl-home.
5. Press shift-space: OSARA will say: No selection.
6. Now, this gets very bad, because there are no way to get OSARA to remember the time selection which is still active, so a new user could be quite confused. In fact if you selected an item or a track and unselected all this by pressing shift-escape, you are still out of luck, because OSARA can not determine the time selection anymore. The only way to get this going is either to do the edits, and ignore the OSARA feedback, or clear the time selection and start over again.

**Comment by ScottChesworth** [comment]
It's Control+Shift+Space to report selection. 

Is your OSARA up to date @tbdalgaard?

I remember this being an issue at one point, but can't reproduce it with the latest snapshot. 

If memory serves, the workaround I used was to give the Left and Right arrows a wiggle to remind OSARA that I wanted to know about the timeline, then Control+Shift+Space would return to reporting the active time selection.

**Comment by tbdalgaard** [comment]
Hi @ScottChesworth!

Thanks, you are right. Using the arrow keys did the trick. My OSARA is updated. I thought it was a bug, so sorry for the noise on here...

**Comment by jcsteh** [comment]
I added feedback and context tracking for these actions in 29da8a50. Let's file a separate issue for the config of time movement feedback during playback (https://github.com/jcsteh/osara/issues/285#issuecomment-668732019).
