### ISSUE TITLE
Bug: tracks contained within nested folders are still navigable in tracklist when top level folder is closed

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#286]
1. Create 5 tracks.
2. Make track 1 a folder, and track 5 the end of the folder.
3. Close the folder and verify that only track 1 is the only track that's navigable. This all works as expected. Let's break it.
4. Reopen the folder, and create a nested folder. Designate track 2 as the start of the nested folder and track 4 the end.
5. Now close the top level folder again. At this point, I'd expect either the same result as step 3, or I guess maybe tracks 2 3 and 4 would still be navigable seeing as the nested folder is still open. What actually happens is that track 2 (the start of the nested folder) disappears, tracks 3 and 4 remain navigable. IE, there's no way to close the nested folder without reopening the top level folder, closing the nested one and re-closing the top level folder.

This one was difficult to describe in words, most of the above sentences seem barely functional. If a recording would be a better way to illustrate the issue, just shout.

**Comment by jcsteh** [comment]
Fun. Your steps to reproduce make perfect sense. I have a feeling I
understand what's going on, but don't know how to fix it yet. That said, I
haven't actually looked at the code for that in years, so... :)

**Comment by jcsteh** [comment]
Implementation note: When walking tracks, it's not sufficient to just check whether the parent track is a closed folder. We must check whether any ancestor track is a closed folder.
