### ISSUE TITLE
Sliders and edit field values in P dialog don't always match up

### ISSUE THREAD

**Issue by CastleStarter** [jcsteh/osara#287]
Sometimes you can press P to get the parameter dialog up, move to a slider and change the value, then tab and shift tab, and the reported value of the slider is different.

For example, The Qyoo synth from Full Bucket at:
https://www.fullbucket.de/music/qyooo.html

Put this on a track and get to the P dialog.  Press O to get to oscillator one and then down another 9 items to get to osc FM 1.  There are two items labelled like this and you want the second one (and that is a different bug smiley face).  

Press home to ensure the slider is at the bottom.  Press tab to get to the slider.  Up arrow four times and you hear LFO2+.   Then tab and shift tab.    The slider now reports LFO1.  The actual value is LFO2+ still as the synth behaves correctly for LFO2+ being the selected value.

Also try pressing home again on the slider so it reads off.  Then arrow up loads (I think there are 20 possible values) and you get to the slider value of "note".  Yet press the end key and you get a value on the slider of p-pend.  The up arrow isn't able to reach this last value.

I also created  a blank js plugin with the following content:
desc:Sombrero Hat
// Contains just a slider with 5 values 
//Author Chris Goodwin 

slider1:0<0,4,1{Apple, Banana, Cabbage, Daffodil, Eagle}>Choices

@init 

@slider 

@block

Save this in a text file in the Effects Reaper folder in %appdata%.  No file extension necessary.

Instantiate this plugin, it is called Sombrero for no good reason.  Again, get to the P dialog and use the arrow keys to move the slider up.  It can't get to the value of Eagle.  You have to press end.

I think that this last js plugin part demonstrates the problem is with Osara rather than a poorly written plugin.  I've never known whether the problem seen with the Qyoo synth was the synth that was the problem or Osara.  Or indeed anything else.

**Comment by jcsteh** [comment]
This is fixed for JS FX now. I'm not sure about other cases; I didn't test Qyoo. Different plugins handle formatting and snapping of values differently (and there are often inconsistencies between those two things even in the same plugin), so there are probably some cases I can't fix, at least not without breaking others. That said, one of the changes I just made should make things slightly more reliable across the board.

**Comment by CastleStarter** [comment]
Thanks James.  That sounds handy and I hope it helps in Qyoo.

I’m new to posting bugs and having someone fix them smiley 

Is this fix in the latest release of Osara or an upcoming one?

Kind regards,

Chris G

**Comment by ScottChesworth** [comment]
Chris, just grab the latest snapshot now and you'll get this change.
You might find it handy to bookmark this link: https://github.com/jcsteh/osara/commits/master
That's a feed for the master branch of OSARA.
New code contributions arrive in the form of what GitHub calls "pull requests", then Jamie reviews the contribution, sometimes requests changes, and when he's happy, he merges the new code into the master branch. Code that's been committed to the master is what Jamie then builds and releases as a snapshot. Using the page linked above, you can see who's committed what, when they did it, and which issue each commit addresses.
Ergo, when the date on the snapshots page matches the date of the latest commit to master, you know you're getting the latest and greatest.

FYI, all of the above is my very rudimentary understanding of GitHub terminology. No doubt Jamie or Robbie will arrive to slap me about in due course if I'm giving you bad info. 👍

**Comment by jcsteh** [comment]
Snapshots get built automatically when I land commits in master. While the
date kinda allows you to match up commits on master, it isn't precise,
particularly if I've landed multiple commits in one day. A more precise way
to match up snapshots to master commits is to look at the last part of the
snapshot version number. For example, the current Windows snapshot is
2020.1pre-192,0004c85b. That was built from commit 0004c85b on master.

**Comment by ScottChesworth** [comment]
Aha, so that's what that's for! Thanks, good to know.

**Comment by CastleStarter** [comment]
Hi,
Did some testing using latest Reaper and Osara.
Yes, js plug in seems to work perfectly.  Using my own js plugin I can select all the distinct values on the slider and these are matched by the edit field values.
FullBucket Qyoo is not fixed though and I can arrow up to a envelope type e.g. env2, tab to the edit box where it will have a number matching env2, shift tab back to the slider and this now shows env1.  env1 being a value I had passed through to get to env2.

I can imagine this is pretty fiddly stuff.    Appreciate though that can’t fix for all providers.

Many thanks,

Chris G

**Comment by ScottChesworth** [comment]
How much contact have you had with Björn at FullBucket, Chris? He seems like a good dude. Wonder if one of us should hit him up, find out whether he uses GitHub and CC him into this discussion? I'm happy to do it, but figured I'd check whether you had a more established dialogue going first.

**Comment by CastleStarter** [comment]
Hi Scott,
I’ve probably had about 3 email exchanges with him and the most recent was about 4 months ago.  So no real established concorde with him.

I did mention this problem to him in one of my emails but I didn’t get a response to this point.  So yes, I agree he is a helpful person but perhaps maybe on topics he is most comfortable on.  I wouldn’t particularly want to open up this topic with him again.  

Regards,

Chris
