### ISSUE TITLE
Feature request: can we add an OSARA action to pause Peak Watcher notifications?

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#289]
Hi,

I reckon that an action to temporarily snooze Peak Watcher notifications without leaving the TCP would be a valuable addition to OSARA. Right now, users have to load the Peak Watcher dialogue and unfollow tracks, I get that that doesn't take long once you're intimately familiar with the dialogue, but until that point is reached (and tbh even after that point has been reached) reconfiguring a dialogue isn't something most folks want to be doing when either they or the person they're tracking is raring to go.

I'm imagining the screen reader saying "Paused Peak Watcher reports", where upon Peak Watcher could still be doing its thing in the background if that makes this easier to implement, just without reporting. Ideally the action would be a toggle, so a hitting a keystroke a second time would report "resumed Peak Watcher reports" and things would return to how they are right now.

Any mileage?

Scott

**Comment by jcsteh** [comment]
Should the Peak Watcher reporting commands still function while paused? I currently have this implemented such that the Peak Watcher stops monitoring while paused, but if I do that, those commands can't report levels.

**Comment by ScottChesworth** [comment]
seems reasonable to me man, pausing pauses everything.
