### ISSUE TITLE
Request: A simple Mac installation procedure

### ISSUE THREAD

**Issue by tbdalgaard** [jcsteh/osara#291]
Since Mac OS 10.15.4 OSARA is even harder to install on Mac OS. 
The reason is that Apple now are blocking third party unsigned plugins from execution.
There is a workaround, but this has to be done from the terminal.
So here is how I have got OSARA to work when installing on a Mac:

First I run the two terminal commands which are found in the diskimage.
After this I have to find the exact location of OSARA. I know it is in my home directory under /library/Application\ Support/Reaper/UserPlugins
When I have located the file I press command-option-C to copy the full path to the clipboard.
Now I open Terminal for the third time and type the following command:

sudo xattr -rd com.apple.quarantine "/Users/Username/Library/Application Support/REAPER/UserPlugins/reaper_osara.dylib"
After pressing enter here I confirm with my password, and hit enter again.
Now, OSARA is allowed to run, but to be safe I always reboot my machine.

Thanks to  @kyle for finding the terminal command above.
How can we make this installation procedure a bit easier to follow?

**Comment by jcsteh** [comment]
Probably the only way to do this properly is to be signed by Apple. As far
as I know, that requires a paid Apple Developer membership. That's not
something I'm personally willing to pursue, but I'll leave this open in
case someone else wants to pursue it.

One thing that could be done in the short term is to add the sudo command
to the shell script. That would ask for the admin password when the script
runs, which might worry some people, but it's the best I can come up with
for now.

**Comment by tbdalgaard** [comment]
Yes, or perhaps make a pkg-installer. This would be easier for the not so tech savi users. I believe the command line tools for XCode can provide something in this regard, but I am not a programmer by any means... So I can't confirm this idea.
But if the installation could be done this way it would (be possible to execute the script and the end user could decide about installing the OSARA keymap or just get a copy which could be imported via Reaper. This is possible, because the pkg-installer allows the end user to press a "special" key, and in many cases this makes it possible for the end user to customise a few things before the install button is pressed. To complete the install, the user must provide his or her password, and therefor we could easily execute the script to get OSARA through the security system.

I wonder how the keymap can be installed into a portable version of Reaper, since the scripts (as I understand) only focus on a native installed Reaper, and not a portable version. I may have missed some information about installing OSARA and the keymap in a configuration like this, but I wish we could get a little closer to the way the install works on the Windows side, so the installation on Mac OS would be a little more user friendly for people who aren't that tech savi, and for whom the Terminal can be a much unfamiliar area of their computer.

**Comment by jcsteh** [comment]
I tried to create a pkg installer way back when I was standing up the Mac port. The problem is that OSARA and its key map need to install for the user, not the system. Pkg installers have some weird issues. I don't remember specifics, but I vaguely recall you couldn't default to a user installation. The installer always made you choose, and worse, the Mac installer had accessibility problems which made that choice difficult with VoiceOver. Needing to install the plugin and keymap as user and then run the sudo command as admin makes things even more complicated. I think someone who has more experience and/or time for Mac specific development would need to take a look at this.

**Comment by ScottChesworth** [comment]
I've had a quick look into notarizing. There's no cost outside of time and patience, but seems like we'd need to be on Xcode 10. There are also a boat load of requirements that my understanding of OSARA doesn't go deep enough to know whether we'd meet. More info here:
https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

**Comment by ScottChesworth** [comment]
Re an installer, got someone in mind who might be able to help with that. I'll fire off an email and report back.

**Comment by jcsteh** [comment]
If it's helpful, the original work I did on this is in the [macPkg branch of this repository](https://github.com/jcsteh/osara/tree/macPkg). At the very least, it should serve as a useful starting point.

**Comment by jcsteh** [comment]
On the contrary, as described in that article notarizing requires you sign with a valid developer id certificate, which you can only get if you're part of the (paid) Apple Developer Program.

**Comment by jcsteh** [comment]
The other problem with notarizing for OSARA is that every build has to be submitted to Apple. Because OSARA doesn't have specific releases (just continuous snapshot builds), that's probably not feasible. I guess we could just arbitrarily make a "release" every 3 months or so, but then Mac users would be behind Windows users for that period.

**Comment by ScottChesworth** [comment]
My bad for missing the associated cost. I could front that $99 each year if notarizing was practical. The page linked above seemed to suggest that notarizing would often be an automated process, and the final section of the article, there's a link to an article about integrating notarizing into automated build environments. How practical would that be for OSARA though, @jcsteh ?

**Comment by jcsteh** [comment]
I did a bit of research. Notarization is automated, but it is not immediate. I don't think we'd be able to attach the notarization to the download for automated builds. However, it seems that if a notarization ticket isn't included in the build, Mac OS will fetch it from the cloud when you try to run the build. So, that should be okay, at least for snapshot builds.

That said, before we commit and start spending anyone's money, there's a bunch of work that should really be done first. We definitely need to update to Xcode 10, which first means working out whether anyone depends on 32 bit builds of OSARA. Once we move to Xcode 10, we won't be able to build 32 bit. REAPER provides multiple builds for this reason, but I'd really rather not offer multiple builds of OSARA; it makes things way too complicated.

I think it's probably also worth dealing with this pkg installer thing if possible too. I don't think that's an absolute requirement - you can notarize binaries and dmg files - but if we're going to polish things and spend money, we may as well do it properly.

Finally, when I say "we", I mostly mean this will need to be someone else with Macexpertise and time. I could certainly figure all of this out, but unfortunately, I just don't have the time. I'm happy to help where I can - providing guidance, review, integration into automated builds, etc. - but I can't commit to doing most of the actual work.

**Comment by RDMurray** [comment]
A solution to the quarantine problem would be to use cat instead of cp in the install script.  I have tested this and "cat file1 > file2" doesn't copy the quarantine bit.

**Comment by tbdalgaard** [comment]
Cool @RDMurray !
If that will work I am happy. However is there any way to make a portable version of OSARA without knowing to use the Terminal?
Would be fantastic if there was a small script which prompted the user to browse to the directory where the portable Reaper was located and then did its usual thing.

I am considering to update some of the information on the Reaper Accessibility wiki about Mac installation, but @jcsteh would you be willing to have some of it on the Github readme as well?

**Comment by RDMurray** [comment]
Here is a build for Mac users to test.  I tested it, but only on a beta version of Catalina.  [Download it here.](https://www.dropbox.com/s/1wsw4r5fu3hkhsw/osara_2020.1pre-50%2C8799be2c.dmg?dl=1)

**Comment by RDMurray** [comment]
@tbdalgaard I don't see why not.  I have very little macOS experience, but I'll look into it...

It looks like it can be done easily with applescript.

**Comment by RDMurray** [comment]
I have created an installer which can install in a portable version of Reaper.  It can also copy the keymap.  Please test [this build](https://www.dropbox.com/s/vd6auor9g77vyso/osara_2020.1pre-54%2Cebc2ee07.dmg?dl=1) and let me know if everything works as it should.

I tried making it an app to start with to avoid the terminal window opening, but then you had to open it twice in a row from the context menu to get round the security dialogs.
