### ISSUE TITLE
UX change: would it be possible to load the OSARA Parameters dialogue by hitting P in the FX window?

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#292]
During tutoring sessions and on the various support channels, I've noticed that the question of how to get access to the OSARA Parameters dialogue comes up often. The sticking point in the majority of cases I've observed has been that people's intuition leads them to hit P whilst still in the FX window after they've instantiated a plugin.

I don't think we should change the existing behaviour, but I'm wondering whether hitting P within the FX window could be implemented without too much grunt work? I can see how closing the FX window isn't particularly intuitive.

Scott

**Comment by jcsteh** [comment]
1. It's almost certainly possible on Windows. I'm not sure about Mac,
though. Technical: Depends whether REAPER accelerator_register_t captures
keystrokes in the FX window (on both Windows and Mac) and whether the
control id (GetWindowLong GWL_ID) for the FX list is the same on Mac.
2. The "p" key in the FX window would have to be hard-coded. It wouldn't
honour any remapping of the action in the main section, nor would it be
customisable.
3. The FX window would probably end up being left open. Given how windows
float in REAPER, is that likely to be a problem? I don't think it's going
to get focus when the user dismisses the OSARA parameters dialog. So, the
user would have to hit f and then escape to fully close it if it was
obscuring something.

**Comment by ScottChesworth** [comment]
Looks like we can handle this in the next keymap revision by assigning P with global scope, so closing the issue. Shout out to Garth for the solution.
