### ISSUE TITLE
Can we slightly soften the language on the snapshots page?

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#295]
Over the years, I've received quite a few instances of feedback that the language on the snapshots page is kinda scary to new users. Given that OSARA is stable nowadays, can we soften that language? I'd like to see something like:
This page contains the latest snapshots of OSARA in its current state of development for Windows and Mac. OSARA is an open source extension under ongoing development, so we encourage you to check back here every so often to ensure that you're running the latest release (note the date after each build number).
Be aware that technically, OSARA has not yet had a stable 1.0 release. That said, the extension can safely be considered stable. At this point, OSARA is being used every day by people all over the world.
If you find a bug, please open an issue at https://github.com/jcsteh/osara and describe what's happening (preferably with steps of how to reproduce the issue).
Support requests should be posted on the Reapers Without Peepers (RWP) group at https://groups.io/g/rwp.

**Comment by jcsteh** [comment]
Done, with some slight tweaks. The fact that this has remained this way is mostly my tendency to try to avoid people contacting me expecting more than they should. However, the RWP community (you chiefly among them) have done a great job of shielding me from that kind of thing with OSARA, so I'm happy to make the change. :)
