### ISSUE TITLE
echo undo and redo actions

### ISSUE THREAD

**Issue by GianlucaApollaro** [jcsteh/osara#3]
Hi, I wanted to thank you for the work you've done for reaper and its accessibility. I'm working on a keymap and I assigned some more actions besides the ones you suggested. I wanted to report though that the undos and redos are not echoed and that would be a good thing to have, aswell as when something gets deleted, for example 1 item deleted or track deleted.
I thank you again,
Keep it up,
Best regards,
Gianluca from Italy

**Comment by jcsteh** [comment]
Can you give an example of echoing undos/redos? I don't think it's useful to just say "undo" or "redo", since you already know you pressed that key and it may not have actually done anything. Also, do sighted users get this indication? (They would for deletion of items/tracks, since it'd be obvious that it disappeared.)

**Comment by GianlucaApollaro** [comment]
Hi again,
It is useful to have it say for example: Undo split items. Let's say You 
split an item, then you do other things and then you understand that 
your previous split needs to be undone because it was unnecessary. When 
you hit CtrlZ you won't know when you undid the action that created that 
split if you don't hear it. A sighted person would see it, we would have 
to go back and check how many items we have. That's why I think 
rea-access does it good by echoing those actions.
I hope I explained it well enough.
Thanks,
Best regards,
Gianluca from Italy
Il 06/02/2015 00:17, jcsteh ha scritto:

**Comment by jcsteh** [comment]
Ah okay, so ReaAccess reports what is actually being undone. That would be useful. I'm not sure how ReaAccess is doing that. I'll try to figure out it how it can be done. :)

**Comment by jcsteh** [comment]
Note to self: Use functions Undo_CanUndo2 and Undo_CanRedo2. Will probably need to intercept the entire action, not just post action.

**Comment by GianlucaApollaro** [comment]
thanks a lot, that's very much apreciated
