### ISSUE TITLE
Showstopper in Params dialogue with OSARA 2020.1pre-192,0004c85b

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#300]
In this snapshot, parameters reporting floating values seem to be causing a huge amount of lag at best, and crashing the DAW at worst.
I've also seem some params fail to respond to arrows/Paging keys, then start responding again on a second load of the dialogue.
Kyle (a Mac user) flagged it on WhatsApp, and I can reproduce issues here on Windows.
Strange thing is, sometimes it all works smooth as butter, other times the wheels fall off. I'm not noticing an obvious pattern yet.

It's getting late here and I've got a super early start, so I probably can't poke at this more tonight. For now, I've shot a message out asking people to hold off updating until we give 'em the all clear.

Do you think it's worth reverting what's on the snapshot page until we've tested recent commits more thoroughly, @jcsteh?

Sorry to be the barer of grim news.

**Comment by jcsteh** [comment]
Hopefully fixed, but please reopen if not. I couldn't reproduce crashes here, but there was an uninitialised variable in some cases, so that would have caused all sorts of weirdness.

**Comment by kyleman** [comment]
here is my audio I sent to WhatsApp as well:
https://www.dropbox.com/s/8fa3v7lnjzjs495/AUDIO-2020-09-03-18-22-04.m4a?dl=0

**Comment by jcsteh** [comment]
@kyleman, can you please test the latest snapshot (OSARA 2020.1pre-165,1eeb8396 for Mac)?

**Comment by kyleman** [comment]
That build seems to work. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ScottChesworth** [comment]
All seems well here on Windows with pre194 too. Thanks for the super speedy fix @jcsteh
