### ISSUE TITLE
Crash after changing track parameters via the parameter dialog

### ISSUE THREAD

**Issue by tbdalgaard** [jcsteh/osara#302]
The following steps will crash Reaper on Mac OS 10.15 running Reaper 6.13:

1. Open an empty project and create a track.
2. Press up or down arrow so the track is focused.
3. Press command-shift-p. This activates the action: OSARA: View parameters for current track/item (depending on focus)
4. Don't need to change anything here. Just press return.
5. Reaper will shut down with no warning and all changes you did is lost.

**Comment by jcsteh** [comment]
Can you please confirm which exact version of OSARA you are running? There have been quite a few updates to OSARA in that area in the last couple of days, including a crash fix, so it's crutial we confirm you're running the latest build.

**Comment by tbdalgaard** [comment]
I use: OSARA 2020.1pre-167,b4a9e858
and this still crashes Reaper.


Sendt fra min Mac Mini via Apple Mail

**Comment by jcsteh** [comment]
If you close the window using the window close command (whatever that is on Mac) instead of pressing enter, does it crash then too?
Can you adjust parameters just fine before you dismiss the dialog and crash?

Can anyone else on Mac reproduce this? I can't reproduce it at all on Windows, even inside a debugger. Unfortunately, I don't use Mac and am not likely to get a chance to do anything on a Mac for a while.

**Comment by jcsteh** [comment]
I just landed a tiny correctness fix, but I very much doubt it will fix this, though the issue may or may not have been causing a memory leak.

**Comment by jcsteh** [comment]
@kyleman, can you reproduce this crash?

**Comment by tbdalgaard** [comment]
Just updated to osara_2020.1pre-168,41f0596e

**Comment by ScottChesworth** [comment]
You closed this Thomas. Just checking, does that mean it's resolved in pre-168?

**Comment by tbdalgaard** [comment]
Hi Scott. Yes I was not able to reproduce the issue after updating to the build Jamie posted. Thought my comments came along when I closed the issue... Oh Well Github is still new to me. 

Sendt fra min iPhone via Braille Sense U2/MBraille

**Comment by ScottChesworth** [comment]
All good dude. Just figured I'd check because that "Close and comment" button has caught me out before. :)

**Comment by kyleman** [comment]
No crashes here with OSARA 2020.1pre-172,3e400838 for Mac (Mon Sep 7 10:28:58 2020)
