### ISSUE TITLE
UX inconsistency: select all in MIDI Editor reports, select all in TCP doesn't

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#306]
Right now, when a user hits Control+A to select all in the piano roll view of the MIDI Editor, the new selection is reported (@RDMurray's handiwork I believe).
When a user hits Control+A to select all in the TCP, no selection is reported.

Can the TCP action below provide feedback to square this inconsistency away?

Action: Select all items/tracks/envelope points (depending on focus)
ID: 40035

Thanks in advance.

**Comment by jcsteh** [comment]
Duplicate of #236.

**Comment by ScottChesworth** [comment]
So it is. Apologies. I should've checked.
