### ISSUE TITLE
Feedback when the track is in a group

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#316]
Hello,
when I do alt + g and assign controls to the group on multiple tracks, if I scroll in the track view it is not reported by OSARA.
Do you think it is possible in tcp to signal when a track is in a group?
It would be very useful, track number, track name and then the rest of the information, in this case if it is in group 1, 2, 3 and so on.
Thank you!

**Comment by RDMurray** [comment]
Yes, it is definitely possible, the question is how much information to report.  A track could be volume lead for group1 and pan follow for group 2 and so on.  Is it enough just to hear the group numbers for the track? 

Perhaps it would be good to have a command to report detailed information about track group membership.

There's one problem I see with implementing this correctly and that's that the API only provides group numbers, so we couldn't easily report the names of the groups if they are renamed.

**Comment by jcsteh** [comment]
> There's one problem I see with implementing this correctly and that's that the API only provides group numbers, so we couldn't easily report the names of the groups if they are renamed.

I (and now @ScottChesworth) have had a fair bit of luck getting Cockos to add new stuff to the API where necessary. Might be worth a shot here?

**Comment by Lo-lo78** [comment]
Hello everybody, 
if it were possible to report the group number it is not bad. 
Of course, it would be great if there was the group number and name. 
In any case it is necessary that the track indicates that it is linked to a specific group. 
If you can't get feedback on a group name, the group number is a good thing: 
group 1, group 2 and etc. 
Thanks, you are great!

**Comment by ScottChesworth** [comment]
Requested new API from Cockos. I'll report back if/when their response comes in.

**Comment by Aleskis** [comment]
Thanks Scott for your feedback to Cockos. Can you provide the link to the demand? I would like to support it.

**Comment by ScottChesworth** [comment]
I can't link to that @Aleskis because it was requested via email, not via the forum. It's been a while and we haven't seen any movement yet, I'll bump the thread today.

**Comment by RichCaloggero** [comment]
Yes, +1 for this functionality. I don't use groups all that often, but for people that do it would be very helpful to know, at a minimum, whether a track is part of a group. I'm thinking of complex projects with 20 or more tracks; very difficult to remember everything, especially if your working on several large projects simulaneously.

Thanx for everyone's work on reaper accessibility! It is an amazing piece of software, and certainly the most usable / accessible music software I've ever seen!

**Comment by Aleskis** [comment]
Maybe we could re-launch the subject by making a post on the forum? This would have the advantage of mobilizing several people to support the idea? Besides, it wouldn't prevent us from mentioning this thread via email, Twitter or other afterwards by indicating the URL.

**Comment by ScottChesworth** [comment]
Mobilizing several people doesn't have any noticeable impact on the timeline with Cockos in my experience, but sure, you could try the FR forum.

**Comment by ScottChesworth** [comment]
This just in from Justin:
"I will add support for names to GetSetProjectInfo_String() in the next build-ish"
Will that work for ya, @jcsteh?

**Comment by jcsteh** [comment]
That should work nicely. Note that there are still unanswered UX questions; see https://github.com/jcsteh/osara/issues/316#issuecomment-700998684.

**Comment by ScottChesworth** [comment]
> the question is how much information to report. A track could be volume lead for group1 and pan follow for group 2 and so on. Is it enough just to hear the group numbers for the track?
> 
Hmmm, I see what you mean. Reporting could get very verbose very quickly if we're not careful.

> Perhaps it would be good to have a command to report detailed information about track group membership.
> 
I think this is the way to go yeah. Where it'll go on the key map is anybody's guess, but we'll find a home for it.

Maybe OSARA only reports "grouped" when moving through tracks, and the user hits a key to run a new OSARA action called something like "OSARA: report track grouping status" to get more info on demand? That way, if the project is familiar we'll hear minimal extra reporting, but info can be easily obtained when needed. I reckon that strikes a good balance.

**Comment by jcsteh** [comment]
How often would a track be in many groups? We don't want to spam the user, but on the other hand, if it's usually only one or two groups, I wonder whether we should report the numbers when navigating to the track.

If we did have a command to report group membership, should it aggregate by toggle or group? That is, should it be like this:

> volume lead: 1, 2
> pan follow: 1, 3

Or this:

> 1: volume lead, pan follow
> 2: volume lead
> 3: pan follow

**Comment by Aleskis** [comment]
It's hard to say outside the context of use, the first proposal seems better to me:
"volume lead: 1, 2
pan follow: 1, 3"
But, again, it will have to be verified in use.
In any case, I think that the announcement should be done on demand, either via a toggle action or via an action that states the status once.
Thanks for all the work done.

**Comment by jcsteh** [comment]
I ended up going with this format:

1: volume lead, pan follow

The reason is that there are some controls like "reverse volume", etc. that I think are more important to understand with the rest of the information for that group, rather than separately.
