### ISSUE TITLE
Automation Items names

### ISSUE THREAD

**Issue by betov75** [jcsteh/osara#318]
It would be great to hear the name we assigned to an automation item instead of only its number. If the API permits it of course...
Thanks for all!

**Comment by jcsteh** [comment]
The API does support this now, though I'll have to check what version that was added; it'll require OSARA to drop support for some older versions of REAPER. However, technically, the name set for automation items is the name of the automation item pool, not the name of the automation item itself. I don't really understand what this does, but apparently, you can have multiple automation items in the same pool, and when you do this, they apparently have the same name.

What makes things confusing is that by default, a pool gets a number as a name. So if OSARA reports both the automation item number and the pool name, you could get two numbers, like "auto 2 1". But if we don't report the number, then you won't be able to tell two items in the same pool apart.

I guess we could report "auto 1 pool poolName", so you might hear "auto 1 pool 1" if you haven't renamed it or "auto 1 pool blah" if you renamed it to blah. Or perhaps it's enough for the position to differentiate two items in the same pool?

**Comment by betov75** [comment]
Hi James,
Auto 1 Pool poolName is the perfect workaround for that API's limitation. Because it's clearly when pooled that it's important to be able to track it. Great suggestion.

**Comment by betov75** [comment]
It can also be "Auto 1 2" or "Auto 1 blah" to make it quicker. The pause seems enough.

**Comment by jcsteh** [comment]
Just to be clear, this isn't just an API limitation as far as I know. It applies to Righteaper as a whole; i.e. auto items don't themselves have names, only pools do. I assume if you have two pooled items, the name you see in the properties dialog for both will be the same and one will impact the other.

**Comment by betov75** [comment]
I've tested it and it's exactly the behavior that you're describing. So,
the name of the item, when I rename it using action #42091, the name that
appears is the same for a non-pooled and a pooled one. A new one is
numbered but the number is only it's poolName I assume. Is something like
that possible when moving on an automation item:
auto poolName bar 32 beat 4 50 percent? I think it's more useful than it's
position. But the reported position can easily be added as a custom action
anyway. (I add the position on almost everything :) )

>

**Comment by betov75** [comment]
Oh nice, it's perfect! So helpful.
Again, thanks for all. A gigantic workflow improvement for me.
