### ISSUE TITLE
The delete key stops deleting items.

### ISSUE THREAD

**Issue by betov75** [jcsteh/osara#319]
Hi!
At one point, the delete key stops working correctly. But it still works fine if I start a new project in a new tab. I've tried to find my own mistake, if there's one. It's in a project, not in all open projects.

**Comment by ScottChesworth** [comment]
Can you pop the troublesome RPP file in Dropbox and post a link to it here so we can take a poke around? No need to include media, just the RPP file will do.

**Comment by betov75** [comment]
Hi Scott,
It may be hard to find, the problem vanishes when the project is reloaded. It happened only twice.
Here's the link to the RPP file: https://drive.google.com/file/d/1C_lOo7fTBzq-Bhg4nQP4EAUMx8-sWI05/view?usp=sharing

**Comment by betov75** [comment]
I'm very sorry, It was bad shortcut handling on my side. Not a real issue. They were locked by mistake.
