### ISSUE TITLE
From the FX chain, go directly to the buttons: Param, I / O, preset and the FX comment

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#320]
Hi James and everyone!
It would be very interesting to be able to do it from the FX chain list. select a plugin and with shortcuts go directly to the Param button, button for routing the I / O plugin, button for managing presets and the ... button for plugin comments.
A bit like you can do with F6.
In this case, being buttons it would be nice if they could be activated automatically with shortcuts.
Type: I make the shortcuts that leads to the Param button and directly opens the context menu and so on for the other buttons.
Thank you!!!

**Comment by ScottChesworth** [comment]
Can you outline a workflow to explain the benefit of implementing this? Those controls are already easily accessible in the tab order of the FX windoe, so I’m not seeing a reason for OSARA to change the UX here yet.

**Comment by Lo-lo78** [comment]
Hello Scott,

it is a way to speed up browsing while mixing.

With the tab key you have to search for it and take some time for it.

With shortcuts it could be a convenience to work quickly.

Thank you guys!

Il 09/10/2020 21:28, ScottChesworth ha scritto:

**Comment by ScottChesworth** [comment]
Given that accessing the generic controls within the FX window is a pretty small tab order anyway, I'm not convinced of the benefit when actual implementation time is thin on the ground and unfunded as it is right now. Feel free to reopen if you can outline a stronger, more specific use case.
