### ISSUE TITLE
possible bug: copying/pasting envelope points inside automation item copies the automation item itself instead

### ISSUE THREAD

**Issue by ns-studios** [jcsteh/osara#323]
Not sure if I'm doing something wrong or if there's something weird going on with my setup/Reaper, but
if I
focus a track,
Select the envelope I'm looking for (OSARA: Select next track/take envelope (depending on focus)),
select an automation item (Item navigation: Select and move to next item),
get to the point I need (OSARA: Move to next envelope point),
and I either copy a single item, or select a few (OSARA: Move to next envelope point (leaving other points selected)) (Edit: Copy items/tracks/envelope points (depending on focus) ignoring time selection),
it tells me: 1 automation item copied,
and then if I paste (Item: Paste items/tracks), it pastes the item instead of points.
The same scenario happens if I try to copy the points explicitly with Envelope: Copy selected points,
and then use paste (Item: Paste items/tracks and SWS/AW: Paste both do the samething).
REAPER 6.14 x64
osara 2020.1 pre 227 3ed5d5c9

**Comment by ScottChesworth** [comment]
Seems like context sensitivity is what's tripping you up. I'm pretty sure that if you select the envelope you want to paste the automation item or points to before pasting, it'll work as expected for ya. At least, it does here. Closing this for now. Feel free to reopen if there's still an issue persisting once you've tried that out.
