### ISSUE TITLE
Visual display does not follow track selection

### ISSUE THREAD

**Issue by nwolek** [jcsteh/osara#325]
I am a sighted person who was watching a demo of OSARA today by Derek Lane. As he was demonstrating the ability of OSARA to change track selections using keystrokes, I noted that the visual display did not follow his selections. It took a few minutes for us to figure out what was happening. 

The selection started with tracks that were on screen, then he used the keystrokes to advance through higher numbered tracks. Eventually his screen reader would read the name of the track he was working on, but that track seemed to be off-screen and not part of the visual display. 

It would be nice for OSARA to update the vertical scrolling in Reaper so that the current selected track remains on the screen. Having the visual display match the screen reader would help facilitate collaborations between blind and sighted users.

Let me know if you need additional details or assistance.

**Comment by jcsteh** [comment]
Wow. This is puzzling. OSARA just asks REAPER to set the selected track and
I would have thought it'd scroll to the most recently selected track
automatically. This makes me wonder whether REAPER scrolls the screen when
you navigate through tracks with a control surface?

I have no idea how one would manage this with the REAPER API.

**Comment by nwolek** [comment]
It was surprising for Derek too! I'm completely new to your project, but have done C++ programming before. Can you point me to the relevant part of your code so I can take a look?

**Comment by jcsteh** [comment]
It just unselects and selects the track, which ensures it becomes the "last
touched" track:
https://github.com/jcsteh/osara/blob/910e7db4963a7964bcf1ef7814ed9ebdb7c404cf/src/reaper_osara.cpp#L1866
