### ISSUE TITLE
Last Track Title Repeatedly Spoken Whilst Navigating In Media Explorer

### ISSUE THREAD

**Issue by ironcross32** [jcsteh/osara#331]
Invoking Media Explorer and tabbing through its interface will, in most cases, cause the name of the last selected track to be spoken per each press of the tab. This is most notable when performing a search, then tabbing to the list to see the results.

**Comment by ScottChesworth** [comment]
At a glance, I haven't been able to reproduce this here.

Which version of Reaper, which screen reader, and which version of the screen reader (if Windows) are you using?

**Comment by ironcross32** [comment]
NVDA version alpha-21225,26273124 on Windows version 1909 build 
18363.1139. Reaper 6.14/x64 rev 985751

**Comment by ironcross32** [comment]
Here is an audio recording of the behavior as I am experiencing it.

**Comment by ScottChesworth** [comment]
I don't think that audio recording made it up here dude, unless I'm missing something obvious. Can you re-post?

**Comment by ironcross32** [comment]
[Osara_iss#331.zip](https://github.com/jcsteh/osara/files/5398301/Osara_iss.331.zip)

**Comment by ironcross32** [comment]
Done @ScottChesworth It must not have fully uploaded the first time but I see it there now.

**Comment by ScottChesworth** [comment]
Got it, thanks. Ouch, that's a clanger!
