### ISSUE TITLE
Display of the midi input

### ISSUE THREAD

**Issue by ranetto** [jcsteh/osara#332]
Hello, as you surely know in reaper, when you play a midi instrument or an external synthesizer, the midi signal is displayed on the miter, therefore the velocity of the notes and their presence.
Could it be found in osara?
I think it is useful to know if midi is entering the reaper and to check the operation of the peripherals even if it is not possible to hear the sound of the synth in question.
Thanks in advance.

**Comment by ScottChesworth** [comment]
Just had eyes confirm this, incoming MIDI does indeed register on the track meter visually even when the VSTI I had instantiated on the track was bypassed. Varying the velocity was also reflected in the metering visually.

**Comment by jcsteh** [comment]
I'd be interested to know whether the existing metering commands report anything in this case. The values are probably obscure at best, but if they report something other than -150.0, that suggests REAPER exposes this info in the same way it does for audio. The question would then be how to tweak those values to be useful on MIDI tracks.

**Comment by ranetto** [comment]
Hi James, I tried this:
created a track, set input to midi, armed and activated the monitor:
nothing the level was always -150 I then inserted a synth in that track to make sure again that the midi arrived, in fact the synth sounded and the instruments marked the normal level of the synth.
In reaper preferences you can find some instrument settings to signal the midi level which I believe is expressed as velocity.
Thanks for your interest.

**Comment by ranetto** [comment]
Hi James, I try to post these tips from reaper preferences to see if they can help you find a way to solve this problem:

"Flash MIDI editor keys on track input:
Show a brief color flash on the MIDI editor keyboard when the track receives MIDI note-on input. "
"Show MIDI velocity on track VU:
When a track has MIDI input, show the MIDI note velocity as a thin line at the bottom of the track VU meters. "
"Show MIDI output activity on track VU:
When a track has MIDI output, show the activity on the track VU meters, as a thin line for note velocity and a small square for other activity. "

**Comment by ScottChesworth** [comment]
Nice thought, but OSARA doesn't screen scrape for meter information, so the visual feedback options in Prefs won't have any bearing on getting this implemented.

**Comment by leonardder** [comment]
I'm pretty sure that it is not possible to get to anything like the midi data.

**Comment by ranetto** [comment]
Hi Scott and everyone, clearly we couldn't read this information from the meter, but I just gave James this suggestion to test if any of the "APII" reaper exhibited could give us a trig midi, either in the form of notes or in the form of velocity values or simply in the form of an event when a midi signal of any type arrives from one of the configured ports.
Thank you all.

**Comment by jcsteh** [comment]
Is the new feature to report MIDI input in shortcut help sufficient to address this? It's different to the visual UX, but it seems equivalent IMO.

**Comment by ScottChesworth** [comment]
I think it's sufficient yeah. We don't report velocity, but neither does the visual metering do that in specific numbers.
