### ISSUE TITLE
Search for tracks:

### ISSUE THREAD

**Issue by ranetto** [jcsteh/osara#333]
Hello, I wanted to know if it was possible to create an osara action that presents an editing field where you can write the name of a track, if it is found then osara will select it, otherwise it will say not found.
I know that there are other actions that you can use, and in fact I am using them, but they always involve having to display a list, such as the trackmanager, fill in an edit field, exit the dialogue and see the tracks found and then re-enter the dialogue. manager, clear the edit field to review all traces of the project.
This would make my work much faster than scrolling through 70 or 80 tracks of music and vocals.
Thanks in advance.

**Comment by ScottChesworth** [comment]
You can already use ReaConsole to do this. For example, to select and move to a track called guitar, hit Alt+C to load ReaConsole, type "S guitar", then hit Control+Enter to execute the command and close the console window. The S in that command being uppercase tells ReaConsole to select just that track. A lowercase s would add the track called guitar to your existing track selection, which might still move you to it, not sure.

**Comment by jcsteh** [comment]
Closing given this is already possible with ReaConsole.
