### ISSUE TITLE
FX parameters added to a track:

### ISSUE THREAD

**Issue by ranetto** [jcsteh/osara#334]
Hello, in the new function of viewing the FX parameters added to the TCP, osara does not vocalize the correct name of the added FX and its parameter in the list, but is only vocalized by moving the focus on the slider that adjusts the value of the parameter with the tab key .
In this way, scrolling through the list it is not possible to understand which FX the parameter refers to.
Can anything be done to improve this situation?
Thank you!

**Comment by jcsteh** [comment]
I can't reproduce this. If I create a clean project with one track, add ReaEQ's Freq-Low Shelf parameter to track controls, open the Track Parameters dialog and arrow down the list of parameters, I get: volume, pan, mute, VST: ReaEQ (Cockos) Freq-Low Shelf. What are you seeing in the parameters list? Please provide the exact steps you took, what you expected and what happened instead.

**Comment by jcsteh** [comment]
Please also specify what screen reader you're using and whether you have any scripts/add-ons installed.

**Comment by ranetto** [comment]
Hi James, then I realized that the problem manifests itself with jaws:
with NVDA, I'd say okay, in the listview it announces the name of the instrument and the name of the parameter, clearly it doesn't announce the value that is announced correctly when you focus on the list with the tab.
With jaws, this does not happen but it's not osara's fault but the snowman's jaws scripts.
Thank you and you can safely close it!

**Comment by ScottChesworth** [comment]
@ranetto , are you good to make contact with Jim to get this fixed up in his scripts? I can do it if not, just don't want to duplicate effort.

**Comment by ranetto** [comment]
don't worry tonight I'll contact him and tell him everything:
meanwhile I am already in contact with him since version 37 and we are working well:
thanks Scot.
