### ISSUE TITLE
Item in solo

### ISSUE THREAD

**Issue by ranetto** [jcsteh/osara#335]
Hello, when I put an item solo in a track and then I go to modify it, then lengthening it or especially shortening it, I am no longer able to remove the solo of that item in any way.
Maybe because its size changes?
Not even selecting all the tracks and therefore all the items of the tracks of that project and removing the solo can no longer remove the solo from the items and return to a normal play.
To do this I have to close the project, and reopen it, after saving it select all the tracks and all the items and use the one action only for all the items.
Can anything be done?

**Comment by ScottChesworth** [comment]
Nearest I can get to reproducing this is that for some reason, after the item length changes, I have to hit the item solo toggle twice for it to unsolo. Dunno why. The behaviour holds up without OSARA though, ergo, this is an issue for Cockos.

**Comment by jcsteh** [comment]
Given that this is not OSARA or accessibility specific, I'm closing this. This should be raised with Cockos.
