### ISSUE TITLE
Context sensitivity when selecting items and working with a time selection

### ISSUE THREAD

**Issue by tbdalgaard** [jcsteh/osara#338]
I thought of adding this under issue #285
but decided to create this instead.

Can context sensitivity be smarter when working with different selections?

See this example where I want to delete the contents of a time selection, but instead I delete an item instead

Steps to reproduce:

1. Open a project and import one media file.
2. Make three item splits, or how many you want.
3. Now go to the first item and move the cursor to the end of the item.
4. Make a time selection by pressing shift-home to select from cursor to start of project.
5. Press ctrl-shift-space to confirm the time selection.
6. Now press ctrl-right arrow to select the second item in the project. Keep in mind that the time selection is still active.
7. Now press shift-escape to unselect all items.
8. Press home to go to the start of the time selection.
9. Press delete to remove the time selection.

Problem: OSARA did not get that I wanted to delete the contents of the time selection, even when the item was unselected via Reaper. Is this a bug or a feature?

**Comment by jcsteh** [comment]
The problem here is that home and end aren't tracked by OSARA (notice you
get no feedback), so OSARA doesn't know it needs to switch to the ruler
context. (REAPER has no ruler context, so OSARA fakes this.)

**Comment by tbdalgaard** [comment]
I get why this is an issue. Perhaps we should try to request for time selection context in a future Reaper release of Reaper?

In the meantime we may try to get a workaround for this. As I explained in my first comment it took me some time to figure this out, because this differs from the context sensitivity in OSARA. Can we "fake" something for the time context sensitivity when it is active and nothing else is selected?
If we can't this **must** be documented somewhere.

**Comment by jcsteh** [comment]
I already worked around this and the change is in OSARA, hence the issue being closed. :)
