### ISSUE TITLE
Osara shows first and last trace during the filtering of the same

### ISSUE THREAD

**Issue by ranetto** [jcsteh/osara#341]
Hey everyone, when I filter the tracks to only have all the vocal tracks displayed using the "SWS: Show Tracklist" action, it always shows the first and last track of my TCP, which are not clearly displayed on the screen .
Could this be corrected?
Thanks in advance.

**Comment by ScottChesworth** [comment]
Can't reproduce this. Talk us through what you're doing there step by step.

**Comment by ranetto** [comment]
Hi Scot then:
I create ten tracks called piano, guitar, organ, flute, clarinet, drums, bass, distorted guitar, carpet and others.
I call the action "SWS: Show Tracklist", here I am shown all the tracks I have created, then I move with the tab to focus the edit box to search for a track within those created:
For example, I write organ:
now put the check mark, again with the tab, to hide the filtered tracks, which would be precisely those that do not belong to the search criteria.
Also put the check you find after the one to link the TCP and the MCP.
If you go back with capital plus tab, you will go back to the list and only the track you searched for will be shown, as in my case organ.
If you press escape and return to your "TCP", you will see only the organ track or all those that contain the word organ in their name on the screen.
Osara instead adds to the tracks actually visible on the screen the first track whatever it is and the last one as if they belonged to the research.
Was I able to explain myself?
Thanks Scot.

**Comment by ScottChesworth** [comment]
Gotcha. So the SWS track list window reflects the filtered as expected, but OSARA still reports the first and last tracks as being visible in the TCP, even though visually, they're not (confirmed by my long-suffering light slave).

In the TCP, OSARA actions still work on those unexpectedly reported first and last tracks, but Reaper actions don't.

One more detail to add to this, if you filter tracks with the master visible, the first track does disappear from the OSARA's reporting of the TCP as expected.

Seems like a bug to me.

**Comment by ScottChesworth** [comment]
Simplified reproduction steps:

1. Open a blank project and create 3 tracks called "first", "second track" and "last". It's important to only use the word track in the second one.

2. Run the "SWS: Show Tracklist with filter focused" action (ID _SWSTL_OPENFILT) and filter by the word "track".

3. Check the "Hide Filtered Tracks" and "Link TCP and MCP Vis" options using NVDA+Enter on each check box.

4. Examine the list box within this window, and you'll find that only the second track is visible now as expected.

5. Now hit Escape to close the window and compare the result that OSARA is reporting back in the TCP.
As indicated above, if your master track is hidden, both the first and last tracks will still be reported. If master is visible, first track is hidden as expected, but last is still unexpectedly reported.
Actions specific to OSARA still work on those unexpectedly reported tracks. Reaper native actions do not.

Hth clarify things for whoever can fix this.

**Comment by ScottChesworth** [comment]
If I were an hexapod invertebrate, I'd be very, very afraid of @jcsteh this week.

**Comment by ranetto** [comment]
Hi James, I did not understand if this report was closed because it was resolved or because it could not be resolved.
Thank you!

**Comment by jcsteh** [comment]
It's fixed. When GitHub says an issue was closed by/in a commit, that means a code change was landed which closed the issue.

**Comment by ranetto** [comment]
Thanks James and I'm really sorry, I'm new here and I'm still not sure how it works:
maybe you have already noticed:
I'm sorry but now I understand:
thanks again for solving this problem.

**Comment by jcsteh** [comment]
You're welcome... and no need to apologise. This stuff can be pretty overwhelming for people who aren't developers or not experienced with it.

**Comment by ranetto** [comment]
Hi Scott and everyone, the problem has already been communicated to the snowman for the jaws scripts and it has been solved: I already have the working version but maybe it will come out soon or maybe it is already out !.
