### ISSUE TITLE
OSARA ReaPack repository?

### ISSUE THREAD

**Issue by jcsteh** [jcsteh/osara#342]
I wonder whether it'd be worth OSARA having its own ReaPack repository. This would make it easier for users to keep up to date.

It's possible to create custom ReaPack repositories. Furthermore, it should be possible for the continuous integration scripts to update such a repository automatically.

Is this worth doing?

One big question is what to do about the key map. In this context, we definitely don't want to override the user's key map automatically, and I'm fairly sure ReaPack doesn't provide a way for packages to ask installation questions. Should we just dump it in the key maps folder and let the user update that if they wish? But then, how would users who use the OSARA key map know when they need to do that? That's probably the one big reason I'm not sure if having an OSARA ReaPack is worthwhile.

Thoughts, @ScottChesworth?

**Comment by Christianlm** [comment]
In general, when updating ReaPack  new actions are integrated.  The problem of assigning commands is only for the user  (professionals or not) who works with Reaper, it is "the actions" that make the plugin interesting, anyone can make their own keymap by themselves based on how it works.
To follow the same philosophy, OSARA should be distributed without keymap, or with a basic keymap, so that it does not overwrite the personal keymap. 
In general this is the philosophy of Reaper, and of other programs such as foobar.
I love  the idea to include OSARA in reapack, but if that means imposing a keymap during installation I think we need to find a different solution.
Below my proposal, open to comments:
1. Include OSARA in ReaPack:
2. Preserve the personal keymap when updating OSARA with reaPack.
3. For beginners (or I don't know for whom else), give the possibility to import the keymap proposed by OSARA or others.

Let me be clear, any decision here to improve accessibility in Reaper with OSARA is gold to me.
Thanks.

**Comment by jcsteh** [comment]
As I noted in my initial comment, I agree we don't want to replace the key map without asking... and there may not be any way of asking the user with a ReaPack installation, so it may not be possible at all.

That said, while there's some merit in the general philosophy of starting with a basic key map, this just isn't feasible for OSARA users. Without a key map (or spending hours mapping hundreds of actions yourself), it's literally impossible for a screen reader user to use REAPER. Where a sighted user can navigate and manipulate tracks, items, envelopes, etc. out of the box without mapping a thing, a screen reader user can't do much at all because REAPER's default key mappings are so limited. Try using REAPER with the keyboard alone (no mouse) out of the box. It just isn't possible.

The other reason for the default key map is teaching. While the REAPER user guide explains how to do many things with the mouse (and most of that can be done out of the box), it's very difficult to provide material that teaches screen reader users without standard keyboard commands to refer to. You'd have to use action names for the simplest of tasks, even navigating tracks and items, and the user would have to map all of those commands manually before they could get anywhere. That makes for a totally unintuitive learning experience.

All of this is what we had for quite some time in the early days of OSARA when I didn't want to ship a default key map. In time, I realised (after a lot of discussion with daily users) that this just wasn't sustainable.

All of this is to say that while I don't want to override user config without asking, not including the key map at all also isn't really an acceptable option.

**Comment by ScottChesworth** [comment]
Tbh, without a way to include keymap updates, I'm not seeing a significant advantage to being on ReaPack here. If anything, the approach would be less familiar to newbie/intermediate users than our current standard installers are. I can support people through it, but I'm not convinced the change of approach would yield a significant uptake in users staying current. It' just be a change from me saying "you need to update your OSARA" to saying "you need to update your keymap" instead lol.

I think we either need 1) our own updater, or 2) someone to collaborate with ReaPack to get it supporting installation questions/the possibility to place a keymap. I know, both easy suggestions for me to idly make when I don't have the chops to contribute either option. Please don't take that as any sort of demand, it's just me saying that those would be the steps forward that would benefit the highest amount of the users that I'm supporting.

**Comment by jcsteh** [comment]
Sounds like too much effort/controversy for too little clear gain at this point. Thanks for your feedback.

**Comment by leonardder** [comment]
> As I noted in my initial comment, I agree we don't want to replace the key map without asking... and there may not be any way of asking the user with a ReaPack installation, so it may not be possible at all.

Might this be something worthy to discuss with the ReaPack authors (e.g. @cfillion)?

I'd imagine it should be possible to distribute the library and the keymap separately, so people have control over what to update. Of course a particular keymap might rely on a particular version of OSARA.

**Comment by jcsteh** [comment]
> I'd imagine it should be possible to distribute the library and the keymap separately, so people have control over what to update.

Given how much of a major part the key map plays in the OSARA UX for most users, I'm not sure separate distribution makes sense. Most users see the key map as being a core part of the product and experience, as I learned early on when I initially chose not to distribute a key map with OSARA. On the other hand, we don't want to surprise more advanced users with their own customised key maps by overwriting their hard work. It's a tricky balance.

**Comment by jcsteh** [comment]
Oh, I think I was missing your point. I assumed you meant distribute the key map via an entirely separate channel. You mean distribute them as separate components, but both within ReaPack? So you would choose one or both, but you would explicitly make that choice?

**Comment by leonardder** [comment]
> You mean distribute them as separate components, but both within ReaPack? So you would choose one or both, but you would explicitly make that choice?

Exactly.

**Comment by jcsteh** [comment]
1. Would this work for users? Will most users (those that don't customise much, if at all) understand the need to install two components instead of one?
2. What happens if a user installs the key map via ReaPack but then decides they want to customise it and don't want updates henceforth? They might intuitively think they should remove it. But if they remove it, that'll delete their reaper-kb.ini, which seems bad.

**Comment by ScottChesworth** [comment]
@jcsteh, given that ReaPack only seems to appeal to the techier users anyway, I'm wondering whether including a snapshot version and build date into the properties of the dll and dylib files would be less work for a similar result? From here, I see more requests for a way to obtain information on the current version being run than I do requests for an auto-update service. The current snapshots page is so minimal and quick to check, I think adoption would improve if people could reference what's on the snapshots page against the version that they're currently running. That way, they'd know whether they actually need to update or not. Right now, it seems like updating is a "I guess I should, just in case" type thing for most users. Those "I guess I should" type things are easy to never get around to.

**Comment by RDMurray** [comment]
How about just including the keymap in the keymaps folder.  I would think that anyone using reapack would be able to import the keymap.  We could pop up a dialog whenever the keymap changes to let the user know they need to import the new keymap.  I don't think it is a good idea to automatically replace the reaper-kb.ini file because it wipes out custom actions and reapack scripts.

**Comment by ScottChesworth** [comment]
That'd work.
@jcsteh, just for clarity, you're talking about a ReaPack repo in addition to the current snapshots page right? Not instead of?

**Comment by jcsteh** [comment]
I would've included the key map in the key maps folder anyway, but this still leaves users with no way of knowing whether the key map has been updated. They see OSARA got an update, but they don't know whether they have to manually import the key map.

I guess this partly came up because I've seen quite a bit of chatter on the list about wanting to know when updates are available without checking the snapshots page, and now we have two (not one, but two) projects doing auto update for OSARA.

All of that said, given that this is still controversial even after this latest round of discussion, I'm not going to bother. I think there are other OSARA things that would be a better use of my time. :)

**Comment by vgjh2005** [comment]
I've read all comment above. I think Reapack and installation can exist at the same time. Because installation can hold all newest users and reapack repository is for advance users!
