### ISSUE TITLE
Consider undocking the Media Explorer by default

### ISSUE THREAD

**Issue by jcsteh** [jcsteh/osara#343]
By default, when you open the Media Explorer, it gets docked and does not get focus. This makes it pretty hard to access. When you're done with it, dismissing it when docked is also not intuitive or trivial. It might be worth OSARA disabling this automatically.

I'm generally pretty reluctant to mess with user settings without asking, as a user might have configured things that way for a reason, might be working with a sighted user, etc. It's also just rude. In this case, though, I wonder whether the difficulty of accessing this with default settings justifies this.

Alternatively, we could have OSARA ask the user whether to make some recommended setting changes at startup and give them the option. That does add complexity, though.

Technical notes:

1. There's an action in the Media Explorer section to dock the Media Explorer. It doesn't seem to have a toggle state unless the Media Explorer is open. I'm also not sure whether SetToggleCommandState will work on this.
2. This is controlled by the docked key in the reaper_explorer section of reaper.ini. Setting to 0 undocks. However, I don't know whether REAPER will reflect this setting automatically if it's modified at runtime.

**Comment by ScottChesworth** [comment]
I wouldn't perceive this to be rude so long as the dev is transparent about it. Could a new default option be added to the installer, something like "Automatically configure Reaper preferences to recommended settings for screen reader users", then an additional screen explaining what changes we'll be making to reaper-ini if that option is left checked? If we're gonna go down this road, there are other options I'd like to see included. Hiding the MCP and Prefs -> Keyboard/Multi-touch -> "Allow space key to be used for navigation in various windows" springs to mind.

**Comment by jcsteh** [comment]
I'd rather not do this in the installer, as it's much harder to maintain that across both Windows and Mac. I was thinking OSARA could pop up a dialog on first run (and maybe whenever our setting recommendations change) asking whether to make the changes.

**Comment by jcsteh** [comment]
>     2. This is controlled by the docked key in the reaper_explorer section of reaper.ini. Setting to 0 undocks. However, I don't know whether REAPER will reflect this setting automatically if it's modified at runtime.

It looks like REAPER doesn't. So that's one challenge with doing this in OSARA: we'd have to tell the user to restart REAPER (I don't see a way to force a restart). While not ideal, that doesn't seem too arduous.

**Comment by ScottChesworth** [comment]
That'd work yep. Could you also add a button to OSARA Config to manually trigger that dialog? Some folk are bound to click through it without listening properly.

**Comment by ScottChesworth** [comment]
I'll shoot Cockos a note to see if they can provide any advice on forcing a restart.

**Comment by ScottChesworth** [comment]
Advice from Cockos re forcing a restart:

From a C/C++ extension, you could execute a new instance via CreateProcess() or ShellExecute(), then quit immediately after (via ExitProcess() or exit())

**Comment by jcsteh** [comment]
I thought of that, but I didn't think it'd work on Mac, since that's a
Windows API. That said, it looks like SWELL has some support for this,
though it's kinda weird.

Initially, I think I'm just going to tell the user to restart and then exit
REAPER for them, unless you think that's ugly enough that it's not
something we want to do at all.

**Comment by ScottChesworth** [comment]
Still definitely worth doing I reckon. Handling the big tweaks that practically everyone ends up needing/liking would cut back on the WhatsApp support traffic here, if nothing else.

**Comment by leonardder** [comment]
I think several additional accessibility related options should be taken into account when implementing a dialog that suggests tweaks to the  Reaper config. I'm thinking about the new accessible fade names option as well as the ability to pass through space to controls instead of toggling play/pause in dialogs.

**Comment by jcsteh** [comment]
We should also probably tweak "Show FX state as accessible text in name". And may we also want to consider setting legacy_filebrowse=1.
