### ISSUE TITLE
Control surfaces

### ISSUE THREAD

**Issue by davidkreynolds** [jcsteh/osara#355]
With keyboard help switched on, some buttons on the control surface are slipping through the net. Interestingly, track select is one of these, and whilst it correctly speaks the selected track, it also selects the track. Interestingly, when keyboard help is off, the track name is not spoken.

**Comment by ScottChesworth** [comment]
Hey David, feedback is best logged here:
https://github.com/jcsteh/osara/pull/352
Thanksies.

**Comment by davidkreynolds** [comment]
Shucks. Shall I log it there now?

 

David.

**Comment by ScottChesworth** [comment]
Yeah please. Once you've done that, pop back and close this issue. Just helps to keep the legwork to a minimum for @jcsteh .

**Comment by davidkreynolds** [comment]
Scott,

 

I just commented on your post. I’ll close the issue now,

 

David.
