### ISSUE TITLE
Is any plant to upload osara to reapack?

### ISSUE THREAD

**Issue by vgjh2005** [jcsteh/osara#358]
Hi
Is any plant to set osara to reapack? I used reapack to collect lots of good scripts and plugins! When I Synchronize packages, all update data and changelog  that are included at added repositories have been set up. I don't need to download them manually when they are up to day. It is easy to realize what's news on it! Thanks for your hard work!

**Comment by jcsteh** [comment]
No. See #342 where this was discussed before and we decided against it for various reasons.
