### ISSUE TITLE
Remove OSARA: View I/O for master track

### ISSUE THREAD

**Issue by jcsteh** [jcsteh/osara#360]
In REAPER 5.x, there was no builtin action for this, so OSARA provided its own action and used some Windows specific hacks to access it. REAPER 6.01 added a builtin action: Track: View routing and I/O for master track (42235). OSARA just redirected to that action where possible.

Since take markers required OSARA to drop support for REAPER 5.x altogether, I've removed the old hack for REAPER 5. Since OSARA: View I/O for master track now always just calls the builtin one, it's pointless. I've left it for now so we don't break the key map. However, next time there is a revision to the key map, this should be replaced. Once that's done, we can remove the OSARA action.

@ScottChesworth, can you/the key map overlords please handle the key map side of this in a future update? Thanks.

**Comment by ScottChesworth** [comment]
Just remembered I was supposed to do this. The key map change is ready for Windows and Mac, can be included in my current PR. I just need clarification on removal of the old OSARA action. Would you prefer that code to be commented or actually deleted @jcsteh?

**Comment by jcsteh** [comment]
Please remove the code rather than commenting. We can always get it back from git if we need it for some reason. I'd normally prefer that to be done as a separate PR, but I understand key map changes are a pain to handle separately, so I can live with it being the same PR.

**Comment by jcsteh** [comment]
Oh. I just saw the code for this wasn't removed, even though the key map was updated. Reopening.

**Comment by ScottChesworth** [comment]
Sorry, I forgot to come back to remove the code. Currently attempting to do that and causing a hilarious amount of build errors. Every day's a should've gone to school day.
