### ISSUE TITLE
Selecting All Tracks in a Project Makes NVDA Speak Gibberish at the Begining

### ISSUE THREAD

**Issue by MatejGolian** [jcsteh/osara#361]
[NVDA.zip](https://github.com/jcsteh/osara/files/5506246/NVDA.zip)
Hello,
It's just as the title says. I have included a zipped MP3 in case you want to check it out. I have NVDA set to Slovak, but that does not really matter - I think you will be able to discern what shouldn't be there as it's right at the beginning.
This problem is not noticeable with only a handful of tracks, but around 20+ tracks it's absolutely apparent.
It's not a dealbreaker, but it would be nice if it could be fixed.

**Comment by jcsteh** [comment]
Do you have "Report changes made via control surfaces" enabled in OSARA's configuration dialog? Disabling this should work around this problem in the interim.

**Comment by jcsteh** [comment]
Fixing #236 should address this.

**Comment by MatejGolian** [comment]
Yes, I had it enabled, but the current build fixed it.
Thank you.

2020-11-08 23:30 GMT+01:00, James Teh <notifications@github.com>:
