### ISSUE TITLE
Hope to add new features

### ISSUE THREAD

**Issue by c469591** [jcsteh/osara#363]
Hello,
Hope to add a function,
The key combination declares that those tracks are sent to the master,
It's important for mixing,
Thank you!

**Comment by ScottChesworth** [comment]
Important for mixing how exactly? Can you describe how you'd use this? What feedback would you want from the screen reader?

**Comment by leonardder** [comment]
@c469591 Could you please clarify your request?

**Comment by jcsteh** [comment]
Closing due to lack of info. Please reopen if you're still interested in this. Thanks.
