### ISSUE TITLE
Feature request: is it possible for OSARA to report the presence of track notes when moving to a track?

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#369]
Is it possible for OSARA to detect and report when the SWS track notes edit field has been populated as we move through tracks? I'm imagining just reporting the presence of notes, not reading the notes themselves to prevent extraneous speech. If we only reported when present, then this wouldn't require any additions to OSARA Config, no additional speech would be forced on people who don't use the feature.

**Comment by ranetto** [comment]
it would also be nice to be able to indicate if an "item" contains audio or midi or nothing

**Comment by ScottChesworth** [comment]
Probably best to open that as a separate issue

**Comment by jcsteh** [comment]
Not really feasible at this stage. We could do it easily if SWS added an API function to check if a track has notes.

**Comment by ScottChesworth** [comment]
Hey @nofishonfridays, is that something you could handle? No worries if not, I'll file it on the SWS GitHub.

**Comment by nofishonfriday** [comment]
There's an API function to get SWS track notes:
https://www.extremraym.com/cloud/reascript-doc/#NF_GetSWSTrackNotes

**Comment by jcsteh** [comment]
Sorry, @nofishonfriday. I did check the SWS code for this, but my checkout was way out of date. Rookie error. 🤦‍♂️

**Comment by tbdalgaard** [comment]
Could this be implemented for items as well, or should we create another issue for this?

**Comment by jcsteh** [comment]
Please file a separate issue for this. Among other things, this is a REAPER
feature, not SWS, which perhaps suggests it's more commonly used and thus
the verbosity impact might be more risky and require some discussion.

**Comment by ScottChesworth** [comment]
Feedback from the user who requested this @jcsteh:
"Scott and Team OSARA, I'd buy you all a case of beer, if finances ever allowed. For now, the thought has to be what counts.    Damn, you rock. this is exactly what I wanted. Works perfectly." 👯‍♂️ 
I improvised a little with the emoji, but I concur. This might be the feature that puts a dent in my current note-keeping system during mixes, which is convoluted at best, and oh so ready to be laid to rest.
