### ISSUE TITLE
If a track is not selected OSARA gives incorrect feedback when opening the action SWS: Show Tracklist with filter focused 

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#385]
Hello to all,
I use the SWS filter a lot:
SWS: Show Tracklist with filter focused;
Command ID: _SWSTL_OPENFILT;
If not selected, the track gives the right feedback:
Track List  Dialogo  Filter;
when a track is selected instead OSARA from this feedback:
Unselected tracks/items/envelope points.
Nothing serious, if the focus is still in the search for a track.
It's just more elegant that it gives you the feedback you expect.
Thank you and greetings!

**Comment by Lo-lo78** [comment]
Sorry, it was a problem with my custom action.
Take care and good work!

**Comment by ScottChesworth** [comment]
Thanks for revisiting to close this. You are a good GitHubber. :)
