### ISSUE TITLE
Fix accessibility of setting fade shapes in item properties

### ISSUE THREAD

**Issue by leonardder** [jcsteh/osara#388]
In the item properties, in the tab order after the fade in / fade out edit field, there is an unlabeled button. When pressed, it shows a meny with unlabelled items.
As far as I can tell, these are fade shapes.

1. These currently can't be easily activated using the keyboard, the space bar still toggles playing, for example.
2. I wonder how easy it would be to assign labels to both the button and its menu items.

Thoughts @jcsteh?

**Comment by leonardder** [comment]
I assigned needs REAPER fix, since idieally, I think cockos should fix the labels here.

**Comment by ScottChesworth** [comment]
FYI, those shapes are temporarily labeled by Sibiac, LBL and Snowman's JAWS scripts. I agree that ideally a fix would come from Cockos themselves. Have nudged several times already though and not seen any movement yet.

**Comment by jcsteh** [comment]
For reference, this was discussed in [this RWP thread](https://groups.io/g/rwp/topic/77029439).

@ScottChesworth wrote:

> Scott has already approached Cockos about this one. Sadly, no movement. For reasons that Scott doesn't really understand, it's apparently not as simple as just labeling some menu items in this case.

I replied:

> The reason it's difficult for Cockos to fix (or at least so they think) is that these menu items are probably owner drawn or bitmaps and Win32 doesn't provide an API which allows both text and graphics in menus. However, there's a way around this. They can use IAccPropServices::SetHmenuPropStr, passing the HMENU of the menu, the index of the menu item (1 upwards), PROPID_ACC_NAME and the name they want to use for the menu item. The name will then be exposed via MSAA to screen readers, etc. Developer docs:
> https://docs.microsoft.com/en-us/windows/win32/api/oleacc/nf-oleacc-iaccpropservices-sethmenupropstr

**Comment by leonardder** [comment]
> > However, there's a way around this. They can use IAccPropServices::SetHmenuPropStr, passing the HMENU of the menu, the index of the menu item (1 upwards), PROPID_ACC_NAME and the name they want to use for the menu item. The name will then be exposed via MSAA to screen readers, etc. Developer docs:
> > https://docs.microsoft.com/en-us/windows/win32/api/oleacc/nf-oleacc-iaccpropservices-sethmenupropstr

Is this something we could do as well?

**Comment by jcsteh** [comment]
Scott, I assume you did pass that technical info on to Cockos? If so (and if it doesn't get us anywhere any time soon), we might be able to hack around this in OSARA, but probably only on Windows:

1. We already watch for focus win events.
2. If we get a focus win event for a menu item (window class `#32768`, child id > CHILDID_SELF) and one of the curve buttons has focus (GetFocus will return the button even when the menu is open),
3. we can get its identity string using IAccIdentity and then annotate its accName property ourselves using IAccPropServices.

**Comment by jcsteh** [comment]
Note that we'd probably use [IAccPropServices::SetPropValue](https://docs.microsoft.com/en-us/windows/win32/api/oleacc/nf-oleacc-iaccpropservices-setpropvalue), not SetHmenuPropStr, since we can't get an HMENU directly, but we can get the raw identity string using [IAccIdentity::GetidentityString](https://docs.microsoft.com/en-us/windows/win32/api/oleacc/nf-oleacc-iaccidentity-getidentitystring).

**Comment by ScottChesworth** [comment]
> Scott, I assume you did pass that technical info on to Cockos?
> 
Correcto. Didn't get a response though. I'll resend and try pushing a little harder for some acknowledgement this time.

**Comment by ScottChesworth** [comment]
Got a response, and it seems like we might be getting some movement on this soon. All hail polite persistence. 👍

**Comment by Lo-lo78** [comment]
Hi! It worked for me, for a while it read me the fade-in and fade-out 
curves, told me: linear, fast and so on ... Now it just tells me it's a 
button. Two days ago, the button described the shape, with shift + space 
in the list it gave me all the fades. All this with the OSARA version: 
2020.1pre-340,7d6129f6.
Does it happen to you too?
Regards!

**Comment by ScottChesworth** [comment]
Unless I've missed something being implemented, OSARA doesn't do anything to accessify those fade shapes. There are two NVDA addons that do though, Sibiac and LBL. Your variable is most likely one of those not running now whereas it was when the shapes were reported.

Closing this to keep the place tidy, but feel free to reopen if the above is incorrect.

**Comment by Lo-lo78** [comment]
Hey, Scott you're absolutely right!

**Comment by jcsteh** [comment]
Reopening because it'd be good to track this in case Cockos don't give us a solution on their end.

**Comment by leonardder** [comment]
And, if they don't, I still would like to have a try to implement this in OSARA, also to support other screen readers.

**Comment by leonardder** [comment]
Wow, awesome. They did it in 6.19!
