### ISSUE TITLE
Event feedback for cutting, copying and pasting on the piano roll

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#398]
Hi,
it would be very interesting and fruitful to work on the piano roll.
If there was feedback when you cut, copy and paste a note or midi event, such as a control change, working on a midi item would be much smoother and faster.
Greetings and thanks!
You are great!

**Comment by leonardder** [comment]
What kind of feedback would you expect? Could you describe a scenario where this will benefit you?

**Comment by ranetto** [comment]
I also answer:
it would be nice to have a chance to know if the note has been copied to the clipboard, to have a chance to know that it has been pasted.

**Comment by Lo-lo78** [comment]
Hi Leonard, congratulations on the work on NVDA, you are strong! On what 
you ask me, I would expect that if I do ctrl + x, ctrl + c and ctrl + v, 
OSARA would give simple feedback. I do ctrl + c and OSARA says, Note 
copied to clipboard, or if there are multiple notes, two or three notes 
copied to clipboard.If not known, event copied to clipboard, if it is a 
CC, CC copied to clipboard.Same with cut.When you paste, it simply says 
what you have pasted, a note, multiple notes, or CC pasted. I don't 
know, does it convince you? Great Leonard, and James, you have created a 
great screen reader along with other strong ones! Now I can't give up 
NVDA! Thanks for everything!

**Comment by leonardder** [comment]
Thanks for your kind words.

Feedback for the cut/copy actions should be possible I think. As for pasting, I'm not so sure, as we don't know what's on the clipboard at the moment of pasting, it could as well be text, a file, or whatever garbage.
@jcsteh What are your thoughts on this?

**Comment by jcsteh** [comment]
The way that pasting works outside of the MIDI editor is that we count various things (tracks, items, etc.) before and after the paste. If one (or more) of those counts goes up after the paste, we say, for example, "1 track added". I think we could do something similar for the MIDI editor; i.e. count notes, CCs, etc. before and after the paste and say, for example, "5 notes added". Is there anything else that can be pasted into the MIDI editor? I don't think so, but I might be missing something.

**Comment by Lo-lo78** [comment]
Hi James, in addition to the notes we can include the CC, Program change 
or even you could think of having 5 notes glued and otherwise call them 
events.I think it is better to distinguish the midi events in CC, PG, 
but it's ugly, or in full, control change and program change. However in 
piano roll feedback is important because it happens that two midi items 
are overlapped and when you copy the note you are not actually copying 
it and you do not immediately understand that it is not Reaper that does 
not work but they are two items midi on top of each other.So the 
feedback helps to understand if you are actually doing that action or 
not doing it and you are not in the dark!

Thanks for all you are doing!

Il 04/12/2020 23:32, James Teh ha scritto:

**Comment by Lo-lo78** [comment]
@leonardder How do you see this problem?
I think it is very useful to know with ctrl + x, ctrl + c and ctrl + v what we are doing.
It may happen that a note or a midi event is not copied because we are off the edge of the midi item or for other reasons.
Feedback could speed up the work on the midi editor a lot.
Greetings!

**Comment by Lo-lo78** [comment]
I generated 3 lua scripts with AI that cut, copy and paste the midi notes with OSARA which counts the notes in the clipboard.
Unfortunately I wasn't able to get OSARA to say all the events like the cc.
However they are pasted even if they are not counted by the scripts.
For example if there are 5 events:
3 midi notes and 2 cc; 5 events will be pasted but the message says 3 midi notes added.
[Midi editor - Piano roll - Cut copy and paste speak.zip](https://github.com/jcsteh/osara/files/15024243/Midi.editor.-.Piano.roll.-.Cut.copy.and.paste.speak.zip)

**Comment by Lo-lo78** [comment]
@LeonarddeR 
I managed to generate the copy and cut with the OSARA messages.
In these two actions, both the selected notes and the cc are signaled.
I could arrange them so that it adds up both notes and ccs for OSARA messages.
In this way we have the sum of all midi events.
It's easy!
[Copy & cut.zip](https://github.com/jcsteh/osara/files/15049011/Copy.cut.zip)

**Comment by Lo-lo78** [comment]
@LeonarddeR 
I have no idea how to do this for paste.
The messages there are contradictory.
When you select events the script sees all the selected events. also of the cc of the active lanes. So for cut and copy there is no problem.
When you paste and no longer see the cut or copied events in the piano roll, the script does not know how many cc were actually pasted.
Maybe it's likely that I didn't understand something important.
I'm sure it can be done.

**Comment by Lo-lo78** [comment]
Unfortunately when I paste at the end of the article a new one is created.
If they are close to the edge and the events exceed the length of the item it lengthens it.
The Paste speak.lua It's not perfect yet.

**Comment by Lo-lo78** [comment]
Okay. All resolved. I had to use the command id:
40011:
"Edit: Paste"
but I hadn't specified the midi editor section.
In main 40011 it is:
"Item properties: Show media item source properties"
By mistake I used the command id 40058:
Item: Paste items/tracks (old-style handling of hidden tracks)
This command id is from the main section which didn't work well for piano roll. Obviously!
here is the code to paste:
-- Inizialize variables to count the number of MIDI notes and CCs
local noteCountBefore = 0
local ccCountBefore = 0

-- Get the active MIDI editor
local editor = reaper.MIDIEditor_GetActive()

if editor then
  -- Get the active item
  local item = reaper.MIDIEditor_GetTake(editor)

  -- Check if the take is valid and contains MIDI events
  if reaper.TakeIsMIDI(item) then
    -- Get the total number of MIDI notes and CCs in the take before pasting
    local _, notesBefore, ccsBefore, _ = reaper.MIDI_CountEvts(item)
    noteCountBefore = notesBefore
    ccCountBefore = ccsBefore

    -- Execute command ID 40011 (paste from clipboard) in the MIDI editor section
    reaper.MIDIEditor_OnCommand(editor, 40011)

    -- Get the total number of MIDI notes and CCs in the take after pasting
    local _, notesAfter, ccsAfter, _ = reaper.MIDI_CountEvts(item)

    -- Calculate the number of added MIDI notes and CCs
    local noteCountAdded = notesAfter - notesBefore
    local ccCountAdded = ccsAfter - ccCountBefore

    -- Construct the message based on the obtained data
    local message = ""
    if noteCountAdded > 0 then
      message = noteCountAdded .. (noteCountAdded == 1 and " note added" or " notes added")
    end
    if ccCountAdded > 0 then
      message = message .. (message ~= "" and ", " or "") .. ccCountAdded .. (ccCountAdded == 1 and " CC added" or " CCs added")
    end

    -- Print the appropriate message
    if message == "" then
      reaper.osara_outputMessage("No  event added")
    else
      reaper.osara_outputMessage(message)
    end
  else
    reaper.osara_outputMessage("No MIDI data in the active take")
  end
else
  reaper.osara_outputMessage("No MIDI editor open")
end

**Comment by Lo-lo78** [comment]
Nobody was interested and I closed the issue.
