### ISSUE TITLE
Sounding notes in midi editor:

### ISSUE THREAD

**Issue by ranetto** [jcsteh/osara#399]
Hi everyone, I wanted to present this problem:
it often happens that in shortening a note or lengthening it with the zoom or by grid values ​​in the midi editor or when I change its velocity, especially if it is about strings or carpets so sounds that are not percussive but long or even horns it is very annoying to listen the notes repeated by the actions of lengthening or shortening the note that cause the sound to become a single long and interminable sound caused precisely by the myriad of repetitions that dare to make them play.
Would it be possible to add an option to prevent notes from sounding when lengthening or shortening them or when adjusting the velocity?
In addition to this, I lack the feedback to know when I move a note with the 4 and 6 of the numeric keypad to know at which position this same note went.
Can anything be done?
I take advantage of this new request to also report that for some months it has happened to me that by changing the length of a note or its position, when I return reaper in plai for the first time after the modification, the note is cut to a minimum value compared to what you should have after the change.
By repeating stopp and then play, everything returns as it should be.
It also happens to others and can you tell me why?
Thanks in advance.

**Comment by leonardder** [comment]
As for the functioning of 4 and 6 on the numeric keypad, they should have feedback in the most recent osara.

I think we could add an option to osara's option to at least silence the note previews generated by us, but that doesn't solve the issue for previews generated by REAPER itself, such as when changing pitch.
Have you also tried to silence the notes with f3? Does that really silence them?

**Comment by ranetto** [comment]
Hi, I would say that it would be enough to mute the notes generated by us optionally, for the 2 or the 8 it is clearly not so much a problem because they usually have fewer steps to take, however yes I only meant the notes generated by us.
As for the fact of the play mentioned above after editing do you know anything about it?
I thank you in advance:
    Stephen

**Comment by ScottChesworth** [comment]
Which VSTI are you using when playback stops prematurely?

**Comment by ranetto** [comment]
Hi Scott, I would say any, clearly I notice it more on arches and carpets, but also on the piano it is the same thing:
I would say it has been happening to me for six months now, but it's a very annoying thing because I always have to play, then stop and play again, I don't think it's a reaper problem as I've never seen anything like this reported:
Do you have any suggestions or has this ever happened to you?

**Comment by ScottChesworth** [comment]
Yep, it happens here too. More often with some synths than others though, hence I assumed it wasn't an OSARA problem. I'll try to find time to test a troublesome synth without OSARA in the mix. That should at least narrow down who's table we'll need to pop the issue on.

**Comment by jcsteh** [comment]
My guess is that the note preview causes problems here. Are you perhaps pressing play before the note preview finishes? I guess the timer which stops the note preview would then kick in, which would cut off the note prematurely. OSARA probably needs to kill the preview timer when playback starts.

**Comment by ranetto** [comment]
Hi Giames, no no I play the play, but also from a previous half bar and when I get to the place where I modified he completely cuts the note I modified and gives it a minimum value, like an octave, whatever its value was . Then I quickly hit stopp, and by pressing play again everything returns to normal.
If I change a second one, it still does.
What do you think James?

**Comment by ScottChesworth** [comment]
> I guess the timer which stops the note preview would then kick in, which would cut off the note prematurely. OSARA probably needs to kill the preview timer when playback starts.
> 
Well today's your lucky day punk, just done tests and confirmed that guess. Waiting until the preview finishes, it stops happening with all of the instruments I tried (Zampler, Kontakt, XPand, Punch, Dexed).
I've not been smart enough to figure out how to try killing the preview timer on play here, but I reckon that'll solve it.

**Comment by jcsteh** [comment]
> Well today's your lucky day punk, just done tests and confirmed that guess. Waiting until the preview finishes, it stops happening with all of the instruments I tried (Zampler, Kontakt, XPand, Punch, Dexed).

Okay. Thanks. Fixed in latest snapshot.

**Comment by ScottChesworth** [comment]
Works a treat for me, thanks. @ranetto, how's this working for you?

**Comment by ranetto** [comment]
It works great, well done it's a really nice problem eliminated:
already tried everything ok, congratulations!

**Comment by jcsteh** [comment]
@ranetto, you mentioned other issues here as well (e.g. disabling previews). Please file separate issues for each of those other requests. Thanks.

**Comment by ranetto** [comment]
Excuse me James, forgive my eagerness to communicate with you, I will open other requests for the rest of the problems:
my inexperience with gtab makes me make these mistakes along with my passion for these topics.
