### ISSUE TITLE
UX consistency: requesting action feedback for moving to the start of current measure, start of next measure and beginning/end of loop

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#404]
Low priority, but can feedback be implemented for the following actions in the name of consistency please?

Action: Go to start of loop
ID: 40632
Action: Go to end of loop
ID: 40633
Action: Move edit cursor to start of current measure
ID: 41041
Action: Move edit cursor to start of next measure
ID: 41040

Reporting these would go hand in hand with the feedback OSARA already provides for actions like "Go to start of time selection" and "Move edit cursor back one measure".

Ideally, the new reports would be included in the list of time movement actions that can be optionally silenced by checking "Report time movement during playback/recording" in OSARA Config.

Many thanksticles.

**Comment by ptorpey** [comment]
You guys are quick!  This works great now with JAWS.  Position is spoken when hitting Home/End to move to the beginning/end of the time markers.

Thanks.
