### ISSUE TITLE
Is it possible to give feedback when markers, stretch markers and more are erased?

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#406]
Hello to all,
these days I'm trying to create feedback with custom actions, I'm very happy!
Is it possible to make OSARA tell when you remove all markers and so on?
I am attaching some custom actions, maybe they can give you an idea.
1.
Custom: Manolo: Crea un marker dal cursore di modifica
  Markers: Insert marker at current position
  OSARA: Report edit/play cursor position
2.
Custom: Manolo: Crea un time selection dall'item selezionato
  Time selection: Set time selection to items
  Go to start of time selection
  OSARA: Report edit/play cursor position
3.
Custom: Manolo: Crea uno stretch marker dal cursore di modifica
  Item: Add stretch marker at cursor
  OSARA: Report edit/play cursor position
4.
Custom: Manolo: converte le note midi in inviluppi di tempo
  SWS/BR: Create project markers from notes in selected MIDI items
  SWS/BR: Convert project markers to tempo markers...
5.
Custom: Manolo: crea una traccia e la mette in coda con un feedback di OSARA
  Track: Insert new track at end of track list
  Track: Go to next track
6.
Custom: Manolo: ricarica il primo loop e va all'inizio
  SWS: Restore loop selection, slot 1
  Go to start of time selection
  Transport: Play
For this last custom action I used some SWS actions to save the time selection and load it when needed:
SWS: Restore loop selection, slot 1
SWS: Restore loop selection, slot 2
SWS: Restore loop selection, slot 3
SWS: Restore loop selection, slot 4
SWS: Restore loop selection, slot 5
SWS: Save loop selection, slot 1
SWS: Save loop selection, slot 2
SWS: Save loop selection, slot 3
SWS: Save loop selection, slot 4
SWS: Save loop selection, slot 5
Greetings and thanks for everything James
[Manolo, Custom actions.zip](https://github.com/jcsteh/osara/files/5636511/Manolo.Custom.actions.zip)
 does and all of us who follow!

**Comment by jcsteh** [comment]
It's not clear to me how these custom actions relate to your request. Can you please provide specific details of the REAPER actions that don't provide feedback and what exact feedback you'd like them to provide? Thanks.
