### ISSUE TITLE
add right click to the envelopes and envelope points to the applications key to open their context menu

### ISSUE THREAD

**Issue by GianlucaApollaro** [jcsteh/osara#41]
Hi, it's all in the title. Can you make those context menus be clicked depending on focus? I discovered some interesting context menus concerning the envelopes and the envelope points that could help us a lot to choose which envelope I want to activate. When I select an envelope using the actions select next and select previous envelope, I have to use jaws cursor to right click them, I couldn't get NVDA's object nav to bring me where I needed to click. When I select a single envelope point instead using the sws action called move edit cursor to next (or previous) envelope point and select it, I can't get anything to click its context menu, that is different than the one that appears on the general envelope selection. So, to specify a bit more, The general context menu gives us the ability to choose other envelopes to be activated, like pan, volume, and others. The specific context for the points gives us the ability to change values of that selected point, very useful for the volume for example,.

**Comment by jcsteh** [comment]
I looked into this a while ago.

I *might* be able to make the general Envelope context menu accessible 
with the applications key. However, I'm pretty sure this is the same 
menu you get if you move ot a track, press control+applications and 
select the Envelopes sub-menu. If I'm correct, IMO, this is low 
priority, since there's a fairly simple workaround.

The really interesting one, as you say, is the envelope point context 
menu. Unfortunately, I don't know of any way to make this accessible. As 
far as I've discovered, neither the REAPER API nor MSAA expose anything 
that would enable me to get this context menu directly or the screen 
location of the point so I can click it. REAPER 5 does allow you to get 
and set data about envelope points, but not to access the context menu. 
With REAPER 5, I might at least be able to add some custom way to move 
through envelope points and edit the raw data, but I'd really prefer to 
be able to use REAPER's own context menu.

**Comment by jcsteh** [comment]
Actually, looking again, the envelope context menu isn't quite the same as the Envelopes sub-menu in the track context menu. However, unless I'm missing something, you can still do everything and more using the envelope and automation sub-menus in the track context menu.

**Comment by GianlucaApollaro** [comment]
You're right, the two menus are similar in terms of what you can do. 
There is another interesting action I discovered called view envelopes 
for current track. If you have effects on a track, you can use the 
envelope points to adjust the fx parameter and automate them, like make 
a reverb come and go away, or use an eq and mute it when you don't want 
it. Now it seems that list is available only when using the jaws cursor, 
nvda doesn't seem to like it much. It would be cool to access it better

Il 01/09/2015 15:10, James Teh ha scritto:

**Comment by jcsteh** [comment]
You can access it with NVDA screen review, which is basically equivalent 
to JAWS cursor. From what I've been able to determine, I don't think I 
can do much about that list either, but I'll look into it. Note that you 
still can't access the envelope point context menu, so I'm not sure how 
useful this is.

Note that there are other ways to access this too. You can arm 
individual FX parameters by pressing the Param button in the REAPER FX 
dialog and selecting Show track envelope. Also, if you're writing 
automation and you have things configured correctly, FX parameter 
envelopes will become visible and armed as soon as you touch the parameter.

**Comment by GianlucaApollaro** [comment]
I have a little question concerning what you said in a previous comment.
You said: With REAPER 5, I might at least be able to add some custom way 
to move
through envelope points and edit the raw data. If I understand correctly 
in reaper 4 is not possible to edit the value of an envelope point.
So here's my question: how could the sws people have created actions 
like increase or decrease envelope value x ammount of db? These actions 
are available using reaper 4 aswell. Is volune the only envelope to 
expose some values?
Sorry if I understood your comment wrong
Il 01/09/2015 22:54, James Teh ha scritto:

**Comment by jcsteh** [comment]
Even in REAPER 4, it is possible to get the entire raw (XML) data for an envelope. I haven't read this specific part of the SWS code, but based on other parts I've read, I think this is how they're doing it. This requires sifting through and manipulating the data for the entire envelope and then writing it back. While possible, it's pretty tricky, ugly, potentially slow  and error prone. REAPER 5 adds API functions to work with envelope points which is far cleaner.

**Comment by jcsteh** [comment]
Cool! From the change log for REAPER 5.02pre4:

> Envelopes: added action to manually edit envelope point at cursor

This pops up a little dialog which allows you to manually edit the value, shape, etc. We should be able to use the API to move the cursor among envelope points. Hopefully, the practical upshot is that we'll be able to manually edit envelopes without massive ugliness.

**Comment by GianlucaApollaro** [comment]
This is cool! I can already move and select  envelope points using sws. 
The actions are: move edit cursor to previous (or next) envelope point 
and select it.

Il 12/09/2015 05:38, James Teh ha scritto:

**Comment by chrisbelle2015** [comment]
Hey question, when you use the control l to select envelopes, when you 
have more than one kind of envelopes, it toggles between say a volume 
and a high pass eq envelope.

Is it rreally doing that, is that how you decide which envelopes you 
want to edit?

It doesn't say it's a toggle, but according to the speech feedback it's 
indicating that's what's happening.

I can experiment, but thought I'd ask anyway.

**Comment by GianlucaApollaro** [comment]
Yes it does, it selects the next envelopes and after having chosen the 
envelope you can insert points and move them.

Il 12/09/2015 13:48, chrisbelle2015 ha scritto:

**Comment by chrisbelle2015** [comment]
Wow, I'm beginning to see how this works.

I've assign a key to write automation all the way to the end,
and this doesn't seem to interfere with when I've done it befofre, so 
you can keep doing that and keep your current values.

That means things will stay put, and you can update it as you go.

YOu can also change stuff before that if you are careful where your 
transport is when you write.

I am still not used to automation snapping back like a rubber band, but 
I think I can learn to work with it.
And once in a while it might work to your advantage.

I thought I might like that setting in preferences which let's you set a 
value for how fast automation snaps back, and set it to a really high value,
but that's doing some strange things now I'm not sure of,
so I might have to investigate that further to wsee if that's the 
behavior I really want.
I really would like to find the defeat button on that,

**Comment by chrisbelle2015** [comment]
One thing which I do like how it acts is that when you write values 
outto the end, it seems to bring in an automatic offset mode,
so you can change volumes relative to that.

I wish we could have feedback though of the actual values of envelopes 
when we are changing their values,
like how far down we are, but I guess that would be hard to do because 
it's probably a graphical thing.

**Comment by chrisbelle2015** [comment]
I've done some experimenting,and am making good progress with reaper 
automation.

After all these years, finally,
I'm not totally comfortable with it or comfident, but I'm not falling on 
my but everytime I take a step either.

This is gonna be good.

**Comment by GianlucaApollaro** [comment]
Hi, I think this issue ccan be closed since in reaper 5 they added the action to edit the envelope point value.

**Comment by jcsteh** [comment]
Leaving open because it'd be nice to support this if we ever can, but 
it's not high priority now certainly.

**Comment by jcsteh** [comment]
I'm going to close this after all. We'll probably never be able to access the envelope point context menu and we now have the manual edit action anyway. As for the envelope context menu, as noted above, this can all be accessed elsewhere and it's not tedious to do this. We can always reopen this if it becomes necessary for some reason.
