### ISSUE TITLE
Braille messages.

### ISSUE THREAD

**Issue by GabrieleBattaglia** [jcsteh/osara#415]
Since some releases, each actions I take with OSARA, the Braille output appears as a flash message on the display. It stays there for some seconds then desappears. Before instead, messages were steady and it was better to me. Any volountary changements to this?

**Comment by leonardder** [comment]
This has to do with OSARA switching to UIA for message output.

Assuming you're using NVDA, would it be ok for you to enable the option "show braille messages indefinitely" in NVDA"s braille settings?

**Comment by leonardder** [comment]
@GabrieleBattaglia Assuming my comment above will work for you, I'm closing this issue. Feel free to get in touch if it isn't sufficient.
