### ISSUE TITLE
UX: Reaper's overzealous firing of control surface notifications can cause intermittent incorrect reporting in TCP when "Report changes made via control surfaces" is enabled in OSARA Config

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#416]
Reproduction steps and audio came in from Alexis on RWP:

1. Ensure that "Report changes made via control surfaces" is enabled in OSARA Config, and create two tracks in an otherwise empty project.
2. Place an effect on the first track, ReaEQ for example.
3. Move a slider (gain band 1 for example) in the FX window, then back in the TCP, hit Control+Alt+L to arm the last touched parameter envelope.
4. On track 1, press Shift+Enter to create a folder.
5. Now, move between the two tracks. OSARA will intermittently report the name of the effect placed on track 1 instead of reporting the name of track 2 as expected.

Audio demo: https://www.dropbox.com/s/lbjrht9s9xe0sih/Alexis%20demoing%20OSARA%20surface%20feedback%20breaking%20reports%20in%20TCP.mp3?dl=1

@jcsteh confirmed that he's able to reproduce on 8th Dec 2020.

**Comment by jcsteh** [comment]
Wow. So the reason this happens is that once you have an FX param envelope, REAPER continually fires surface notifications for that parameter, more than 5 each second. And they never stop. This is really, really horrible. I guess I could cache every FX parameter we ever get notified about, but... ug.

**Comment by jcsteh** [comment]
I emailed Cockos requesting a fix. We'll se what happens.

**Comment by jcsteh** [comment]
Fixed in REAPER 6.19rc3, so this will be in the final 6.19 release when it comes out.

**Comment by ScottChesworth** [comment]
Splen-diddly-doodles!
