### ISSUE TITLE
Control + tab and control + shift + tab do not work in the render window

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#418]
Hello to all,
congratulations for the latest snapshots!
Speaking of control + tab and control + shift + tab, there are two tabs in the render window:
Primary output format tab,
Secondary output format tab;
Unfortunately, to go to the second tab you have to look for the tab:
Primary output format tab, then right arrow and the system cursor will be placed in the second tab:
Secondary output format tab.
Is it possible that when we open the render window we can control + tab, control+shift+tab to switch to the second tab?
Thank you so much for everything you do!

Auauauaua!
Sorry for the shitty English!

**Comment by leonardder** [comment]
Assigning this p3, since while it would be a nice to have, it's not that the secondary output feature is not accessible currently.

**Comment by Lo-lo78** [comment]
@LeonarddeR 
Absolutely true! There are much more important issues for OSARA.
