### ISSUE TITLE
With multi timbral VST midi in the event list the note feedback does not correspond with the midi channel

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#420]
Hello,
i'm trying a multi channel midi vst, when i go to a track of the 16 channel midi folder, in the internal tracks, in the event list, the feedback does not match with the midi channel.
I give an example:
at the top we have the folder with the vst midi, inside we have all the midi tracks, I choose the drum track and go to the piano roll, here everything is fine, I do alt + 3, I enter the event list, and when I meet a note, I don't plays the drums but a different channel, in this case the midi channel 1.
This is important because when you make midi files you use a 16 channel multi timbral vst to export it.
Do you have a solution?
I am attaching a fantastic free accessible sound font reader!
I also wear a sf2 to rehearse quickly.
If you want, here is the direct link:
http: \\ www.falcosoft.hu/bassmidi_vsti.zip
This is the github:
https://github.com/kode54/BASSMIDI-Driver
It is a very effective project born on Linux, I prefer it to Sforzando; check it out, it's one of the few accessible VSTs.
Thank you all!
[BassMidiVSTi.zip](https://github.com/jcsteh/osara/files/5688993/BassMidiVSTi.zip)

**Comment by leonardder** [comment]
Sounds like something is wrong in the code I introduced. I'll have a look.
N.b. I assume the event list shows the correct channel?

**Comment by Lo-lo78** [comment]
Hi Leonard, yes, the information is right in the list. In the example I 
was talking about drum channel 10, it is written but another midi 
channel plays. Greetings!

Il 14/12/2020 14:50, Leonard de Ruijter ha scritto:

**Comment by leonardder** [comment]
@Lo-lo78  how about [this](https://ci.appveyor.com/api/buildjobs/kekmwf51u4gqlj8m/artifacts/installer/osara_pr421-392,38cdec8c.exe) build? Does it fix it for you?

**Comment by Lo-lo78** [comment]
Yes! It's really ok, you solved the problem! Bravo! 👍

Il 14/12/2020 19:23, Leonard de Ruijter ha scritto:
