### ISSUE TITLE
Shift+R does not give speech feedback when new Region is created

### ISSUE THREAD

**Issue by ptorpey** [jcsteh/osara#422]
1.  Create a time selection using the left and right brackets
2.  Hit Shift+R to create a region from the selection
3.  There is no speech feedback to verify that the region has been created.

**Comment by ptorpey** [comment]
As an additional comment, it is understandable why hitting "M" to create a marker does not speak since this function can be used while playing or recording and users may want to keep it silent for such purposes.  But I don't think that creating a Region can be done or is likely to be done while playing/recording since creating a Region requires a region to be defined by it's start and end points.  It is always nice to have feedback when an action is successful if possible.

**Comment by jcsteh** [comment]
I agree and it's definitely possible (and not too hard). Someone (me or someone else) just needs to find the time to do it.

**Comment by ptorpey** [comment]
As a follow on comment to this, although it is understandable that creating a marker with "M" does not give audible feedback since a user can perform this action during playback/recording, this is probably not the case for creating a Region.  Regions must be defined by a start and end selection and aren't likely to be created during playback/recording.  As sighted users have feedback when an action was successful, it is always nice for the user of a screen reader to have feedback as to whetehr an action was successful or not if possible.

**Comment by jcsteh** [comment]
> it is understandable why hitting "M" to create a marker does not speak since this function can be used while playing or recording and users may want to keep it silent

Although it's not a perfect fit, I think it's reasonable to tie this to OSARA's Report time movement during playback/recording option, unless @ScottChesworth disagrees.

**Comment by ptorpey** [comment]
Maybe some day I’ll figure out how to help out on that end.  Right now I’m just learning to use Reaper and doing some scripting with their API.  Nice system!  You folks have done a great job making this accessible and easy to use.  Keep up the good work.

 

Thanks.

 

--Pete

**Comment by ScottChesworth** [comment]
> I think it's reasonable to tie this to OSARA's Report time movement during playback/recording option, unless @ScottChesworth disagrees.
> 
Scott Chesworth has two thumbs up (tbh it's making hitting the space bar kinda difficult, no wonder cats can't type).

**Comment by ptorpey** [comment]
This now reports the region that is created.  Thanks.

 

Question: I understand why there are separate hotkeys “M” for silently creating a marker and shift+M for creating (if necessary) and labeling a marker.  I wonder if it makes sense to have shift+R create a region (if necessary) and label the region as with the shift+M hotkey for markers.  This could free up a hotkey for other functions.  Don’t know how cramped things are for assigning new hotkeys.

 

--pete

**Comment by ScottChesworth** [comment]
Very cramped, but switching "Markers: Insert region from time selection" out for "Description: Markers: Insert region from time selection and edit" is likely a good call. I'll float it in the keymap group now.

**Comment by jcsteh** [comment]
Haha. That somewhat defeats the point of having feedback for the existing shift+r action, as the new action is self-confirming because of the dialog. Ah well.

**Comment by ScottChesworth** [comment]
All good, Hargen won't update his keymap until 2030 at the earliest.

**Comment by ptorpey** [comment]
Yes, sorry about that.  I hadn’t thought of this when I first asked if we could get feedback for creating the region.  After using these hotkeys in several projects though, it occurred to me that they were somewhat redundant and the functions might be combined.  Plus, as I said, it seems there is always another hotkey that would like to be assigned if there was space on the keyboard.

 

I guess if the keymap team agreed you could just move the edit function to be included in the create function that now speaks!

 

--Pete
