### ISSUE TITLE
OSARA key map fails to install on someone's Mac

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#427]
We have a new Mac user on RWP (Cankut değerli) who's getting the below error when installing OSARA.

Last login: Fri Dec 18 11:21:09 on console
/Volumes/OSARA\ 2020.1pre-394\,2ee2048f/Install\ OSARA.command ; exit;
cankutdegerli@Cankut-MacBook-Air ~ % /Volumes/OSARA\ 2020.1pre-394\,2ee2048f/Install\ OSARA.command ; exit;
execution error: Error: Error: sh: /Users/cankutdegerli/Library/Application Support/REAPER/UserPlugins/reaper_osara.dylib: No such file or directory (1)
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.

Any idea what's up? I don't know my way around Macland well enough to troubleshoot this. Hoping that @RDMurray or perhaps @GarthHum might have some input.

**Comment by RDMurray** [comment]
Looks like a bug in the install script I wrote.  I'll look into it ASAP.

**Comment by ScottChesworth** [comment]
Thanks man. Keep us posted.

**Comment by RDMurray** [comment]
I can reproduce this error by trying to install Osara when Reaper hasn't been opened yet.  The fix is easy, pr coming soon.

As a work around for now, just open Reaper once and quit it before installing Osara.

**Comment by ScottChesworth** [comment]
Lovely stuff. Thanks for bumping the thread on RWP too.
