### ISSUE TITLE
The keys Tab and Shift+Tab no more focuses in most controls in Open/Save as dialogues on non-latin operating systems

### ISSUE THREAD

**Issue by outsidepro-arts** [jcsteh/osara#431]
At the first time when i'd save the project, i thought Reaper something has broken. But then I've just saw this commit:
Revision: d86815807afe01c4050a17630f706ae35c2d70bd
Author: James Teh <jamie@jantrid.net>
Date: 03.12.2020 3:50:22
Message:
Overide the tab/shift+tab key in Save dialogs so it can reach REAPER specific controls: Create subdirectory for project, etc.

----
Modified: src/reaper_osara.cpp

Now this keys focuses in the listview with file explorer, name and extension and no more. If a Open/Save as dialog has some extended controls, the focus can ge them. No buttons like as "Open", "Save", "Cancel" and search box gets the focus.

**Comment by jcsteh** [comment]
What exact version of Windows is this?

**Comment by outsidepro-arts** [comment]
Windows 10 Pro, Version 2004 (OS Build 19041.388)

**Comment by jcsteh** [comment]
I think we're going to need to revert the change to make tab/shift+tab hit the REAPER custom controls in the save dialog. Besides your report, I've heard some talk on RWP about this breaking things in some cases. I have no idea why this doesn't work on some systems. I guess the dialog must be different somehow, but without being able to reproduce it, there's nothing I can do to diagnose it.

CC @ScottChesworth for awareness.

**Comment by outsidepro-arts** [comment]
May I provide some info for trying to fix it without fix revert?

**Comment by outsidepro-arts** [comment]
I have just checked the source code in this section and don't understand too why this doesn't works...
Just checked again: now it works in Save project As dialogue , but still doesn't works in save as dialogue which doesn't contains the custom toolbar, for example, in the save as dialogue from "Browse for file..." in render settings window.

**Comment by outsidepro-arts** [comment]
Seems it skipps the OS toolbars and Save/Cance buttons when the custom REAPER toolbar is not presented

**Comment by jcsteh** [comment]
The Render Browse dialog works for me, so I still have no idea why it would
skip stuff on your system. Those OS dialogs are pretty broken in other ways
(object navigation is asymmetric, etc.), so I'm not even sure what
information to ask for to help diagnose this. I think it's going to end up
being a revert unfortunately.

**Comment by outsidepro-arts** [comment]
Today i got the Windows update. The build now is 19041.685. I'd checked this case right now and no found this: all controls gets the focus correctly. I still doupt that we need to revert the changes and close this issue... Let wait the report about this situation from other users.

**Comment by ScottChesworth** [comment]
@Justinmac84, can you update to this build of Windows on your machine and re-test to see if you're still afflicted?

**Comment by jcsteh** [comment]
I haven't heard any further reports of this, so closing. Please reopen if the problem persists.
