### ISSUE TITLE
Unable to properly navigate between CCs at the same position

### ISSUE THREAD

**Issue by Batworx** [jcsteh/osara#434]
When using the "OSARA: Move to previous CC" and "OSARA: Move to next CC" actions, if multiple CC messages are on the same MIDI tick, the actions don't seem to know which one of them to move to. Could this problem be solved by treating all CC messages at the same position as a chord or group, and having additional actions to move between individual messages in the group in ascending or descending order, much like Osara is already doing with notes?

**Comment by leonardder** [comment]
I looked briefly into this. It looks like CC events are ordered arbitrarily, and the order can even change between invocations of the next/previous cc actions or the event list. I added [an example project](https://github.com/jcsteh/osara/files/5743125/ccIndex.zip)

@jcsteh Do you have any thoughts about this? Should we do our own ordering? I understand that cc indices can change when new events are inserted between orders, but I'd assume that they ought to be stable when you don't change anything. If not, that's something Cockos (not we) should fix.

**Comment by leonardder** [comment]
@jcsteh Just a friendly reminder that there's a question open for you in https://github.com/jcsteh/osara/issues/434#issuecomment-751356276 if you don't mind.

**Comment by jcsteh** [comment]
Does MIDI_Sort do anything useful to help here?

When you say they're ordered arbitrarily, do you mean just CCs at the same tick or all CCs? That is, are they at least ordered by position?

I agree it's pretty weird they shift even when you don't insert or delete. That said, sorting probably isn't that difficult if they're at least sorted by position. We already do that for notes. We could just sort by CC number, which is kinda arbitrary but should serve well enough.

I can't quite remember how the sorting for chords works. I guess we'll have to track the sorted number of the CC at the current position or something.

**Comment by leonardder** [comment]
> Does MIDI_Sort do anything useful to help here?

I'm afraid not. I added it to MoveToCC, just above `auto cc = findCC(take, direction);`, but that doesn't make any difference.

> When you say they're ordered arbitrarily, do you mean just CCs at the same tick or all CCs? 

All cc's at the same tick are ordered arbitrarily. The order can change by 
That is, are they at least ordered by position?

> I agree it's pretty weird they shift even when you don't insert or delete. That said, sorting probably isn't that difficult if they're at least sorted by position. We already do that for notes. We could just sort by CC number, which is kinda arbitrary but should serve well enough.

That makes sense, I will see how to do this.

**Comment by leonardder** [comment]
I had a look at this. The logic behind chord movement is slightly different from the cc logic as we do cache the current cc number, so we don't have to loop over all the ccs before or after the cursor. If we want to fix this bug, we probably introduce severe lag, as the number of ccs in a midi item can be much more than the number of notes, especially with a stepped sustain pedal, mod wheel movement, etc.

**Comment by jcsteh** [comment]
What if we cached the cc number for the position, as well as the ordered cc
number within that position's ccs? For example, currentCc might be 50, but
currentCcAtSamePos might be 0. We'd then walk back from currentCc to find
the first cc at that position, walk forward from currentCc to find the last
cc at that position, sort the ccs within that range and finally use
currentCcAtPos to work out which cc we really wanted.
