### ISSUE TITLE
Unable to use previous and next CC actions to move to events that are not CCs

### ISSUE THREAD

**Issue by Batworx** [jcsteh/osara#436]
The OSARA: Move to previous CC and OSARA: Move to next CC actions seem to treat all events that are not notes as CCs. So, if an item contains pitch bend, aftertouch, or program change messages, incorrect numbers and values are reported.

**Comment by leonardder** [comment]
I found the source of this. We're currently ignoring the first byte of the midi message. I think I'll do some refactoring and rename ControlChange to MidiMessage, control to msg2, value to msg3 to be more consistent with how midi messages are created.
