### ISSUE TITLE
Overriding note previews when moving the pitch cursor

### ISSUE THREAD

**Issue by Batworx** [jcsteh/osara#437]
When moving the pitch cursor up or down in semitones, the note that gets played is so short that it sometimes isn't even audible, and moving the cursor in octaves doesn't play any notes at all. Could Osara modify the semitone actions to lengthen the played note and add the ability to play the note when moving by octave?

**Comment by jcsteh** [comment]
through is out of scope for OSARA. It should instead be filed as a REAPER feature request.
