### ISSUE TITLE
Sync pitch cursor with currently selected note

### ISSUE THREAD

**Issue by Batworx** [jcsteh/osara#438]
When moving between chords or notes, would it be possible to have Osara keep the pitch cursor in sync with the currently selected note? This way, after moving to a note, inserting new notes could be done relative to the note currently selected, and the newly inserted notes could inherit certain other properties from the selected note, such as velocity, length, position, and channel.

**Comment by jcsteh** [comment]
While it's possible to do this with the API (MIDIEditor_SetSetting_int active_note_row), I'm not convinced this is in scope for OSARA:

1. It's a huge change to REAPER's existing behaviour.
2. I'd argue it's counter-intuitive for most users. What's the use case/scenario for this?
3. It's not just the pitch cursor OSARA would have to change. It'd also have to set the length and velocity for the newly inserted note.
4. I don't see how this is specific to screen reader users. Is there some equivalent sighted users already have here that OSARA users don't?

**Comment by leonardder** [comment]
@Batworx: would you be able to give your opinion on @jcsteh's questions? I tempted to close this as per https://github.com/jcsteh/osara/issues/438#issuecomment-749943171, as I think these are valid points.

**Comment by leonardder** [comment]
I'm closing this issue as @jcsteh cleary pointed out in https://github.com/jcsteh/osara/issues/438#issuecomment-749943171 that this is pretty much out of scope for OSARA. Feel free to reach out if you think otherwise.
