### ISSUE TITLE
MIDI patch browser

### ISSUE THREAD

**Issue by Batworx** [jcsteh/osara#441]
Would it be possible to have a dialog to browse through a list of MIDI patches, and have Osara insert the necessary bank and program change events in the MIDI editor when you press OK? Idealy, you'd be able to import information from something like a tab-delimited text file containing bank MSB, bank LSB, program number, and instrument name. You could then list instruments in any order you wanted, and search a large list of instruments with a filter edit box, much like OSARA's effect preset and effect parameter dialogs have. Reaper's built-in facilities for this insist on organising patches by bank, despite the fact that some plug-ins or hardware MIDI devices do not organise sounds this way. Reaper's patch selection dialogs also don't provide a search feature, and don't send the bank and program information out to plug-ins or hardware MIDI devices while you browse through patches. You have to continuously Tab to and press a "Send Now" button.

**Comment by jcsteh** [comment]
I think this is out of scope for OSARA unless you can justify otherwise. It seems like this is more than just providing access to something which isn't accessible right now or making something equivalently efficient for screen reader users that's already more efficient for sighted users. To put this another way, you're asking for a feature that would benefit all users, not something accessibility specific.

**Comment by Batworx** [comment]
@jcsteh, Reaper's built-in patch browser is definitely more efficient for sighted users, because they can expand either the bank or patch combo boxes and skim read with their eyes to find what they want, then easily click on the desired items, and just as easily click on the "Send Now" button if they want to send their changes out to a MIDI device. How would having an OSARA dialog with a list view and a filter edit box for this be any different to the new preset selection dialog? Sighted people don't have the luxury of the "type to select" functionality that your list view provides, nor do they have an edit box to display only presets containing the text you type, which would be faster even than skim reading with eyes. The native Reaper presets combo box has note of these niceties, yet we get a fancy, separate, OSARA-specific dialog added with no fuss. The same is true for the FX parameters dialog, which I believe we've had since OSARA's inception. By your logic, we shouldn't have note previews in the event list, because that's not accessibility specific. It can benefit everyone, yet instead of leaving that for Cockos to sort out, we now have it in OSARA.

**Comment by leonardder** [comment]
> By your logic, we shouldn't have note previews in the event list...

I don't think that's necessarily true. Note preview in the event list allows for much more rapid skimming through the list.

I think the main reason for @jcsteh to state that this is out of scope for OSARA is your idea to have a way to import definitions from a text file.

**Comment by jcsteh** [comment]
First, you should already be able to navigate those combo boxes by letter without consequences. You can also hit the send button. So, I don't follow what is less efficient here.

Second, your request was asking for insertion into the editor, different organisation of the lists, etc.

**Comment by Batworx** [comment]
The organisation of the list would have been handled by the text file from which you import your instrument names. But all right, I accept that this is a bit outside of OSARA's scope. I'll either attempt to put together a script that does this, or submit a Reaper feature request.
