### ISSUE TITLE
Osara can't select first cord's note one by one with up/ down arror keys at the first item in the project.

### ISSUE THREAD

**Issue by vgjh2005** [jcsteh/osara#446]
Hi:
I found a bug:
1. press ctrl+left arror key then letter A to select first item
2. Press ctrl+alt+e to open midi editor
3. Press left arror to select the first 4 notes cord.
4. Try to press up/down arror to select a note. But nothing is selected.
Sample project has been uploaded. Please rename it before  open.
[example.rpp.txt](https://github.com/jcsteh/osara/files/5741547/example.rpp.txt)

Thanks!

**Comment by leonardder** [comment]
There's something really odd with this project in that the first chord of the midi item starts at position -32.1.00, according to the events view. Do you have a possible explanation for that?

**Comment by leonardder** [comment]
It indeed seems that the midi data is broken here. I will close this issue for now. We can always reopen if we think that this is really an issue in OSARA itself, but I doubt that, given it works just fine in wellformed midi items.
