### ISSUE TITLE
Add action feedback for "Track: Toggle record arm for selected tracks" (ID 40736)

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#455]
Another upcoming keymap substitution planned once feedback is in place, this time suggested by @tbdalgaard. Switching to this action for arming will shore up consistency in that users will then be able to toggle arm state for multiple tracks when selected, as they currently can for mute, solo, record monitor and phase.

Action: Track: Toggle record arm for selected tracks
ID: 40736

Thanks in advance, as always!

**Comment by jcsteh** [comment]
Is that the wrong id? For me, the id reports as 9.
