### ISSUE TITLE
Bug: OSARA reports "open" "small" and "closed" states on tracks

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#460]
Is there any way to get these reports restricted to folder tracks only? I've had it confirmed visually that cycling through our "open" "small" and "closed" reports on either child tracks or tracks that aren't part of a folder does diddly squat visually, so seems like misleading feedback.

Thanks in advance for any tightening you can do.

**Comment by jcsteh** [comment]
That might be so visually. However, the command is a REAPER command (not an
OSARA command) and it does affect the state of the track. For example,
press enter until you hear "closed", then press shift+enter until you hear
"folder". Even though you made it a folder second, the track is now a
closed folder. Refusing to report anything when the user presses enter is
thus lying to the user, though I'll grant REAPER lies visually too.

I'd say this is a UX bug that ideally needs to be fixed in the REAPER
command; i.e. it shouldn't do anything on a non-folder track. After that,
we can tweak OSARA to respect that. Failing that, we could override this
completely in OSARA, but that feels slippery.

**Comment by jcsteh** [comment]
@ScottChesworth, thoughts on my comment above? What do you think is the right path forward here?

**Comment by ScottChesworth** [comment]
Apologies for the slow response. I've emailed Cockos now, explained how it leads to a deceptive UX and requested the action to either only run or only return a result when run on folders.

**Comment by ScottChesworth** [comment]
Justin says:
"It would probably be best if OSARA ignored that attribute for non-folder tracks…"
That attribute as in I_FOLDERCOMPACT.

**Comment by ScottChesworth** [comment]
I pressed a little harder and got:
"Changing the API might break other scripts or plugins that depend on being able to set collapse state independently, so I would be really hesitant to change it when it is simple to get the desired behavior on the plug-in side…"

**Comment by jcsteh** [comment]
I'm reluctant to keep pushing on this, but I think we have a misunderstanding here. I'm not suggesting the API should be changed. I'm suggesting the action bound to enter shouldn't change the compacting state for non-folder tracks. Sure, we can ignore it, but as I said above, what if a user accidentally changes it to closed, then later turns it into a folder?

Anyway, I guess I'll just change OSARA to ignore it for now and we can blame REAPER if users get bitten. :)

**Comment by ScottChesworth** [comment]
> I think we have a misunderstanding here. I'm not suggesting the API should be changed. I'm suggesting the action bound to enter shouldn't change the compacting state for non-folder tracks.
> 
Pasting what I wrote to Justin to check that I haven't caused crossed wires, but I'm pretty sure that's what I asked for:
"1. Select a folder and run "Track: Cycle folder collapsed state" to cycle its state through Open, Small and closed. Each time the state changes, I_FOLDERCOMPACT returns 0, 1 or 2 respectively, and OSARA delivers "open, small" or "closed" to be reported by screen readers in accordance with what's being returned from the API. All of that works wonderfully well. 
2. Now select a track instead and run the same action. This is where things seem odd. According to the API documentation I_FOLDERCOMPACT is "only valid on folders", so if a track is selected, I'd not expect this to return a result, but it still does. 
As a consequence, OSARA users are hearing those "open, small" or "closed" reports even though nothing about the track is changing. 
Any chance of some tightening? Ideally, that action would only run on folders."
I think that's what you were after, yeah? If not, let me know and I can try again or CC you in.

**Comment by jcsteh** [comment]
The only thing I can think is that Justin misinterpreted your suggestion. Since you mention that I_FOLDERCOMPACT unexpectedly returns a value, he might have thought you meant it shouldn't return a value even if the value is changed, whether that be by an action or by a script. In contrast, what we're saying is that the builtin action shouldn't change the value on a non-folder track.

**Comment by ScottChesworth** [comment]
That's possible. Hold fire, I'll go for another round.

**Comment by ScottChesworth** [comment]
He stuck to his guns, then changed his mind 6 minutes later. Dunno what swayed him, but it looks like this is gonna be tightened in Reaper. Keep the issue open until it happens I guess.

**Comment by jcsteh** [comment]
Even once this is tightened in REAPER, there'll probably need to be some
minor tightening in OSARA. Once it no longer changes the compacting state,
OSARA is still going to report "open" when you press it. It should probably
instead report "not a folder" or something. I can make that change
regardless, but I was worried about users getting confused if they later
made a track into a folder, hence my pushing the REAPER side.

**Comment by ScottChesworth** [comment]
Yah, makes sense.

**Comment by jcsteh** [comment]
I've done the OSARA part of this. Just know that until Cockos stop this from c7cling, it's going to say "not a folder", but under the hood, it will be changing the collapsed state. Of course, that will only matter if the user later changes the track to a folder.

**Comment by ScottChesworth** [comment]
It's like that classic Queen lyric: "I want to ride my bic7cle, I want to ride my bike".
That time, I did wanna rub it in. :)
