### ISSUE TITLE
Can't navigate left on filtered notes in the midi editor.

### ISSUE THREAD

**Issue by CastleStarter** [jcsteh/osara#462]
Record a series of notes in the midi editor such as an ascending scale.
Open filter events dialog with F
Set to display only events that pass filter
Select type of notes
Filter notes from, say, half way up the scale to the top.
Apply selection and press escape to close dialog.
Use right cursor key to move through filtered notes.
Pressing left arrow returns to the start of the item rather than going back through the filtered notes.

And tagging on feature requests here as don't know where else to put them.
A Kenny Joya video suggests sighted users can play the midi with the filter events dialog still open.
Could this be reproduced in OSARA as, particularly with the solo option ticked, this would allow the effect of the filtering to be heard and then adjustments made without having to re-open the dialog and tab lots.

And there are some related actions which it would be useful to get speech feedback on:
Filter: Enable/disable event filter
Filter: Invert filter
Filter: Toggle filter solo

**Comment by jcsteh** [comment]
Please file the individual feature requests as separate issues with examples of what steps you would take and what you would expect to happen. Thanks.

**Comment by ranetto** [comment]
Hi everyone, I too have not been able to use the filter to filter midi events for example: when I activate the osara filter it no longer works and I do not see only the type of midi event that I have filtered.
Are there any solutions?
Thanks in advance!

**Comment by CastleStarter** [comment]
Will raise new issues for everything here so this one can be closed.
