### ISSUE TITLE
Allow midi editor play with filter event dialog open

### ISSUE THREAD

**Issue by CastleStarter** [jcsteh/osara#464]
A Kenny Joya video suggests sighted users can play a midi item in the midi editor with the filter events dialog still open.
https://www.youtube.com/watch?v=GId0W5402BI

Could this be reproduced in OSARA as, particularly with the solo option ticked, this would allow the effect of the filtering to be heard and then adjustments made without having to re-open the dialog and tab lots.
So for example:
Open up midi editor on midi item which contains notes
Open up filter event dialog with F
Make options and press Set Selection button but then don't press escape to close dialog.
Press shift space to play the midi item from the current position.  Press shift space again to stop it.
Can adjust filter options  and press Set Selection button again.  Can now press shift space to hear how the changes in filter options has changed the selection.

**Comment by RDMurray** [comment]
@CastleStarter  Like in many other Reaper dialogs, Control+space is play/stop. I have verified that it works in the midi filter dialog. set the filter parameters, check solo, then use control+space to hear the result.

I think this is what you wanted, therefore I am closing the issue. Feel free to open again if I misunderstood.

**Comment by CastleStarter** [comment]
Yes, works for me.  Thanks.
