### ISSUE TITLE
Is it possible to give feedback to these SWS actions for the volume control of the master track?

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#470]
Hi,
I found 3 SWS actions to control the master volume of a DB or to reset to 0 db in the master track.
The actions are:
Xenakios / SWS: Nudge master volume 1 dB up
Xenakios / SWS: Nudge master volume 1 dB down
To reset to 0 DB:
Xenakios / SWS: Set master volume to 0 dB
Is it possible that OSARA can give feedback for these actions?
Greetings!

**Comment by ScottChesworth** [comment]
Please accompany actions with their ID when requesting feedback. It saves our developers a bit of time. FYI, these ones are:
Xenakios/SWS: Nudge master volume 1 dB up (ID _XENAKIOS_NUDMASVOL1DBU)
Xenakios/SWS: Nudge master volume 1 dB down (ID _XENAKIOS_NUDMASVOL1DBD)
Xenakios/SWS: Set master volume to 0 dB (ID _XENAKIOS_SETMASTVOLTO0)
To find the ID, focus on the relevant action in the actions list, hit Applications key or right click, then choose the "Copy selected action command ID" option. That puts the ID on your clipboard, ready for pasting here.
Cheers.

**Comment by Lo-lo78** [comment]
Sorry Scott, I forgot!

Description: Xenakios/SWS: Nudge master volume 1 dB down;

Command ID: _XENAKIOS_NUDMASVOL1DBD


Description: Xenakios/SWS: Nudge master volume 1 dB up;

Command ID: _XENAKIOS_NUDMASVOL1DBU


Description: Xenakios/SWS: Set master volume to 0 dB;

Command ID: _XENAKIOS_SETMASTVOLTO0

Greetings!

Il 02/02/2021 13:22, ScottChesworth ha scritto:

**Comment by ScottChesworth** [comment]
@jcsteh, can I just reuse your code for reporting track volumes and switch out the IDs to get this implemented, or do we do anything special to report SWS actions? If the former, I can probably do it. If the latter, gimme a nudge in the right direction whenever you have time, I'm keen to learn.

**Comment by jcsteh** [comment]
You'll need to use the function which specifically reports master track volume. We definitely have actions already which do that.

You can't just use the POST_COMMANDS array though because you need to specify the id as a string for extension actions. I think there's a POST_CUSTOM_COMMANDS array or something like that (not in front of PC right now). Check out how we handle the other SWS volume actions and copy that, swapping the id and also the function to use the master volume function.

**Comment by ScottChesworth** [comment]
Found it right at the top of the POST_CUSTOM_COMMANDS array, thanks. I've got it working, will submit a PR soon.

**Comment by ScottChesworth** [comment]
Oh, nope, not quite as easy as I thought. Right now it works as expected if focus is on the master, but gives me a report related to the current track if focus is elsewhere. Hmmm. an extra if statement needed somewhere I guess. Will revisit this asap, I should be able to figure it out.

**Comment by ScottChesworth** [comment]
Duh, turns out I was calling the wrong function earlier. Face-palm.
