### ISSUE TITLE
Suppression of the number of tracks:

### ISSUE THREAD

**Issue by ranetto** [jcsteh/osara#472]
Hi James, I propose again a problem I have already heard, and this time I almost ask you a personal favor, assuming that here we can express ourselves in this way:
for some time I have switched to windows 10 and with my system I am using exclusively NVDA, as jaws is much slower in the scrolling in reaper and works much worse than NVDA.
I miss terribly the possibility that I have with jaws scripts to suppress the track number and this confuses me and slows down my work and often I can't orient myself as fast as when I don't have the track number.
The objections raised to me are what to say when a track has no name:
well when a track has no name you could vocalize the number or say no name.
Simply re-ticking the osara preferences could result in normal behavior or the suppression of the track number.
I tried to suppress the display of the track number from the reaper theme, but clearly reading Osara from the bees, I had no effect.
This is almost a favor I ask of you: is it possible to implement this thing so that I can work without having to buy a new i10 to get jaws to read at NVDA speed?
James thank you in advance and I hope you will like to accept my feature that for those who do not want to use it, disabled by default I do not think it can create problems.

**Comment by jcsteh** [comment]
There is already an issue filed for this which you have commented on, #175. Please don't file duplicate issues. Of course, I understand you might have just forgotten there was en existing issue, which is fine. Thanks.
