### ISSUE TITLE
Reading of events in "lane"

### ISSUE THREAD

**Issue by ranetto** [jcsteh/osara#473]
Hi James and everyone: is it possible to have the events read in osara exclusively in their wards?
Is the example of my request the following?
I want to remove a CC from an area of my song, let's admit the number 64, I would like to be able to scroll by selecting the appropriate lane relating to that event, only events number 64, since the event filter can only be used in the events list and not in the "pianoroll ".
is it possible to implement this functionality?
I thank you in advance.

**Comment by ScottChesworth** [comment]
If you're talking about the Filter window @ranetto, that can be used from the Piano Roll view, just hit F.

**Comment by ranetto** [comment]
Hi Scott, no no my I was referring to being able to see only the lane of an event type after setting it:
however, I can only use the filter by filtering what I want and then in the events list I find what I have filtered, it doesn't work for me in the "piano roll": there is a way to filter the events and scroll through them without seeing the notes in the "piano roll "?
It would be fine too!
Thanks Scott.

**Comment by MatejGolian** [comment]
@ranetto, If I understand your issue correctly, in the piano roll this can be done by using the commands for working with CC lanes and events.
1. If you are on Windows, keep on pressing CTRL+Alt+- or CTRL+Alt+= to select the CC lane you want to work with.
2. Once you have the appropriate lane selected, you can move between the available CC events in that lane with CTRL+- and CTRL+=.
3. For making selections use CTRL+Shift+- and CTRL+Shift+=.

**Comment by mattymc2** [comment]
Hey guys. I’m not sure if I have this incorrect or not however when I’m using ctrl+ Or = to move through the events it doesn’t seem to stay to the lane that I’ve selected. For example if I select cc Lane 64 I can see those cc events but then it will just jump out to mod wheel data and all kinds of other stuff. Shouldn’t it only show cc 64 events after I’ve selected the lane and nothing else?

**Comment by MatejGolian** [comment]
You are correct. It seems that when there are no more CCs onthe selected lane, Osara jumps to whatever other CCs it can find. To me this behavior feels buggy as well. Maybe opening an issue is in order here.
In the mean time, @ScottChesworth or @jcsteh , do you this issue can be closed?

**Comment by ScottChesworth** [comment]
So far as I can tell, existing CC navigation commands address what was requested and it hasn't seen any activity in forever, so I'm closing.
Re CC navigation switching lanes unexpectedly, please open a new issue, preferably with a test project as I can't recall seeing it happen in situ here.
