### ISSUE TITLE
mac key map conflicting with system command

### ISSUE THREAD

**Issue by KeithRempel** [jcsteh/osara#476]
In the midi editor there is an action assigned to command shift q. Quantize selected notes to grid or something close to that. this is in conflict with an OS default command to log out of current user account. My fix for this has been to switch the action over to control shift q. Probably worth switching across the board.

Another issue with the key map is that the slash key in the main actions dialogue has not been mapped to the action that moves edit cursor to play cursor. I think this is standard in windows. If needed I can make these tweaks to a fresh osara key map and pass an updated version along?

**Comment by ScottChesworth** [comment]
Hey Keith, please make those changes to a freshly installed map and link to it here. I'll do the GitHub dance to get it incorporated and update documentation. Thanks!

**Comment by KeithRempel** [comment]
https://www.dropbox.com/s/ok4jxnhne18856u/Mac%20modified%20by%20Keith.ReaperKeyMap?dl=0
Clean osara key map with the following modifications
1. Slash key mapped to View: Move edit cursor to play cursor
2. Added shortcut Control+Shift+Q to midi editor action “quantize note’s position to grid” I couldn’t figure out how to get rid of the command+shift+Q shortcut mapped here. Hoping to do so for the sake of tidiness.
3. mapped shift+TopRowDash (underscore) to the zoom out horizontally action in midi editor.

**Comment by ScottChesworth** [comment]
Move to where both shortcuts are displayed, use Arrows to select Command+Shift+Q, then move to the Delete button, wallop.
Whoopsy, that zoom assignment is missing on Windows too. I'll fix that when I submit your new map to the reppo.

**Comment by KeithRempel** [comment]
https://www.dropbox.com/s/a84jegy95wt1ouz/Mac%20Modified%20again%20by%20keith.ReaperKeyMap?dl=0 <https://www.dropbox.com/s/a84jegy95wt1ouz/Mac%20Modified%20again%20by%20keith.ReaperKeyMap?dl=0>

Same thing without the extra shortcut.

**Comment by ScottChesworth** [comment]
Thanks. Submitting posthaste. :)

**Comment by ScottChesworth** [comment]
Actually Keith, before I submit these, can I get you to do two more tweaks on Mac?
In the Main (Alt recording) category of the actions list, I'd like to get Space assigned to "Transport: play/stop" and R assigned to "Transport: record".
This is to prevent an edge case where if you enable the "Use alternate key map when recording" preference then start recording, there's no way to stop because nothing's mapped in that category.

**Comment by KeithRempel** [comment]
Here it is.
https://www.dropbox.com/s/xk9xmntk1bawdmv/updated%20mac%20keymap%20take%203.ReaperKeyMap?dl=0

**Comment by ScottChesworth** [comment]
Rest easy Rempel, I really have submitted it this time. :)

**Comment by jcsteh** [comment]
Fixed in PR #526.
