### ISSUE TITLE
Very strange Media Explorer problem urgent

### ISSUE THREAD

**Issue by piano777wzy** [jcsteh/osara#478]
Hello everyone, I have a very strange question here, which is about Media Explorer.
My system is windows10 64-bit home edition
The screen resolution is 1024 × 768, I also tried other resolutions
reaper version:The latest official version 6.23 and 6.24rc3
osara version:osara_2021.1pre-447,e23ca7d9:Including the later version,
Problem Description
The problem is this,
When I opened Media Explorer, I browsed to a sound file,Can't open Insert into projecti This menu,The version before 447 can be used normally here.
In the later version, as long as I press the hotkey, he will run to the desktop of the computer.
I thought of many ways, but they all failed.
I maximized the software and adjusted the resolution of the flat wood but failed. Is there a solution?
I can only use:osara_chs2021.1pre-446,

**Comment by jcsteh** [comment]
Once you find the file in the Media Explorer, what key (or keys) exactly
are you pressing to insert the file?

**Comment by piano777wzy** [comment]
Hello,&nbsp;the&nbsp;hotkey&nbsp;I&nbsp;said&nbsp;is&nbsp;application,
The&nbsp;context&nbsp;menu&nbsp;can&nbsp;be&nbsp;opened&nbsp;in&nbsp;previous&nbsp;versions
Starting&nbsp;from&nbsp;version&nbsp;447,I&nbsp;press&nbsp;application,Can't&nbsp;open&nbsp;Media&nbsp;Explorer,Context&nbsp;menu&nbsp;inside,
use&nbsp;application&nbsp;This&nbsp;hotkey
It&nbsp;will&nbsp;jump&nbsp;directly&nbsp;to&nbsp;other&nbsp;places,&nbsp;it&nbsp;will&nbsp;jump&nbsp;to&nbsp;the&nbsp;computer&nbsp;desktop,&nbsp;or&nbsp;the&nbsp;reaper&nbsp;main&nbsp;window








 ---Original---

**Comment by ScottChesworth** [comment]
Reposting the comment above with all of the rogue character encoding stuff removed:
Hello, the hotkey I said is application,
The context menu can be opened in previous versions
Starting from version 447,I press application,Can't open Media Explorer,Context menu inside,
use application This hotkey
It will jump directly to other places, it will jump to the computer desktop, or the reaper main window

**Comment by ScottChesworth** [comment]
Just tested Media Explorer context menus with Reaper 6.23, 6.24RC3 and OSARA pre-467. Couldn't reproduce the issue here.
Short-term, can you hit Enter to insert the desired file?

**Comment by jcsteh** [comment]
The difference between those two versions is that we click in the centre of
list view items instead of the top left. The fact that this isn't working
for you in the Media Explorer suggests that your Media Explorer is somehow
positioned off screen, has been shrunk or is obscured. I'm going to land a
tweak to only click in the centre of items in the Project Render Metadata
list, since that's the only place we really needed to click in the centre.
However, the behaviour you're seeing is still pretty strange; I can't
reproduce it either.

>

**Comment by piano777wzy** [comment]
ok,&nbsp;this&nbsp;version&nbsp;issue&nbsp;has&nbsp;been&nbsp;resolved.








 ---Original---
