### ISSUE TITLE
The following error occurs when building osara with Visual Studio Community 2019 version 16.8.5:

### ISSUE THREAD

**Issue by dingpengyu** [jcsteh/osara#479]
hi all
The following error occurs when building osara with Visual Studio Community 2019 version 16.8.5:
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
cl /Fobuild\x86\controlSurface.obj /c src\controlSurface.cpp /TP /EHsc /std:c++l
atest /W3 /WX /nologo /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinyge
ttext\include /Iinclude\fmt\include /Z7
controlSurface.cpp
cl /Fobuild\x86\dictionary.obj /c include\tinygettext\src\dictionary.cpp /TP /EH
sc /std:c++latest /W3 /WX /nologo /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iin
clude\tinygettext\include /Iinclude\fmt\include /Z7
dictionary.cpp
cl /Fobuild\x86\envelopeCommands.obj /c src\envelopeCommands.cpp /TP /EHsc /std:
c++latest /W3 /WX /nologo /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\ti
nygettext\include /Iinclude\fmt\include /Z7
envelopeCommands.cpp
E:\Source\Repos\reaper\osara\include\fmt\include\fmt/format.h(1): error C2220:
以下警告被视为错误
E:\Source\Repos\reaper\osara\include\fmt\include\fmt/format.h(1): warning C4819:
 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防
止数据丢失
scons: *** [build\x86\envelopeCommands.obj] Error 2
scons: building terminated because of errors.
Compiler Environment:
Lenovo Saver ISK15 Notebook
windows10 20h2 64-bit
Visual Studio Community 2019 16.8.5
python3.7.9+virtualenv Latest Stable Version
scons Latest stable version
ps:
The compilation is done with the latest master partition.
And the repository was re-cloned.
thanks

**Comment by jcsteh** [comment]
Does this error go away if you modify line 36 of src/archBuild_sconscript to include /wd4819 after /WX? Like this:
`	env.Append(CXXFLAGS="/EHsc /std:c++latest /W3 /WX /wd4819")`

**Comment by dingpengyu** [comment]
> Does this error go away if you modify line 36 of src/archBuild_sconscript to include /wd4819 after /WX? Like this:
> ` env.Append(CXXFLAGS="/EHsc /std:c++latest /W3 /WX /wd4819")`
scons: done building targets.
Test Pass
