### ISSUE TITLE
osara Translation Language: english to zh_CN

### ISSUE THREAD

**Issue by dingpengyu** [jcsteh/osara#480]
hello
Is it possible to create osara translations of zh_CN in Crowdin?
crowdin user name: dingpengyu
osara Translation Language:
 English to Simplified Chinese
reaper Language Pack Name:
zh_CN.ReaperLangPack
thanks

**Comment by jcsteh** [comment]
You should hopefully have a Crowdin invite. Please let me know if you don't
get it.

Can you please provide the names of the language pack (or packs) that your
users will be using? Thanks.

**Comment by dingpengyu** [comment]
> You should hopefully have a Crowdin invite. Please let me know if you don't get it. Can you please provide the names of the language pack (or packs) that your users will be using? Thanks.
The language name of my reaper is: zh_CN

**Comment by jcsteh** [comment]
Ah. Thanks. I didn't see this language pack on the REAPER stash. Is this a
REAPER language pack you're developing yourself?

**Comment by dingpengyu** [comment]
hello The current URL of IE8N code is incorrect, the code should be zh_CN Here is the example:
https://crowdin.com/project/osara/zh-CN#

**Comment by dingpengyu** [comment]
> Ah. Thanks. I didn't see this language pack on the REAPER stash. Is this a REAPER language pack you're developing yourself?
The language pack has not yet been uploaded to the official page

**Comment by dingpengyu** [comment]
Here are the differences between Simplified Chinese and Traditional Chinese
[Simplified Chinese characters - Wikipedia](https://en.wikipedia.org/wiki/Simplified_Chinese_characters)
[Traditional Chinese](https://en.wikipedia.org/wiki/Traditional_Chinese_characters)

**Comment by jcsteh** [comment]
Sorry, I selected the wrong one by mistake. Hopefully fixed now.

**Comment by dingpengyu** [comment]
hi 
Thank you for your work, the problem has been solved.
The translation of osara in Simplified Chinese is also finished.
I will close this issues
thanks
