### ISSUE TITLE
Undesirable feedback using Klinke MCU driver and X-Touch control surface

### ISSUE THREAD

**Issue by gordio69** [jcsteh/osara#481]
I am using the X-Touch control surface with the Klinke MCU driver.  I have created several plugin maps.  The process of doing this is a bit involved and I will probably present it in an audio file.  The basic concept when designing a plugin map is to use the faders for continuous controllers, and the rotary encoders for parameters that have definite stopping points.  The faders work fine.  For the most part, values are spoken as you might expect.  The problem arises with parameters that are assigned to the encoders, (VPOTs).  TO do this, the parameter is defined with its number in the effect parameters list, 0 indexed, and a short 6 character label (Short) and a 12 character label (long) are entered.  The values from the sliders are each entered on a separate line starting with a STEP value= followed by the number that appears in the edit box of the parameter list.  This is followed by the short and long names to describe the value.  The plugin map files are written as xml files.  Pressing or turning the encoder assigned to the root parameter moves you through the defined steps.  The problem is that Osara speaks the numeric value instead of the text.  The odd thing is that turning the encoder all the way to the minimum or maximum value does speak the text.  If the same parameter is assigned to a fader instead, the text is spoken, but a lot of other numeric values are spoken in between.  This isn't a big problem when there are only two or three settings, but I've defined some that have 30 or 40 settings.  I'm putting this out here in case somebody might have some insight about what is going on.  
Gord

**Comment by jcsteh** [comment]
OSARA tries to get the friendly version of the value from the effect. The key here is that the friendly value comes from the effect, not the surface. There's no API in REAPER for labelling parameter values, so my guess is that this short/long value text you are assigning is internal to the Klinke MCU driver.

As to why the top and bottom values get read as expected, my guess is that the plugin does label these correctly.

If you haven't done this already, you could try using OSARA's FX Parameters diaog to figure out which parameter values are labelled correctly by the effect and grabbing the exact numbers from the edit field.

**Comment by gordio69** [comment]
The problem with this theory is that this happens with any plug-in I try. I am going to have to try this with control service integrator even though there is a limit to how many parameters you can access. I think I have mapped something like five or six plug-ins now. I have even loaded maps that were done already

**Comment by jcsteh** [comment]
Does OSARA's FX Parameters dialog report friendly values for the same numeric values? if not, perhaps these FX just don't support friendly values properly?

The Cockos Rea plugins do support friendly values very well. Have you tried these, and if so, do they suffer from the same problem?

**Comment by gordio69** [comment]
I have done some experimenting since my last post.  Yes, the text values of parameters are shown in the parameters dialog.  I think this problem is due to how Klinke controls parameters with the VPOTS.  If I assign the same parameter to a fader, Osara speaks the text when I touch the fader.  While this does take up realestate on the surface, it is a workable solution.  I can use the VPOT to step through values, and then touch the fader to hear the text value.  This is only necessary for parameters with a lot of steps.  For those that are just on or off, hearing 1 and 0 isn't a big deal.  Sends, however, are not spoken at all.  Is there a reason for this?

**Comment by jcsteh** [comment]
> Yes, the text values of parameters are shown in the parameters dialog. I think this problem is due to how Klinke controls parameters with the VPOTS. If I assign the same parameter to a fader, Osara speaks the text when I touch the fader.

That is really strange. I wonder what the difference is there? Any FX parameter change should fire the same REAPER API notification. Seems like this might actually be a REAPER bug, but it's difficult for me to know what the bug is exactly without knowing how the surface driver is doing things differently for the two cases. The driver's code is open source, but I'm not familiar with it, so it'd take me some time to figure out the difference and that's probably not time I'm going to have in the near term.

> Sends, however, are not spoken at all. Is there a reason for this?

OSARA doesn't support this yet. Looking briefly, it looks like the REAPER API does fire an obscure notification for send volume and pan changes, so OSARA should be able to capture those. There's no notification for other send parameters such as mute, though. Please file a separate issue request for surface send volumes and pans if you'd like those.

**Comment by gordio69** [comment]
OK. I’ll file a separate post. Right now, if you are just a send, oh sorry
constantly speaks the master volume level.

**Comment by gordio69** [comment]
Do you know, I was thinking, the mutes  for the sends  do show up in the
track parameters list. I would think that would mean that they would be
accessible through the surface to.
G

**Comment by jcsteh** [comment]
Sure, you can get and set the value of send mutes on demand. That doesn't mean you can get an automatic notification when it changes. Unless you want to poll the value of mute for every send in the project every 50 ms or so, but that would be horribly inefficient and would probably slow things down a tonne.

**Comment by gordio69** [comment]
Well the truth is, I went and tried CSI. CSI reads the rotary encoders just
fine. Of course, there are only a few zone files available. I want to try
making one myself, but I’m not sure of all the tabs spaces that you need to
put in. I don’t know how critical all that is. I was following one that
works, for the Rio EQ. The only real drag about this is that you don’t have
access to nearly as many parameters as you do with the clink he. However,
this seems to prove that the rotary in corners read just fine. I just hope
that maybe someday we can straighten it out with cranky.
gord

**Comment by gordio69** [comment]
Well, I really think that we should close this issue for now. It really seems to be a problem with clicky, rather than oh sorry. I just need to learn more about CSI.

**Comment by jcsteh** [comment]
I wouldn't say it's a problem with Klink so much as an incompatibility... but I don't understand enough about Klink to know why. Still, if it works with CSI and you're happy, I'll close this. Please reopen if you decide to pursue this further.
