### ISSUE TITLE
osara translate traditional Chinese

### ISSUE THREAD

**Issue by windrofy** [jcsteh/osara#482]
Crowdin username: windrofy
English to tranditional Chinese
REAPER language pack: zh-TW.ReaperLangPack
This is my own translated version.

**Comment by jcsteh** [comment]
Thanks. I've invited you.

Since this is your own language pack, would you mind renaming it from zh-TW to zh_TW (underscore instead of hyphen)? This will mean I don't have to map it in OSARA. Thanks.

**Comment by windrofy** [comment]
zh_TW it's OK.
What can I do next?
Thanks!

**Comment by jcsteh** [comment]
Did you get the invite? Once you have that, you can go to Crowdin and
translate online, sync with Poedit or download the po file to translate
offline and upload it again:
https://crowdin.com/translate/osara/4/en-zhtw

**Comment by windrofy** [comment]
How do I upload the translated files?
Thanks!

**Comment by jcsteh** [comment]
The easiest way is to go here:
https://crowdin.com/translate/osara/4/en-zhtw
and hit control+insert. If you're running NVDA, you'll need to hit insert twice, since NVDA overrides the insert key. That should pop up a dialog which will let you upload a po file. If you need it at some later stage, from that same page, you can hit control+s to download the translation as a po file.

If you're using Poedit, once you've uploaded the initial translation, I'd suggest you have Poedit open the translation from Crowdin. That way, you can sync back and forth as needed from Poedit.

**Comment by windrofy** [comment]
Thank you for your explanation, I have completed the synchronization.
But {} bpm ID: 169,
It can't translate.
Don't know what went wrong?
Thanks!

**Comment by jcsteh** [comment]
Crowdin shows that the translation for just that one string is missing
altogether. Maybe it didn't save in the po file or something? Do you still
see it locally?

**Comment by dingpengyu** [comment]
> Thank you for your explanation, I have completed the synchronization. But {} bpm ID: 169, It can't translate. Don't know what went wrong? Thanks!
This problem also occurs in Simplified Chinese
There are also these entries that cannot be translated::
c ID: 27
d ID: 29
e ID: 31
f ID: 32
g ID: 34
a ID: 36
b ID: 38
FX: ID: 109
FX: ID: 136
thanks

**Comment by dingpengyu** [comment]
> Crowdin shows that the translation for just that one string is missing altogether. Maybe it didn't save in the po file or something? Do you still see it locally?
hi
You can see this string in the po file, but it is lost after translation and syncing to crowdin.

**Comment by jcsteh** [comment]
Can you paste the entry from the po file here, including msgid, msgstr and any comments before it? Thanks.

**Comment by windrofy** [comment]
What i can't translate is:
#. Reported when changing the tempo. {} will be replaced with
#. the new tempo; e.g. "50 bpm".
msgid "{} bpm"
msgstr "{} bpm"

**Comment by dingpengyu** [comment]
> Can you paste the entry from the po file here, including msgid, msgstr and any comments before it? Thanks.

#. The name of a musical note.
msgid "c"
msgstr "c"
#. The name of a musical note.
msgid "d"
msgstr "d"
#. The name of a musical note.
msgid "e"
msgstr "e"
#. The name of a musical note.
msgid "f"
msgstr "f"
#. The name of a musical note.
msgid "g"
msgstr "g"
#. The name of a musical note.
msgid "a"
msgstr "a"
#. The name of a musical note.
msgid "b"
msgstr "b"
#. Reported when navigating tracks before listing the effects on
#. the track.
msgid "FX:"
msgstr "FX:"
#. Reported when switching takes before listing the effects on
#. the take.
msgid "FX: "
msgstr "FX: "
thanks

**Comment by jcsteh** [comment]
Ah, I see the problem. Your translation is identical to the original. I understand why that is, but Crowdin is ignoring it because it thinks it is an error and not correctly translated. I think I can configure Crowdin to allow this. I'll look into it.

**Comment by jcsteh** [comment]
Ah. When you're manually importing the translation from a .po file, you need to enable the option "Allow target translation to match source". I've gone through and fixed these now and this probably won't happen very often anyway, but that's how to fix it for future reference.
