### ISSUE TITLE
Osara simplified Chinese

### ISSUE THREAD

**Issue by cn-peter** [jcsteh/osara#484]
Crowdin user name: cn-peter

English to Simplified Chinese

Reaper+SWS_CHSDOU

Thank you.

**Comment by cn-peter** [comment]
We have been translating through osara.dll for almost 3 years.

Now, we transplant the translation here.

We have unified the file name of the language pack with the Chinese author.

From Reaper6.23_2021.0207Before+SWS2.10.0.1_CHSDOU.ReaperLangPack
To Reaper+SWS_CHSDOU.ReaperLangPack

Many visually impaired people in China are using translated osara.

**Comment by jcsteh** [comment]
I can add you as a Simplified Chinese translator, but note that @dingpengyu has already completed the translation. That said, not all messages are translatable yet, so you could potentially still collaborate going forward.

I've sent a Crowdin invite.

**Comment by cn-peter** [comment]
@jcsteh
OK, thank you.

**Comment by cn-peter** [comment]
> 我可以将您添加为简体中文翻译，但请注意，@ dingpengyu已经完成了翻译。也就是说，并非所有消息都可以翻译，因此您可能仍可以继续合作。
> 
> 我发送了一个Crowdin邀请。

Sorry. I haven't received the invitation. Please send it again. Thank you.

**Comment by jcsteh** [comment]
Done.
