### ISSUE TITLE
translation osara english to simplified Chinese

### ISSUE THREAD

**Issue by szzyyzz-com** [jcsteh/osara#487]
Crowdin username: szzyyzz.com
English to Simplified Chinese
REAPER language pack: REAPER_zh_CN_www.szzyyzz.com.ReaperLangPack
https://stash.reaper.fm/41464/REAPER_zh_CN_www.szzyyzz.com.rar

**Comment by szzyyzz-com** [comment]
Crowdin username: szzyyzz.com
English to Simplified Chinese
REAPER language pack: REAPER_zh_CN_www.szzyyzz.com.ReaperLangPack
https://stash.reaper.fm/41464/REAPER_zh_CN_www.szzyyzz.com.rar

**Comment by jcsteh** [comment]
Invite sent.

**Comment by szzyyzz-com** [comment]
I have logged in to crowdin,. How can I start translating? Thank you!

**Comment by dingpengyu** [comment]
> I have logged in to crowdin,. How can I start translating? Thank you!

See the translated section of osara/readme.md

**Comment by jcsteh** [comment]
You can go to [this page](https://crowdin.com/translate/osara/4/en-zhcn) to translate online or download/upload translations. Alternatively, you can sync with Poedit. Please note that the Simplified Chinese translation is currently 100% complete, so there's nothing to do right now until more strings are added.

**Comment by szzyyzz-com** [comment]
Hello! May I understand your following passage in this way?
"You can go to this page to translate online or download/upload translations. Alternatively, you can sync with Poedit. Please note that the Simplified Chinese translation is currently 100% complete, so there's nothing to do right now until more strings are added."
There is only one language pack for each language, and the current simplified Chinese language pack is jointly translated by all those who apply to translate such languages.
If this is the case, there will be a contradiction:
In the simplified Chinese environment, several REAPER language packs are popular.
In these different versions, there are great differences in the use of words and grammar.
If all REAPER simplified Chinese language packs use the same OSARA language pack, then the current osara can only feedback the Chinese in the current language pack.
According to my observation and analysis, in the current osara Chinese language pack, many translations come directly from automatic translation, which is far from what osara really wants feedback, and even has nothing to do with the meaning of osara in some places.
The above contents are my doubts with many visually impaired people, and we all look forward to your detailed answers to your questions.
Finally, on behalf of ourselves, we would like to express our heartfelt thanks to you for all your efforts to osara. I wish you a happy life and success in your work!

**Comment by jcsteh** [comment]
Thanks for the details. That's a difficult situation I'm not sure how to
solve. Most software provides only a single translation for each language
and the user doesn't have to decide which to choose. That isn't the case
with REAPER, but that does complicate things,  for translation frameworks
(which generally only support one translation per language), for users (who
have to choose the translation) and for me as the OSARA maintainer.

My intention was that translations would be bundled with OSARA and users
wouldn't have to worry about trying to find them and install them manually.
I can't realistically do that with multiple translations. So, I guess the
Chinese translations might have to be maintained and distributed separately
and users will have to copy them in manually.

As for the existing translation containing automated entries, I can't
comment on that. That's something the Chinese translators are going to need
to sort out between them.

**Comment by szzyyzz-com** [comment]
Thank you very much for taking the time out of your busy schedule to answer our questions!
If this is the case, there should be no better solution to this problem at present.
Users with additional needs are allowed to invoke the OSAAA language package with the same name by manually changing the name of the .po file under the "osara\ locale" path.
I am the founder of the music production website (http://www.szzyyzz.com/) for the visually impaired. If you are good at Chinese, I look forward to visiting our website when you are free!
Finally, I wish you good health and all the best!

**Comment by jcsteh** [comment]
Thanks for your understanding.

If you're unhappy with the current zh_CN translation in OSARA and you can't resolve this with the other translators, I can remove the mapping for REAPER_zh_CN_www.szzyyzz.com.ReaperLangPack. This way, OSARA will search for osara\locale\REAPER_zh_CN_www.szzyyzz.com.po instead of osara\locale\zh_CN.po when your language pack is installed.

**Comment by szzyyzz-com** [comment]
There is no need to unbind the language pack from the zh_CN.po, so that the visually impaired who like to use that language pack will not have to modify the language selection settings.
I will just add a pair of language packs with other names to the REAPER language pack self-extracting file on our website, and let the visually impaired who are used to our website translation change the language settings of REAPER themselves.
In order not to waste your precious time, this question ends here for the time being. Thank you for your patient reply these days! Goodbye!

**Comment by jcsteh** [comment]
To be clear, are you happy for OSARA to search for zh_CN.po when your language pack is installed? Would it be easier for your users if it searched for REAPER_zh_CN_www.szzyyzz.com.po? Removing the mapping is not difficult for me; it's a one line code change.

**Comment by szzyyzz-com** [comment]
Thank you very much! There is no need to unbind the language pack of our website from osara.
Things are taking a turn for the better, and the author of zh_CN accepted our translation advice.
