### ISSUE TITLE
TR Translation

### ISSUE THREAD

**Issue by cankirca** [jcsteh/osara#490]
Hello,
 
Here my information to translate OSARA to Turkish.
Crowdin user: cnkrc
Language: Turkish
Reaper pack: original reaper english source pack.

Thank you.

**Comment by jcsteh** [comment]
Am I understanding correctly that there's no REAPER language pack for your language? I don't think it makes sense to translate OSARA without there also being a REAPER translation. For that reason, that's not currently possible with OSARA.

**Comment by jcsteh** [comment]
Closing due to lack of response. Please reopen if you're interested in pursuing this. Thanks.
