### ISSUE TITLE
OSARA translation crash REAPER

### ISSUE THREAD

**Issue by Aleskis** [jcsteh/osara#491]
When pressing shift+F8 shift+F9 and shift+F10, translations corresponding to item mono mode crash REAPER. I see nothing about syntax error.
I created and attached a .zip with the french langpack and the .po file. Can someone help me figure out what's wrong?
Anyway, I find it very dangerous that a simple translation can crash the whole REAPER without a preamble. I don't know if in terms of code, there's something that can be done to protect the execution of the program, but if so, let's do it because if it happens to me, it will happen to others.
[OSARA French Translation.zip](https://github.com/jcsteh/osara/files/6084960/OSARA.French.Translation.zip)

**Comment by ScottChesworth** [comment]
First step, can any of our other French-speaking users reproduce this?

**Comment by windrofy** [comment]
I tested that the files provided by your compressed package did not crash.
osara version is osara_2021.1pre-483,22e726e4.
reaper version is reaper624_x64-install.

**Comment by jcsteh** [comment]
As I [explained to you on Twitter](https://twitter.com/jcsteh/status/1366834245956562945):

> The problem is, for example, "set {count} takes to {mode}". {count} and {mode} need to be left untranslated.

So, this string:

set {count} take to {mode}

has been translated as:

{Comptage} de prise réglé sur {mode}

You've translated the "count" in the braces, but that needs to be left alone. As the translator comment explains:

> {count} will be replaced with the number of takes affected.

Anything in braces is a placeholder and needs to be left alone, though you can move it wherever you need to. The translators comment always explains what the placeholders mean.

Regarding your other questions:

> I see nothing about syntax error.

I see you haven't uploaded your translation to Crowdin. Crowdin has a QA feature which will detect errors like this.

> Anyway, I find it very dangerous that a simple translation can crash the whole REAPER without a preamble. I don't know if in terms of code, there's something that can be done to protect the execution of the program, but if so, let's do it because if it happens to me, it will happen to others.

Protecting against this is tricky. After hours of work, I think I've come up with a way to prevent the crash, but all you're going to get is a message like "error in translated string". I can't provide anything more specific than that.

I can probably set up some automation to detect bad translated strings while syncing them from Crowdin and reject the translation, though the question is how to notify translators at that point.

**Comment by Aleskis** [comment]
Thank you James, didn't saw comment translation on Poedit. Anyway, I corrected the translation and it works. Thanks also for the work to try to exclude translations that could crash REAPER.

**Comment by jcsteh** [comment]
Unfortunately, translator comments are very difficult to access for screen reader users now in Poedit. NVDA used to have a command to access them, but more recent versions of Poedit broke it.
