### ISSUE TITLE
scons does not see C++ compiler on Windows 10

### ISSUE THREAD

**Issue by ptorpey** [jcsteh/osara#494]
I am having difficulty compiling/creating the installer for Osara on my Windows 10 system by running the scons program.  I'm wondering if anyone has some idea of what might be wrong.

Here is what I did:
- I successfully cloned the Osara code from Github onto my system.
- Per the directions on the web site and readme, I installed the latest versions of:
  nsis 3.06.1
  python 3.9.2-amd64
  scons-4.1.0
  vs_community__1431843706.1614116977

When I run scons from within the Osara folder on my system, I get the following error:
 scons: Reading SConscript files ...
 scons: warning: No version of Visual Studio compiler found - C/C++ 
 compilers most likely not set correctly File 
 "C:\Users\Peter\Documents\installs\osara build 
 tools\osara\SConstruct", line 15, in <module>

I checked in the VS19 program that I do have the C++ Desktop compiler installed.

Any ideas or suggestions?

Thanks.

--Pete

**Comment by jcsteh** [comment]
I honestly have no idea. If you installed Visual Studio Community 2019 (I can't tell what version it is from their cryptic file naming) and the "Desktop development with C++" workload, that should be all you need. Note that the "Desktop development with C++" workload probably installs more than just the compiler, so you want to make sure you check the workload, not just the individual compiler.

**Comment by ptorpey** [comment]
Under the Workloads tab I have:

.NET desktop development checked‑

Which is what I think the instructions on the web said to enable.

 

Also on the individual components tab I have:

C# and Visual Basic Roslyn compilers checked 

(in addition to a lot of other things checked and many not checked)

 

Any other thoughts?

 

--Pete

**Comment by ptorpey** [comment]
I re-installed VS 2019 several times and used one of the magic JAWS touch cursors (or some other magic cursor) to find another item on the screen that referred to Desktop C++ which I didn’t see with the normal JAWS cursor.  I checked that and did the reinstall of VS 2019.

 

After the reinstall, the scons command does produce an osrar_unknown.exe file without any complaints.  Problem solved.  Thanks for the hint about another component that might have been missing.

 

Now I can start going through some of the source code and learning to use Github!

 

--Pete
