### ISSUE TITLE
After translating osara.po using crowdin and saving it, the following entry appears with an error

### ISSUE THREAD

**Issue by dingpengyu** [jcsteh/osara#496]
Test environment: 
Microsoft Windows [version 10.0.19042.867]
poedit version: 2.4.2
The wrong entry appearsunselected 翻译 — 中文（中国）: 取消选中, ID: 18
loop start 翻译 — 中文（中国）: 循环开始, ID: 134
loop end 翻译 — 中文（中国）: 循环结束, ID: 135:
msgid "unselected "
msgstr "取消选定"
msgid "loop start "
msgstr "循环开始"
msgid "loop end "
msgstr "循环结束"
thanks

**Comment by jcsteh** [comment]
I'm sorry, but I don't quite understand what entry has the error and what the error is. Could you try explaining this another way? Thanks.

**Comment by dingpengyu** [comment]
When the above entries are translated using poedit and saved and synchronized to crowdin, the IDs of the entries are not validated properly
msgid "unselected "
msgstr "取消选定"
This entry has loaded properly
There are two other entries that have not yet loaded properly
msgid "loop start "
msgstr "循环开始"
msgid "loop end "
msgstr "循环结束"
The top number of translation entries that cannot be loaded are followed by trailing spaces

**Comment by jcsteh** [comment]
I wonder if Crowdin is treating the ones with trailing spaces as duplicates or something like that. In any case, I've now removed the strings with trailing spaces, so maybe this will fix the issue? Please let me know if it doesn't.

**Comment by jcsteh** [comment]
Oops, I missed a few messages with trailing spaces, so I've now fixed those too.

**Comment by dingpengyu** [comment]
Problem solved
Can we automatically handle trailing spaces in our code? This issue has been fed back twice, thank you for your work.

**Comment by jcsteh** [comment]
I'm actually not quite sure where things are failing, so it's difficult to answer that. That is, I'm not sure if this is Crowdin or Poedit or something else. There really shouldn't be strings with trailing spaces in the first place, but I'm having to make a lot of messages translatable, so it's hard to be as careful as I'd like to be. Ideally, there'd be some kind of automated check to prevent me from making those mistakes, but writing the code to do that check is work itself I doubt I will be able to find the time for at this point.

Thanks for your work and sorry for the trouble.
