### ISSUE TITLE
OSARA: View I/O for master track doesn't work if certain themes are used

### ISSUE THREAD

**Issue by GianlucaApollaro** [jcsteh/osara#50]
All in the title:
The action OSARA: View I/O for master track no longer works, not even using the reaper action Track: View I/O for current track when master track is focused. I'd preferre the osara action to work again though.
Thanks

**Comment by MatejGolian** [comment]
It still works overhere and I downloaded a fresh copy of Osara just some 5 minutes ago.

**Comment by GianlucaApollaro** [comment]
Here when I run that action I can't see any dialogue popping up. Using 
latest reaper, latest osara on a windows 10 64 bit with both jaws and NVDA

Il 15/11/2015 21:06, MatejGolian ha scritto:

**Comment by GianlucaApollaro** [comment]
On a portable 32 bit reaper, it works. Is it only an issue with 64 bit 
then? Or it's just my machine?

Il 15/11/2015 21:06, MatejGolian ha scritto:

**Comment by jcsteh** [comment]
Still works for me. Just tested in both 32 bit and 64 bit.

I guess this would break if you somehow had additional controls on your 
master track before the I/O button, but I don't see how that's possible.

**Comment by GianlucaApollaro** [comment]
Hi,
I fixed it.
Your previous comment gave me the idea. Basically changing the theme 
fixed it. For some reasons I was using the theme called default_4.0, 
putting it back to default fixed it.
Il 15/11/2015 23:41, James Teh ha scritto:

**Comment by jcsteh** [comment]
Hmm. I'd really prefer it weren't linked to the theme. I can fix this if i search for the string "I/O" instead of relying on a specific position. I'm not a big fan of relying on language specific text either, but it's probably better than relying on the theme. Low priority, though, since there's a workaround which doesn't seem unreasonable.
