### ISSUE TITLE
Translation of Osara to German Language

### ISSUE THREAD

**Issue by michaelvogt33** [jcsteh/osara#500]
Initial translation to german language done (osara 021.1pre-493).
Crowdin username: michael.vogt
Langpack filename: DE_(+SWS).ReaperLangPack

**Comment by jcsteh** [comment]
Thanks. Crowdin invite sent. Once you accept, you can [go here to manage your translation](https://crowdin.com/translate/osara/4/en-de). if you use Poedit, you can sync using that. Alternatively, you can go to the link above and press control+insert (twice if you're running NVDA) to upload a .po file.

**Comment by michaelvogt33** [comment]
German translation completed at https://crowdin.com/translate/osara/4/en-de - ready to publish with next osara release.
(hint for other osara translators: it is possible to import a translation file to crowdin (message "imported successfull"), but the imported translations are not applied to the source strings (maybe if there are differences of amount of translated items and amount of items to translate available at crowdin project (version differences.))
