### ISSUE TITLE
Make Osara's context menu actions work in track IO dialog

### ISSUE THREAD

**Issue by pitermach** [jcsteh/osara#503]
Long story short I got a new keyboard that no longer has an applications key. I didn't think it would be too much of a problem because Osara has the 3 actions to trigger menus, and it wasn't until today when I wanted to change the destination channel for a send, and found that the actions don't work either on Windows or Mac. On the Windows side, Shift+F10 does open a menu, but it just has a "Close window" option so isn't particularly helpful.

This is less of an issue on Mac, because the VoiceOver cursor will happily reach the on-screen controls to set the destination channels. On Windows this seems to be impossible with NVDA object navigation. I was able to reach these controls with ZDSR's screen review, but 95% of Osara users are going to be either on NVDA and JAWs so I think this issue is important.

**Comment by jcsteh** [comment]
I can't reproduce the problem with shift+f10. Like with the applications
key (as documented in the readme), you have to press it while focused on
the Delete button for the send. If I do that, I get the correct menu.

**Comment by pitermach** [comment]
Never mind, blame this one on user error. I just updated Osara and it works perfectly. Should have probably done that before opening an issue. ☺️
