### ISSUE TITLE
A windo rappot position to open it when i launche custom action containe this osara rapport 

### ISSUE THREAD

**Issue by vigi71** [jcsteh/osara#504]
Hello since the last updates I have a window which displays the cursor reports that I had introduced in custom action which opens when I run some of these actions it is very annoying would you have a solution for me if it you like

**Comment by vigi71** [comment]
hey see that when i launch personnal action custom contain rapport osara action https://zupimages.net/up/21/13/ud37.gif

**Comment by jcsteh** [comment]
I'm totally blind, so I can't see screenshots. I totally understand English is challenging for you, but I'm afraid we won't be able to progress this without a full explanation. What custom action are you trying to use and what happens exactly?

**Comment by vigi71** [comment]
i create several custom actions ex create a 4 bare loop area at the start of the project. this custon action contains several actions including track item selection report. When I run these actions a window opens to display in text the result of the track item selection report action placed in this custom action.

**Comment by jcsteh** [comment]
Ah, I think I understand. My guess is that you are running the report selection action twice. Running it twice quickly will cause it to report the info in a message window for review. It's not useful to run it twice in a custom action, so you should only run it once. It might be helpful if you could provide the list of actions that your custom action runs.

**Comment by vigi71** [comment]
Ok I understood I have to forget this action because I do not know what at the time it only worked like that. I will resume these few actions thank you very much
