### ISSUE TITLE
OSARA on off

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#513]
Hi James and everyone!
        For months I have been dating a sound engineer who works in the international field, he is in very important situations.
        I tell you this because he is a Black Rooster beta tester, great plugins for mixing and mastering.
        With Gianluca Apollaro we described the world of OSARA with NVDA and Reaper and he was very fascinated by how we use Reaper; think that he now has a Reaper portable with OSARA and tests it with NVDA.
        He is very willing to test the Black Rooster not only for the company but also for OSARA and asked me if it would be possible to fully activate or deactivate OSARA with one action.
        In my opinion it is a great opportunity, we are talking about a sound engineer who lives in London, has worked with Dua Lipa and other excellent names, makes audio books, TV series and has sampled brass for the BBC plugin.
        Yesterday while he was testing OSARA with Black Rooster plugins he needed to deactivate or activate OSARA, would it be possible to develop an action for this?
        I wanted to tell you, it is not an advertisement, that the Black Rooster have a very convenient license that can be used without limits in all computers and not only, my license can also be used without limits by another person without limits.
        The license is a serial number that can also be put offline without any kind of problem.
        Basically it's the license I always wanted for other plugins.
        Sincere greetings!

**Comment by Lo-lo78** [comment]
Maybe there is no need to specify it!
Obviously OSARA from on off should also be from off to on.
Greetings!

**Comment by ScottChesworth** [comment]
This has been requested before. So far as I'm aware, there's no elegant way to implement it.
Can your guy just run OSARA in Reaper portable when testing? If he unchecks "Check for multiple instances when launching" in the General category of Reaper Prefs for both copies, then he'll be able to run them simultaneously and just switch back and forth as needed. He can also copy over his reaper.ini configuration file into the root of the portable copy to get an exact mirror of his preferences in one shot.

**Comment by Lo-lo78** [comment]
Ahahha!
Ok, sorry for my English, he's a friend! I'm still a big lover of women! 
(Rofl) Yes I had thought about this possibility. It would have been more 
convenient to be able to activate or deactivate OSARA ... Thanks and 
regards!

**Comment by jcsteh** [comment]
Actually, this would be fairly trivial to implement. However, it doesn't make any sense from a UX perspective.

If you don't want screen reader output, mute your screen reader. I don't follow why OSARA output is a specific exception here. That's like saying "I want to read the UI of a text editor, but not read the text I'm editing". It also opens up a bunch of questions like: should we also prevent OSARA dialogs from speaking? Should we prevent other REAPER dialogs from speaking? If not, why not?

**Comment by jcsteh** [comment]
To be clear, there are obvious use cases for not reporting certain things; e.g. not reporting cursor movement during playback or not reporting transport changes. We already have options for those. However, the use cases for generally silencing just OSARA output (but no other part of the UI) are far from clear to me.

**Comment by jcsteh** [comment]
Okay, but what is the use case for getting feedback from menus and dialogs but not item navigation? Why is item navigation "special"?

Let's figure out the use cases and justifications first before we figure out the UX. Otherwise, it's bound to be suboptimal.

**Comment by ScottChesworth** [comment]
I think perhaps I could've been more emphatic. I'd love you almost as much as @Lo-lo78 loves women. :)

**Comment by jcsteh** [comment]
Now we're getting somewhere. So we're specifically concerned about item navigation during playback. In that case, should we just tie this to the existing "Report time movement during playback/recording" setting (and perhaps rename it to "Report time/item movement during playback/recording")? When you're stopped, item navigation would get reported, but when you're playing, it wouldn't.

This also makes me wonder whether it's really worth speaking take names at all or just numbers.

**Comment by GarthHum** [comment]
Item navigation was the main use case for me, as Scot explained. Even with very short item names, it’s too verbose to hear the short items that I will be trying to hunt down in a long dialog track. 
I think there is still value in having item names spoken if items are being reported. 
I’d be happy with tying it to the existing action as proposed. 
The prior bug was just the best solution to hand.

**Comment by ScottChesworth** [comment]
> should we just tie this to the existing "Report time movement during playback/recording" setting (and perhaps rename it to "Report time/item movement during playback/recording")?
> 
 That'd work like a charm for me.
> This also makes me wonder whether it's really worth speaking take names at all or just numbers.
> 
Definitely still worth speaking take names. They can be tweaked in Preferences to be super useful, it's just kinda buried, so most folk don't know to do that.
