### ISSUE TITLE
Mac OS X Build is Broken: Where is file 'WDL/db2val.h'?

### ISSUE THREAD

**Issue by cohler** [jcsteh/osara#514]
Build on Mac OS X does not work at present.

Where is this missing file?

```
src/controlSurface.cpp:12:10: fatal error: 'WDL/db2val.h' file not found
#include <WDL/db2val.h>

```

**Comment by jcsteh** [comment]
Did you follow the instructions in the "Getting the Source code" section of the readme?

> `git clone --recursive https://github.com/jcsteh/osara.git`

Note the `--recursive`. If you don't do that, you won't get submodules, which is where WDL (and other dependencies) come from.

If you did omit `--recursive` when cloning, you can fix this with:

`git submodule update --init`

**Comment by cohler** [comment]
Hi James,

That's only one of about 10 problems with the install procedure which is
listed on the main OSARA web page  at https://osara.reaperaccessibility.com/

Here is a summary of all the many problems with the Mac install procedure.
I haven't tried the PC procedure yet, but evidently, it also doesn't work.

> Dependencies
> To build OSARA, you will need:
>
>    - Mac only: Either the command line developer tools
>    <https://developer.apple.com/library/ios/technotes/tn2339/_index.html> or
>    Xcode 12.3:
>
> Xcode 12.3 is only usable on Mac OS X 10.15.4 or later (i.e. largely
useless), because most people are not running 10.15. Much more useful to
specify versions here that most people are using like Xcode 10.1 etc...

>
>    - You can download Xcode from the Mac App Store
>    <https://apps.apple.com/us/app/xcode/id497799835?ls=1&mt=12>.
>
> No you cannot. The ONLY thing available from the Mac App Store is 12.3,
which as I've pointed out above is largely useless.

>
>    - Python, version 3.7 or later:
>
> I'm not certain this is correct. I first installed Python 3.9 directly
from the Python website, but then reinstalled using brew.

>
>    - This is needed by SCons.
>
> Yes.

>
>    - Download Python <https://www.python.org/downloads/>
>
> No. Better to install with "brew install python"

>
>    - SCons <https://www.scons.org/>, version 3.0.4 or later:
>
> Yes.

>
>    - Once Python is installed, you should be able to install SCons by
>    simply running this at the command line: pip install scons
>
> No you need to type "pip3 install scons"

How to Build
> To build OSARA, from a command prompt, simply change to the OSARA checkout
> directory and run scons. The resulting installer can be found in the
> installer directory.


The included file "archBuild_sconscript" needs to first be modified as
follows. Comment out the line that has both -arch x86_64 and -arch arm64.
That is incorrect syntax and results in it always trying to build an arm64
version which produces errors on non ARM systems (i.e. MOST systems). Then
the correct directory for -isysroot is noted below.

 coreFlags = ("-mmacosx-version-min=10.7 -stdlib=libc++ "
# "-arch x86_64 -arch arm64 "
"-arch x86_64 "
"-isysroot $xcodeDevDir/SDKs/MacOSX.sdk")


Jonathan Cohler
***@***.***
http://jonathancohler.com/

**Comment by ScottChesworth** [comment]
Just FYI @cohler, the Windows build issue I was having yesterday has already been resolved by #2bff88b

**Comment by jcsteh** [comment]
If this isn't a result of missing submodules as you suggested in https://github.com/jcsteh/osara/issues/515#issuecomment-838406356, please provide the full output from scons. Also, do you have the file include/WDL/WDL/db2val.h in your osara checkout?

**Comment by cohler** [comment]
Hi James,

Don't appreciate your nonsense about "toxic attitude". Stick to the facts.
I also work on a million things for free in my spare time. Like creating
the first truly accessible VI classical music editor.

Now back to the facts.

Anyone who wants to build software that runs natively on Apple silicon has
> to use Xcode 12.


Incorrect. The VAST majority of the installed Mac user base is NOT on M1
and won't be for quite some time.

As for the "pip" vs "pip3", it's exactly as I stated. When you install
python, the "pip" command is NOT defined. You need to use "pip3" or you
have to specially define the "pip" command yourself. In any case, the
instructions are incorrect.

If you have Xcode 12, it results in a build for both Intel and ARM64, even
> if you're building on an Intel system. Of course, that's not going to work
> on Xcode earlier than 12, but see above regarding the need for us to
> support Apple silicon.
>
The instructions on the website DO NOT say that Xcode 12 is a requirement.
Indeed, it states the precise opposite and says you can also use Command
Line Tools, which is what the vast majority of Apple Developers and users
do.

In any case, the instructions on the website are CLEARLY incorrect.
Precisely as I have documented. And they need to be updated.

Best,
Jonathan

Jonathan Cohler
***@***.***
http://jonathancohler.com/

<http://jonathancohler.com/> ***@***.***>
<https://facebook.com/J.Cohler> <https://twitter.com/cohler>
<https://youtube.com/cohler59> <https://instagram.com/JonathanCohler>


Video: Cohler • Weber <https://www.youtube.com/watch?v=rUVBVn8S1N4>
Video: Bozza Bucolique <https://www.youtube.com/watch?v=ptnkmhfw5sw>
Video: Schumann Intermezzo <https://www.youtube.com/watch?v=m3uaW0D5tFk>
Video: McAllister Black Dog <https://www.youtube.com/watch?v=v4XVow4gT-0>

*This message (including any attachments) may contain confidential,
proprietary, privileged and/or private information. The information is
intended to be for the private use of the individual or entity designated
above. If you are not the intended recipient of this message, please notify
the sender immediately, and delete the message and any attachments. Any
disclosure, reproduction, distribution or other use of this message or any
attachments by an individual or entity other than the intended recipient is
prohibited. *

**Comment by jcsteh** [comment]
> Anyone who wants to build software that runs natively on Apple silicon has
> to use Xcode 12.
> Incorrect. The VAST majority of the installed Mac user base is NOT on M1 and won't be for quite some time.

That might be true, but those users who *are* on M1 and want to run REAPER natively need an ARM64 build. That requires Xcode 12. This was done per user request.

> As for the "pip" vs "pip3", it's exactly as I stated. When you install python, the "pip" command is NOT defined. You need to use "pip3"

Is that also true for the official (not Homebrew) Python?

> The instructions on the website DO NOT say that Xcode 12 is a requirement. Indeed, it states the precise opposite and says you can also use Command Line Tools, which is what the vast majority of Apple Developers and users do.

Confusingly, the Apple article about command line tools says they come with Xcode, but you can also download them separately. It doesn't say what SDK they include, etc. It's probably easiest to just drop mention of them altogether.

> The WDL issue was a result of missing submodules, but I solved that early on. Again, the instructions on the website under the title "Dependencies" mention nothing about submodules.

No, they don't, because the instructions for getting the source clearly state to add the `--recursive` option, which will fetch those submodules automatically.

**Comment by cohler** [comment]
>
> Anyone who wants to build software that runs natively on Apple silicon has
> to use Xcode 12.
> Incorrect. The VAST majority of the installed Mac user base is NOT on M1
> and won't be for quite some time.
>
> That might be true, but those users who *are* on M1 and want to run
> REAPER natively need an ARM64 build. That requires Xcode 12. This was done
> per user request.
>
That's fine. There's nothing wrong with including information about M1
build procedure, but excluding and not even mentioning the correct build
procedure for the VAST MAJORITY of Mac users is a big problem. Furthermore,
NOTHING in the build procedure says "THIS IS ONLY FOR ARM64 Macs" or only
for 10.15+ etc... So as I said, once again, the build procedure ON THE
WEBSITE is incorrect and DOES NOT, WILL NOT, and CANNOT work for the VAST
MAJORITY of Macintosh developers and users who are not on ARM Macs and not
running 10.15+ without the modifications that I enumerated.

> As for the "pip" vs "pip3", it's exactly as I stated. When you install
> python, the "pip" command is NOT defined. You need to use "pip3"
>
> Is that also true for the official (not Homebrew) Python?
>
Yes.

> The instructions on the website DO NOT say that Xcode 12 is a requirement.
> Indeed, it states the precise opposite and says you can also use Command
> Line Tools, which is what the vast majority of Apple Developers and users
> do.
>
> Confusingly, the Apple article about command line tools says they come
> with Xcode, but you can also download them separately. It doesn't say what
> SDK they include, etc. It's probably easiest to just drop mention of them
> altogether.
>
No. It doesn't make the build procedure BETTER to provide LESS information.
Simply provide complete, correct information.

> The WDL issue was a result of missing submodules, but I solved that early
> on. Again, the instructions on the website under the title "Dependencies"
> mention nothing about submodules.
>
> No, they don't, because the instructions for getting the source clearly
> state to add the --recursive option, which will fetch those submodules
> automatically.
>
Yes, I see that now, and figured that out after a short while. But when you
have a headline in boldface "*Dependencies" *I would suggest you list the
MAJOR, FIRST and MOST IMPORTANT dependency under that headline somewhere,
or it will be missed by more people like me who expected to find all the
DEPENDENCIES there. This software depends on software written by other
people in other repositories. So that should be noted under Dependencies.
Simple enough.

Jonathan Cohler
***@***.***
http://jonathancohler.com/

<http://jonathancohler.com/> ***@***.***>
<https://facebook.com/J.Cohler> <https://twitter.com/cohler>
<https://youtube.com/cohler59> <https://instagram.com/JonathanCohler>


Video: Cohler • Weber <https://www.youtube.com/watch?v=rUVBVn8S1N4>
Video: Bozza Bucolique <https://www.youtube.com/watch?v=ptnkmhfw5sw>
Video: Schumann Intermezzo <https://www.youtube.com/watch?v=m3uaW0D5tFk>
Video: McAllister Black Dog <https://www.youtube.com/watch?v=v4XVow4gT-0>

*This message (including any attachments) may contain confidential,
proprietary, privileged and/or private information. The information is
intended to be for the private use of the individual or entity designated
above. If you are not the intended recipient of this message, please notify
the sender immediately, and delete the message and any attachments. Any
disclosure, reproduction, distribution or other use of this message or any
attachments by an individual or entity other than the intended recipient is
prohibited. *

**Comment by cohler** [comment]
>
> There's nothing wrong with including information about M1 build procedure,
> but excluding and not even mentioning the correct build procedure for the
> VAST MAJORITY of Mac users is a big problem.
>
> Currently, there is no correct build procedure for Mac users who can't run
> Xcode 12.3. Your workarounds will work right now, but I can't guarantee
> they won't break in future. I personally am not able to put the time into
> maintaining proper support for multiple Xcode versions.
>
Of course there IS a correct build procedure. Namely, the one I specified
in detail. Furthermore, if you are going to publish only one procedure,
then that should be the one that reaches 99% of the universe instead of one
for the 1%. In any case, if you simply publish the information I already
gave you, it would VASTLY improve the situation.

> No. It doesn't make the build procedure BETTER to provide LESS
> information. Simply provide complete, correct information.
>
> I'm dropping mention of command line tools because it seems you can't
> properly build OSARA with them. I'm making the Xcode 12.3 requirement
> absolute. This will cause problems for users who can't run Xcode 12.3, but
> reduces potential confusion.
>
Incorrect. Repeating INCORRECT statements over and over again doesn't make
them any more true. You CAN build OSARA with Command Line Tools, JUST AS I
DID!

Jonathan Cohler
***@***.***
http://jonathancohler.com/

<http://jonathancohler.com/> ***@***.***>
<https://facebook.com/J.Cohler> <https://twitter.com/cohler>
<https://youtube.com/cohler59> <https://instagram.com/JonathanCohler>


Video: Cohler • Weber <https://www.youtube.com/watch?v=rUVBVn8S1N4>
Video: Bozza Bucolique <https://www.youtube.com/watch?v=ptnkmhfw5sw>
Video: Schumann Intermezzo <https://www.youtube.com/watch?v=m3uaW0D5tFk>
Video: McAllister Black Dog <https://www.youtube.com/watch?v=v4XVow4gT-0>

*This message (including any attachments) may contain confidential,
proprietary, privileged and/or private information. The information is
intended to be for the private use of the individual or entity designated
above. If you are not the intended recipient of this message, please notify
the sender immediately, and delete the message and any attachments. Any
disclosure, reproduction, distribution or other use of this message or any
attachments by an individual or entity other than the intended recipient is
prohibited. *

**Comment by jcsteh** [comment]
> Of course there IS a correct build procedure. Namely, the one I specified in detail.

Hacking source files to get it to build isn't something I want to officially support, especially because it's likely to break going forward and then we'll be back where we started.

> Furthermore, if you are going to publish only one procedure, then that should be the one that reaches 99% of the universe instead of one for the 1%.

Since you claim to be only interested in the facts, note that [StatCounter suggests that 68.57% of Mac OS users run Mac OS 10.15](https://gs.statcounter.com/macos-version-market-share/desktop/worldwide). Coupled with the [tens of billions in annual Mac sales](https://www.macrumors.com/2020/10/30/apple-says-strong-mac-sales-led-by-macbook-pro/), even allowing for a significant error margin, that indicates that your 99%/1% figure is wildly incorrect. Also, OSARA is hardly alone in depending on Xcode 12 for building. Firefox and Chrome, which are far from obscure applications, both require Xcode 12, probably because they too need to support users on Apple silicon.

In any case, I've made some updates to the readme to make the Xcode 12.3 requirement clearer, fixed the instructions for installing scons and added an additional note about submodules for extra clarity. I don't think any further discussion here is constructive, since I don't think we're going to arrive at a mutually satisfactory conclusion.

**Comment by jcsteh** [comment]
> Wrong again. Those market numbers you quote are CURRENT sales NOT installed base.

The StatCounter number is install base. The sales number is indicative that there are a significant number of users using more recent versions of Mac OS, since new Macs ship with the most recent version at time of shipping.

> “Hacking” a source file aka correcting an INCORRECT install file that doesn’t work!!

It is correct according to the specified build requirements, which are Xcode 12.3 or later.

> attempting lame, counterfactual excursions into nonsense land and wasting everyone’s time?

You don't appreciate having your toxic attitude called out, but you continue to demonstrate it.

At the end of the day, your (paid) product depends on (free) OSARA to provide its accessibility. Given your attitude, I have no interest in discussing anything further with you, so please don't expect any help from me going forward. I am closing this discussion to further comments.
