### ISSUE TITLE
unable to build on Windows, SCons transcript enclosed

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#515]
I've been able to build OSARA from source here for a fair while. So far as I'm aware, nothing has changed about my local environment, but it's broke, even with a fresh recursive clone and cleaned SCons cache. Anyone got any ideas based on this SCons output?

scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
Creating 'build\x86\buildVersion.h'
cl /Fobuild\x86\controlSurface.obj /c src\controlSurface.cpp /TP /EHsc /std:c++latest /W3 /WX /wd4819 /nologo /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
controlSurface.cpp
cl /Fobuild\x86\dictionary.obj /c include\tinygettext\src\dictionary.cpp /TP /EHsc /std:c++latest /W3 /WX /wd4819 /nologo /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
dictionary.cpp
cl /Fobuild\x86\envelopeCommands.obj /c src\envelopeCommands.cpp /TP /EHsc /std:c++latest /W3 /WX /wd4819 /nologo /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
envelopeCommands.cpp
cl /Fobuild\x86\exports.obj /c src\exports.cpp /TP /EHsc /std:c++latest /W3 /WX /wd4819 /nologo /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
exports.cpp
cl /Fobuild\x86\format.obj /c include\fmt\src\format.cc /TP /EHsc /std:c++latest /W3 /WX /wd4819 /nologo /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
format.cc
cl /Fobuild\x86\fxChain.obj /c src\fxChain.cpp /TP /EHsc /std:c++latest /W3 /WX /wd4819 /nologo /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
fxChain.cpp
cl /Fobuild\x86\language.obj /c include\tinygettext\src\language.cpp /TP /EHsc /std:c++latest /W3 /WX /wd4819 /nologo /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
language.cpp
cl /Fobuild\x86\log.obj /c include\tinygettext\src\log.cpp /TP /EHsc /std:c++latest /W3 /WX /wd4819 /nologo /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
log.cpp
cl /Fobuild\x86\midiEditorCommands.obj /c src\midiEditorCommands.cpp /TP /EHsc /std:c++latest /W3 /WX /wd4819 /nologo /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
midiEditorCommands.cpp
cl /Fobuild\x86\os.obj /c include\fmt\src\os.cc /TP /EHsc /std:c++latest /W3 /WX /wd4819 /nologo /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
os.cc
cl /Fobuild\x86\paramsUi.obj /c src\paramsUi.cpp /TP /EHsc /std:c++latest /W3 /WX /wd4819 /nologo /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
paramsUi.cpp
cl /Fobuild\x86\peakWatcher.obj /c src\peakWatcher.cpp /TP /EHsc /std:c++latest /W3 /WX /wd4819 /nologo /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
peakWatcher.cpp
cl /Fobuild\x86\plural_forms.obj /c include\tinygettext\src\plural_forms.cpp /TP /EHsc /std:c++latest /W3 /WX /wd4819 /nologo /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
plural_forms.cpp
cl /Fobuild\x86\po_parser.obj /c include\tinygettext\src\po_parser.cpp /TP /EHsc /std:c++latest /W3 /WX /wd4819 /nologo /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
po_parser.cpp
include\tinygettext\src\po_parser.cpp(338): error C2220: warning treated as error - no 'object' file generated
include\tinygettext\src\po_parser.cpp(338): warning C4309: 'static_cast': truncation of constant value
include\tinygettext\src\po_parser.cpp(339): warning C4309: 'static_cast': truncation of constant value
include\tinygettext\src\po_parser.cpp(340): warning C4309: 'static_cast': truncation of constant value
scons: *** [build\x86\po_parser.obj] Error 2
scons: building terminated because of errors.

C:\Users\Scott\osara>scons --version
SCons by Steven Knight et al.:
        SCons: v4.1.0.post1.dc58c175da659d6c0bb3e049ba56fb42e77546cd, 2021-01-20 04:32:28, by bdbaddog on ProDog2020
        SCons path: ['c:\\users\\scott\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\SCons']

**Comment by cohler** [comment]
No that is not correct.

Jonathan Cohler
***@***.***
http://jonathancohler.com/

<http://jonathancohler.com/> ***@***.***>
<https://facebook.com/J.Cohler> <https://twitter.com/cohler>
<https://youtube.com/cohler59> <https://instagram.com/JonathanCohler>


Video: Cohler • Weber <https://www.youtube.com/watch?v=rUVBVn8S1N4>
Video: Bozza Bucolique <https://www.youtube.com/watch?v=ptnkmhfw5sw>
Video: Schumann Intermezzo <https://www.youtube.com/watch?v=m3uaW0D5tFk>
Video: McAllister Black Dog <https://www.youtube.com/watch?v=v4XVow4gT-0>

*This message (including any attachments) may contain confidential,
proprietary, privileged and/or private information. The information is
intended to be for the private use of the individual or entity designated
above. If you are not the intended recipient of this message, please notify
the sender immediately, and delete the message and any attachments. Any
disclosure, reproduction, distribution or other use of this message or any
attachments by an individual or entity other than the intended recipient is
prohibited. *
