### ISSUE TITLE
Osara feedback when pasting might be improved

### ISSUE THREAD

**Issue by ptorpey** [jcsteh/osara#516]
Scott suggested that I bring this issue over to GITHub.  with the thought that Osara's feedback might be more descriptive when pasting items.  I was confused by Osara's feedback when I selected, copied, and pasted items and Osara said that an extra track was created.
 
Here is the scenario that I've run into many times and (thanks to Scott) just figured out what was really going on:
1.	I have a multi track project.
2.	I make a time selection using the left and right bracket.
3.	I hit alt+shift+A to select the items within the time selection on the track that has focus or is selected.  Osara announces something like “4 items selected”.
4.	I hit control+shift+C (smart copy) to copy the selected items within the time selection.  Osara correctly announces “4 items copied”.
5.	Now if I hit control+V to paste the items, Osara announces “4 items pasted” as it should and this actually happens correctly.
6.	Problem: If instead of the last step I arrow to another track and perform the paste with control+V, then Osara announces “1 track pasted” and, indeed, an additional track appears in my project.  This feedback is confusing since, presumably, I only copied items but I am told that a track has been copied.

Here is Scott's explanation as to what is going on:
Essentially, when an item selection spans multiple tracks, Reaper expects you to paste onto the topmost track where you want the items that are on the clipboard to land. the extra tracks are being added because there's not enough tracks below where you've pasted for the vertical spacing of the items on the clipboard to be maintained. You could verify that behaviour by pasting higher up in the track list, and then you'd hear the solely item-based report you were expecting.

**Comment by ScottChesworth** [comment]
@jcsteh, the best UX I can think of for more descriptive reporting would be something like:
"<conten from clipboard> and <extra stuff> pasted".
That, in combination with knowing how track spacing works should at least clear up the confusion that @ptorpey was experiencing.
Any thoughts?

**Comment by GarthHum** [comment]
How are you proposing this is changed? Currently the feedback about the one extra track being added is possibly confusing however it is also an excellent indication that you’ve done something unintentional. . 
Are you wanting additional feedback about not only the number of items but also the tracks on which they are being pasted?

**Comment by ScottChesworth** [comment]
> How are you proposing this is changed?
>
The comment right above yours lays that out, me old cobber. :)
Right now, the item related report is being replaced by the report of additional track or tracks being added. That's the specific thing to focus on I reckon.
Ideally, speech would report both things that've occurred when pasting. That way, we'd have confirmation that the contents of the clipboard have been pasted as expected, but also we'd be made aware that something else has happened (something that will warrant closer investigation if we weren't anticipating hearing both reports).

**Comment by GarthHum** [comment]
Sounds good

**Comment by ptorpey** [comment]
Not being able to see the screen, the feedback from Osara about items being copied but tracks being pasted provided me no useful information when I occasionally had this issue occur.  Thus I knew something went wrong but couldn’t tell what went wrong.

 

Now that Scott has explained what is going on and what a sighted person can see is going on, perhaps some feedback like:

 

“items copied to tracks L through M and N additional tracks created to fit”

 

Something like that would indicate that the copying of items did not start with track 1 and let the user know that additional tracks had to be created to accommodate the shift of track position when copying.

 

--Pete

**Comment by jcsteh** [comment]
> The comment right above yours lays that out, me old cobber. :)

Are you sure about that? :) Your comment reads:

> @jcsteh, the best UX I can think of for more descriptive reporting would be something like:
> " and pasted".

How does " and pasted" clarify things?

**Comment by ScottChesworth** [comment]
> Are you sure about that? :)
> 
DOH! I enclosed dynamic parts of the text inside less than and greater than symbols trying to be a pro, and GitHub hid those bits to remind everyone that I'm not. Fixed now.

**Comment by jcsteh** [comment]
Heh, that's better.

Yeah, I was thinking along similar lines. Strictly speaking, we didn't "paste" a track, since it wasn't in the clipboard. Ideally, then, we might hear "4 items pasted, 1 track added". Unfortunately, this isn't possible because we don't actually know what was on the clipboard; we make this determination based on what changed.

That also makes me realise that this is going to be a problem when you paste tracks. When you paste tracks and those tracks contain items, you end up pasting items as well. OSARA can't reliably differentiate between these two cases.

Can you live with getting this tracks + items announcement when you paste tracks as well? For example, if you paste a track that contains 5 items, you'll get "1 track 5 items added". Note also that the order will always be the same: tracks, then items. So, in the earlier example, you'll get "1 track 4 items added".

Note that I've shifted to "added" here over pasted. I think that's more accurate, since we can't know what was on the clipboard vs what was added because the paste required it.

**Comment by jcsteh** [comment]
I'd point out that visually, you don't know what's on the clipboard either; you just see what changed.

**Comment by jcsteh** [comment]
> perhaps some feedback like: “items copied to tracks L through M and N additional tracks created to fit”

I don't think this is realistic from an implementation standpoint. I'd also argue that a sighted user doesn't know why the extra tracks were created either. They do see that items were pasted on earlier tracks and that a new track was created with some items, but they still have to understand why an additional track got created; it's not like they can see what's on their clipboard and how that overlaps with what got pasted.

**Comment by ScottChesworth** [comment]
> we don't actually know what was on the clipboard; we make this determination based on what changed.
> 
Could Cockos help us with knowing what's on the clipboard, I wonder? Happy to try my luck at requesting an addition to the API, I haven't asked Justin anything difficult for... oh... at least a week. :)

> Can you live with getting this tracks + items announcement when you paste tracks as well? For example, if you paste a track that contains 5 items, you'll get "1 track 5 items added". Note also that the order will always be the same: tracks, then items. So, in the earlier example, you'll get "1 track 4 items added".
> 
Sure. It's a bit more verbose, but if anything, it's clearer than what we currently report for folks who struggle to visualize the timeline mentally.

> Note that I've shifted to "added" here over pasted. I think that's more accurate, since we can't know what was on the clipboard vs what was added because the paste required it.
> 
Yep, makes sense.

**Comment by jcsteh** [comment]
> Could Cockos help us with knowing what's on the clipboard, I wonder? Happy to try my luck at requesting an addition to the API

Maybe, but I think it's hard to justify. As I said, sighted users don't really know what's on the clipboard either. Also, for all we know, whether you copy tracks or items across multiple tracks, REAPER may represent it the same way (a collection of items on tracks). I have no idea, but that's entirely possible.

**Comment by ptorpey** [comment]
Agreed about the fact that sighted users don’t see what is on the clipboard.

 

Also agree that using “added” instead of pasted gives much better feedback.

 

One thing that could help screen reader users better understand what might be going on is to notify them somehow that the pasting of items started at some track other than track #1.  Sighted users can easily see that their paste might have been shifted down relative to where they intended whereas this isn’t otherwise apparent to the person using a screen reader.  Don’t know how hard that would be to implement if folks think that would help.

 

In either case, using “added” rather than “pasted” and specifying both added/pasted items and tracks would probably go a long way to providing better feedback even if nothing else could be done.

 

--Pete

**Comment by jcsteh** [comment]
> One thing that could help screen reader users better understand what might be going on is to notify them somehow that the pasting of items started at some track other than track #1.

That's a tricky one. It'd certainly help when you intended to copy just items across multiple tracks. On the other hand, if you're pasting entire tracks (including all their items), that reporting is pretty redundant because it's intuitive that the paste always starts at the current track.

Let's start with the "2 tracks 5 items added" style report and maybe improve from there in future.

**Comment by ptorpey** [comment]
Let's start with the "2 tracks 5 items added" style report and maybe improve from there in future.

[PT] Sounds like a plan.

 

--Pete

**Comment by jcsteh** [comment]
> Note that I've shifted to "added" here over pasted.

Haha. Apparently, OSARA already says "added", not "pasted". Because I totally know my own code.

**Comment by jcsteh** [comment]
I notice no one corrected me... and you lot use this thing more than I do,
more's the pity.

**Comment by ScottChesworth** [comment]
> you lot use this thing more than I do
> 
Fair point. I use the thing so much here that often I don't consciously consider what it's saying anymore, it's just "sure, that felt like what I was expecting". I must be more careful to test in situ before commenting in these threads.
