### ISSUE TITLE
MIDI Editor Suggestion: Instead of Reporting How Many Notes Have Been Selected, Report How Many Events Have Been Selected

### ISSUE THREAD

**Issue by MatejGolian** [jcsteh/osara#521]
It's all in the title, really, but to clarify further, I think the changing of the feedback the pressing of CTRL + A results in could benefit from a little adjustment. The problem is that Osara doesn't take into account that CTRL + A (and related actions) don't just select notes, but all types of MIDI events. So, maybe reporting how many MIDI events have been selected would make more sense instead of just focusing on note events.

**Comment by ScottChesworth** [comment]
+1 from me in principal, but that change of feedback needs a bit of debate I reckon, because observation in the field suggests that beginner/intermediate users typically think of MIDI in terms of notes.
Would it be possible to segment the feedback, I wonder? Something like:
"2 notes and 3000 other events selected"

**Comment by MatejGolian** [comment]
@ScottChesworth, fine with me, but of course, whatever the community decides.

**Comment by leonardder** [comment]
I strongly second this issue as I actually found it really confusing that ctrl+a reported me selecting only notes, whereas I also selected the several control changes related to my sustain pedal.

**Comment by ScottChesworth** [comment]
Given that you know your way around the MIDI Editor code @leonardder, any chance you'd have time to take a shot at implementing this?

**Comment by leonardder** [comment]
> Given that you know your way around the MIDI Editor code @leonardder, any chance you'd have time to take a shot at implementing this?

Sure. #581 😉

**Comment by Lo-lo78** [comment]
Hi Leonard, that's ok!

👍
