### ISSUE TITLE
Opinions wanted: floating a change to our reporting order

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#528]
I reckon that the order we currently report information about tracks and items in could be made more productive.
As things stand, the report when navigating to a muted track might read something like this:
"3 Snare Top (SM57) muted 60 items" (for the purposes of this example I was behind the kit, hence more punches than Tyson :P).
With Reaper's default naming conventions in play (which is what the majority of people are using), navigating through items on that track to try and locate one that's muted would not be productive. A report might look like:
"27 03-Snare Top (SM57)-690616_2359.wav muted"
The rub is that I'm being told the take was captured just before midnight in mid June of 1969 before I'm able to asertane whether the item is muted.
I've dramatically cut back on verbosity here by rethinking those naming conventions, but still, most folk haven't, and Reaper's presentation of the convention is kinda nerdy, so it's understandable that new folk probably won't.

My proposition is that we change to reporting dynamic information about tracks and items (mute, solo, arm, phase etc) before tracks, and item reporting would fall in line with that.
Re-runs:
"3 muted Snare Top (SM57) 60 items"
"27 muted 03-Snare Top (SM57)-690616_2359.wav"

I think that in larger projects, this change would bring us a little closer to the sighted user's potential to scan.

@jcsteh, if this would be a hellish amount of work to implement, then just say no and I'll get back in my box.
If it's technically easy but tedious grunt work (adjusting function by function perhaps), I could probably handle it. More time with the code chasing things I'd like to see happen suits where I'm at in my learnings.

Thoughts?

**Comment by jcsteh** [comment]
What you're suggesting assumes that the state is more important to the user than the name. While I can understand why this might be true for items, I think this might be less of a clear certainty for tracks, where they are always explicitly named by the user or left unnamed.

That said, I don't have a strong opinion here and it isn't particularly difficult to implement, just a matter of moving stuff around. Track reporting is handled in the postGoToTrack function. Item reporting is handled in the moveToItem function (look under the comment that says `// Report the item.`)

**Comment by ScottChesworth** [comment]
> What you're suggesting assumes that the state is more important to the user than the name. While I can understand why this might be true for items, I think this might be less of a clear certainty for tracks
> 
My thinking is that it draws attention to state sooner, kinda like the audible version of noticing that a button is lit up, blinking or whatever as you scan through tracks. Once you've been working in a project for a while, chances are you're gonna be fairly familiar with the track order, so this would just help state to cut through more and prevent those few seconds where I'm tuning out track names I already know and waiting for information I want.
There is of course a strong argument of "use the report functions man, that's what they're for".
That's true, but with high track counts, if you're already pretty close to what you're looking for in the track list, often I find moving through tracks is a little quicker.
Let's wait and gauge feeling among the troops I guess. :)

> it isn't particularly difficult to implement, just a matter of moving stuff around. Track reporting is handled in the postGoToTrack function. Item reporting is handled in the moveToItem function
> 
Thanks! I'll probably whip up a test build at some point this week, need to get the ReadMe revamp squared away before noodling with this sorta thing though.

**Comment by leonardder** [comment]
Anything against making this an option? This way people can decide for themselves.

**Comment by jcsteh** [comment]
My only thing against it is that it becomes a very slippery slope. Do we
then have 7 billion options to reorder every piece of info in every message
that presents multiple pieces of info? :)

That said, as long as we can agree this is a common difference in workflow
and we won't allow this to start a "the order of everything must be
configurable" slide, I guess an option would be fine.

I don't think we're there yet, though. If the general consensus is that
state should come first (or at least that it wouldn't be harmful), I don't
think we need an option. Again, use cases/scenarios first, implementation
second.

**Comment by mattymc2** [comment]
I second the state first. With high track counts scanning through to find the track that is soloed or whatever can be time consuming  since the state is only reported if it’s active it only really affects the order if that track is muted or whatever.  Does that endnote make sense? I haven’t had a lot of sleep

**Comment by leonardder** [comment]
> If the general consensus is that state should come first (or at least that it wouldn't be harmful), I don't think we need an option. Again, use cases/scenarios first, implementation second.

I agree. In that case, I like the proposal to go for state first, that is, after the actual track number/item.

**Comment by GarthHum** [comment]
Totally support the state before track name proposal

**Comment by jcsteh** [comment]
This is a bit trickier than I initially anticipated.

For tracks, we currently report the folder state before the track; e.g.

1 open folder vocals muted 0 items

In this proposed new world, where should the folder state go?

1. 1 open folder muted vocals 0 items
2. 1 muted open folder vocals 0 items
3. 1 muted vocals open folder 0 items

I'm guessing option 2, but thought it worth checking.

**Comment by ptorpey** [comment]
Option #2 seems to make sense if all the tracks within the folder are muted.

 

Otherwise if it is just the first track that is muted one might want to hear option #1

 

I’ve never used folder so don’t know if the muting applies to everything within the folder.

 

--Pete

**Comment by ScottChesworth** [comment]
Option 2 makes sense here.

**Comment by jcsteh** [comment]
Okay. Locally, I have it so you get the following:

1 muted armed open folder vocals notes grouped 0 items free item positioning

- "notes" and "grouped" are still after the track name, as I figure they are less likely to be changed super often, in contrast to muted/armed which might change quite frequently.
- "free item positioning" is very unlikely to change once set, so I left it after the item count.

Thoughts?

For items, should the group number be reported before or after the name?

**Comment by Lo-lo78** [comment]
I'm for 2 with a change:

2 armed muted soloed open folder vocals 0 items

Greetings!

**Comment by ScottChesworth** [comment]
> * "notes" and "grouped" are still after the track name, as I figure they are less likely to be changed super often
> 
Makes sense, although I'd like to see those two aspects of the report switched if possible: grouping before notes.
Going on what I've seen of how grouping is being used in the wild, I reckon information about that is higher priority than the nudge to remind the user they've got notes.
> * "free item positioning" is very unlikely to change once set, so I left it after the item count.
> 
Yep agreed.
> Thoughts?
> 
How would you feel about arm going before track number?
If there's any state to make that exception for, it's probably arming, because of the potential impact of missing that detail. Putting "armed" before the track number would help the state stand out as the user scans through tracks, as there's no number that starts with that "ar" sound.
> For items, should the group number be reported before or after the name?
> 
Definitely before. Those default item names are a curse on productivity.

**Comment by jcsteh** [comment]
> How would you feel about arm going before track number?

One concern is that this could be pretty annoying with heavy use of Automatic record-arm when track selected. You'd basically always hear armed before the track number.

> Putting "armed" before the track number would help the state stand out as the user scans through tracks, as there's no number that starts with that "ar" sound.

That justification is very English centric. :) Granted, the majority of our users use OSARA in English, but I think justifying behaviour on that basis is sketchy.

**Comment by ScottChesworth** [comment]
Fair points. Scratch that idea.

**Comment by jcsteh** [comment]
> How would you feel about arm going before track number?

Although we're not moving armed before track number, I am moving it before muted and soloed at least.

**Comment by ScottChesworth** [comment]
Cool, thanks, that'll help.

**Comment by ScottChesworth** [comment]
Look at the snapshots page.
Is it a bird?
Is it a plane?
No, it's @jcsteh, crushing it again! :)

**Comment by mattymc2** [comment]
On my way to the studio to update this right now. So bloody excited. Thank you so much @jcsteh.

**Comment by ScottChesworth** [comment]
Reopening this because we've had some feedback come in via RWP that Jamie was on the money, the change is less than ideal for some folks who use auto-arm. They're requesting the check box to adjust positioning. To me it seems like a valid justification, but I'm probably not the poor bugger who'll implement it.
Thoughts?

**Comment by mattymc2** [comment]
Bloody sooks

**Comment by ScottChesworth** [comment]
I don't know what a sook is, but I'm gonna guess you're projecting. :)

**Comment by jcsteh** [comment]
A check box for what, though? All states or just arm? And if this is just about auto arm, can we just report armed after the track name only if it's auto armed, thus avoiding the need for a check box?

**Comment by ScottChesworth** [comment]
> if this is just about auto arm, can we just report armed after the track name only if it's auto armed, thus avoiding the need for a check box?
> 
Reporting arm in context of auto-arming being enabled is the only productive feedback I've seen so far, so yep, I reckon that'd do it.

**Comment by jcsteh** [comment]
> can we just report armed after the track name only if it's auto armed

API says no. :( We could do it with the state chunk, but we'd then end up with the performance problems we had trying to support solo defeat.

**Comment by ScottChesworth** [comment]
> API says no. :(
> 
Should I ask Justin to make API great again?

**Comment by jcsteh** [comment]
I asked. I figured we can spread the API request exasperation across two
people instead of just one. :)
