### ISSUE TITLE
Suggestions on Snapshots feature

### ISSUE THREAD

**Issue by c469591** [jcsteh/osara#532]
Hello everyone,
I would like to suggest that OSARa can read the name of Snapshots when switching Snapshots.

When I press
When Ctrl + Alt + 7 or Ctrl + Alt + 9,
Reading
My mix Snapshots1, my mix Snapshots2
Thank you!

**Comment by jcsteh** [comment]
This is a duplicate of #110. It isn't possible without changes to SWS.
