### ISSUE TITLE
Show performance meter window Not easy to handle with screen reader

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#536]
Hello,
I am using a slow CPU and I would need to check how much CPU, RAM and the consumption of plugins.
If you use the right plugins you can have a complex project even with slower computers.
Still cannot control the window of:
performance meter.
The action is:
Description: View: Show performance meter window; State: off; Command ID: 40240
It is very important to know how much Reaper consumes CPU.
This performance meter window is composed of two tables, one global, where it tells you how much Reaper takes of CPU, RAM, how many FX there are in the project and another with the single tracks, how much they consume CPU, FX.
Greetings!

**Comment by ScottChesworth** [comment]
Last I checked this was all information that's easily obtained using object navigation. Has that changed?

**Comment by Lo-lo78** [comment]
Yes, Scott, with NVDA you can partially read the window. It is possible 
to read the consumption of the CPU and RAM global and not of the single 
tracks. The window has two environments one global, for the whole 
project and another table for the single tracks. Tracks. The single 
track is not easy to use because NVDA reads the updated data every half 
second. The information changes very quickly, preventing the screen 
reader from reading what you are selecting.
Greetings!

**Comment by RDMurray** [comment]
I can't reproduce the problem here.  Object nav works fine in that dialog, even when the numbers are updating.  What version of Reaper and NVDA are you using @Lo-lo78?

**Comment by Lo-lo78** [comment]
Yes, with the object navigation of NVDA you can see the general values 
​​but the table of the individual tracks is updated every second and is 
not exactly intuitive to find.

There are two tabs, one of the master that gives the general values ​​of 
the project and another tab that gives the list of tracks but with the 
real-time update NVDA continuously reads the string.

It does not depend on OSARA but certainly on Reaper; to understand if 
this issue makes sense, perhaps it is better to report it to Cockos.

I'm with Reaper 6.45, OSARA Version: pr650-755,b9925b83, Windows 10 20H2 
(x64).


Greetings!Message ID: ***@***.***>

**Comment by Lo-lo78** [comment]
It's a screen reader problem.
If Cockos doesn't solve the problem I doubt OSARA can do anything.
