### ISSUE TITLE
Is it possible to pass directly to the OSARA: FX parameters to the plugin from the FX chain?

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#538]
Hello,
98% of the plugins are not accessible and I thought it would be convenient to add a plugin to the chain and go directly into the OSARA: FX parameters.
Guy:
Add FX to Track 2 Filter Dialog:
tal j 8;
VST3i: TAL-J-8 (TAL-Togu Audio Line) (6 out); after sending the effects I will have, with copy paste:
VST3i: TAL-J-8 (TAL-Togu Audio Line) (6 out)
VST3: FETISH (AnalogObsession)
I select the TAL and with the "P" or "shift + P" key you enter directly on FX parameters without doing "ESC" and then "P", look for the FX and then in the FX parameters ..
In this way you enter more quickly in the parameters of the plugin, then for the accessible ones you already do "F6".
Greetings!

**Comment by mattymc2** [comment]
This would actually be pretty cool. Especially when you have multiples of the same plug-in on a track it’s sometimes hard to know which plug-in you are editing with the parameters dialogue. Also it would be a lot quicker :-)

**Comment by jcsteh** [comment]
This might be possible, though I don't think it should use the p key because that would break navigation by letter in the FX list. We could perhaps use alt+p though. If alt+p gets swallowed by the FX chain dialog and not passed through to the main section, I'll have to intercept this key directly, which will mean we can't support this on Mac.

**Comment by ScottChesworth** [comment]
> I don't think it should use the p key because that would break navigation by letter in the FX list.
> 
Given that Reaper prefixes plug-in type anyway, is not being able to hit P in the FX chain list a big deal? I'd gladly lose being able to type P if it means it's easy to support on Mac.

**Comment by jcsteh** [comment]
That would make it harder to support on Mac, not easier. :)

**Comment by ScottChesworth** [comment]
> That would make it harder to support on Mac, not easier. :)
> 
Ah, oops. I wasn't here, you didn't see that. :)

**Comment by mattymc2** [comment]
Does it have to be P? I mean I know it should be consistent with reapers main window but that could be something else that works in both windows as well.
