### ISSUE TITLE
Is it possible to put Play / pause in the FX parameters?

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#542]
Hello,
excellent work on FX parameters done in recent months!
One important thing is missing:
the Play / Pause; can it be integrated in this OSARA window?
The shortcuts for example:
ctrl + shift + space,
shift + space,
alt + space but this has a windows 10 menu, not really important as a menu, you could use.
Greetings and thanks!

**Comment by ScottChesworth** [comment]
Control+Space already plays/stops in the Params dialog.
I'm not keen on the idea of taking over Alt+Space, since the Params dialog has a basic GUI and we have some low vis folk in the community who use it for visual cues.

**Comment by Lo-lo78** [comment]
Yes, alt + space is incorrect, I agree! 👍

**Comment by jcsteh** [comment]
The only way to do this would be to explicitly catch shift+space (or whatever) and call play/pause directly. It wouldn't be possible to customise this. It might also be weird for anyone who might have overridden space, shift+space, etc. in their key map. That said, I'm actually not sure what REAPER does if you override space in this case; I've never tested that. (The control+space behaviour in the OSARA Parameters dialog is REAPER behaviour, not OSARA.)

**Comment by RDMurray** [comment]
OSARA does pass certain keys to the main window from the parameters window, I don't know why control space changes to play/stop though.  It's the same in reaper dialogs.
@Lo-lo78  F1 is free, you could assign that to play/pause if you want.

**Comment by Lo-lo78** [comment]
Yes please!

👍

**Comment by RDMurray** [comment]
I wasn't suggesting assigning f1 in the official keymap, just that it is available for a custom assignment.

**Comment by Lo-lo78** [comment]
Hi, yes I understood it but I think that the OSARA project is not so 
useful. Perhaps the only reason to keep the issue could be to have a 
shortcut dedicated to the fx parameter. In this way we do not occupy a 
shortcut in the keymap . If I remember correctly I had suggested shift + 
space, however F1 is more than efficient!

**Comment by RDMurray** [comment]
Why don't you ask on rwp to see if there is a lot of support for a dedicated play pause key in the params dialog, and reopen this if you get a lot of support.

**Comment by jcsteh** [comment]
I was also told recently that this behaviour is inconsistent across Mac and
Windows. Apparently, in the Params dialog on Mac, control+space pauses
rather than stops. If true, I'm thinking it might be worth OSARA
implementing this itself to make it consistent. The question is which way
to go: control+space for stop and shift+space for pause or vice versa.
