### ISSUE TITLE
Critical bug with Osara in MIDI event editor

### ISSUE THREAD

**Issue by ElCrackLoko** [jcsteh/osara#545]
- [x] 👋Hello everyone! How's life going First hoping that it is good, but if we ask Osara I think she is a bit sad hehe.

After going through the figurative, let's get to the heart of the matter.
When the Midi event editor is opened from obviously Reaper, and CC carriles such as Chorus, Rever, Tremolo, etc. are added, and the following critical message starts to be manipulated with arrows, the following critical message appears, closing Reaper and deleting everything you have in your project if unfortunately you have not saved.
Microsoft Visual C ++ Runtime Library Dialog Error!

Program: C: \ Program Files \ REAPER (x64) \ reaper.exe

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

It should be noted that in the community where we handle Osara several users have reported the same bug to me and if you ask, yes, we have the complete collection of Microsoft Visual C ++ Redistributables Libraries, 2005-2008-2010-2012-2013-2015-2019
With Osara 2020 the error does not happen, only with 2021. I imagine that something must be there.
Even trying to replicate the error, it was enough to add a carril CC and move with arrows to give me the mentioned error. He gives other teammates the error when they select more than 2 CC carriles at the same time to eliminate. I would have liked to report the error much earlier, but between work and many things I had not given the time and also that I hardly use the MIDI event editor.
I hope and my message is understood, forgive my bad English.
Who wants to have a beer? Because I do. Or maybe a coffee, greetings from Ecuador brothers. To continue with this project.

**Comment by jcsteh** [comment]
That does sound nasty. It would be helpful if you could provide precise
steps to reproduce this, including the keys you pressed to create the
scenario and the keys you pressed to eventually cause the crash. Thanks.

>

**Comment by ElCrackLoko** [comment]
Hi bro! @jcsteh
Yes, as unpleasant as losing a project that you worked for hours for your girlfriend and then not being able to give her anything for the anniversary day 😁
But hey, after the bad joke I answer your question. Try to replicate the problem in the following way.
1. Open Reaper, record any midi, press Control Alt E and then Alt + 3 to go to the midi event view.
1.1. It has happened to me that quickly scrolling between events with the up and down arrows I get the error, but this may just be a universe thing. It's just pressing the down arrow as if stopping would make the world end jaja.
2. If you are still alive and Reaper has not died with your little Midi recording, replicate the error as follows. Select all the notes with Control A. Then press applications and add any CC carril (To be more feasible, add a multitude of CC carril, I recommend adding about 4 or 5)
Applications, down arrow to Insert Event, then Enter. 3 Arrows down to where it says Controller Change (CC) according to the translation. Then tab 3 times to what it says
Controller:
69 Sustain 2 (Pedal) (on / off)
This is where you can add CC by CC as you need. Just tabbing to the button that says add.
Once you have added 2, 3, 4 CC or whatever you want, click the OK button. Locate on the CC, give it Start control to select them all and give delete. Boom! Reaper will explode.
I hope I have made myself understood despite the language. There you tell me if the error happened to you, since as I mentioned, with Osara 2020 what was said does not happen.

**Comment by jcsteh** [comment]
I've just tried this and I can't reproduce it. :( Perhaps you could provide a simple REAPER project file with a MIDI item where this happens for you?

**Comment by ElCrackLoko** [comment]
A thousand apologies, it seems that this only happens to those of us who 
have the Spanish translation, I don't know if it's because of the 
template or maybe the Osara translation file; I just checked but with 
the default Reaper language, (English) and the error doesn't happen. I 
don't know what we're going to do. I am a happy man, but now I am not so 
happy.

--
(---El derecho al conocimiento no debe ser negado. Y no compartirlo debería ser un pecado)---

**Comment by jcsteh** [comment]
Okay. Let's diagnose. If you remove the OSARA Spanish translation file,
does the problem persist?

>

**Comment by ElCrackLoko** [comment]
I just did several tests and comment the following.
When deleting the language file es_mx.po the error persists with the 
current version of Osara.
By doing what one of the community members told me (Use an older version 
of Osara), in my case, I used the 2020.1pre-192,0004c85b from Thursday, 
September 3, 2020, even though I have the current translation template 
(Not Osara's obviously because Osara was not yet translated at that 
time) the error no longer happens.

--
(---El derecho al conocimiento no debe ser negado. Y no compartirlo debería ser un pecado)---

**Comment by ElCrackLoko** [comment]
Update: One of the members of the PMA community has just sent me the 
version of Osara that he uses with which the error also does not happen, 
which corresponds to 2020.1pre-201,8b652d72


--
(---El derecho al conocimiento no debe ser negado. Y no compartirlo debería ser un pecado)---

**Comment by jcsteh** [comment]
Are you using NVDA or JAWS? If NVDA, could you set your log level to input/output and provide the NVDA log showing you reproducing the problem?

**Comment by jcsteh** [comment]
Also, do you still get the crash if you switch to piano roll (alt+1) and
disable Options -> Note preview -> Preview notes when inserting or editing?
(My hunch is that this is where things are going wrong, though I don't know
why yet.)

>

**Comment by ElCrackLoko** [comment]
Hello. Sorry to answer so far, but I'll go on to answer the questions.
All of us who reported this bug use NVDA.
Currently with the last Osara update published on Friday July 2 (2021.1pre-573,42606289) I can no longer replicate the Bug, however, 2 people do keep happening, one of them was the one who originally reported the bug. She then she left that person's Log.
On disabling the options you mention in the Piano Roll (Alt + 1)
-> Note preview
-> Preview notes when inserting or editing?
Where do I find them? Since pressing Alt or Applications does not open any options menu, and when exploring the view menu of the Reaper menu bar, I also do not find anything similar, neither there nor in the options category.
I have asked the RPP project from the person who sent me the Log to replicate the error through his project to see what happens and if I am successful, I will attach it later as well.
Thanks for the predisposition, seriously. 
[nvda registro de entrada de Namdelo.log](https://github.com/jcsteh/osara/files/6759312/nvda.registro.de.entrada.de.Namdelo.log)

**Comment by ElCrackLoko** [comment]
* Update: I have gotten the RPP project from the person to whom and have been able to replicate the error with the latest version of Osara. In my case I have not even had to delete any CC, just hovering over a note gives the error. Here I leave my Log too. Remember that this happens with the most resentful version of Osara and that with the one reported, (the oldest) this does not happen. Also, it only happens with Reaper in Spanish, with the translation by Javier Robledo. It's all pretty confusing. 
[nvda-elcrackloko.log](https://github.com/jcsteh/osara/files/6759341/nvda-elcrackloko.log)
And since GitHub won't let me attach the RPP, I leave the direct link to my Google Drive.
https://drive.google.com/uc?id=1Br9Mz9AqGTVV9seGHHLsSzQyopptz9Yq&export=download

**Comment by jcsteh** [comment]
I was hoping the NVDA log might yield some useful info, but it seems all the info in the list view item is as I expected. Could you provide me a link to the REAPER language pack you're using please?

**Comment by ElCrackLoko** [comment]
Of course yes, with pleasure,
[here you have it](https://drive.google.com/uc?id=1ZtGvuD86vXTLisCL5Hn61vtEh52A6x7E&export=download)
Greetings and here we are at your command
