### ISSUE TITLE
OSARA on Windows stops speaking after closing Pianoteq 7.4's GUI.

### ISSUE THREAD

**Issue by kara-louise** [jcsteh/osara#547]
This will probably occur with other future plugins built using the new version of Juice with the accessibility additions.
Steps to reproduce:
1. Insert Pianoteq 7.4 on a track.
2. Press f6 to move focus to the plugin UI.
3. Tab round the UI.
4. Press escape to close the fx window.
5. Move to a different track. NVDA will say "pane".
6. Try pressing any other command where you'd expect speech and notice there isn't any.
Note that this will also occur if you just press escape to close the fx window without moving to the UI.
I'm running:
 OSARA version 2021.1pre-567,25d022cb
REAPER 6.29 64 bit
NVDA version 2020.4
Windows 10 Version 21H1 (OS Build 19043.1052).

**Comment by ScottChesworth** [comment]
This needs to be fixed by JUCE, not us. I've already made sure they're aware of it. For the time being, the workaround is to force the TCP window to redraw. I usually do that here by hitting Control+O then Escape.
