### ISSUE TITLE
Presentation of stats after dry run renders

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#550]
Visually, stats are presented in a table. However, table navigation isn't supported, so examining results isn't productive with a screen reader yet.
Is this something that OSARA can hack to tighten up, or what should I be asking Cockos for?

**Comment by jcsteh** [comment]
Tables are a really tricky thing, especially on Windows. The easiest thing to do would be to present the data in a web view, but I doubt Cockos will want to do that. I believe there's already API to get the stats from the last render, so we could have some OSARA action to format that into HTML. However, creating a web view is not something that can be done in a platform agnostic way. I could probably manage it on Windows, but I have no idea how on Mac nor the time to learn. I guess we could just spit out an HTML file and open it in the user's default browser (like REAPER keyboard shortcuts), but that's a pretty nasty UX for something like render stats.

**Comment by jcsteh** [comment]
Probably overthinking this. Cockos will want the table format and probably won't want to go HTML. However, if we're creating an OSARA action, I guess we can just spit out the text in whatever order we like, line by line.

**Comment by jcsteh** [comment]
Of course, that does mean coming up with a keyboard shortcut for bringing that up. I could probably detect the render window and have some key specific to that window on Windows, but not Mac.

**Comment by ScottChesworth** [comment]
Given that all of these options are tricky to implement cross platform though, doesn't it make more sense for Cockos to format the information in a friendlier fashion before you attempt any of this? If so, what would you suggest we ask for? My thinking is that we're coming in nice and early before the majority of users have had chance to get attached to the way things are.

**Comment by jcsteh** [comment]
The thing about the tabular format is that it's nice and concise for sightlings. Anything else that would be readable to us in plain text would be far less concise. Of course, it's entirely possible to make a table accessible, but only really with a web view if you want it to work well across the various screen readers.

You could try asking Cockos to do the table in a web view, but I don't think they're going to like it.

**Comment by pitermach** [comment]
How about asking Cockos to turn that text field into a list view like the SWS loudness tools work now? I don't know how much of an impact it might have on sighted people, but in theory it would keep the tabular format while making it more accessible for us.

**Comment by jcsteh** [comment]
If I recall correctly, the info is presented horizontally, not vertically; i.e. there are only two rows. That's not condusive to a list view, where items are rows, not columns. If it were just a two column plain text table, that would probably be fine for screen reader users already.

I think the best course of action might be to start a discussion with Cockos and see what they'd be willing to do, giving them a couple  options as starting points:

1. Present the info in text vertically rather than horizontally. That would be the simplest.
2. Present it in a table in a web view.

**Comment by ScottChesworth** [comment]
I've floated these proposals to Cockos and CC'd @jcsteh in, just in case they ask literally anything about the technical side of this...

**Comment by Lo-lo78** [comment]
Hi, you could think of a list, for example:

SysListView32.

It is the same list as the action list.

Greetings!

**Comment by ScottChesworth** [comment]
Cockos have fixed us up with the ability to open stats in the default browser, and I haven't seen anyone pushing for change since, so closing this.
