### ISSUE TITLE
Replace existing hotkey config or add new hotkey items from osara's update package instead of replace the keyboard configuration file by compare two files.

### ISSUE THREAD

**Issue by vgjh2005** [jcsteh/osara#551]
Hi Jteh:
Is it any possible to compare local key configuration and osara's key configuration to decide how to process the key change?
I think:
When user is sure to update hotkey from the installation, we could use the different way to deal with those situations.
1. If local hotkey config include hotkey items that are not in osara, keep them there.
2. If the same hotkey item has the different hotkey config, import osara's config.
3. If osara include new key items that aren't in the local key config,, import them.
4. However, show a dialog to decide which key item should be importted may be a good idea across to install procedure bassed on above 1 through 3.
5. certainly, We also could set some quick selection for user, for example: select all, deselect all, smart selection.
Thanks!

**Comment by jcsteh** [comment]
I don't think this is possible. One user's idea of intuitive here would be bad for some other user. Also, we have no idea what the values in the key map mean outside of REAPER, so displaying a dialog to resolve conflicts isn't possible.
