### ISSUE TITLE
fx parameters dialog closing after losing focus

### ISSUE THREAD

**Issue by ns-studios** [jcsteh/osara#556]
Reaper 6.32, Osara 2021.1pre-580,a72d78f7:
If the open fx parameters dialog loses focus (e.g., alt+tab), it closes, which means that you have to reopen the dialog every time you leave the window, which can be quite inconvenient.

**Comment by jcsteh** [comment]
This was a necessary sacrifice to allow function keys, etc. (e.g. mute, solo) to be passed through to REAPER while the Parameters dialog is open. See https://github.com/jcsteh/osara/issues/523#issuecomment-846324679. For most users, the gains that brings outweigh the losses. I wasn't able to find a way to give us both. If anyone can find a way, a pull request is welcome. For now, I'm closing this as can't fix.
