### ISSUE TITLE
solo defeat functionality not working

### ISSUE THREAD

**Issue by ns-studios** [jcsteh/osara#557]
Reaper 6.32, Osara 2021.1pre-580,a72d78f7:
The solo defeat functionality does not seem to work, i.e., the solo defeat state is not announced when going through the track list, or with the report all soloed tracks action. #383

**Comment by ScottChesworth** [comment]
I can't reproduce that. Both of those scenarios are working reliably here with the same versions.

**Comment by ns-studios** [comment]
After restart, everything works. I appologize; not sure what happened there.
