### ISSUE TITLE
Make remaining untranslatable strings translatable

### ISSUE THREAD

**Issue by ElCrackLoko** [jcsteh/osara#560]
Hello everybody. How are they?
In the translation I saw something that says that it can be enabled / disabled so that the automation points move when we move the items, just as if we were talking about one Riple per track but for the automation points. If this is the case, I would like to check it but I would like to know the command since I have not seen it or have not known how to look for it.
I would also like to know where I could send Osara lines that are not yet part of the translation but are obviously part of Osara.
Here are some for example:
"Change Item Selection"
(This, as perhaps many already know, is when we scroll through items with control plus the right or left arrows)
When configuring the peak meter with Alt + W there are also a couple of options like
"none"
Y
"Follow current track"
I take this opportunity to leave another one that I found, in the Midi event editor,
"1 event removed"
As well as in the singular and in the plural, as
"3 events removed"
Maybe they are trifles but I wanted to report it
Thank you very much and sorry for the inconvenience.

**Comment by jcsteh** [comment]
> In the translation I saw something that says that it can be enabled / disabled so that the automation points move when we move the items, just as if we were talking about one Riple per track but for the automation points. If this is the case, I would like to check it but I would like to know the command since I have not seen it or have not known how to look for it.

Could you provide the exact string you're unsure about? That'll make it a lot easier for me to find it.

> I would also like to know where I could send Osara lines that are not yet part of the translation but are obviously part of Osara.

I'm aware there are quite a few (at least 50 strings!) I haven't gotten around to making translatable yet. The process of going through them all and making them translatable is super tedious, mind-numbing and time consuming and I just haven't gotten to the rest of them yet.

> "Change Item Selection"

This one wasn't in my list and should be an easy fix. Thanks for pointing it out.

> When configuring the peak meter with Alt + W there are also a couple of options like
> "none"
> "Follow current track"

These weren't in my list either and should also be pretty easy. Thanks.

> "1 event removed"
> As well as in the singular and in the plural, as
> "3 events removed"

These ones are in my list, but are somewhat trickier to fix.

**Comment by jcsteh** [comment]
If anyone wants to work on the code for this, I explained what needs to be done in https://github.com/jcsteh/osara/issues/573#issuecomment-925427115.

**Comment by RDMurray** [comment]
I've started working on this. Currently going through midiEditorCommands.cpp.

**Comment by jcsteh** [comment]
Amazing. Thank you.
