### ISSUE TITLE
Add a way to hear the transport state

### ISSUE THREAD

**Issue by pitermach** [jcsteh/osara#563]
Inspired by a recent conversation on the RWP list, a user was wondering what's the best way to figure out if Reaper is recording. Since a sighted person can see that the record button is pressed I think Osara could have a way to figure this out as well. 2 ideas come to mind:

- Speak the transport state as part of the CTRL+Shift+J position report after the time is spoken. In some of the other audio editors I used like Studio Recorder or Amadeus Pro on Mac the recording state was in the status bar which also included the time, so it was very easy to figure out whether you were recording and if you were at the right spot this way.
- Add a new action to report the transport state (recording/playing/paused etc. Not sure what a good key for that could be, but if you'd rather not clutter the report position command with more verbosity this approach might work better.

**Comment by jcsteh** [comment]
I'd be happy with it being reported as part of control+shift+j, but some
users might not like that. It would be after the time, so it shouldn't
impact productivity, but change is hard. 🤷‍♂️

If we did add a new action, I'd suggest it be unbound by default. That way,
users who want can bind it (I don't think there would be that many), users
who don't avoid having their key map cluttered.

**Comment by mattymc2** [comment]
Agree with you James. I prefer to be on control shift J but either way the functionality would be useful

**Comment by ScottChesworth** [comment]
Chris G already scripted this and uploaded to the Reaper Dropbox. I'd like to see OSARA append to what's reported by "OSARA: Report edit/play cursor position" when pressing Control+Shift+J during recording, it is an important piece of context after all, but gonna label this low priority seeing as we have a solid script now.

**Comment by jcsteh** [comment]
Low priority, but a piece of cake to implement, so it's done.
