### ISSUE TITLE
Respect the Project Start Time Offset Set in Project Settings 

### ISSUE THREAD

**Issue by MatejGolian** [jcsteh/osara#567]
Osara currently doesn't honor the project start time offset when reporting the edit/play cursor position. In case #566 gets implemented, it would be nice if Osara had support for the project start time feature as well. Of course, provided that's possible at all.
      Thanks a lot.

**Comment by leonardder** [comment]
the REAPER API has support to retrieve the time offset, I have a prototype that works.
Something I don't understand though is how project start time and project start measure relate to each other. What should I imagine when project start measure is set to -2 when project start time is set to 0:10.00, for example.

**Comment by MatejGolian** [comment]
@leonardder, as far as I understand project start time and project start measure aren't really related in the technical sense of the word - changing one setting doesn't affect the other, but these 2 things are logically related in that they both affect how the values respective to them are being displayed on screen.
What's more, these 2 settings affect the values in the jump to time/marker/region dialog as well, so there is a way of checking whether Osara reports the values exactly like they appear on screen.
