### ISSUE TITLE
Save error with Osara - Cannot build envelopes over 500

### ISSUE THREAD

**Issue by ElCrackLoko** [jcsteh/osara#568]
Hi everyone. How are they? I hope it's ok.
Surely they are wondering what I am referring to and calm down. That's what I'm going to do. I have a project with Kontakt, which has a library that is not accessible and I need the vibrato of it to be activated in certain parts. This, in Kontakt, I can manually activate it with the parameter Breath Controller (MSB) (545) The point is that everything is fine, I move it, it does what I want but the inconvenience occurs when I want to build that envelope with the Control + Alt command + L which was the last used. It precisely gives me the message that says no envelope has been used. I have tried to record the Midi by assigning the aforementioned parameter to a Fader of my controller, then to record that envelope I give Control + Applications, I look for automation mode and I have tried all of them, but simply nothing happens. In real time use if changes occur, but not at the time of recording since only a nothing is recorded in the Midi. And yes, I have put in the option "Add what we touch", by the way. But what is with the parameter that I want to be recorded, nothing at all. It would only be easier to put it together with Osara and voila. I do not know if I have implied, hopefully yes.
Tanks Brothers.

**Comment by ScottChesworth** [comment]
Dunno if you can automate CC parameters like that. I think you'd have to either:
1. Use CC lanes in the piano roll view of the MIDI editor, or
2. Insert those in the Event List view instead.

**Comment by ElCrackLoko** [comment]
Hello, and how do I use CC Lanes in the PianoRoll Midi editor? I mean, there is no menu bar, there is no context menu, how do I interact with it? Thank you very much for the tip. I'm going to try what you recommend, especially # 2. If I can't, notice here.

**Comment by jcsteh** [comment]
I'm going to close this, since automating midi CCs isn't possible, so this isn't an OSARA deficiency. However, please feel free to discuss your findings further here if that's useful.
