### ISSUE TITLE
Keymap suggestion: Add alternative mapping for "insert virtual instrument" for Mac

### ISSUE THREAD

**Issue by pitermach** [jcsteh/osara#570]
THis just came up on the RWP list. While I was working on Mac I just did this through the insert menu thinking that the key wasn't assigned on Mac. Turns out that it is mapped to command+Insert, which although does mirror the Windows keymap convention isn't as practical on Mac in my opinion. I would imagine the majority of Mac users will be working from laptops or the smaller Apple keyboards, neither of which offer a way to press the Insert key.

On my end I decided to assign this action to Command+CTRL+I, which is just adding an extra modifier to the existing Command+I action that inserts a file, so it's similar to adding CTRL to the insert key. I think this could be a useful mapping that could ship with Reaper in addition to the Command+Insert one that's there now.

**Comment by leonardder** [comment]
Added the sentToKeymapCrew label to see what the keymap peeps think about this.
