### ISSUE TITLE
Approval translation

### ISSUE THREAD

**Issue by leejul** [jcsteh/osara#576]
Hi James,

The French Canadian translation has been completed. It is awaiting approval.
There is a problem with the following string:
[Unsaved]
Cannot translate it, there is an error. It tells me that a specific character is missing.
Thanks.

**Comment by jcsteh** [comment]
Thanks for your work!

Although there is an option for approval, it isn't required to be merged into OSARA. Unless you want to work with other translators and verify their translations, you can safely ignore the approval process.

With regard to the `[Unsaved]` string, do you mean this error?

> Source text contains a variable "[Unsaved]" that is missing in the translation.

You can ignore that error. Crowdin thinks the square brackets are a variable, but they aren't. Variables in OSARA translatable strings are surrounded by braces, not square brackets. Unfortunately, I don't think there's a way for me to disable that error for square brackets in Crowdin. You should be able to save that translation despite the error; e.g. by pressing control+enter.

Finally, I periodically merge updated translations into OSARA, so there's no need for you to notify me when an update has been made.

Thanks!
