### ISSUE TITLE
Action feedback requests for time selection and region creation

### ISSUE THREAD

**Issue by leonardder** [jcsteh/osara#58]
I'd like request Osara to give feedback for the following actions:
- Item navigation: move cursor left/right to edge of item
- Time selection: set start/end point
- Markers: insert region from time selection

**Comment by jcsteh** [comment]
What do you expect the latter two would report? You've already chosen the time, so the time seems superfluous. Just the action name?

**Comment by ScottChesworth** [comment]
@leonardder, is there anything you're still yearning for here? If not, please close (we're having a tidy up) :)

**Comment by leonardder** [comment]
Ugh, I'm sorry for abandoning this one for so long. Closing.
