### ISSUE TITLE
Subsequent translation entries for osara

### ISSUE THREAD

**Issue by xingkong0113** [jcsteh/osara#583]
hello all
thank @jcsteh The work of
osara has been switching to gettext's translation module for some time now and he is working well.
However, some of the later translation entries remain untranslated, e.g:
alt+up
Tracks: Move track volume upward slightly
alt+down
Tracks: Move the track volume down slightly 
ctrl+up
Xenakios/SWS: Microshift active clip volume up
ctrl+down
Xenakios/SWS: Shift active clip volume downward
The above are just a few examples.
If jcsteh or any of the contributors have time, see if you can fill in the last translation string?
A regular reaper user.

**Comment by jcsteh** [comment]
The strings you mention are all either from REAPER or SWS, so you'll need to have them translated in the associated REAPER language pack (not OSARA). There are a bunch of strings in OSARA that aren't translatable yet too, but not the ones you mention. Those are covered in #560.
