### ISSUE TITLE
Is it possible to vocalize when activating or deactivating the Delta solo from the action?

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#584]
Hello,
there is action to activate or deactivate the Delta solo, is it possible for OSARA to send information to the screen reader?
The action is:
FX: Toggle delta solo for last focused FX
Very convenient, as for the bypass it would also be useful for the delta solo.
Greetings!

**Comment by leonardder** [comment]
This should be trivial to do. I will look into it.

**Comment by jcsteh** [comment]
Probably another example where TrackFX_GetParamFromIdent will be useful. :)

**Comment by ScottChesworth** [comment]
delta is already reported through surface feedback here, if memory serves. Would be cool to not need surface feedback engaged though.
