### ISSUE TITLE
Keymap: Add Shortcuts For Moving The Edit Cursor To The Start & End Of Selected MIDI Events

### ISSUE THREAD

**Issue by MatejGolian** [jcsteh/osara#585]
Hello,
Could we have shortcuts assigned to the below actions by default?
1. Navigate: Move edit cursor to start of selected events (ID 40440)
2. Navigate: Move edit cursor to end of selected events (ID 40639)
I find them quite useful when working with selections in the MIDI editor. I've included the action IDs in parentheses for completeness' sake, but I actually think that having spoken feedback in this case is not necessary at all.
My suggestions would be CTRL + Shift + Home and CTRL + Shift + End respectively.

**Comment by ScottChesworth** [comment]
I'd want to get feedback working before mapping these. Both actions can modify the position of the edit cursor, we usually report that. At a glance, seems like it'll be easy enough to add though.
Is there a reason why Control+Shift+Home and End makes more sense than just Shift+Home and End? Both combinations of modifiers are free at the moment.

**Comment by MatejGolian** [comment]
My logic behind including the CTRL key was partly derived from the CTRL+Home and CTRL+End shortcuts. Since those go to the start and end of the item, I thought it would seem logical if adding shift to that went to the start and end of the selection. you're right though, it would make sense without shift as well, but I guess it depends on how one looks at it. In me bare Shift+Home and Shift+End don't necessarily evoke that the cursor has to move, but than again the Home and End keys already denote some kind of movement, so I don't know. I would be perfectly fine with just shift as a modifier if you think that it makes more sense. That way the CTRL versions would still be free for some more complex task. Further more, the point could be made that it's generally more reasonable to start by adding shortcuts with less modifiers.
    I'm not against spoken feedback, but I'm not sure what that would be in this particular case and honestly, to me it feels that it would be somewhat of a workflow killer, but of course, it would be fine either way. Whatever makes more sense for the community.

**Comment by MatejGolian** [comment]
Can I back down on my original opinion of not having feedback for these actions a bit?
I still don't think it's absolutely necessary, but I've been considering the pros and cons and now I believe that having the right amount of feedback would be generally more beneficial. It's easier for me without feedback since it was me who proposed the addition of these actions to the keymap, but probably everyone else would welcome receiving feedback in these cases.
I was just thinking something simple like "start of selected events" and "end of selected events". Anything longer would start to feel a bit long, but this sounds OK to me.

**Comment by ScottChesworth** [comment]
I haven't tried these yet. Do you already get either a preview and/or a report of the position if changed? I'm thinking those would be more useful than generic speech. Like, it's more useful to know where you are and what's selected than hearing about what you've just pressed.

**Comment by MatejGolian** [comment]
I do agree that a report of the position would be much more useful, although more hard to implement, but of course, a piece of cake for the programming powers that be over here.
Currently there's absolutely no feedback whatsoever with these actions. I don't think having note previews would make that much sense here though - especially not with the action that moves to the end. That's because it literally moves to the end of the selected events. For example, if you have a note of length 0.0.50 at the end, let's say exactly at bar 9 beat 1, pressing this shortcut would send you to 9.1.50.

**Comment by MatejGolian** [comment]
@RDMurray, thank you for the info. In that case we can roll with that.

**Comment by MatejGolian** [comment]
Closing since this has now been incorporated.
