### ISSUE TITLE
Peakwatcher: linking and unlinking meters

### ISSUE THREAD

**Issue by Justinmac84** [jcsteh/osara#587]
Hi,

since we're poking around with the Peakwatcher at the moment, I had the following idea, which I think could increase productivity and more closely reflect a sighted person's workflow. Would it be possible to change the Peakwatcher dialogue in the following ways and/or add actions.

the Peakwatcher dialogue currently allows you to select the type of metering you can view, but it is only possible to have the same type of metering for both tracks the peakwatcher can observe. Would it be possible to incorporate a checkbox similar to that which exists in many effects to link and unlink the two tracks. If unchecked, a second combo box could be exposed allowing you to select a different meter type for the second track. 

this would allow one to monitor the same track with different types of metering simultaneously for example if one wanted to observe Luf and true peak values. One could also have the master track always set to monitor Lufs or true peak, while having the option to be flexible with metering for other tracks as required. 

A sighted person would be able to access information in this way using different loudness plugin metering instances or easily toggling between metering modes for the same track. 

I wonder if it would be possible to add actions to cycle metering modes for speed, but I think this would be lower priority.

Thanks for reading,

Regards,

justin

**Comment by jcsteh** [comment]
I implemented this a while ago in #508. However, it presents some user experience problems that are not easy to solve. See #508 for details and discussion.
