### ISSUE TITLE
Reporting and focus sensitivty for remove actions

### ISSUE THREAD

**Issue by GianlucaApollaro** [jcsteh/osara#6]
Hi,
in rea-access by pressing the delete key we could have the item, the selected track, or the selection deleted when we pressed the delete key. In osara this doesn't happen, even if the action says it does. I think this is a focus issue; a sighted user when puts the mouse on a track selects that track and the focus gets to the track, same with items. When I use the delete keys with osara I can delete only items, for deleting tracks or removing the selection I have to use specific actions,. So It turned out I had to map the delete key with shift, ctrl, and both to get the wanted result
Thanks

**Comment by jcsteh** [comment]
Yeah, I don't really understand REAPER's idea of focus. As you say, it seems to be somehow related to the mouse, which is unusual at best.

I think I'm going to have to handle each action separately. You say "actions", but you only mention delete. Specifically what actions do you require focus sensitivity for? There are quite a few, but I suspect some of them won't actually be relevant.

**Comment by jcsteh** [comment]
Actually, REAPER 4.75 allows us to set the focus using the API.

This covers tracks and items. However, you mention "the item, the selected track, or the selection". I assume you mean time selection? The REAPER actions only say "tracks/items/envelope points", not "time selection", so the REAPER actions can't (and shouldn't) touch the time selection. Was this your intention? If so, that'd require new actions.

**Comment by GianlucaApollaro** [comment]
Yes, I meant time selection. If handling the time selection is a 
problem, don't worry, I mapped the action to remove the time selection 
to alt+Shift+Delete key. Here's how this deleting worked in rea-access. 
If I moved to a track with up or down arrow, the delete key deleted that 
specific track. If I was selecting an item with Ctrl and left or right 
arrows, The delete key deleted that item, and, If I was on a time 
selection the delete key got rid of the time selection. To make that 
work in osara I had to map the delete key with keys like alt, or ctrl, 
or shift depending on what I wanted to delete. In my keymap I'm using in 
osara, CtrlShift delete deletes the tracks, using the action remove 
tracks; pressing Only the delete key deletes items (it does it by 
default); and AltShiftDelete deletes the selection, using the action 
remove time selection moving later items. In rea-access we could do all 
this using only the delete key and, depending on focus it got rid of 
item, tracks, or the time selection. I hope I explained it well
Il 22/02/2015 11:13, jcsteh ha scritto:

**Comment by jcsteh** [comment]
Fair enough. I'm happy to consider this; I can certainly see how it would be useful. I'm just pointing out that REAPER's in-built actions don't specify they will do this and I think overriding them to do so would be potentially confusing given that the description of the action doesn't mention time selection. That doesn't mean I can't create new actions, though.

Anyway, for now, this will at least work for tracks and items. I'll make a custom action to cover this plus time selection when I get some more time.

**Comment by GianlucaApollaro** [comment]
Ok, the new version works perfectly. One mor thing. I think it could be 
useful to know what we are deleting. For example, if we delete 3 items, 
hear 3 items deleted, or if we deleted a track, one track deleted. So we 
have feedback. Thanks and keep it up!
Il 22/02/2015 11:13, jcsteh ha scritto:

**Comment by dgl1984** [comment]
Agreed.  This is also the case for an unsuccessful attempt to select or delete something.  If I'm going through a project with several items, and think I have 1 or more selected, I'd like to know how many were deleted, cut, copied, pasted, etc.  Even if 0 things ere deleted, that's good to know because it's happened before.

**Comment by jcsteh** [comment]
Please provide specific action names and exactly what you want reported. As I said, this has to be done specifically for each action. Please always be as specific as possible. Otherwise, we'll go back and forth for a few centuries trying to nail all the actions, since there are just so many in REAPER. Also, please keep separate issues in separate issue reports. Reporting this kind of information is a separate issue to focus sensitivity, yet they're both being discussed here. Thanks.

**Comment by jcsteh** [comment]
Please file new issues for other actions/groups of actions. Thanks.
