### ISSUE TITLE
Alt+DownArrow fails to open presets combo box with OSARA pre-638 and Reaper 6.42

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#606]
This got reported on RWP. I can reproduce here.

1. Instantiate an effect that provides presets in stock library format, let's say ReaEQ.
2. In the FX window, navigate to the Presets combo box.
3. Hit Alt+DownArrow. Expected behaviour is that the combo box pops open and OSARA's search filter is revealed. Actual behaviour here is that neither of those things happen. Instead, the Alt+DownArrow keystroke still decreases track volume as if I were in the TCP.

Any idea what's up?

**Comment by leonardder** [comment]
Can you reproduce this with older versions as well? It could possibly be #598.
