### ISSUE TITLE
Refining what OSARA reports when effects are present (this needs input from translators)

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#608]
In the comments of issue #592, I proposed a shorter reporting format when users move to a track or item that has effects instantiated. This would involve splitting the string we get from Reaper based on punctuation and spacing. The goal is to cut back on extraneous speech and relay all useful information to the user in a shorter time.
If you're a translator, or you use Reaper and OSARA in a language other than English, please examine the format of the two reports below and let us know the following things:
1. Are the spacing and punctuation I've used here consistent in your translation?
2. Would the second, shorter report still make sense in your language?
3. Can you think of any examples of effects that aren't covered here, IE, where the spacing and/or formatting of how they're reported differs?

Here's our current report when moving to a track:
1 Guitar Riff 1 item; FX: VST: ReaEQ (Cockos), VST3: Ultimate Serious Pro (Waves), JS: Soft Clipper/Limiter

Here's the shorter, more productive version I'm proposing. Note that this example includes notification that the second effect in the chain is bypassed, which is what we're hoping will be implemented in #592.
1 Guitar Riff 1 item; FX: ReaEQ, Ultimate Serious Pro bypassed, Soft Clipper/Limiter

Thanks in advance for any feedback.

**Comment by jcsteh** [comment]
I'm inclined to just go ahead and do this given the lack of response. At worst, it won't break for other languages; they just won't get the best experience. We can cross that bridge if we get there.

That said, I implemented this and one problem is that JS effects aren't consistent with respect to the vendor name. Many of them don't have a vendor name, but some do. For example, this one does:
JS: Bit Meter (Cockos)
But this doesn't:
JS: Avocado Ducking Glitch Generator
Worse, we have some which don't have a vendor name, but do use parentheses. For example:
JS: Transient-Driven Auto-Pan (Transmitter)
With my change, we strip (Transmitter) from that last one, and given that there's an accompanying (Receiver) plugin, that is not ideal.
