### ISSUE TITLE
It is possible to signal the end of folder when we go with alt + applications in the context menu of Sends and Receives?

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#620]
Hi, I often have two folders and between the two folders I have two tracks out.

For example: I select the track, I do alt + applications and I go to the Sends submenu and I find the selection of the folder but I don't understand when the folder ends I make a Send from track one which is a voice folder and between the folder of voice c 'is a track outside the folder which is the vocal saturation and after that there is another folder where the acoustic guitars begin.When I do alt + applications and look for the vocal saturation track I slow down a bit to understand when a folder ends Is it possible to indicate the end of folder in the context menu?

Greetings!

**Comment by ScottChesworth** [comment]
That's a Reaper menu, not something OSARA has control over. You could get more clarity by using a blank track for the end of each folder, named accordingly.
