### ISSUE TITLE
Can We Have Note Velocities Reported In The Piano Roll?

### ISSUE THREAD

**Issue by MatejGolian** [jcsteh/osara#626]
Hello,
I think it would be nice if we could get note velocities reported in the piano roll when moving between notes. Right now the only ways of finding out what velocity a given note is at is either opening the event dialog or pressing the V and Shift + V shortcuts. The V/Shift + V method is quick, but it is kinda annoying. Having this feature would make drum programming more comfortable.
Perhaps the most intuitive approach would be appending the velocity after the note length and separating these 2 pieces of information with a semicolon - so, similarly to how notes get reported in the event list editor.
Any thoughts?

**Comment by MatejGolian** [comment]
Correction: I meant to say appending it after the note length so I've edited my initial comment accordingly.

**Comment by ScottChesworth** [comment]
Given that the use case is drum programming, how about we append velocity when in Drum Map view (Alt+2). That way, users can just choose the view that matches what they want to hear. Lengths in the Piano Roll, velocity  in the Drum Map or both by switching to the Event List.

**Comment by MatejGolian** [comment]
Scott, that sounds reasonable. If I get you correctly, there wouldn't be any changes as long as reporting of note names is concerned, which is good.
I also have another idea and if I could choose, that's the ultimate way I'd like to have it, but it would require more programming on the Osara end of things. On the other hand it could be the most flexible option all in all and it would provide a similar experience to what sighted users have. That being said, not everyone might find it a good idea, because it would be somewhat of a behavior changer and might prove initially confusing.
In short, perhaps Osara could honor the settings in 'View > Piano roll notes', namely 'Show velocity numbers on notes' and 'Show note names on notes'. Having both of these disabled would only make Osara report note lengths. Enabling 'Show note names on notes' would make Osara prepend the note name information exactly like we have it now and enabling 'Show velocity numbers on notes' would append the info on note velocities. So, one could either have Osara report just the note length, note name + length, note length + velocity or note name + length + velocity, based on those 2 settings in the view menu. The down side would be that note lenghts would always get reported. It would likely be possible to get rid of the note length information in drum editing mode, but of course that would mean even more coding.
What do you think? If you think my idea is overkill or it's not possible to do it like that, @ScottChesworth, your suggestion is perfectly fine.

**Comment by ScottChesworth** [comment]
I like it, but I'm not the person who'll be coding this if it happens. For now, I can only do easy stuff here.

**Comment by MatejGolian** [comment]
What ever way it gets implemented (hope it indeed does so), will be a pretty significant improvement when it comes to drum/MIDI programming IMO. In any case, cool that you like my idea. :-)

**Comment by jcsteh** [comment]
I'm not keen on disabling note names when "Show note names on notes" is disabled. While that would match the sighted UX speaking in the strictest sense, it kinda doesn't because I imagine sighted users still have some indication of the note even without an explicit "name". In contrast, screen reader users don't have any indication other than the name (forgetting about preview, which is the same for both sighted and screen reader users).

@ScottChesworth , I'm also confused by your comment re Drum Map view (Alt+2). Here, that's called "named notes" view. While I get that this is mostly commonly used for drum map work, the fact that it's not explicitly named that makes me reluctant to tie velocity behaviour to it, especially because its name talks about "notes".

**Comment by MatejGolian** [comment]
@jcsteh, I could be wrong, but the way I understand it is that enabling "Show note names on notes" pulls the note names from the note name map, while having that option disabled displays the standard note pitches, as if there wasn't any note map loaded.

**Comment by jcsteh** [comment]
Yeah, I figured that might be the case. Either way, disabling this
shouldn't completely disable reporting of note pitch/name.

**Comment by MatejGolian** [comment]
@jcsteh, as I wrote, I'm not entirely sure that that's how that option works for sighted folks as the user guide is a bit vague about it, but IMO it wouldn't make much sense otherwise. Either way, how complicated would it be to add support for that option to Osara as per my previous comment? I know, it's more of a luxury feature.

**Comment by jcsteh** [comment]
Are you asking for it to note report pitch at all when that option is disabled or just note names? I'm not willing to implement the former because that option is disabled by default and that would mean users would not get pitch at all where sighted users do. If you mean just custom note names, that seems more reasonable, but it's still a change in behaviour which might not be popular for existing users.

**Comment by MatejGolian** [comment]
I mean the latter - so as a toggle between note pitches and custom note names.

**Comment by jcsteh** [comment]
I'd like to see use cases for note pitches vs note names before committing
to a behaviour change which may hurt existing users. Regardless, it'd be
great if you could open a separate issue for this. Thanks.

**Comment by MatejGolian** [comment]
I don't know if this qualifies as a use case (probably not), but I
have a MIDI item containing drum hits which I loaded my own "a
work-in-progress" note name map on to. The strange thing is that after
clearing the note/CC names, Osara doesn't report any name or pitch
when selecting notes - it only reports their length. This behavior
seems to only be isolated to that sole item, so not sure what's going
on there. Either way, I was thinking that adding support for that
pitch/note name toggle could act as a way of bringing note pitches
back in edgy situations like this. But as I wrote, this probably isn't
much of a use case, so I guess we'll leave note names alone for now -
that's why I'm still commenting here and haven't opened a new issue.
My only other argument would be that back in the day I expected that
toggle to do something, but got confused when it didn't appear to do
anything. In other words, I expected a similar behavior to what
sighted folks have, but I acknowledge that mimicking the user
experience of sighted users is not always necessary.

2022-01-11 2:35 GMT+01:00, James Teh ***@***.***>:

**Comment by jcsteh** [comment]
To be clear, I actually think your argument is entirely fair and valid: normally, I'd say the experience should mirror the visual UX wherever practical. If this had been thought of in the beginning, I wouldn't have raised this. The only reason I'm concerned is that the behaviour change might hurt existing users. That said, thinking on it more, it doesn't seem like it'd be too difficult to support users through this. @ScottChesworth, what say you? Do you think this will be problematic from a support perspective?

**Comment by ScottChesworth** [comment]
Nah, can't see it causing any problems. I've only ever seen more experienced users relying on modified note names. Those folks have already cracked the seal on customizing the MIDI editor to configure options for the task at hand, so this option becoming part of that equation seems reasonable to me. From here it doesn't seem urgent, but still worth implementing if or when you have time I reckon.
