### ISSUE TITLE
String question

### ISSUE THREAD

**Issue by leejul** [jcsteh/osara#627]
Hi James,

I have a problem with the following trad:
#. Reported when setting the channel mode of takes.
#. {count} will be replaced with the number of takes affected.
#. {mode} will be replaced with the mode being set.
#. For example: "set 2 takes to mono (left)"
msgid "set {count} take to {mode}"
msgid_plural "set {count} takes to {mode}"
Can I replace {mode} "for another string?
{mode} "is used for the word normal. But in French I would like to use (default).
How could I not use {mode} "for this string?
Thanks.

**Comment by jcsteh** [comment]
{mode} is replaced with the mode to which the take has just been set. That could be "normal", "mono (left)", etc.

The individual modes are also translatable. You should have a string "normal" with a comment "A take channel mode.". You can translate that how ever you wish.

**Comment by leejul** [comment]
Yes I know but the normal string is used in 2 different places. {mode} is also used for monitoring. If I change the word normal, as this string is used in another context, I cannot change it. So, would it be possible to make a new string with the word {By default}? I could use this string instead of normal. 
{mode} is used bolth for monitoring.
Thanks.

**Comment by jcsteh** [comment]
Okay. Now the two "normal" strings can be translated separately. Note that this doesn't affect how you translate {mode}; you should leave that as is. What you will do instead is translate the two instances of "normal" differently. The message context and comment will indicate which one is which.

**Comment by leejul** [comment]
Cool, Thanks. Is it normal that I don't see a new string to translate?
I am not sure what to do.
Thanks.

**Comment by jcsteh** [comment]
Nope, it's not normal. I broke something; thanks for flagging. It should hopefully update shortly.
