### ISSUE TITLE
OSARA causing Reaper to crash when pressing Alt+F4 in a Juce plugin

### ISSUE THREAD

**Issue by pitermach** [jcsteh/osara#630]
THis issue was first discovered during accessibility work on SurgeXT [here](https://github.com/surge-synthesizer/surge/issues/4616#issuecomment-1005608245)

STR:

- Add a juce-based effect. I tested with [SurgeXT](https://surge-synthesizer.github.io/nightly_XT), Pianoteq 7 and Sonobus all of which caused a crash.
- Focus the plugin with F6 or by tabbing into it.
- Press ALt+F4
Expected: The FX window should close and you should be back in the main Reaper window.
Actual: Reaper crashes.

The crashes happened if any screen reader was running - tried NVDA, Narrator, ZDSR and JAWS. If I renamed Osara so it wouldn't start or ran reaper without a screen reader running and did these steps there weren't any crashes. The Mac version of this - pressing command-W in the FX window, also works fine.

**Comment by jcsteh** [comment]
I can confirm this. However:

1. For me, if I rename reaper_osara64.dll so it doesn't load, I still get the crash. I confirmed that OSARA was non-functional after renaming; i.e. there was no speech output from OSARA. Could you please re-test this?
2. I took a look with a debugger. The stack shows that the crash occurs within Surge. There are no frames from OSARA whatsoever in the crash stack; i.e. no OSARA functions were running at all when the crash occurred, not even any of its hooks. I don't have debug symbols for Surge, so I can't tell you where in Surge it was crashing, unfortunately.

Closing as per point 1: this is not an OSARA issue.

**Comment by pitermach** [comment]
After trying again I got it to crash without OSARA as well, so you're right, whatever causes this must be in Juce, and I think Scott has reported it to them. Thankfully escaping out of the FX dialog works fine which is what most people do so this issue can very easily be avoided.
