### ISSUE TITLE
Change shortcut for "Time selection: Extend time selection to next transient in items"

### ISSUE THREAD

**Issue by leonardder** [jcsteh/osara#632]
"Time selection: Extend time selection to next transient in items" is currently bound to ctrl+alt+tab. However, at least in Windows 11 and likely in Windows 10 as well, ctrl+alt+tab opens an app switcher window and doesn't execute the actual action.

**Comment by leonardder** [comment]
@ScottChesworth curious to know whether you have thoughts about this. It's probably hard to come up with an alternative shortcut.

**Comment by RDMurray** [comment]
I can confirm this is also unusable in Windows 10.  Adding to #667
  
As this moves the right edge of the time selection, would something with ] make sense? Control+Shift and Control+Alt+Shift are free.  It might pair up nicely with "Time selection: Swap left edge of time selection to next transient in items", which could go on [ with the same modifiers.

**Comment by tbdalgaard** [comment]
Sounds good to me. I checked on Mac OS and substituted the ctrl with command-key, and those keys are free too.

**Comment by RDMurray** [comment]
@ScottChesworth  What do you think of the suggestions above?￼

**Comment by ScottChesworth** [comment]
Using Control+Shift as the modifiers and introducing "Time selection: Swap left edge of time selection to next transient in items" are both fine with me.

**Comment by jennykbrennan** [comment]
I would like to understand what Time selection: Swap left edge of time selection to next transient in items is supposed to accomplish in practice. From my tests, it doesn't move the start of time selection to anywhere I want it. So I'm certain I simply don't get how and when it's useful. Can someone give me a use case for it? As it is, that key is one I will avoid as the plague and will replace instantly with something I feel is well paired with Command shift ], extend time selection to next transient in item. I feel like I'm missing something and I'd like to know what it's good for. :)

**Comment by RDMurray** [comment]
It is for selecting the area from one transient to the next.  Here's an example:

tab to the first transient. Press [ to start the time selection.  then use Control+Shift+] to set the end of the time selection to the next transient.  You can then do what ever you like with the selection, E.G. "create measure from time selection...".  Pressing control+shift+[ will then move the start of the time selection to where the end was, and move the end to the next transient.

It's quite an efficient way to go through audio, selecting from one transient to another.

**Comment by jennykbrennan** [comment]
Gotcha. Now I get what it's doing. Thanks for that. And yes, I have to agree with pairing these up. Just had to wrangle my brain a bit to see the point. And it does seem to be a good one.  :)

**Comment by ptorpey** [comment]
When you say “next transient” does this refer to a zero crossing or peak?  Sounds like a nice function.

 

--Pete
