### ISSUE TITLE
Since Reaper 6.44 ReaEQ has a new filter: Parallel Band Pass

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#635]
Hello,
since Reaper 6.44 ReaEQ has a new filter:
Parallel Band Pass.
Being new, in ReaEQ's FX Parameters window it is not in the Band type combo box.
Greetings!

**Comment by Lo-lo78** [comment]
I actually made a comparison between the Band Pass and the Parallel Band 
Pass; I found no differences.

Ciao!Message ID: ***@***.***>

**Comment by jcsteh** [comment]
The idea is to allow you to pass multiple separate bands. Normally, if you
apply a band pass, it strips out stuff from other bands, so you can't apply
another band pass after that, since the earlier band pass removed that
audio. With a parallel band pass, they work together so this is possible.

**Comment by Lo-lo78** [comment]
Uau, I hadn't rehearsed on more bands yet.

Very cool!Message ID: ***@***.***>
