### ISSUE TITLE
SCons error after updating to Build Tools for Visual Studio 2022

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#639]
I've updated to Build Tools for Visual Studio 2022. Checked Desktop development with C++ and Clang during installation (figured I'd get that done ready for upcoming changes).
Since updating though, SCons terminates during building uia.cpp:
src\uia.cpp(11): fatal error C1083: Cannot open include file: 'atlcomcli.h': No such file or directory
scons: *** [build\x86\uia.obj] Error 2
I'm still able to build other projects that use UIA with SCons since updating, so I guess this is specific to OSARA in some way.
So far I've tried scons -c to clean the cache and double-checked all OSARA dependencies are in place.
Currently using SCons v4.3.0.559790274f66fa55251f5754de34820a29c7327a, Tue, 16 Nov 2021 19:09:21, pip tells me that's the most recent.
Any ideas appreciated.

**Comment by jcsteh** [comment]
Ah. Looks like I missed something in the readme. In the Build Tools, you
also need to install "C++ ATL for v143 build tools (x86 and x64)". That's
not a new requirement, but I guess you somehow had it installed with 2019
despite the lack of mention in the readme.

**Comment by ScottChesworth** [comment]
Solved in one, thank you! I'll add that to the readme.
Hey, is there an easier way to do that instead of via a pull request? Happy to do the usual PR and merge if not, but it seems like the sort of thing that might be able to happen just in a browser.

**Comment by jcsteh** [comment]
I think GitHub might have a web editor for text files, but I don't know
much about it. I feel like I tried it years ago and it was pretty painful,
but I really can't remember and things have probably changed. You'd be
somewhat on your own if you decided to go down that path. :)

**Comment by ScottChesworth** [comment]
No worries, I've already added the extra line and merged it the usual way.

**Comment by RDMurray** [comment]
Github includes an online version of VS Code now.  It's actually quite accessible. Press "." to open it.   It would be fine for quick edits like this.  Ctrl+Shift+e opens the file browser, Ctrl+Shift+G opens source control where you can create a pull request or commit directly.

**Comment by ScottChesworth** [comment]
Nifty, cheers!
