### ISSUE TITLE
Trad string no longer works

### ISSUE THREAD

**Issue by leejul** [jcsteh/osara#642]
Hi James,

The next string no longer works.
SOURCE STRING
normal
CONTEXT
#. Record monitor set to normal.
record monitor
Osara does not state the sentence I wrote for the translation.
Thanks.

**Comment by jcsteh** [comment]
I haven't synced updated translations for a few days. I'll do it when I get
a chance. (This doesn't happen automatically.)

**Comment by jcsteh** [comment]
I synced translations, so this should be fixed now. For future reference, please note that translation sync is not automatic, so it may take a few days for new translated strings to appear.

**Comment by leejul** [comment]
Ok cool, I thought the trad update was being done at the same time as OSARA update. Sorry for inconvenience.
