### ISSUE TITLE
Add Support For Switching Between Note Names And Note Pitches Via The Show note names on notes Action

### ISSUE THREAD

**Issue by MatejGolian** [jcsteh/osara#643]
I'm opening this issue as a result of our previous discussion under issue #626. To sum it up, it would be nice if we could switch between note pitches and named notes based on the state of Reapers 'Show note names on notes' command. Having this implemented would make our user experience in the MIDI editor more customizable and closer to that of our sighted peers. Obviously, as @ScottChesworth rightly pointed out, this issue is a low priority one.

**Comment by leonardder** [comment]
Could you elaborate on the expected behavior? I.e. I assume you mean C3, E4 with note names, but how about the pitches? Is that just the raw pitch value 0--127?

**Comment by jcsteh** [comment]
The distinction here is hard-coded pitch names such as C4 vs note names queried from the REAPER API (e.g. set for drum maps, etc.). This should be a fairly straightforward check in OSARA's note name code.

**Comment by MatejGolian** [comment]
@leonardder, off course.
By pitches I actually mean things like C3, E4 and so on, so just like it is now when you open a fresh instance of the MIDI editor. Sure, C2, E4 and so on are also note names, but they're not the kind of note names one would typically find in a Reaper MIDI note name map that one can load from the MIDI editor's file menu.
When you currently load a MIDI note map in the MIDI editor, let's say one containing drum names, instead of C3, D3, E3, Osara will instantly start reporting things like 'Kick', 'Snare' or 'Snare Rimshot' instead of the 'normal' note names depending on the values specified in the loaded note name map. Basically my request is, with the option 'Show note names on notes' disabled report things like C4, F6 and so on; and with 'Show note names on notes' enabled report things like 'Kick', 'Snare' and so on. So, not anything drastic from a coding perspective - probably this should just be a matter of an extra if statement or two.
Hope that clears things up a bit.

**Comment by MatejGolian** [comment]
@jcsteh, sorry, haven't noticed your reply. It came in while I was typing mine... :D
