### ISSUE TITLE
Can we clarify what J and K report by tweaking action names?

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#644]
Someone on RWP has just noted that the functionality of our "OSARA: Report current peak for channel 1 of current track" and accompanying action for channel 2 wasn't immediately clear to them, in that they weren't sure whether it was the current highest peak measured or the peak at the current position. This isn't the first time I've seen that confusion occur, so I'm proposing adjusting the names of these actions slightly for extra clarity:
OSARA: Report peak at play cursor position for channel 1 of current track
OSARA: Report peak at play cursor position for channel 1 of current track
OSARA: Report peak at play cursor position for channel 1 of master track
OSARA: Report peak at play cursor position for channel 2 of master track

Any objections?

**Comment by jcsteh** [comment]
I think these actions will also report the peak of input at the current time when input monitoring? Or am I incorrect about that? While not particularly useful, this would be inconsistent with the "play cursor" wording.

**Comment by ScottChesworth** [comment]
Ooh, good catch. Their behaviour changes when the track is armed. Monitoring doesn't have any impact so far as I know. I'll rethink those names.

**Comment by ScottChesworth** [comment]
The behaviour for the master track variants stays consistent, so I think my first proposal for those can stand if you agree it adds clarity. For the track-based ones, how about:
OSARA: Report level in peak dB at play cursor for channel 1 of current track (reports input level instead when track is armed)
OSARA: Report level in peak dB at play cursor for channel 2 of current track (reports input level instead when track is armed)

Hmmm, they're long names, but at least it's clear what to expect.

**Comment by ptorpey** [comment]
How about something like:

 

OSARA: Report peak at current position for channel 1 of master track

 

That should eliminate the ambiguity that appeared on the RWP list and also address Jamie’s observation.

**Comment by ptorpey** [comment]
Even better!

**Comment by jcsteh** [comment]
I'm not a massive fan of those massively long names, but this is certainly
not the longest action name in REAPER by a long shot, so I can live with it.

**Comment by ScottChesworth** [comment]
576586f9cc645886a943d421758b8479310239ae
