### ISSUE TITLE
the actions for the piano roll: "Navigate: Select next note with the same pitch and Navigate: Select previous note with the same pitch", do not allow navigation forwards or backwards

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#651]
Hello,
I am trying these actions which I believe to be very useful but the navigation seems to have no effect.
For instance:
bar 2 beat 1 0%,
Navigate: Select next note with the same pitch,
bar 2 beat 1 0%.
I don't know, did I misunderstand how these actions work or do they have no effect?
Maybe they are only for the mouse?
The category is very descriptive: it "Navigate", but I don't understand why it doesn't work.
Greetings!

**Comment by ScottChesworth** [comment]
They work, but the edit cursor doesn't sync to the change of selection.

**Comment by jcsteh** [comment]
Those actions are kinda weirdly named. They say "Navigate", which
reasonably leads one to assume they will move the cursor, but they only
select. That feels like a REAPER UX problem to me.

**Comment by Lo-lo78** [comment]
@jcsteh @leonardder 
I found two actions on spk77's ReaPack that work well:

Script: spk77_Add to selection next note at same pitch.eel
Script: spk77_Add to selection previous note at same pitch.eel

These two actions move the edit cursor and delete the selected events smoothly.
I know that the OSARA project does not follow ReaPack but it is possible to take the code of these two actions, improve it and put them on OSARA.
The problem with these two actions is that when you select notes with the same pitch there is no audio feedback from the midi instrument.Vi può interessare?
Greetings guys!

**Comment by MatejGolian** [comment]
Check it if you want, but this issue has been fixed as per Reaper version 6.47.
>   + MIDI editor: move edit cursor on actions to navigate to previous/next note
I have tested it and it seems to be working fine, so @ScottChesworth (or others), I believe that this can now be closed.

**Comment by Lo-lo78** [comment]
Yes, these are the new two actions of Reaper's midi editor.

But the two actions I reported in issue # 651 have another function.

These two actions:

Navigate: Select next note with the same pitch

Navigate: Select previous note with the same pitch

They should move between notes of the same pitch.

If in the 2 beat 1 0% bar I have two events, a kick and a hi hat, and I 
select the kick, these two actions should always move at the same pitch 
that corresponds to the selected kick excluding all other notes, snare, 
kick, hi hat ...

It can be very useful if there are few notes of that pitch in an item, I 
think of a cymbal, if the two actions worked they would select the 
second cymbal of the item, the modification would be much faster, 
without having to move event by event to search the various cymbals;

For example:

in a 32 bar item there could be 2 cymbals:

bar 1, bar 17.

With these two actions I select the first cymbal and then go comfortably 
into the second cymbal.

It can be used in very large items with many notes.

Greetings!

**Comment by ScottChesworth** [comment]
> They should move between notes of the same pitch.
> 
They do now. I had Cockos fix it in 6.47.

**Comment by Lo-lo78** [comment]
Yes, that's right, I'm getting old!


Il 18/02/2022 11:14, ScottChesworth ha scritto:
