### ISSUE TITLE
[Query] And apologies. How could I disable in Reaper so that when I paste a Midi note into the Midi editor, the cursor doesn't go to the end of the note I pasted?

### ISSUE THREAD

**Issue by ElCrackLoko** [jcsteh/osara#662]
Hello. First of all, a thousand apologies for consulting here, I know that this is for errors or requests.
But there is something that has my head broken because I don't know if it is that I played something in Reaper or in Osara. When I paste a Midi note in the Midi editor, Example, I cut a note at 3.1.00 and paste it at 3.1.01, or wherever, the cursor is placed at the end of the note duration. I find this a bit annoying, is there a way to remove that? Please. I hope I have explained myself.
I've been looking in Reaper preferences but I can't find anything that tells me to disable that or enable something that disables that feature, in Osara the same. By the way. I don't know what the "Edit cursor follows focus in MIDI event list" function does according to me, this was so that when we are in the event editor (Alt+3), we give space to play and if we want stop at a specific place, let's give space control and just stop at that note/Midi event to be able to edit as we please. If this is the function, it is not working for me and the editing cursor continues to stay at the beginning. IF this is not what that function does and I was making silly assumptions hehe, tell me to more or less know what the hell it does, I would appreciate it.

**Comment by jcsteh** [comment]
As you noted, technical support questions don't really belong here. The best place for those is the [RWP discussion group](https://groups.io/g/rwp). I'd suggest joining there for questions like this.

That said, I don't think there's a way to do what you want. That would be a REAPER feature request, not OSARA. Note that this is consistent with how REAPER handles pasting of other things such as audio items.

Edit cursor follows focus in MIDI event list means the edit cursor will move as you move up and down in the event list. By default in REAPER, that is not what happens; the edit cursor never moves in the event list.

If you want to move the event list focus to the edit cursor, press control+f.
