### ISSUE TITLE
Add delta solo actions to the key map

### ISSUE THREAD

**Issue by RDMurray** [jcsteh/osara#664]
We need to find keys for:
- FX: Toggle delta solo for last focused FX

AND ONE OR BOTH OF
- FX: Clear delta solo for all project FX: I think this would be the most useful 
- FX: Clear delta solo for all FX on selected tracks

**Comment by ScottChesworth** [comment]
Ideally I'd like to see these on F6 seeing as everything else to do with solo lives there. How's about:
FX: Toggle delta solo for last focused FX: Alt+Shift+F6
FX: Clear delta solo for all project FX: Control+Alt+Shift+F6

**Comment by ScottChesworth** [comment]
There's also (I think) potential to replace "Track: Toggle solo for master track" which is currently on Shift+F6. I've never heard a use case for it, seems like one of those "might be useful at some point" assignments.

**Comment by RDMurray** [comment]
I think that all it does is silence hardware outputs from other tracks.  definitely not useful enough to take up a valuable key. Plus you can show the master track and use f6.

**Comment by ScottChesworth** [comment]
Well then, seeing as the Control+Alt+Shift modifier combination always seems to be unpopular, shall we do:
FX: Toggle delta solo for last focused FX: Alt+Shift+F6
FX: Clear delta solo for all project FX: Shift+F6
Shift being the modifier to clear delta for every effect in the project, which feels kinda like a master command, kinda. Add Alt to work with the selected track.
It seems a little odd to me that the more powerful action has one less modifier, but we have other examples of that, I'll survive. :)

**Comment by RDMurray** [comment]
It would still make sense the other way round.  Shift for delta solo, add alt to clear.  Alt being the modifier to clear everything on F5 to F9.

**Comment by RDMurray** [comment]
bumping, we are almost half way through the month.

**Comment by ScottChesworth** [comment]
> It would still make sense the other way round. Shift for delta solo, add alt to clear. Alt being the modifier to clear everything on F5 to F9.
> 
Fair point. Alt to clear is well established, let's roll with that. I'll add your keystrokes to the meta issue.
