### ISSUE TITLE
Add loop segment scrub to key map

### ISSUE THREAD

**Issue by RDMurray** [jcsteh/osara#665]
We need to find a key for 
- Scrub: Toggle looped-segment scrub at edit cursor

On the whatsapp group, @dgl1984  suggested a custom action to allow going straight into loop segment scrub from playback:
- View: Move edit cursor to play cursor
- Scrub: Toggle looped-segment scrub at edit cursor

**Comment by pitermach** [comment]
If this helps I’m using backslash for this, which was suggested by Garth in another issue

**Comment by ScottChesworth** [comment]
I'd prefer Slash.
1. It's closer to the arrows. 
2. It can be toggled using the same hand you'll be scrubbing with. 
3. Now that OSARA has the "Move relative to the play cursor for time movement commands during playback" option, I'm not finding much use for the "View: Move edit cursor to play cursor" action that's currently there.
Thoughts?

**Comment by RDMurray** [comment]
I think / is fine.  What about Derek's proposal?  I can't think of a situation where it would cause a problem.

**Comment by ScottChesworth** [comment]
> What about Derek's proposal?
> 
I like the functionality of it, but ideally I'd prefer to have looped-segment scrub actions respecting our "Move relative to the play cursor for time movement commands during playback" preference. Standard scrub already does this, and it feels strange for the modes to behave differently. If implemented, users could have whichever behaviour they prefer without their key map deviating from default assignments.

**Comment by ScottChesworth** [comment]
> I can't think of a situation where it would cause a problem.
> 
One slight issue with what I've proposed in the previous comment is that the toggle looped-segment scrub action specifically mentions the edit cursor. We'd be overriding that behaviour when "Move relative to the play cursor" is checked in OSARA Config. Does that matter?

**Comment by RDMurray** [comment]
We already override Reaper behaviour with that checkbox, so it should be fine.

**Comment by RDMurray** [comment]
done in #669 

I haven't seen any objections to "/" for the key.  Is it decided?

**Comment by jcsteh** [comment]
Note that https://github.com/jcsteh/osara/issues/665#issuecomment-1026684887 suggested backslash, not slash. Slash is already bound.

**Comment by jcsteh** [comment]
Ignore my previous comment. I missed part of the thread somehow.
