### ISSUE TITLE
Discussion: It is recommended to generate the Key map.html shortcut file while compiling osara

### ISSUE THREAD

**Issue by xingkong0113** [jcsteh/osara#671]
The current osara Key map and readme.md are stored in the same file.
It is recommended to separate the Key map section from the readme and use appveyor to generate the Key map.html file.
This way, if there is a new Key map update, users can better find and learn it.
thanks

**Comment by jcsteh** [comment]
Can you clarify why separating this out of the readme would make it easier
to discover changes? I don't follow how that would make it any easier at
all. Note that the current version of the readme is always available at
https://osara.reaperaccessibility.com/

**Comment by xingkong0113** [comment]
> Can you clarify why separating this out of the readme would make it easier to discover changes? I don't follow how that would make it any easier at all. Note that the current version of the readme is always available at https://osara.reaperaccessibility.com/

Thanks for the reminder!
Just to add
Sometimes it is not convenient to view osara's Key map from https://osara.reaperaccessibility.com when you are working offline on the audio.
In this case, if there is a Key map.html, it may solve the above problem

**Comment by jcsteh** [comment]
Okay. There has been some discussion about bundling the readme (or at least
the bulk of it) with OSARA. The problem is that this creates problems for
non-English users, since it's not currently possible to translate the
readme. I'm somewhat reluctant to bundle the documentation until we can
solve that problem somehow.

**Comment by jcsteh** [comment]
Note that you can press shift+f1 at any time within REAPER to have it
generate a full key map.

**Comment by xingkong0113** [comment]
> Note that you can press shift+f1 at any time within REAPER to have it generate a full key map.

Thank you for your note
I will
 close this issue.
