### ISSUE TITLE
Keymap: Assign key for "OSARA: Report regions, last project marker and items on selected tracks at current position"

### ISSUE THREAD

**Issue by RDMurray** [jcsteh/osara#672]
This action was just added in #668  

Control + shift would probably make sense to be consistent with other reporting commands.  Control+Shift+; or control+shift+ (what ever the key for next marker is; it's different on uk and us layouts) are free.  There is also Control+Shift+Alt+J, but I guess that wouldn't be popular.

**Comment by RDMurray** [comment]
Any thoughts anyone?

**Comment by ScottChesworth** [comment]
Control+Shift+R? Other region stuff is on R, and we'd sidestep the marker keystroke disparity.

**Comment by ScottChesworth** [comment]
The action's been available for a week and we've had no suggestions other than mine, so I'm gonna add Control+Shift+R to the meta issue.
