### ISSUE TITLE
The Newest Version of Osara Doesn't work on REAPER 6.47

### ISSUE THREAD

**Issue by Mike20001123** [jcsteh/osara#686]
It doesn't work at all, makes no difference from no instalation of Osara. My system is Windows 11 21H2 (x64) build 22000.527

**Comment by Mike20001123** [comment]
Version 2018.1 of Osara works instead.

**Comment by jcsteh** [comment]
Some questions:

1. If you open the Actions list with f4 and search for OSARA using the search box, do you se any actions in the list?
2. What screen reader are you using? Do you have any add-ons installed in your screen reader? If so, does the problem persist if you disable them?

**Comment by jcsteh** [comment]
There's nothing I can do about it in OSARA, I'm afraid. This seems to be an issue in Windows App Essentials experienced by several users. Curiously, I have that add-on installed here and I don't seem to have this problem.

CC @josephsl: Windows App Essentials seems to break UIA notification events on some systems, which is what OSARA uses to announce messages via screen readers.

**Comment by Mike20001123** [comment]
Very useful information! 

The interesting fact is that 2018.1 version of Osara is not affected. 

Hope this can be fixed soon, no matter by Osara team or Wintenapp team ~ 

Thanks again!

**Comment by Mike20001123** [comment]
Problem solved 👍 
I disabled "report notifications" for some reasons before and forgot to turn it back on. LOL.

**Comment by ScottChesworth** [comment]
Thanks for remembering to let us know, glad the show's back on the road. :)

**Comment by jcsteh** [comment]
Thanks Joseph.

Aside from being ancient, OSARA 2018.1 used a horrible MSAA hack instead of
UIA notification events, which is why it worked for you there. There are
various reasons for the change which I won't go into here, but suffice it
to say that it was necessary for various reasons.

**Comment by ScottChesworth** [comment]
Another OSARA user got bamboozled by this, bumping this thread in hope of increasing my understanding.
Here, I don't have the Win10 App Essentials addon installed. On my machine, "report notifications" is enabled by default. So two questions:
1. Does installing the Win10 App Essentials addon disable that setting?
2. if so, would leaving it enabled as a default break things for users of your addon @josephsl?
Thanks in advance for any clarification.

**Comment by josephsl** [comment]
Hi, Windows App Essentials add-on does not disable “report notifications” setting at all. However, it does turn off UIA notification event handling if “report notifications” is turned off after installing the add-on. That is, installing the add-on does not automatically turn off notifications from Reaper via OSARA. Thanks.

**Comment by ScottChesworth** [comment]
Gotcha. Thanks for the speedy reply.
