### ISSUE TITLE
New key map bindings and action feedback in Media Explorer

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#688]
In Reaper 6.47, Cockos introduced Media Explorer toolbar, relocated some controls, and as a consequence they're no longer part of the tab order. Those being:
- Tempo sync
- Auto-play
- Start on bar.

I've been back and forth with them about it and they want to keep this new design. So I guess the question now becomes, is there anything OSARA can do to simplify using those controls? Right now, reaching them unavoidably involves object navigation.

Here's a list of actions that I think would get us back to prior productivity if they can provide feedback:
- Tempo match: Toggle on/off (40023)
- Tempo match: /2 (40021)
- Tempo match: x2 (40022)
- Autoplay: Toggle on/off (1011)
- Start on bar: Toggle on/off (1012)

Thanks in advance for any implementation or advice on it.

**Comment by ScottChesworth** [comment]
It's the latter. There's no objection to the controls remaining in the tab order, they just haven't been able to get it to happen now that they're toolbar buttons. Or I should say, visually they're buttons on the toolbar. From NVDA perspective, they're all check boxes.

**Comment by jcsteh** [comment]
Okay, that makes sense. Yeah, Win32 toolbars are silly. Have they tried
setting TBSTYLE_FLAT and WS_TABSTOP? That should apparently make it
possible to tab to the toolbar and then to navigate it with the arrow keys.

**Comment by ScottChesworth** [comment]
I don't know the ins and outs of how they've been trying to do it, only that it was tricky. I'll pass that along.
