### ISSUE TITLE
OSARA intercepting Shift+F10 when plugin controls have focus

### ISSUE THREAD

**Issue by pitermach** [jcsteh/osara#689]
STR:

- Add the latest version of Surge XT to a track
- In the plugin interface, tab to any slider and press Shift+F10

Expected: The plugin's internal context menu should open.
Actual: Reaper's track context menu is opened instead, though it can't be navigated with the arrow keys.

This issue only comes up on Windows since Mac uses different keys for the menus. This problem just came up on the Surge Discord where a user couldn't get SHift+F10 to work, but for some other people it worked fine. I did some testing and narrowed it down to OSARA after reverting my keymap to default. If you assign OSARA's "Show first context menu" action to something other than Shift+F10 which was the case for me, then this issue doesn't occur.

**Comment by jcsteh** [comment]
I know this makes no difference to a user, but strictly speaking, OSARA isn't intercepting this. REAPER is, since this is a REAPER key binding. The reason that matters is that OSARA has no control over how REAPER key bindings work, including the cases where REAPER chooses to pass through to the window.

I guess we could fix this by implementing shift+f10 in the key hook instead of binding it in the key map, but... yuck.

**Comment by pitermach** [comment]
Hmm. Sounds like there's a lot of ugliness here indeed then ☹

Interestingly enough Reaper passes through Shift+F10 fine in the list of FX (which you can verify by turning keyboard help on in the FX dialog), it also lets the plugin see many other keys like CTRL+S, at least on Windows.

There are a few ways to work around this, but they're all also a bit awkward:

- Simulate a right click with the SR, which may sometimes not work if the mouse doesn't root correctly
- Use the "send all keyboard input to plugin" option, which saves per track so if you want it to stick you need to use a track template
- Reassign OSARA's menu keys - this is something I did to make them easier to hit because my keyboard's function row is very cramped. However I guess a lot of people are very used to this combo being used for menus everywhere.

The question is should this be left as it is now or perhaps if we should contact Cockos about this key being past through by default or think about reassigning Shift+F10 on the keymap. Because we're starting to see more plugins getting onboard the accessible Juce train this is probably going to come up more often, and I'm now wondering what I should tell developers on how they should make their right click menus accessible from the keyboard.

**Comment by ScottChesworth** [comment]
I'll ask Cockos if Reaper can release Shift+F10 once focus is in a plug-in GUI. Leaving this open until I get a response in case we need to hack around it.

**Comment by ScottChesworth** [comment]
Justin says possibly. He's gonna look into it in a couple days. I've set a reminder to nudge him in a week if we haven't seen anything in dev builds.

**Comment by jcsteh** [comment]
FWIW, this is easy enough to hook in OSARA's keyboard hook, albeit somewhat
ugly. So, if it's going to be a lot of effort for Cockos, it's probably
best to just hack around it and move on; bigger fish to fry and all that.

**Comment by ScottChesworth** [comment]
I'm thinking it'd be better implemented by Cockos because devs don't always have OSARA to test their keyboard UX in Reaper. Let's see what he says once he's had a chance to take a look.

**Comment by jcsteh** [comment]
I think this is only an issue when OSARA is installed, though, because
OSARA binds shift+f10 in the key map. Most users wouldn't bind shift+f10,
so I think it'd just get passed through to the plugin. Unless it doesn't
even then?

**Comment by ScottChesworth** [comment]
Fair point. I'm just about to turn in but will verify tomorrow.

**Comment by ScottChesworth** [comment]
@jcsteh is right, it's exclusively a mapping issue. It doesn't depend on whether OSARA is running, only on whether our current key map is being used. Does that make it one for us to hack around then? Shall I tell Justin he's off duty?

**Comment by jcsteh** [comment]
It's debatable. On one hand, you could argue REAPER should handle this just like it handles space, the arrow keys, etc. and bypass the key map when particular things have focus, given that it's a standard keystroke. On the other hand, OSARA is somewhat special in binding that key; I doubt any other extension would do that. Given that we already handle the applications key specially, it's probably easiest for us to just handle this. So yeah, let Justin off the hook. :)

**Comment by jcsteh** [comment]
Ug. Implementing this really hurt my brain, but I'll submit a PR in a sec.
