### ISSUE TITLE
Bind "Item properties: Normalize items (peak/RMS/LUFS)" to Control+Shift+N, replacing "Item properties: Normalize items to +0dB peak"?

### ISSUE THREAD

**Issue by manhcuong0312** [jcsteh/osara#699]
I usually use this feature, then I added that keystroke for my own keymab. Now I'd like to share that to community by adding it the default Ossara's keymab.  
Thank you.  
Cuong from Vietnam.

**Comment by ScottChesworth** [comment]
Hi @manhcuong0312, is there a reason why you've chosen to use the SWS action instead of "Item properties: Normalize items (peak/RMS/LUFS)"? Seems like the native Reaper action offers more flexibility.

**Comment by manhcuong0312** [comment]
Hi @ScottChesworth 
There is no reason. I only know the "Xenakios/SWS: Normalize selected takes to dB value" so I use it, and my goald is to normalize my audio so I don't care about where is the action come from.  
Thank you.

**Comment by ScottChesworth** [comment]
Thanks for confirming. In that case, I'd propose we map "Item properties: Normalize items (peak/RMS/LUFS)" to Control+Shift+N, replacing "Item properties: Normalize items to +0dB peak", as the newer action can provide the same functionality and a lot more where needed.

**Comment by ScottChesworth** [comment]
I've changed the title of your issue to reflect the current proposal so that I can add it to the task list for this month. Hope you don't mind. :)
