### ISSUE TITLE
Media Explorer actions

### ISSUE THREAD

**Issue by leejul** [jcsteh/osara#709]
Hi guys,

As the Media Explorer will remain what it is now, it would be interesting to have the following actions stated:
Autoplay: Toggle on/off
Start on bar: Toggle on/off
Tempo match: Toggle on/off
Tempo match: /2
Tempo match: x2
Thanks.

**Comment by RDMurray** [comment]
@ScottChesworth  It is possible to add feedback for these commands.  You can use `GetToggleCommandState2()` to get the state. See `midiEditorCommands.cpp` for examples.

Add your function to `postMExplorerCommands`.

**Comment by ScottChesworth** [comment]
Update: Cockos have made the toolbar control accessible, but it required some deep level work on SWELL, so will need to undergo a longer testing period than usual before it makes it into a stable release. I'm gonna take a look at getting some bindings and spoken feedback going to tide us over. Thanks for the hints Robbie.
