### ISSUE TITLE
gain reduction monitoring doesn't play nice with disabled holds in peak watcher

### ISSUE THREAD

**Issue by ObjectInSpace** [jcsteh/osara#717]
Unlike with peakDB or lufs, gain reduction triggers the peak watcher when the level drops below the specified amount, rather than above it. If holds are disabled or set to less than 1000MS, silence will trigger an endless stream of screenreader announcements no matter what level the watcher is set to. These interrupting all other feedback which makes it quite difficult to recover. This can happen in many circumstances: the track is removed, muted or disarmed, the effect is removed, etc. Interestingly enough, bypassing the effect causes it to stop sending values and remain at its previous level, which works just fine.

**Comment by ScottChesworth** [comment]
I can't reproduce this with ReaComp. Which plug-in are you monitoring gain reduction for there?

**Comment by ScottChesworth** [comment]
Don't think I've got that here. Does anyone else?

**Comment by ObjectInSpace** [comment]
I can reproduce this in reacomp by removing the plugin from the track while it is being monitored for gain reduction with holds disabled. NVDA starts to say "second watcher: -150DB" over and over but cuts itself off after the first s.

**Comment by jcsteh** [comment]
I think I understand what's happening here. I'll try to take a look as soon as I can.

**Comment by jcsteh** [comment]
And the fix was a single line of code.

**Comment by ptorpey** [comment]
Only because you are such a good programmer.  I’m sure others could have done it in 5 or 6 steps!  😁

**Comment by jcsteh** [comment]
In this case, I knew exactly what the problem was. However, I can tell you that even for an experienced programmer, sometimes the smallest fixes (even a single character) can take hours or even days to track down. The amount of code isn't necessarily proportionate to the amount of effort required. :)

**Comment by ptorpey** [comment]
Been there.  But I do admire your coding prowess!

 

--Pete

**Comment by ScottChesworth** [comment]
Bravissimo! Thanks for the fast fix.
