### ISSUE TITLE
In MIDI Editor, bind ; and ' to pass to main action

### ISSUE THREAD

**Issue by jcsteh** [jcsteh/osara#720]
In the main section, the ; (semi-colon) and ' (apostrophe) keys move to the previous and next marker, respectively. It would be useful to have those actions available in the MIDI Editor. While there are no marker actions in the MIDI Editor, we can bind them to pass through to the main section.

@ScottChesworth  noted that when he lasted tested, the MIDI editor movement commands didn't seem to respect the updated cursor position when the marker commands were used. I'm not sure if something's changed, but I can't reproduce that problem; it seems to work as expected for me.

**Comment by Lo-lo78** [comment]
But isn't there already an action that takes the actions of the Main section?
For example:
"Misc: Pass through key to main window"
Maybe you already know.

**Comment by jcsteh** [comment]
Right, but ; and ' aren't bound at all. I'm suggesting we bind them to that
action.

**Comment by MatejGolian** [comment]
@jcsteh, I'm definitely in on this.

**Comment by ScottChesworth** [comment]
Added to March key map update.
