### ISSUE TITLE
Mac keymap included with OSARA is incomplete/out of date

### ISSUE THREAD

**Issue by pitermach** [jcsteh/osara#721]
Just updated OSARA to osara_2022.1pre-892,eba87d7a, I wanted to make some keymap suggestions so decided to override the keymap to be on the same page.

When I did, I noticed that some of the actions, IE slash which should scrub, which it does on Windows, was still assigned to move the edit cursor on Mac. I took a look at the keymap in the .dmg with a text editor to be sure it wasn't a case of it not being copied correctly, and it doesn't appear to be.

I tried out all the changes introduced in #667. In the main section, the only one that appears to be mapped is cmd+F1 for OSARA about. Shift+F6 still toggles solo for the master track, the other new keys are unassigned and just ding. For the media explorer section, the volume keys aren't mapped either. I didn't look at the other sections

**Comment by ScottChesworth** [comment]
Many sorries, this one's on me. Fixing shortly.
