### ISSUE TITLE
Suggesting some Media Explorer actions

### ISSUE THREAD

**Issue by pitermach** [jcsteh/osara#722]
Over the last few Reaper versions the media explorer picked up quite a few new useful actions for file management, pitch adjustment and more. I just took some time to map them on my end and figured they might be useful for everyone. For the suggested keys I tried to follow convention for either the OS or main Reaper shortcut equivalents.

- ctrl+1 Browser: Go to shortcut 1 42098... ctrl+0 Browser: Go to shortcut 10 42107
- ctrl+Shift+N Create new folder 42129
- F2 Edit: Rename file 42078
- Delete File: Delete (trash bin) 42079
- CTRL+Enter Media: Insert in selected media items as new take 41003
- Alt+Enter Media: Insert on a new track 41001
- Shift+Enter Media: Insert into active sample player 42121
- Shift+Alt+Enter Media: Insert into sample player on a new track 42088
- ctrl+Shift+R Preview random file in current folder/database 42184
- Reassign preview: Rewind to start from Shift+left to CTRL+Home
- Shift+Left Preview: Play reversed 42185 ( (this is because Shift+Right is assigned to "Play, cancel reverse playback")
- Shift+0 Preview: adjust pitch by +1 semitones 42163
- Shift+9 Preview: adjust pitch by -1 semitones 42162
- ctrl+Backspace Preview: reset pitch 42239
- ctrl+D Set as favorite 42084
- alt+1 Tempo match: /2 40021
- alt+2 Tempo match: Toggle on/off 40023
- alt+3 Tempo match: x2 40022

**Comment by ScottChesworth** [comment]
This is lovely stuff, thanks man.

> Shift+Delete File: Delete permanently (no trash bin, no confirm)" 
> 
Oosh, that one makes me uneasy. It is a logical assignment, but I'd prefer confident users bind that for themselves. I'd be comfortable binding it in the default key map if there was a variant of the action that asks for confirmation, can request that from Cockos.

> that would require moving rewind to start to a different key
> 
Some variation of Home?

**Comment by pitermach** [comment]
Re: delete, yeah, there isn't a "no confirm" variant of immediate delete for some reason and I agree it could be dangerous. Probably worth asking Cockos for one.

And as for rewind, How about CTRL+Home? It would match up with moving to start of project.

**Comment by ScottChesworth** [comment]
I've requested "File: Delete permanently (no recycle, confirm)" from Cockos.
Can you edit your top comment to include Control+Home and temporarily remove Shift+Delete from the list for now, just so the top comment is accurate for whoever does the map updates this month? Once done, I'll add it to March's meta issue.

**Comment by pitermach** [comment]
Cool. I edited the first comment.

**Comment by ScottChesworth** [comment]
Thanks. The new delete action is coming from Cockos in the next cycle. It'll probably be in the April revision because we never bind actions until they're in a stable release.
