### ISSUE TITLE
Request for translation contextual info for some grid strings

### ISSUE THREAD

**Issue by jcsteh** [jcsteh/osara#724]
@leejul requested contextual information for these translatable strings via Crowdin:

grid one hundred twenty eighth
length sixty forth
length one hundred twenty eighth

@leejul, can you clarify what you're requesting here? Context is usually used when you need different translations where the same English string occurs in two places. I don't quite follow why you'd need that here? The grid is the same in the MIDI Editor as it is in the track view. Or are you asking for translator comments to explain what these strings mean?

**Comment by leejul** [comment]
Sorry for the confusion, I'm not sure I understand, do you mean 1/128 
and 1/64? If so, why is it written in letters? Is this to have the 
length of a note spoken in the MIDI editor?

Thanks.

**Comment by ScottChesworth** [comment]
We write the numbers out in words to make sure that all speech synths will report consistently.

**Comment by jcsteh** [comment]
I think this has been cleared up.
