### ISSUE TITLE
Osara Doesn't Care Which CC Lane Is Selected

### ISSUE THREAD

**Issue by MatejGolian** [jcsteh/osara#730]
I've included a sample project below. It seems that Osara's CC navigation commands don't actually take the selected CC lane into account. Not that the CCs on that lane get ignored, it's rather that Osara always seems to move between all CCs on all lanes. Even if you select a completely empty lane, when using the navigation commands, Osara moves on to the other lanes.
[CC Lane Issue.rpp.txt](https://github.com/jcsteh/osara/files/8322918/CC.Lane.Issue.rpp.txt)

**Comment by MatejGolian** [comment]
Well, in that case I'm not smart enough to be able to tell whether this really is a bug or not, but you're right - the command names don't mention the active lane in any way, so judging by their names, these actions do indeed perform as expected. So I guess we can call this more of a feature request then. I think that it would make sense to have commands that would operate on the selected lane only. Maybe it's not absolutely necessary to get rid of the current actions - they could still come in useful in some scenarios. Adding 2 new actions would perhaps be a better idea.
The reason why the current behavior can feel like a bug is that one could assume (like I did) that that's what the lane selection commands are for - namely to tell the CC navigation actions what to operate on.

**Comment by jcsteh** [comment]
Thanks for the additional context. That's helpful. I confess I don't work with CCs that much, so I'm probably not the best judge of the best UX here. I'll defer to @leonardder on that for now.

**Comment by MatejGolian** [comment]
My pleasure! Actually now I realize that it would have to be at least 4 new actions - 2 for navigation and 2 for navigation + selection. Further more, I don't know how this would impact noncontinuous selection - ideally one would want that to operate just on the active lane when needed as well. Honestly, I would prefer the current behavior to change, so if adding so many new actions could cause confusion down the road and if others agree, maybe rewriting the current ones could be better after all.

**Comment by leonardder** [comment]
I never understood these lanes actually, aren't they basically filters for a particular controller? Also, wasn't there a problem with selecting lanes anyway?

**Comment by MatejGolian** [comment]
@leonardder, you are correct - lanes are essentially like filters. The way I see it, their advantage is that one can manipulate any kind of CC message depending on type right from the piano roll without actually engaging the event filter while still having access to note events. The current behavior in conjunction with the event filter facilitates similar behavior, so to a certain extent it may boil down to personal workflow preference.
I don't know about any problem related to lane selection. Not saying that there isn't one - it's just that I don't know about it.

**Comment by leonardder** [comment]
I looked into this briefly and it seems pretty complex, since we would have to reinvent a wheel. We can ask REAPER the current CC lane, but there's no way to find out to what CC lane a CC belongs. There's also a lane for pitch and the current move to prev/next cc actions ignore these.

**Comment by MatejGolian** [comment]
Thank you for looking into it. It's a bit unfortunate that it's how it is, but I wouldn't call this a high priority issue compared to some of the other issues here, so if you don't mind, we could leave this issue open - who knows maybe there will be some change on the Reaper side of things in the future.

**Comment by leonardder** [comment]
Thanks. We could always request something from Cockos to enumerate CCs in a lane.

**Comment by MatejGolian** [comment]
I have finally decided to open an FR for this over at the forum. The link to the thread can be found below. As I pointed out over there as well, this is not the most urgent accessibility-related issue there is, but I figured why not...
https://forum.cockos.com/showthread.php?p=2607253

**Comment by Lo-lo78** [comment]
Yes, in the plan roll a reaper action that includes a CC would be very useful.
I hope Justin implements it.
👍

**Comment by MatejGolian** [comment]
@ScottChesworth, what are your thoughts on asking Justin about this? I know that the time my request has been out on the forums is not particularly long considering how things work in Reaper-land. It's just that I'm not sure that Justin or any of the guys in charge have read it. If or when they decide to address it is completely up to them and I don't mean to urge them and I definitely don't want to appear ungrateful either. That being said, I'd feel better knowing that they've at least read it. For that reason, I've been on the fence on contacting Justin directly.

**Comment by ScottChesworth** [comment]
Sure, I'll give Justin a nudge.

**Comment by MatejGolian** [comment]
I could do it myself, but if you two already have a kind of relationship going (which you probably 
do), I don't mind if you ask him instead - that is if that's OK. Many thanks.

**Comment by ScottChesworth** [comment]
Done. Will letcha know what comes back.

**Comment by MatejGolian** [comment]
Thanks man, it's really appreciated...

**Comment by ScottChesworth** [comment]
The conversation is a-flowing. Justin has proposed several ways forward and I need opinions from the folk most likely to work on this, so probably @jcsteh, @leonardder and @RDMurray. Here's what's been offered:

1. Do you want an API that lets you say "Set the currently selected (or first if nothing selected) piano roll lane to the type that will best show this MIDI CC"?
2. Or do you want it the other way -- does this CC event appear in this lane? That's a little trickier as there can be some complex rules involved (e.g. 14-bit lanes have a pair of CCs, etc)
3. Or a third way, a MIDI_GetCC_ForLane() which gives you a filtered list for the selected piano roll lane?
4. Fourth option -- we could provide some code which tells you whether a CC would be in a lane based on the existing lane types (this would be doable without us providing the code, though having the code would make it less tedious)...

Happy to bring anyone who's likely to work on this in on the email thread of course

**Comment by MatejGolian** [comment]
Thanks Scott for setting this into motion and of course it's great that Justin is willing to give us yet another improvement. So kudos to him.
BTW, I'm not a programmer, but to me option number 3 seems to be exactly what we want. Either way, I think adding this kind of functionality to the Reaper API could be useful to the ReaScripters out there as well...

**Comment by MatejGolian** [comment]
@jcsteh, @leonardder and/or @RDMurray, any thoughts yet? Sorry for being so pushy, but it's quite a big thing that Justin is willing to enhance the API to make CC lanes more usable to us. Therefore it could be a good thing to let him know how the Osara developers would prefer it all to behave while the iron is still hot, so to speak.

**Comment by MatejGolian** [comment]
@ScottChesworth, is Justin still willing to update this aspect of Reaper for us? I hope so, because it would be a huge improvement for those who spend most of their time in the MIDI editor. That being said, if there's ever going to be an update of this nature, I'm guessing that it will only be implemented after Reaper 7 comes out. Either way, getting something done about this would be tremendously appreciated.

**Comment by ScottChesworth** [comment]
Haven't nagged Cockos about it for a while, but I'd assume it's still improvable. Gonna need feedback on https://github.com/jcsteh/osara/issues/730#issuecomment-1417293624 before I make any more moves here, I'm not the best person to choose which of those proposals we should go with.

**Comment by jcsteh** [comment]
I've been looking into this a bit more. A question before we do anything else: does anyone understand what the velocity lane is for? I'm confused by it because notes already have velocity information, so what does this velocity lane do? Also, is the pitch lane for pitch bends or actual note pitches?

**Comment by Lo-lo78** [comment]
@jcsteh 
Usually in standard MIDI velocity is the parameter that manages the pressure of the sound in a MIDI input.
I think Reaper thought of a velocity lane to better sculpt the midi parts.
Maybe it's more practical than working with single events.
I'm pretty sure it's the same velocity.
Better investigate!
🫤

**Comment by jcsteh** [comment]
I understand what velocity is, but notes already specify velocity information and you can already select notes. So I don't quite follow how being able to select velocity via the CC lane is useful. I think it might have something to do with being able to draw curves or something, but I'm really not sure. It feels like we need someone sighted to way in on the workflow here.

**Comment by ScottChesworth** [comment]
> I don't quite follow how being able to select velocity via the CC lane is useful. I think it might have something to do with being able to draw curves or something, but I'm really not sure. It feels like we need someone sighted to way in on the workflow here.
> 
Paging @mespotine and @AZSlow3, can either of you explain how this works?

**Comment by mespotine** [comment]
Can't help on this one, since I almost never use the Midi Editor...

**Comment by ultrasound1372** [comment]
If I had to guess I'd say it's based on effectively dubbing in velocity given a stream of MIDI notes with some, say fixed, velocity encoded in them. The lane would act as a sort of modifier, either additive or scaling I'm not actually sure, to liven up the dynamics a bit without having to go fiddling with the individual notes?

**Comment by ultrasound1372** [comment]
Also, I think option 3 from that list of 4 would indeed be the most practical if I understand what lanes are to be used for. The case of 14-bit values is tricky but that one would be able to deal with it cleanly even if it doesn't do the whole merge thing.

**Comment by MatejGolian** [comment]
I can ask over at the forum in case we still need more info - maybe someone would be willing to chime in.

**Comment by mespotine** [comment]
> I can ask over at the forum in case we still need more info - maybe someone would be willing to chime in.

That's a great idea.

**Comment by MatejGolian** [comment]
For the record, I have asked for help in my original feature request on the forums and I've also started one other new thread in the dev section, but nothing so far.

**Comment by MatejGolian** [comment]
Due to lack of response on the forum, could we ask Justin directly about this?
@ScottChesworth, I'm happy to do so myself if you give me an E-mail address or if you don't have the time to contact him in the foreseeable future.

**Comment by MatejGolian** [comment]
Thanks for the clarification, Scott. It would be nice to get the ball rolling at least somewhat, as who knows - it may take some time to implement this, even once we have all the answers we need.

**Comment by jcsteh** [comment]
I really think we need sighted clarification from someone who uses this on how the UX works before we start digging into technical details of how we could implement it. For example, what does the velocity lane do? I believe CC lanes can support envelopes. How does that work? Can you actually draw point to point curves like you can in track/take envelopes or is it just a visual feature which plots the points between two points for you (so you end up with lots of little CC events)?

**Comment by ScottChesworth** [comment]
Agreed, hoping to get these questions answered soon.

**Comment by jcsteh** [comment]
So I think this can be done by looking at the current CC lane and the CC data and skipping CCs which don't match. This is Justin's option 4 in https://github.com/jcsteh/osara/issues/730#issuecomment-1417293624.

Unfortunately, this is a lot harder than it might seem. The code for findCC is hurting my head because it has to deal with the fact that there can be multiple CCs at the same position, and worse, CCs at the same position aren't sorted. So instead of just skipping CCs that don't match, we have to somehow... something. 🤯

**Comment by MatejGolian** [comment]
> We have to somehow... something. 🤯

I like that formulation. 🙂

**Comment by jcsteh** [comment]
I'm very slowly noodling on some code for this, but it's very much at the "not remotely helpful, I don't really know what the hell I'm doing" stage at this point. Still, I'll self-assign this for now.
