### ISSUE TITLE
FR CA trad string bug

### ISSUE THREAD

**Issue by leejul** [jcsteh/osara#731]
Hi,

The following string no longer works for FR/CA translation:
#. Used when moving notes in the MIDI
#. editor. {} is replaced by the number of notes, e.g. 
#. "3 notes pixel right"
msgid "{} note pixel right"
msgid_plural "{} notes pixel right"
The translation in the .po file is not what I wrote.
Thanks.

**Comment by jcsteh** [comment]
Can you clarify what you mean by "The translation in the .po file is not
what I wrote"? What did you write and what does OSARA report instead?

**Comment by leejul** [comment]
OSARA correctly states what is in the .po file but the translation in 
the .po file when I update OSARA is not what I wrote on crowdin.com.
I changed this string a few months ago.
Here's what's in the .po file.
msgid "{} note pixel right"
msgid_plural "{} notes pixel right"
msgstr[0] "{} note déplacée d'un pixel à droite"
msgstr[1] "{} note déplacée d'un pixel à droite"

Here is what I wrote on crowdin.com:
msgid "{} note pixel right"
msgid_plural "{} notes pixel right"
msgstr[0] "{} note déplacée d'un pixel vers la droite
msgstr[1] "{} notes déplacées d'un pixel vers la droite

**Comment by leejul** [comment]
Problem solved, thanks.
