### ISSUE TITLE
Toggles failing to speak when added using new map, suspected user error

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#732]
I'm trying to add some new feedback to accompany suggested assignments in March's key map update, but so far, nothing I've added is reporting. Here's two lines of code to compare. If anyone can spot what I'm doing wrong, I'd appreciate being nudged in the right direction.

- Code from @jcsteh which reports as expected:
	{{MAIN_SECTION, 40346}, {"full screen", "normal screen"}}, // Toggle fullscreen
- Code from me that is stubbornly silent:
	{{MAIN_SECTION, 40408}, {"showed Pre FX Volume envelope", "hid Pre FX Volume envelope"}}, // Track: Toggle track pre-FX volume envelope visible

No build errors, but no talking either. Please give whatever time you can to assist the dimwitted. Thanks. :)

**Comment by RDMurray** [comment]
I can't check right now, but is it definitely a toggle action?  That is does it have an on or off state in the action list?

**Comment by ScottChesworth** [comment]
Aha! I was assuming that all of the actions I've tried to add today would have on/off states because they say toggle in their names, but nope, that's not an assumption a hat can be hung on. Thanks man, mystery solved.

**Comment by jcsteh** [comment]
You could try binding this to cmdToggleTrackEnvelope; search for cmdToggleTrackEnvelope in reaper_osara.cpp and use that as an example binding. That's a little heavy handed, as it has to look through all envelopes on the track rather than just querying the one we know changed, but it shouldn't be a problem and it's probably easier than writing special code for each type of envelope like I did for postToggleTrackVolumeEnvelope. Or you could copy what I did for postToggleTrackVolumeEnvelope, but that requires knowing the internal name of the envelope and is a bit more messing about in general.

**Comment by ScottChesworth** [comment]
> Or you could copy what I did for postToggleTrackVolumeEnvelope, but that requires knowing the internal name of the envelope and is a bit more messing about in general.
> 
I spent a while chasing that dragon. Couldn't get it to say anything other than hid and the wrong envelope type.
Is "<VOLENV2" the internal value you're referring to in postToggleTrackVolumeEnvelope? Near as I could tell from the API docs, the 2 would become 1 for pre-fx, but that didn't build.

**Comment by jcsteh** [comment]
I don't know why changing the 2 to a 1 wouldn't build. Silly question, but
I'm guessing you renamed the new function and all that? What was the
compiler error?

cmdToggleTrackEnvelope seems reasonable enough if you want to give that a
shot.

**Comment by ScottChesworth** [comment]
Got it reporting using cmdToggleTrackEnvelope, thanks! I'm gonna push that for now so all necessary feedback is licked.
Still gonna revisit the other approach before we merge though. It's irking me, surely I should be coping with code that's 99% reusable by now.

**Comment by jcsteh** [comment]
If you want to throw me the output of git diff and the error output from
scons, I can try to help.

**Comment by ScottChesworth** [comment]
Thanks, might take you up on that once I've had another shot at it.

**Comment by RDMurray** [comment]
See the similar commands for volume and pan in envelopeCommands.cpp.
