### ISSUE TITLE
FR/CA trad string issue

### ISSUE THREAD

**Issue by leejul** [jcsteh/osara#733]
Hi,

Enabling all of the following actions in the Media Explorer are spoken in English.
The name of the action is spoken in French but not the word Enabled by OSARA.
On the other hand, the Disabled word works perfectly.
Autoplay: Toggle on/off
Tempo match: Toggle on/off
Start on bar: Toggle on/off
Thanks guyes.

**Comment by jcsteh** [comment]
Remember, translations are not synced from Crowdin to OSARA automatically. This "enabled" string was only added very recently, so it just hasn't made it into OSARA yet, even though you may have translated it.
