### ISSUE TITLE
Media Explorer: Assign Shift+Delete to "File: Delete (no recycle)"

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#736]
This is a list of issues for the April Key map update, due to be merged on 2022-04-30.
Please open an issue for each suggestion during the first half of October, mentioning key map in the title.
If you're not comfortable enough with GitHub to open issues yet, you can also float requests/ideas here, just leave a comment below. Again, requests/ideas to be submitted during the first half of October please.

# proposed changes
## Media Explorer
[ ] Assign Shift+Delete to "File: Delete (no recycle)"

**Comment by leejul** [comment]
Is it possible to do a toggle action to enable/disable the following OSARA function: Report changes made via control surfaces?
Thank you guys.

**Comment by tbdalgaard** [comment]
Would #660 be possible ?

**Comment by pitermach** [comment]
Now that Reaper 6.54 added the media explorer action "File: Delete (no recycle)", it's probably worth mapping to Shift+Delete like we discussed during the initial batch of media explorer keys.

Also though this is probably one for May or even later would be curious to hear your thoughts on #737

**Comment by RDMurray** [comment]
Updated title and first comment.

**Comment by RDMurray** [comment]
@pitermach I added Shift+Delete in the media explorer to the first comment above as it seems like a no-brainer.

@leejul there is now an action "OSARA: Toggle Report changes made via control surfaces". Are you suggesting this should be on the default key map, or do you just require the action for use with CSI?

@tbdalgaard I think we should get more input on #660  from RWP with it being such a big change to a core function.

**Comment by RDMurray** [comment]
See #799 about assigning control+. to Set length for next inserted note: dotted preserving division length in the MIDI editor.

**Comment by jcsteh** [comment]
It's been quite some time since October 2022 and we don't seem to be doing these regular, bulk key map updates any more, so I'm re-scoping this just to cover the Media Explorer change.
