### ISSUE TITLE
*Bug with the translation for a language that supports singular and plural

### ISSUE THREAD

**Issue by ElCrackLoko** [jcsteh/osara#740]
Hello everyone. I think I had commented on this in a translation issue that in the end I think was closed when the final update was made; so I don't know if my message finally arrived or was displayed.

Regarding the verbalization of comments when muting one or several notes/chords in the Midi editor, ("muted") that in Spanish this action must be notified both in singular ("muteada") and in plural ("muteadas"). Tried to fix, but to no avail. The comment is verbalized in the singular only.

**Comment by ScottChesworth** [comment]
Oops, sorry, guess I didn't notice there was an outstanding request before closing the issue.
@leonardder, would you have time to look into adapting your contribution in #278?

**Comment by jcsteh** [comment]
As I understand it, @leonardder fixed this in 6921f49.

**Comment by ScottChesworth** [comment]
Two cases of "oops, guess I missed that" in a row? This is starting to sound like a @mattymc2's gig. :)
So what needs to happen to get the fix into Spanish ears? Is it just a case of waiting until someone has time to update to the most recent translation templates?

**Comment by mattymc2** [comment]
🖕

**Comment by ScottChesworth** [comment]
Yeah, that was the one you would've used to play the right note.

**Comment by ElCrackLoko** [comment]
> ¿Dos casos de "ups, supongo que me perdí eso" seguidos? Esto empieza a sonar como un concierto de @mattymc2 . :) Entonces, ¿qué debe suceder para que la solución llegue a los oídos españoles? ¿Se trata simplemente de esperar hasta que alguien tenga tiempo de actualizarse a las plantillas de traducción más recientes?

That's right brother, I'm with the most recent update of everything, the one from April 1st. Both from translation template and from Osara. A hug.

> Según tengo entendido, @leonardder arregló esto en [6921f49](https://github.com/jcsteh/osara/commit/6921f4936f10cdccd853b9f71e1e8a10d128f2c5) .

No no, the problem is not solved. The attempt was made but it still gives the error, that's why I opened this here.

**Comment by jcsteh** [comment]
Can you tell us the exact steps you're taking including keyboard commands, what string is being used and what string you expected instead? I wonder whether there's another instance of the string somewhere that is causing trouble here.

**Comment by ElCrackLoko** [comment]
Of course.
Let's imagine the next scenario; in the Midi editor, I have 3 notes, for example.
First of all we have a single note, (var 1, beat 1 pixel 0) with nothing else. Next, we have 2 notes, (bar 1, beat 2, pixel 0) placed in the same frame. It can be 2, 3, 4, 5, whatever you want to imagine. Then I mute (Alt + M) the note that is alone, the one in the first place (1.1.00) until there, Osara report is correct because he tells me that I have muted a note and he mentions it as it is, in the singular. Then, I go to the 3 notes in (1.2.00) and mute (Alt+M) this is where the origin of the Bug with the translations occurs. Which is why Osara report.
pulso 2 2 notas2 muteada. This is where I should distinguish what is in the plural (notas muteadas) and not singular (nota muteada) I mean? hope so. Guys, sorry for the inconvenience, seriously. If this cannot be corrected, you could find another way so that it is mentioned indistinctly if it is singular or plural. If this is going to be the case, in order not to cause any further inconvenience, the line that was created for the plural could be reversed and not be there unnecessarily. You will say. I know you sure have better things to do, I leave you both alternatives.
