### ISSUE TITLE
Unable to open automation item properties dialogue for pooled items on a second envelope

### ISSUE THREAD

**Issue by Chessel85** [jcsteh/osara#741]
How to recreate problem:
New project and create a track
Add a time selection of one bar
Show and arm the volume envelope
Press control shift I to create an automation item
Control left arrow key to select the automation item
Press shift f2 to open up properties dialogue.  Can give it a name and change values fine.
Press escape to close dialogue.
Arm envelope and control left to select automation item.
Open context sensitive menu  and select create pooled duplicate This creates a second automation item after the first one.
Can successfully select either automation item and edit properties with shift f2.
Can copy and paste onto the same envelope and still select item and edit properties.
Now copy automation item, show and arm pan envelope and paste automation item on this.
Can select it and edit properties but it has a new name suggesting it isn't pooled although has same values as first automation item.
Close this new automation item although can re-select it and edit properties if desired.
Return to volume envelope, select an automation item and now shift f2 does nothing.  Focus is on the track.
Returning to automation item on pan envelope now also doesn't allow the properties dialogue to be opened.

The key trigger appears to be to copy and paste an automation item onto a second envelope and then returning to the original item.  

Desired behaviour is to be able to open the properties dialogue for the pooled automation items.
I've not been able to establish whether this is a Reaper bug (which would be pretty unlikely), an OSARA bug, or my misunderstanding of how this feature works and in fact it is just user error.  I have had another person try the above steps and they experienced the same problem.

**Comment by CastleStarter** [comment]
Further investigations show problem happens if item is not pooled.
I've also had sighted help from a non-Reaper person and they confirmed nothing was being displayed.  It isn't just a case that focus isn't being obtained.

**Comment by ScottChesworth** [comment]
Hmm, so if it's not linked to pooling, is the thing that breaks it two automation items being on the timeline at an identical location?

**Comment by CastleStarter** [comment]
Doesn't look like it. I placed my original automation item at 1.1.0, and the
duplicate on a second track at 2.1.0 and I couldn't open the first one.

I think it is going to different tracks that causes the problem.  But as you
are supposed to be able to save and load automation items it surely must be
okay to place them on different tracks.

Interestingly, if you are in the situation  where the properties dialogue
doesn't open you can cut and then paste it so it is in exactly the same
place but it now allows you to open the properties dialogue.  I guess that
is a workaround.

Chris G

**Comment by jcsteh** [comment]
Can you still reproduce this with the latest OSARA snapshot? I'm wondering whether this is because we were previously failing to unselect automation items in different envelopes (and tracks) when you moved between automation items. In that case, you might have been unknowingly trying to show properties for items in different pools, which doesn't make sense and so REAPER says no. I fixed this today in #1029.

**Comment by Chessel85** [comment]
Great. This is now working as I'd expect.  I can copy and paste, or duplicate pooled automation items on different envelopes and then move between envelopes and select as I wish.  Many thanks.
