### ISSUE TITLE
Number of points reported when selecting all envelope points is number plus one when created by an automation item 

### ISSUE THREAD

**Issue by Chessel85** [jcsteh/osara#742]
How to recreate
New project, new track
Show and arm volume envelope and insert an automation item
Set envelope shape and press escape 
Press control A and a number of points are selected e.g. 5 points selected
Now use shift J and K to move between points and only n minus one, or in this case 4, points can be accessed.

Desired behaviour is that number of points that can be reached with alt J and K matches the number of points selected when hitting control A.
I did start this entry because Reaper was crashing on me when I started using alt J and K but now I can't make it happen reliably.  Which is good I guess.
Whether this mis-reporting of points is important or not I don't know but it doesn't happen if the points are entered manually.
Hopefully this is just a miscount and not some fundamental mistreatment of automation points.  But I am puzzled by some of the points that get generated but this is surely a Reaper thing.  For example, a saw wave with 1 cycle I would think would generate just two points but I think it generates 4 or 5.

**Comment by jcsteh** [comment]
It's unclear to me whether you selected the automation item or not before moving between points. There are a few key things to understand here:

1. When you select an automation item, OSARA restricts envelope point navigation within the automation item. This makes it much easier to understand what points lie within the automation item and what points don't, as well as making navigation more efficient.
2. If you just want to navigate the points that aren't within an automation item, focus the envelope again with alt+l or alt+shift+l.
3. When you select all envelope points with control+a, REAPER selects all points in the envelope, even across automation items.

Given all of this, is there still a bug here, or is this just a misunderstanding?

**Comment by Chessel85** [comment]
Thanks for explaining and I think it is simply a misunderstanding on my part.  All makes sense now.
