### ISSUE TITLE
Is it possible to put the name of the track in the title of the OSARA FX Parameters?

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#743]
Hello,
after so many hours in the mixing session I happened to forget the name of the track while I was setting up an FX on Reaper.
I tried with NVDA + t but it was just telling me FX Parameters.
One might think for example:
"FX Parameters: Track 1 "piano"
Maybe I'm stoned but I think it can come in handy.
Greetings!

**Comment by Lo-lo78** [comment]
@jcsteh 
If it is not useful to others we can close this issue.

**Comment by ScottChesworth** [comment]
Keep it open, I might be able to get it done with Jamie's notes, and would like to see it happen either way.
