### ISSUE TITLE
Productivity suggestions for context menu that opens FX Params dialog

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#745]
1. Can names be stripped in that context menu, matching how they're reported when moving to a track or item nowadays?
2. Could each menu item be prepended with a number? This would make it possible to hit P then 6 to view the parameters for the sixth plug-in instantiated on a track or item, for example. It would also add clarity when the first and last plug-ins on your track/item are the same.

As ever, thanks in advance to anyone who has time to tackle this.

**Comment by ScottChesworth** [comment]
This took me back to the good old days when I just had ideas and you did them instead of me spending entire evenings shouting at the computer. Thanks! Very refreshing. :)

**Comment by mattymc2** [comment]
Very grateful for this. The meaning to open this up as an issue for ages
