### ISSUE TITLE
In Windows, focus no longer lands in "Render to file name" dialog

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#747]
This is the commit that affects focus: https://github.com/jcsteh/osara/commit/53d8cef3f3011194f95f5c13d3118b1ec79fa4d8

To reproduce, hit alt+R to run the "File: Render project, using the most recent render settings, with a new target file name" action.
With any snapshot of OSARA prior to 11th April, focus would go to the file name edit field as expected.
Since the commit above, no dice.

Thanks in advance if there's anything that can be done to tighten this up.

**Comment by jcsteh** [comment]
I haven't investigated this yet, but my guess is that REAPER briefly opens
some other dialog (perhaps the Render dialog), closes it and then opens the
render file name dialog. That would make OSARA return focus to where it was
before, but in this case, that's not what we want. I can't really think of
a way to fix that short of reverting the foreground hack.
