### ISSUE TITLE
Reading Value in Parameter List

### ISSUE THREAD

**Issue by TrapYanto** [jcsteh/osara#748]
In the track parameter list: "P". Jaws, by means of special scripts, is able to announce the value of the parameter we are on at that moment, without necessarily positioning itself on the slider with "TAB"; this is not the case using NVDA. In fact, to know the value currently set, it is compulsory to reach the modification slider with "TAB", once we position ourselves on it. would it be possible to have a behavior similar to that of Jaws? It greatly improves the consultation of values without interacting with its content, even when we do not need it.

Thanks.

**Comment by ScottChesworth** [comment]
Isn't it more efficient to hit Tab and interrupt the parameter label whenever you do need to know the value?

**Comment by pitermach** [comment]
Don't know if this works with the jaws scripts yet or not, but if you use CTRL+Tab to move through the parameters the value does get announced, and you can do that even while the slider has focus.

**Comment by leonardder** [comment]
Yes, the behavior with ctrl+tab was implemented in #703.
I'm pretty convinced that this should fix your issue and therefore I'm closing this. Feel free to disagree with that decision, we can always reopen.

**Comment by ranetto** [comment]
Hello, I also miss this functionality a lot, I don't think it's the same thing in some plugins like pro Q 3, where there are hundreds of parameters, pass in a list and listen to the value of a parameter to press maybe three or 400 times the control more tabs with the related slowdown consequences. What do you think? I still can't use NVDA with reaper for this very problem and I'm forced to use jaws which is much less responsive.
