### ISSUE TITLE
Recent change to window titles has impact on JAWS scripts

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#753]
This just came my way from Snowman Jim. I wasn't aware anything about window titles had change so not sure what to advise. Can anyone provide more info in the comments? Jim says:

When you press p to look at the effect parameters,  the parent window of the window that gains focus,  used to have a name,  such as
Track Parameters,  or item parameters.  But,  when I call the jaws builtin to get that name,  it is blank now.
I can get around this if I can find all the cases,  but it will cause more processing,  which means possible slow down.
The name does seem to be on screen,  and is in the MSAA object,  but not the window name itself.
It is far cheaper for me to get the window name,  I think.
Can those names be restored? Or,  do I need to find a workaround now.

Thanks in advance for any advice.

**Comment by jcsteh** [comment]
I don't know what the JAWS builtin does, but as far as I'm aware, nothing
has changed here. I just verified that the Win32 API function GetWindowText
returns the window title for the dialog as it always did. In fact, that's
how the visual title and MSAA get the title; there is nowhere else they
could get it from.

**Comment by jcsteh** [comment]
Closing since this is not an issue with OSARA. I suspect someone is going to have to debug what JAWS is doing here.

**Comment by ScottChesworth** [comment]
Thanks for the quick response anyway. Jim is chasing now.

**Comment by davidengebretson** [comment]
I'm curious if it has anything to do with the fact Jim is using Win7 and most people nowadays use Win 10 or Win11...

**Comment by jcsteh** [comment]
That's intriguing, but no, I can't see any reason that would have any
impact. The one thing that has changed very recently is that there is now a
label in the dialog showing the parameter value for the benefit of sighted
users. However, that should have no impact at all on the window text of the
dialog itself (the parent window).

**Comment by davidengebretson** [comment]
What field are you populating "label in the dialog showing the parameter value for the benefit of sighted
users"?
Also, from your last message it sounds like there are dialogs inside of dialogs, is this correct?

**Comment by ScottChesworth** [comment]
Jim figured it out. Turned out to be something JAWS specific and obscure.

**Comment by ScottChesworth** [comment]
Oi, be nice.

**Comment by jcsteh** [comment]
The label for sighted users is just a static text control in the dialog. It
isn't reachable in the tab order, so the only way you'd see it with a
screen reader is with the review cursor.

No, it's just a single dialog, no nesting. I said "parent window" because
the dialog is always the parent window of the controls inside it.
