### ISSUE TITLE
Non-correct pitch values zero trailing

### ISSUE THREAD

**Issue by outsidepro-arts** [jcsteh/osara#760]
OSARA trims zeros in a reported pitch value, and if there will be value like "-20.0", OSARA will report it as "-2 semitones". The same behavior watches an another integer values which ends with zeros (-10.0=-1, -30.0=-3 and etc).

**Comment by jcsteh** [comment]
Can you please provide exact steps to reproduce?

**Comment by RDMurray** [comment]
The problem is in the function formatDouble and it is my fault.  It looks obvious now, I don't know how I missed it.
