### ISSUE TITLE
FX oversampling cannot be verified

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#769]
Hello
since the latest versions of Reaper it is no longer possible to check if an instance of an FX chain or the entire FX chain is 2x 3x 4x.
It's a great new Reaper feature!
When this Reaper feature came out it was possible with the object navigator to read if the FX was 2x 3x 4x.
With Reaper 6.60 you can only read the latency and the CPU.
Can a solution be found with OSARA?
Greetings!

**Comment by Lo-lo78** [comment]
@ScottChesworth Yes, great!
I have an interesting idea.
In your opinion, in the FX chain it might be useful to put the indication 2x 3x 4x before the name of the plugin?
For instance:

VST: ReaGate (Cockos)
2x VST: ReaEQ (Cockos)
4x VST: ReaComp (Cockos)

This is for FX instances. If we set up the entire FX chain:

2x VST: ReaGate (Cockos)
2x VST: ReaEQ (Cockos)
2x VST: ReaComp (Cockos)

Or you might think about putting the entire FX chain where the latency and the CPU are.
What do you think?

**Comment by jcsteh** [comment]
I'm not sure modifying the names of the items in the list for this purpose
will be popular with sighted users. It's also very difficult to hack names
of list items with OSARA. So, I think we're going to need an alternative
way to access this.

**Comment by ScottChesworth** [comment]
> I think we're going to need an alternative way to access this.
> 
Maybe Cockos could include it for each effect in the window title? Easy to read when you want to know about it, easy to ignore when you don't.
