### ISSUE TITLE
Peak watcher, an idea, maybe?

### ISSUE THREAD

**Issue by jprykiel** [jcsteh/osara#771]
Dear Osaras,
this idea might be totally wrong and due to my technical ignorance but here it is anyway. 
You have the Osara configuration dialogue, who's settings are stored it seems, as they remain As you set them if you close and relaunch Reaper. 
How about adding a setting for at least one of the peak watchers so that it could be Linked to the master track by default? 
What do you say? 

Cheers, 
JPR

**Comment by jcsteh** [comment]
This request is covered (albeit more broadly) by #100.
