### ISSUE TITLE
Track selection ranges

### ISSUE THREAD

**Issue by mattymc2** [jcsteh/osara#772]
Hey guys. So just had a thought regarding the verbosity of track selection. No idea if this will be doable or how much work would be involved but here's my idea.
Currently when you have a bunch of tracks selected osara Will read out The track number and the name if there is one one at a time when you press control shift space. If I have 20 tracks selected it takes awhile for it to read out each track number and name one after another. Usually I just want to know if I've manage to select all of them. Instead could it say something like "tracks 1 through 20 selected"?
 if they're nonconsecutive tracks you could say something like "tracks 1 through five, 10 through 23 and 32 selected"  
If you wanted more detailed information you could still press control shift space twice to bring up the dialogue with a text field.
By  extension I imagine this could probably work with items too but haven't given that one a lot of thought yet.
Curious to hear your thoughts
Cheers 
Matt

**Comment by ScottChesworth** [comment]
I seem to remember @jscholes rustled up a working implementation of this a while back. Think he wanted to clean up the code before submitting. Did you ever get around to that James? If not, are you likely to? Failing that, is it on GitHub somewhere and can we pinch it?

**Comment by jscholes** [comment]
I never did get around to it, and it was long enough ago that I've forgotten what did need cleaning up.  It was my first shot at writing C++, so almost guaranteed that there is something.

Unfortunately I'm not on my primary work machine with the C++ build toolchain I used.  I may be able to look at this at some point, but for now, here's the code I modified in `reaper_osara.cpp`:

```
string formatTrackRange(int start, char* startName, int end, char* endName) {
	ostringstream s;
	if (start == end) {
		s << end;
		if (endName && endName[0]) {
	s << " " << endName;
		}
		return s.str();
	}
	int diff = end - start;
	s << start;
	if (startName && startName[0]) {
		s << " " << startName;
	}
	if (diff == 1) {
		s << " and ";
	} else {
		s << " through ";
	}
	s << end;
	if (endName && endName[0]) {
		s << " " << endName;
	}
	return s.str();
}

string formatTracksWithState(const char* prefix, TrackStateCheck checkState,
	bool includeMaster, bool multiLine, bool outputIfNone = true
) {
	int rangeStart = 0;
	char* startingTrackName;
	char* prevTrackName;
	bool inActiveRange = false;
	ostringstream s;

	if (prefix) {
		s << prefix << ":" <<
			(multiLine ? "\r\n" : " ");
	}

	int count = 0;
	if(includeMaster) {
		MediaTrack* master = GetMasterTrack(nullptr);
		if (checkState(master)) {
			++count;
			s << translate("master") << (multiLine ? "\r\n" : ", ");
		}
	}

	int trackCount = CountTracks(0);
	for (int i = 0; i < trackCount; ++i) {
		int trackNumber = i + 1;
		MediaTrack* track = GetTrack(nullptr, i);
		char* name = (char*)GetSetMediaTrackInfo(track, "P_NAME", NULL);

		if (checkState(track)) {
			prevTrackName = name;
			if (trackNumber == trackCount) {
				s << (multiLine ? "\r\n" : ", ") << formatTrackRange(inActiveRange ? rangeStart : trackCount, startingTrackName, trackCount, name);
				break;
			}
			if (inActiveRange) {
				continue; // not interested in tracks within a range, only those at each end
			}

			inActiveRange = true;
			rangeStart = trackNumber;
			startingTrackName = name;
		} else {
			if (inActiveRange) {
				++count;
				if (count > 1) {
					s << (multiLine ? "\r\n" : ", ");
				}
				s << formatTrackRange(rangeStart, startingTrackName, i, prevTrackName);
				startingTrackName = NULL;
				rangeStart = 0;
				inActiveRange = false;
			}
		}
	}
	if (count == 0) {
		if (!outputIfNone) {
			return "";
		}
		// Translators: Used when reporting all tracks which are muted, soloed, etc.
		// to indicate that no tracks are muted, soloed, etc.
		s << translate("none");
	}
	return s.str();
}
```

**Comment by ScottChesworth** [comment]
Thanks for the code @jscholes.
Most of that goes over my head, but from what I remember it seemed to be working well when I tried your test build here. I'm wondering what @jcsteh and @RDMurray think, could we include that code without blowing anything up?

**Comment by jcsteh** [comment]
Thanks. The code looks good to me for the most part, though it'll need a bit of tweaking to make it properly translatable.

One UX concern is that this doesn't handle the case where "Report track numbers" is disabled. How should this behave in that case? Currently, we honour that setting and skip the track number, but I wonder whether that's appropriate when we're dealing with ranges.

**Comment by mattymc2** [comment]
I feel like because the information isn’t as verbose it wouldn’t matter quite as much to have that in the full report. I guess that would also affect what track names get reported as well, this wouldn’t bother me but I can see how it would bother other people I suppose.

**Comment by ScottChesworth** [comment]
I turn track numbers off here, but hearing numbers being included with a range report wouldn't be a problem. If anything, I'd say it adds useful context, gives you a quick way to verify that you've selected a block of 8 tracks here, a block of 4 there and the correct couple of strays without needing to remember that track 47 happens to be the accordion or whatever.
