### ISSUE TITLE
Seeking help to troubleshoot build environment on new machine

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#776]
Setting up a new build environment here. Think I've done everything as per the ReadMe, but scons says no. Here are details of what I've installed followed by a paste of what happens when I try to build. If anyone's got time to help troubleshoot I'd really appreciate it, would like to do some key map catch up this month.

* Build Tools for Visual Studio 2022. I checked Desktop development with C++, C++ ATL for latest v143 build tools (x86 & x64) and C++ Clang tools for Windows during the installer.
* Python 3.10.5
* SCons 4.4.0
* NSIS 3.08
* I've cloned OSARA using the --recursive option

Here cometh the scons splurge:
scons: Reading SConscript files ...
The system cannot find the file specified.
Building using 16 jobs
The system cannot find the file specified.
scons: done reading SConscript files.
scons: Building targets ...
Creating 'build\x86\buildVersion.h'
clang-cl /Fobuild\x86\controlSurface.obj /c src\controlSurface.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
clang-cl /Fobuild\x86\dictionary.obj /c include\tinygettext\src\dictionary.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
clang-cl /Fobuild\x86\envelopeCommands.obj /c src\envelopeCommands.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
clang-cl /Fobuild\x86\exports.obj /c src\exports.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
clang-cl /Fobuild\x86\format.obj /c include\fmt\src\format.cc /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
include\tinygettext\src\dictionary.cpp(20,clang-cl /Fobuild\x86\fxChain.obj /c src\fxChain.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
10): fatal error: 'assert.h' file not found
#include <assert.h>In file included from
src\controlSurface.cpp:         ^~~~~~~~~~8
:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\string:11:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\xstring:clang-cl /Fobuild\x86\language.obj /c include\tinygettext\src\language.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
13:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\iosfwd:9:
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\yvals.h(12,10): clang-cl /Fobuild\x86\log.obj /c include\tinygettext\src\log.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
fatal error:
      In file included from 'crtdbg.h'src\envelopeCommands.cpp :file9 :
notIn file included from  C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\stringfound:In file included from 11src\exports.cpp
:
:#include <crtdbg.h>In file included from 10
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\xstring:
:         ^~~~~~~~~~13
src/osara.hclang-cl /Fobuild\x86\midiEditorCommands.obj /c src\midiEditorCommands.cpp /TP /clang:-std=c++20 /EH
:
(In file included from 13C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\iosfwd,:119):
:clang-cl /Fobuild\x86\os.obj /c include\fmt\src\os.cc /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
 C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\yvals.h(12,fatal error: 10): 'windows.h'In file included from  include\fmt\src\format.ccfile:fatal error:  8not:
 In file included from
foundinclude\fmt\include\fmt/format-inl.h      'crtdbg.h':
 file# include <windows.h>11
:
notIn file included from e\algorithm:11          ^~~~~~~~~~~ :al Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\includ
In file included from
foundIn file included from clang-cl /Fobuild\x86\paramsUi.obj /c src\paramsUi.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
src\fxChain.cppC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\xmemory
::#include <crtdbg.h>1112
:
clang-cl /Fobuild\x86\peakWatcher.obj /c src\peakWatcher.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
:
In file included from include\tinygettext\src\language.cpp:src/osara.hC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\cstdlib         ^~~~~~~~~~20((
:
1312In file included from ,,10):11include\tinygettext\include\tinygettext/language.hpp:):  23:
fatal error: In file included from clang-cl /Fobuild\x86\plural_forms.obj /c include\tinygettext\src\plural_forms.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
fatal error: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\string:'windows.h'11
:
In file included from       file not foundC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\xstring'math.h' file
:13# include <windows.h> :

notIn file included from clang-cl /Fobuild\x86\po_parser.obj /c include\tinygettext\src\po_parser.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
 C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\iosfwdIn file included from           ^~~~~~~~~~~found:9src\midiEditorCommands.cpp
In file included from
#include <math.h>:9:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\string:
include\tinygettext\src\log.cpp:
11:
         ^~~~~~~~
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\yvals.h:C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\xstringIn file included from include\fmt\src\os.ccmt\include /nologo /fobuild\x86\reaper_osara.res src\reaper_osara.rc
20:(::Iinclude\f
131213In file included from C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\iostream:11:
:
In file included from :
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\istreamC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\iosfwd:,:In file included from clang-cl /Fobuild\x86\reaper_osara.obj /c src\reaper_osara.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
9In file included from 1011src\peakWatcher.cppinclude\fmt\include\fmt/os.h:
'rc' is not recognized as an internal or external command,
operable program or batch file.
src\paramsUi.cpp):
(:::C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\yvals.hIn file included from 9119In file included from  (C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\ostream,scons: *** [build\x86\reaper_osara.res] Error 1
:
:
include\tinygettext\src\plural_forms.cpp12:10In file included from :C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\cerrno,11fatal error: )C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\string20(10:
:::

12)In file included from  11In file included from       ,: :
In file included from 'crtdbg.h'10fatal error: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\iosinclude\tinygettext\include\tinygettext/plural_forms.hppC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\xstring fatal error: ):::file'math.h':112313
   :
:
:
      notfileIn file included from In file included from In file included from 'crtdbg.h' fatal error:  In file included from C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\xlocnumC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\stringC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\iosfwd foundnot:
:fileinclude\tinygettext\src\po_parser.cpp:
11      9 :12found#include <crtdbg.h>:
'errno.h':
not20:

In file included from
  :
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\yvals.hC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\xstring         ^~~~~~~~~~#include <math.h>filefoundIn file included from C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\cmath(:

 src\reaper_osara.cppinclude\tinygettext\include\tinygettext/po_parser.hpp
:1213not(         ^~~~~~~~:#include <crtdbg.h>9,:
 10
23
:
10In file included from found,:
         ^~~~~~~~~~)C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\yvals.hC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\iosfwd10
In file included from
:(:)#include <errno.h>C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\iosfwd 129:
:,:
 9fatal error: 10         ^~~~~~~~~:
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\yvals.h)
fatal error: (
:C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include\yvals.h12       ('initguid.h','crtdbg.h'12 10 ,fatal error: file)file10 : )not
 not:         found'crtdbg.h'foundfatal error:

filefatal error: #include <initguid.h>#include <crtdbg.h>

not
 'crtdbg.h'         ^~~~~~~~~~~~         ^~~~~~~~~~      found

'crtdbg.h'file
  #include <crtdbg.h>filenot
  not          ^~~~~~~~~~foundfound

#include <crtdbg.h>
#include <crtdbg.h>
         ^~~~~~~~~~
         ^~~~~~~~~~
1 error generated.
1 error generated.
1 error generated.
scons: *** [build\x86\exports.obj] Error 1
scons: *** [build\x86\dictionary.obj] Error 1
scons: *** [build\x86\language.obj] Error 1
1 error generated.
scons: *** [build\x86\plural_forms.obj] Error 1
1 error generated.
scons: *** [build\x86\log.obj] Error 1
1 error generated.
scons: *** [build\x86\po_parser.obj] Error 1
1 error generated.
scons: *** [build\x86\controlSurface.obj] Error 1
1 error generated.
1 error generated.
scons: *** [build\x86\os.obj] Error 1
scons: *** [build\x86\format.obj] Error 1
1 error generated.
1 error generated.
scons: *** [build\x86\envelopeCommands.obj] Error 1
scons: *** [build\x86\fxChain.obj] Error 1
1 error generated.
scons: *** [build\x86\paramsUi.obj] Error 1
1 error generated.
scons: *** [build\x86\peakWatcher.obj] Error 1
1 error generated.
1 error generated.
scons: *** [build\x86\midiEditorCommands.obj] Error 1
scons: *** [build\x86\reaper_osara.obj] Error 1
scons: building terminated because of errors.

Any ideas?

**Comment by jcsteh** [comment]
Perhaps the Windows SDK didn't get installed? I would have thought that was
default, but perhaps not.

When installing Build Tools, in the Installation details tree view, under
Desktop for C++, Optional, ensure the following is selected: Windows 11 SDK
(10.0.22000.0)..

**Comment by ScottChesworth** [comment]
Ah, didn't realise that was needed. I was trying to do a leaner installation of the dependencies, figured I could save a couple GB. Will try adding that now.

**Comment by ScottChesworth** [comment]
That's got it building. Thanks!

**Comment by jcsteh** [comment]
Probably worth documenting this requirement explicitly, even if it is enabled by default, so someone else doesn't make the same mistake.

**Comment by ScottChesworth** [comment]
Sure, I can do that. Do you know whether this is the only default that's essential?

**Comment by jcsteh** [comment]
I'm not sure, but we can add more later if needed.
