### ISSUE TITLE
New Project and Peakwatcher Loudness Meter Integration

### ISSUE THREAD

**Issue by Justinmac84** [jcsteh/osara#778]
Hi, Anyone else experiencing the bug where you set the second peak watcher to monitor the master in true peak level, finish a project, close it out, open a new project tab, reset that Peakwatcher and it crashes Reaper? Happening consistently with me here.

**Comment by jcsteh** [comment]
I haven't experienced it, but thinking about it, it probably makes sense to
me that this would happen. OSARA doesn't realise the project has closed, so
it tries to access a track which no longer exists in memory and crashiness
ensues. Now I think about it, I actually don't know why we don't crash when
you delete a track you're watching.

I'll need to ponder on how to fix this.
