### ISSUE TITLE
Question about Output message and CSI

### ISSUE THREAD

**Issue by leejul** [jcsteh/osara#779]
Hi James, 
We would like to integrate the OSARA Output Message function into the CSI source code. 
Is it possible for you to give us the information and the files to add so that it works. 
It would be great to be able to just write, Speech "the message to do stated", in the zone files. 
So far we need to create a Script file with the Output Message function per sentence we want to make spoken and we call this action ID in the zone file on each page. 
Thanks for your help and suggestion. 
reaperaccessible@gmail.com

**Comment by ScottChesworth** [comment]
A few things to be aware of before going down this road.
1. This function doesn't provide much in the way of flexibility. It's not dynamic, conditional or anything fancy like that, it's purely a method of delivering reports to screen readers piggybacking on OSARA's ability to do that.
2. Note that this may not work on Windows when certain GUI controls have focus such as list boxes and trees.
3. Please be sure to test thoroughly, with a focus on finding edge cases. It's easy to accidentally deliver inaccurate reports. There are many scenarios where no speech feedback is preferable to misleading speech feedback.
4. ideally, add something like "This functionality is always best implemented in direct consultation with screen reader users" to the CSI docs.

Assuming all of that is understood, here's the code you'll need in each supported language:

C: "void osara_outputMessage(const char* message)"

EEL2: "osara_outputMessage("message")" (requires REAPER 6.24 or later)
EEL2: "extension_api("osara_outputMessage", "message")" (legacy syntax, also useful for allowing script to run when third-party extension is not installed)

Lua: "reaper.osara_outputMessage(string message)"

Python: "osara_outputMessage(String message)"

**Comment by jcsteh** [comment]
>     2. Note that this may not work on Windows when certain GUI controls have focus such as list boxes and trees.

I realise you said "may", but just to clarify, this hasn't been a problem on Windows 10 with NVDA and Narrator for quite some time, and with the most recent JAWS scripts, I believe it is no longer an issue with JAWS either. However, that still leaves ZDSR, SuperNova and other Windows versions.

> C: "void osara_outputMessage(const char* message)"

In addition to declaring the function type, you'll need to retrieve a function pointer from the API. Something like this:

```
const void (*osara_outputMessage)(const char* message) = nullptr;
...
// In some init code
osara_outputMessage = (decltype(osara_outputMessage))plugin_getapi("osara_outputMessage");
...
// Somewhere you want to report a message
if (osara_outputMessage) {
  osara_outputMessage("some message");
}
```

> Python: "osara_outputMessage(String message)"

I believe Python requires some additional declaration and maybe reaper.osara_outputMessage or something like that. I'm not quite sure.

**Comment by leejul** [comment]
Okay, thanks guys.
But to make everything clearer, here is the goal.
With version 2.0 of CSI, it is now possible to make sub zones.
Sub zones are additional pages of settings.

With version 1.0, it was possible to make a single .zon file with a 
single parameterss page.
Now each page has its own .zon file.
Example:
Page 1: Main
Page 2: Compressor
Page 3: EQ
When changing the page, we would like to vocalize the name of the page 
when loading it.
For the rest, everything is already vocalized by activating Report 
changes via control surface.
This is why we want to integrate OSARA's Output message function into 
the CSI 2.0 source code.
Otherwise, is there another way to proceed that would be less complex?
As I mentioned, for the moment, we have to create a Script in lua which 
contains only the Output message function and call the script at the 
beginning of each page.
Best would be to embed the Output message function in the CSI source 
code as we could just write this.
Example:
Speech "Compressor"
When changing pages, NVDA would speak the speech string.
Any help or suggestion is welcome.
Thanks.

**Comment by jcsteh** [comment]
No, I think what you're proposing makes sense. Someone would need to
integrate this into CSI's C++ code.

Scott was just making the point that it should be documented that this
should only be used in consultation with screen reader users, as otherwise,
things could get very verbose.

**Comment by ScottChesworth** [comment]
Output_message is totally separate from surface feedback, it doesn't do anything until you send strings to it, so the configuration you've described shouldn't cause any problems.

**Comment by ScottChesworth** [comment]
> I realise you said "may", but just to clarify, this hasn't been a problem on Windows 10 with NVDA and Narrator for quite some time, and with the most recent JAWS scripts, I believe it is no longer an issue with JAWS either. However, that still leaves ZDSR, SuperNova and other Windows versions.
> 
I lifted that point wholesale from the ReaScript API docs. Could be clarified I reckon. How would I update that text, send the update to Cockos?

**Comment by leejul** [comment]
Ok thanks guys.

**Comment by jcsteh** [comment]
That message comes from line 34 of OSARA's src/exports.cpp.

**Comment by jcsteh** [comment]
I guess while SuperNova still has this issue, we probably can't remove that message. :(
