### ISSUE TITLE
request, please add support for selection when moving through a project. 

### ISSUE THREAD

**Issue by soundwarrior20** [jcsteh/osara#78]
Hello in reaaccess there is a feature to select Data whilst moving through A project by pressing shift and page up and down to select by bar, by pressing shift control Page up and page down you can select by beat. Also by pressing shift and The left and right arrow keys you can make selections with the zoom cursor, all the selections are spoken. Please add support for this feature to osara because it would make precise editing easier especially for electronic musicians who use precise quantising on a regular basis. Thanks for your help kind regards trey.

**Comment by leonardder** [comment]
It is already possible to select with shift+left and right arrow. Selecting bars and beats however is a function I'd also like to see.

**Comment by soundwarrior20** [comment]
Please could this feature also be added to the upcoming Mac OS X version? Thanks very much kind regards Trey

**Comment by jcsteh** [comment]
Closing as a duplicate in favour of #152, which is clearer.
