### ISSUE TITLE
Media Explorer preview volume announcements are broken

### ISSUE THREAD

**Issue by pitermach** [jcsteh/osara#781]
First reported on the RWP list, with the latest version of OSARA and Reaper if you use the Alt+Shift+Up/Down hotkeys to adjust the media explorer preview volume, the value is no longer spoken and OSARA just says "DB". The report was on Windows but I can also reproduce this on Mac.

Reaper 6.65 changed the media explorer window by adding an edit box to type in a preview volume in addition to the slider, perhaps these changes are what caused this to break.

**Comment by ScottChesworth** [comment]
Pretty sure it's some @RDMurray code that's gotten broken by the GUI change. Robbie, are you around to have a gander?

**Comment by RDMurray** [comment]
yes. It should be easy to fix, I'll look at it tonight.
