### ISSUE TITLE
Is it possible to move from one marker to another in the OSARA FX Parameters?

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#784]
Hi everyone!
It would be very helpful if a solution could be found.
It is not important to have the numbers from 0 to 9 as it would be that with the tab you go to the progress box and with the two keys of the keymap you could move between the markers.
Obviously I was thinking about actions:

Markers: Go to next marker/project end
Markers: Go to previous marker/project start

I find it impractical to exit the FX Parameters and change markers from the tcp every time to move around the project.
Greetings!

**Comment by jcsteh** [comment]
My work in #702 should fix this, but I'm yet to get the go-ahead from @ScottChesworth . :) Nevertheless, I suggest you try a build from that PR and see if it works for you.
