### ISSUE TITLE
Automation item suggestions

### ISSUE THREAD

**Issue by leejul** [jcsteh/osara#795]
Hi guys,
Here are some suggested actions to make editing automation items more accessible.
Convert selected envelope points to automation item
Move left edge of selected automation items to start of time selection 
Move right edge of selected automation items to end of time selection 
Select all automation items on selected track 
Select all automation items on all tracks 
Select all automation items in time selection on selected track 
Select all automation items in time selection on all tracks 
Split automation items at time selection
Split selected automation items at project markers 
Unselect all automation items in time selection on selected track 
Unselect all automation items in time selection on all tracks 
Move cursor left to edge of automation item
Move cursor right to edge of automation item
Move selected automation item left by grid size
Move selected automation item right by grid size
Trim left edge of automation item to edit cursor
Trim right edge of automation item to edit cursor
Thanks.

**Comment by ScottChesworth** [comment]
Send the request to Cockos. If they get added then maybe OSARA can look at making them contextual, but all of these should be core REAPER actions.
