### ISSUE TITLE
say number of split items

### ISSUE THREAD

**Issue by dgl1984** [jcsteh/osara#8]
There are times when I've made attempts to split items, and the result has failed.  There are also other cases where I've accidentally created more items than I intended.  It would be ideal to have osara report when items are split, and how many were created.

**Comment by jcsteh** [comment]
Are these two actions sufficient? If not, please list the actions for which you desire this reporting.

**Comment by GianlucaApollaro** [comment]
Hi, I like that we have the number of items split reported, but there's a little bug. If you split, then play a bit, pause and make another split, the number of items doesn't get reported; Basically it can't repeat an information if it is the same as what was previously spoken

**Comment by dgl1984** [comment]
Confirmed.
To reiterate a point though, if osara sends any other messages through 
between the first and second splits, you will hear he second split reported.

**Comment by jcsteh** [comment]
Since there are no objections, I'm assuming these two actions are sufficient. Closing.
