### ISSUE TITLE
Using CSI with OSARA and Jaws - Speech issues

### ISSUE THREAD

**Issue by davidkreynolds** [jcsteh/osara#800]
When using NVDA with CSI, I press the FX button on my control surface, and it says FX correctly. Running with JAWS (latest version) it says FX eight times. This may be a CSI problem, and I know that OSARA is primarily tested with NVDA, but just thought you may be able to throw some light on it.
This might be of some help:
the JAWS UIANotification event is being fired many times within a 1 millisecond window,  with the same exact arguments.  they are:
notificationKind = 4
notificationProcessing = 3
displayString = REAPER_OSARA
If you need me to try anything, please get in touch.

**Comment by ScottChesworth** [comment]
Snowman would likely be a good port of call, if you haven't asked him already.

**Comment by davidkreynolds** [comment]
Hmm, did that. We mucked about under the hood, and he said the best thing to do was to file it as an issue.

**Comment by jcsteh** [comment]
If you're not seeing this anywhere else in OSARA (and I don't see why you would be), this is almost certainly because CSI is calling osara_outputMessage more than once with the same string. That would need to be fixed in CSI.

**Comment by leejul** [comment]
If the problem does not appear with NVDA but only with Jaws, the problem 
is probably not with CSI.
No issues like this have been reported with NVDA.
Can you do the same test but unchek the checkbox, Report changes made 
via control surface?
Thanks.

**Comment by jcsteh** [comment]
It's possible JAWS ignores the NotificationProcessing_MostRecent flag, which should cause it to interrupt the previous notification. In contrast, NVDA interrupts in this case. That means that if you fire 6 notifications with that flag set, NVDA will only read the last one, even if it stutters a bit before it does. That might explain why you're not seeing this with NVDA, but it's just a guess. If I'm right, we have two bugs which should probably be fixed, one in JAWS (or the scripts) and one in CSI.

**Comment by davidkreynolds** [comment]
Jamie,

Contacted both parties involved now, so thanks for the heads up.

**Comment by ScottChesworth** [comment]
Snowman has worked around this in JAWS scripts version 60.
