### ISSUE TITLE
The up arrow and down arrow in the close button Close the FX parameter window by mistake

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#803]
Hi, for a few days I noticed that the FX Parameters window was closing for no reason.
By mistake I used the arrows to change the value of the parameter and I happened to find myself in the Close button. But I was tabbed and I realized that I was in the TCP.
Can it be corrected by just making space to close the window?
Up arrow and down arrow can often happen to use them by mistake. One more tab is enough to close the window unwittingly.
Thank you!

**Comment by cn-peter** [comment]
I also have the above problems

**Comment by ScottChesworth** [comment]
The only clue I can offer to anyone who's smart enough to fix this is that it's something that happened between pre-977 and the current snapshot that broke it. Can't reproduce with a portable I found laying around here that's still running pre977, can defo reproduce with most recent snapshot.

**Comment by jcsteh** [comment]
So... recall how you folks wanted as many keyboard commands to pass through to the main section as possible? That's why this is happening. :) Up and down arrow are previous and next track, and since buttons don't do anything with arrow keys, they go through to the main section.

I can make an exception for the arrow keys on buttons, of course, but then we get into the complicated question of what else should be an exception.

**Comment by ScottChesworth** [comment]
> Up and down arrow are previous and next track, and since buttons don't do anything with arrow keys, they go through to the main section.
> 
Oops, obvious now you've said it.

> I can make an exception for the arrow keys on buttons, of course, but then we get into the complicated question of what else should be an exception.
> 
C'mon man, it's a simple if statement. if has bad idea, print "nope". :)

So I guess we need to make a list of anything that can cause the dialog to be dismissed and assess the workload?

**Comment by jcsteh** [comment]
In the interest of pragmatism, I've made an exception for just the up and down arrow keys now, as that seems like an easy mistake to make.
