### ISSUE TITLE
Time selection: with the home and end keys OSARA announces the bar and the percentage but not the beat

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#814]
Hello everybody.
I've been using time selection a lot and I've noticed that OSARA doesn't announce the beat.
I would need to know the exact location of the selection while using the home and end shortcuts.
I use the old key map and the shortcuts are home and end. I don't know if they are the same as the new key map.
The actions I'm referring to are:
Go to start of time selection
Go to end of time selection
Currently OSARA announces:
start bar 1 18%
end bar 4 beat 3 33%
The selection also has the beat that OSARA does not announce:
start bar 1 beat 3 18%
end bar 4 beat 3 33%
True, with the shortcut ctrl+shift+space you have all the useful information but to be faster it is also useful to quickly know with the shortcuts home and end where the start and end of the time selection are.
Thank you and greetings!

**Comment by ScottChesworth** [comment]
By default, we report dynamically. In that example, the beat isn't being reported because there's no difference to report when moving between those two positions. Checking "Report full time for time movement commands" in OSARA Config will get the behaviour you want.
