### ISSUE TITLE
Feature request: make time movement reporting in piano roll optional

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#816]
This request came in via RWP. A thread where I've suggested existing strategies will be linked below for reference, but I'll attempt to summarize.

In the piano roll view of the MIDI editor, OSARA reports edit cursor position (and optionalllly) number of notes when hitting Left or Right arrows. The relevant actions are:
OSARA: Move to previous chord (ID _OSARA_PREVCHORD)
OSARA: Move to next chord (ID _OSARA_NEXTCHORD)
OSARA: Move to previous chord and add to selection (ID _OSARA_PREVCHORDKEEPSEL)
OSARA: Move to next chord and add to selection (ID _OSARA_NEXTCHORDKEEPSEL)
As things stand we always hear position reported in addition to note previews. The request is, can we provide an option in OSARA Config to make time movement reports optional, along similar lines to our "Report MIDI notes in MIDI editor" feature? This would be used during workflows where note previews are enough information to go on and screen reader feedback isn't needed.

Of course, I've suggested muting the screen reader on the fly, but it seems there's a case being made where this behavior could be set as a constant for users who are happy with note previews.
I've custom actioned the behaviour that's been requested and tried editing some MIDI here. At a glance it was a decent UX and I'd likely use the feature if it existed. I haven't put any time into identifying corner cases and, given the tone in the thread where it's been requested, I'm not intending to dig any deeper.

Thread:
https://groups.io/g/rwp/topic/95600676#91345

**Comment by jcsteh** [comment]
Is the argument here that this is somewhat similar to scrubbing? That makes me wonder whether we should tie it to the scrubbing option.

**Comment by ScottChesworth** [comment]
Interestingly, that was exactly what was said. If you came up with that without reading the thread, then perhaps it's a more logical assumtion than I first thought.

**Comment by tbdalgaard** [comment]
Is the argument here that this is somewhat similar to scrubbing? That makes me wonder whether we should tie it to the scrubbing option.Yes, got the exact same idea after reading the first messages on rwp. Could this work for most users?Sendt fra min iPhone via Braille Sense U2/MBrailleDen 12. dec. 2022 kl. 22.31 skrev James Teh ***@***.***>:﻿
Is the argument here that this is somewhat similar to scrubbing? That makes me wonder whether we should tie it to the scrubbing option.
