### ISSUE TITLE
Consider Changing the "Report position when scrubbing" Label

### ISSUE THREAD

**Issue by MatejGolian** [jcsteh/osara#821]
Hello,
This is not a big issue by any means, in fact, whether it is an issue at all is up for debate, but I wanted to throw it out here.
Since now the option "Report position when scrubbing" is tied to the reporting of events in the MIDI editor (which is not technically scrubbing), wouldn't it make sense to change the label in the Osara config dialog so that it gives a clearer indication of what that toggle does now? Could something like "Report position when scrubbing and navigating in the MIDI editor" work? I know that that's quite long and maybe a bit clumsy, but it's just a suggestion. That being said, if that label were to be changed, may be it would make sense to rename the "OSARA: Toggle Report position when scrubbing" action as well and I don't know whether you, @jcsteh, have any objections against that.
Either way, it's just an idea and as I wrote, it's nothing serious, so do as you wish. It's just that I think that the current wording has become technically inaccurate... 🙂

**Comment by jcsteh** [comment]
This is absolutely a fair point. I actually considered changing the label for this reason when I implemented this. Here are my thoughts on this:

1. Coming up with a precise label for this is tricky. "Report position when scrubbing and navigating in the MIDI editor" makes sense at first glance, but it depends how you define navigating. This change very specifically impacts the commands to move to next/previous chord. It doesn't affect CC commands, movement by grid, etc. and I don't think it makes sense for it to impact those. So, now we have to say something like "Report position when scrubbing and navigating between chords in the MIDI editor", which is even longer. And some users may not even immediately think of left/right arrows as navigating chords, particularly if they're dealing with monophonic instruments or rhythm tracks, so they might not even get the meaning here.
2. Even though it's not technically scrubbing, it's about the closest thing you have in the MIDI editor. The idea with scrubbing in audio is to do fine editing, moving one little tiny chunk at a time until you find what you want, listening as you go. That's exactly what move to next/previous chord do in the MIDI editor, albeit with inconsistent time granularity. So, yes, it's not strictly correct, but I'd argue (admittedly with no actual evidence or data) that most users will intuitively get the analogy.
3. This is documented in the readme at least, so users who are confused can discover this, albeit less immediately than is ideal.

All of this said, I'm happy to make the change if there's at least some consensus that this is worth doing.

Note that if I change the label in the dialog, it will also automatically change the name of the setting toggle action, which I think is reasonable.

**Comment by MatejGolian** [comment]
@jcsteh, how about something like "Report position when scrubbing audio and navigating between MIDI chords"? I originally thought of just "Report position when scrubbing and navigating between MIDI chords", but that feels more ambiguous, although it does sound cleaner. I also thought of "Report position when navigating between MIDI chords and scrubbing", but I don't like those 2 things being in that order...
Your points are of course valid and apart from this last suggestion, I think I won't have any more ideas. That being said, maybe someone else will eventually chime in whit their opinion on this whole subject.

**Comment by dgl1984** [comment]
I find myself in a situation where I'd like to hear the notes I'm on in 
the midi editor, but not time position information when scrubbing audio.

Do these parameters need to be linked?  How is that proving helpful?

**Comment by jcsteh** [comment]
Additional config options means more complexity for the user. The thinking here (as explained above) was that scrubbing was a pretty close match.

It'd be interesting to know whether your use case is just different kinds of editing (in which case you'd likely have to adjust options if you happened to be dealing with different kinds of audio) or whether there's something fundamentally different about MIDI editing for you. Can you elaborate on the reasoning here?

**Comment by dgl1984** [comment]
There have been cases where I've revised midi on my laptop even if the 
host plugin doesn't exist.

If I know the note I want and where it is navigating to it is quite easy.

Also, hearing the notes when harrowing is useful because I'm reminded of 
where I placed key switches.

**Comment by ScottChesworth** [comment]
> There have been cases where I've revised midi on my laptop even if the host plugin doesn't exist.
> 
You still can. Control+F12, Alt+S, Enter and things are back the way they've always been for as long as you need positional info. If those cases come up so often that a three keystroke sequence is a showstopper, bind "OSARA: Toggle Report position when scrubbing".

> hearing the notes when arrowing is useful because I'm reminded of where I placed key switches.
> 
The keyswitch would still have its own position when you're arrowing and its preview would behave differently from a standard note. Has what we changed removed some other useful clue? Gonna need more info.

**Comment by jcsteh** [comment]
FWIW, I'm not dead against adding a separate config option if there are solid use cases for it. I believe that was your original thought, @ScottChesworth, so maybe that was the right call in the first place. I just want to be sure we're not cluttering settings without a very good reason; i.e. that it is actually a fundamentally different interaction and not just a different workflow due to a different kind of project.

**Comment by ScottChesworth** [comment]
Following feedback from @dgl1984, @ElCrackLoko and some others who didn't make it over to GitHub, I've unlinked from scrubbing. Feedback is now controlled by a new "Report position when navigating chords in MIDI editor" option in OSARA Configuration, so you can have your cake and eat it (and ideally, send me some). The "Report position when scrubbing" option doesn't need to be reworded now.
