### ISSUE TITLE
An API change in REAPER 6.70/71 causes crash when Peak Watcher loads loudness meter

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#822]
After some hours of what nobody would describe as fun, I've figured out that Track/TakeFX_AddByName got tweaked in REAPER 6.70 and 6.71. This causes an issue where after enabling Peak Watcher to monitor any unit of measurement other than Peak dB, you'll end up with as many copies of loudness meter instantiated as your computer can cope with until REAPER locks up. Windows and Mac are both afflicted. DOH!
Good news though, someone found it before me, Cockos have done further rounds of tweakage and our current code works as expected again in 6.72 RC7.
So does anything need to be changed to compensate for this @jcsteh? My thought is that given how fast releases come and go, maybe it's enough to just warn the community channels that 6.70 and 6.71 are best avoided by anyone who makes heavy use of Peak Watcher?

**Comment by jcsteh** [comment]
Wow. That's pretty nasty.

I'm not really sure how we could work around this. Perhaps the only thing we could do on the OSARA side would be to refuse to run on 6.70 and 6.71, but even that doesn't seem super worthwhile given the imminent release of 6.72 with the fix. By the time people updated OSARA to pick up that change, REAPER 6.72 would probably be out.

That said, happy to consider ideas.

**Comment by ScottChesworth** [comment]
I guess one way to avoid it could be to bump our minimum requirement to 6.72 as soon as that's out, but given how few people actually seem to reference that part of the documentation, that doesn't feel great either.

**Comment by ScottChesworth** [comment]
The immediate danger of current releases not working right is passed and I'm not seeing many people getting caught short, so closing this.
