### ISSUE TITLE
SCons error when building OSARA on new machine, help appreciated but not urgent

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#834]
I'm migrating to a new machine and struggling with some build errors that I don't understand. Have cloned recursively with these dependencies installed:
- Git for Windows 2.39.0.2
- Build Tools for Visual Studio 2022, Workload tab configured as per ReadMe
- Python 3.11.1
- SCons v4.4.0
- NSIS 3.08

Here's what SCons gives me running from a freshly cleaned cache:
Building using 16 jobs
scons: done reading SConscript files.
scons: Building targets ...
Creating 'build\x86\buildVersion.h'
clang-cl /Fobuild\x86\controlSurface.obj /c src\controlSurface.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
clang-cl /Fobuild\x86\dictionary.obj /c include\tinygettext\src\dictionary.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
clang-cl /Fobuild\x86\envelopeCommands.obj /c src\envelopeCommands.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
clang-cl /Fobuild\x86\exports.obj /c src\exports.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
clang-cl /Fobuild\x86\format.obj /c include\fmt\src\format.cc /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
clang-cl /Fobuild\x86\fxChain.obj /c src\fxChain.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
clang-cl /Fobuild\x86\language.obj /c include\tinygettext\src\language.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
clang-cl /Fobuild\x86\log.obj /c include\tinygettext\src\log.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
clang-cl /Fobuild\x86\midiEditorCommands.obj /c src\midiEditorCommands.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
clang-cl /Fobuild\x86\os.obj /c include\fmt\src\os.cc /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
clang-cl /Fobuild\x86\paramsUi.obj /c src\paramsUi.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
clang-cl /Fobuild\x86\peakWatcher.obj /c src\peakWatcher.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
clang-cl /Fobuild\x86\plural_forms.obj /c include\tinygettext\src\plural_forms.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
clang-cl /Fobuild\x86\po_parser.obj /c include\tinygettext\src\po_parser.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
rc /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /nologo /fobuild\x86\reaper_osara.res src\reaper_osara.rc
clang-cl /Fobuild\x86\reaper_osara.obj /c src\reaper_osara.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
clang-cl /Fobuild\x86\translation.obj /c src\translation.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
clang-cl /Fobuild\x86\uia.obj /c src\uia.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
clang-cl /Fobuild\x86\win32_utf8.obj /c include\WDL\WDL\win32_utf8.c /clang:-Wno-deprecated-declarations /clang:-Wno-unused-variable /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
clang-cl /Fobuild\x86\tinygettext.obj /c include\tinygettext\src\tinygettext.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
Creating 'build\x86_64\buildVersion.h'
clang-cl /Fobuild\x86_64\controlSurface.obj /c src\controlSurface.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86_64 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
clang-cl /Fobuild\x86_64\dictionary.obj /c include\tinygettext\src\dictionary.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86_64 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
clang-cl /Fobuild\x86_64\envelopeCommands.obj /c src\envelopeCommands.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86_64 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
clang-cl /Fobuild\x86_64\exports.obj /c src\exports.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86_64 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
src\paramsUi.cpp(611,55): error: unqualified call to 'std::move'
      [-Werror,-Wunqualified-std-cast-call]
        ParamsDialog(unique_ptr<ParamSource> source): source(move(source)) {
                                                             ^
                                                             std::
clang-cl /Fobuild\x86_64\format.obj /c include\fmt\src\format.cc /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86_64 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
clang-cl /Fobuild\x86_64\fxChain.obj /c src\fxChain.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86_64 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
src\paramsUi.cpp(1116,20): error: unqualified call to 'std::move'
      [-Werror,-Wunqualified-std-cast-call]
                new ParamsDialog(move(source));
                                 ^
                                 std::
src\paramsUi.cpp(1138,19): error: unqualified call to 'std::move'
      [-Werror,-Wunqualified-std-cast-call]
        new ParamsDialog(move(source));
                         ^
                         std::
clang-cl /Fobuild\x86_64\language.obj /c include\tinygettext\src\language.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86_64 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
src\paramsUi.cpp(1222,19): error: unqualified call to 'std::move'
      [-Werror,-Wunqualified-std-cast-call]
        new ParamsDialog(move(source));
                         ^
                         std::
src\paramsUi.cpp(1231,4): note: in instantiation of clang-cl /Fobuild\x86_64\log.obj /c include\tinygettext\src\log.cpp /TP /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /nologo /W3 /WX /clang:-Wno-unused-function /Ibuild\x86_64 /Isrc /Iinclude /Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
function template
      specialization 'fxParams_begin<MediaTrack>' requested here
                        fxParams_begin(track, "TrackFX");
                        ^
src\paramsUi.cpp(1222,19): error: unqualified call to 'std::move'
      [-Werror,-Wunqualified-std-cast-call]
        new ParamsDialog(move(source));
                         ^
                         std::
src\paramsUi.cpp(1241,4): note: in instantiation of function template
      specialization 'fxParams_begin<MediaItem_Take>' requested here
                        fxParams_begin(take, "TakeFX");
                        ^
src\uia.cpp(197,48): error: unqualified call to 'std::move'
      [-Werror,-Wunqualified-std-cast-call]
  ...CComPtr<IRawElementProviderSimple> tmpProv = move(uiaProvider);
                                                  ^
                                                  std::
5 errors generated.
1 error generated.
scons: *** [build\x86\paramsUi.obj] Error 1
scons: *** [build\x86\uia.obj] Error 1
scons: building terminated because of errors.

If anyone's got time to point me in a direction it'd be much appreciated. In particular, I'd like to know what informed you if the issue was easy to spot, would be good to troubleshoot this stuff for myself in future.

Thanks in advance.

**Comment by ScottChesworth** [comment]
Forgot to mention above, this machine has a Ryzen CPU. Dunno whether that requires any different dependencies or configurations to be made. It's my first time with anything other than Intel.

**Comment by RDMurray** [comment]
You must have checked out an old version of the code somehow. This was fixed in #811. I think it is because your fork in github is out of date. You can sync your fork by using the [Github docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork). After that do a git pull on your machine.

**Comment by ScottChesworth** [comment]
Duh, how did I miss that. Thanks man!
