### ISSUE TITLE
Can postGoToTrack move to the master?

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#836]
If so, could I get a nudge on how that'd be done? When I've tried here using -1 as master, my cursor ends up in no man's land off the bottom of the track list. IE, the first press of UpArrow selects the bottom-most track.

**Comment by RDMurray** [comment]
postGoToTrack is used to report the track info after it has been moved to. The track parameter is `MediaTrack* track` which means it it is a pointer to MediaTrack. It does work for the master track, but it requires a `MediaTrack*` pointing to the master track, not -1.

I Hope that makes sense. If not, paste the code that isn't working.

**Comment by ScottChesworth** [comment]
No report nope. Thanks, I'll try that.

**Comment by RDMurray** [comment]
Is the master visible? I suspect it has to be. In case it makes any difference, cmdMoveToTrack selects in a different way, and that is what moves to the master successfully with uparrow.
```
// Always select so this will become the last touched track.
		// The track might already be selected,
		// so we must first unselected.
		GetSetMediaTrackInfo(track, "I_SELECTED", &int0);
		GetSetMediaTrackInfo(track, "I_SELECTED", &int1);
		Main_OnCommand(40913, 0); // Track: Vertical scroll selected tracks into view (TCP)
		SetMixerScroll(track); // MCP
		
```

I think the last two lines are purely visual.

**Comment by ScottChesworth** [comment]
cmdMoveToTrack worked better in this case, Thanks! Protected against a crash that could happen if the master wasn't visible now as well. I just wanna get some eyes on finding out whether those two lines about scrolling are effective. If so, guess I'll add those into our go to first and last track actions.
