### ISSUE TITLE
When reporting length of time selection in bars/beats, OSARA doesn't factor in tempo/time signature changes

### ISSUE THREAD

**Issue by MatejGolian** [jcsteh/osara#839]
Similarly to #249, Osara doesn't report the correct time selection length in bars/beats when there are tempo/time signature changes in the project. This issue is medium priority at most, but fixing it at some point would be nice.

**Comment by ScottChesworth** [comment]
I'm gonna assign high priority. Sure this isn't something that every user is going to encounter every day, but inaccurate feedback raises it up the priorities IMO.

**Comment by MatejGolian** [comment]
That other issue was only medium, but that was related to reporting of
MIDI note length and so when I think about it, giving this higher
priority does make sense.

**Comment by ScottChesworth** [comment]
In the other case, there was REAPER's length field to fall back on if in doubt. I'm not seeing an immediately obvious alternative to get accurate info in this case.

**Comment by jcsteh** [comment]
I think we need to use the code in formatNoteLength whenever we report lengths in measures/beats, not just in the MIDI Editor. formatTime has a isLength parameter though, so we should find some way to reuse code here. I'm not sure whether that means integrating formatNoteLength into formatTime, or removing the existing measures/beats length code from formatTime and instead having formatTime delegate to formatNoteLength (renaming it of course).

**Comment by RDMurray** [comment]
formatNoteLength matches Reaper's value in the note properties dialog. The number of bars is calculated using the time signature in affect at the note start time only, so it will be wrong for long notes that cross tempo markers with a change of time signature. 

The length of items as shown in the item properties dialog is different. It shows the actual number of whole measures within the bounds of the item + any extra beats at each end.

I haven't investigated all the edge cases yet though.

I think the item behaviour is more correct for the time selection length, thoughts?

**Comment by RDMurray** [comment]
fixed in #1026
