### ISSUE TITLE
Changing envelope shape with a keystroke 

### ISSUE THREAD

**Issue by CastleStarter** [jcsteh/osara#853]
Hi.  I would like to be able to change the shape of the currently selected envelope points with a keystroke rather than having to open up the envelope point dialogue box, tab to the shape radio buttons and change it there.
So I would use alt J and alt K to navigate to my envelope point.  I could at this time also use shift alt J or K to select other adjacent envelope points, or in fact control A to select them all, and then just press a keystroke to cycle through the options of linear, square, slow start slow finish, slow start, fast staart.  Ideally a keystroke to go backwards maybe through this list?  Don't think it should particularly give Bezier unless there is some wizzy way to change the tension without going into the dialogue box.
As for which keystroke.  Could we use a keystroke that might already be used for something but which isn't meaningful when the focus is on an envelope point.  Global automation mode perhaps control shift alt forward slash.  Open to suggestion here.

**Comment by ScottChesworth** [comment]
+1, I'd use the heck out of this and I'm certain it would be popular with sound designer types too. Any chance it can be factored into the overhaul that's happening in #851 @jcsteh?

**Comment by Lo-lo78** [comment]
+2, Very helpful. Yes I like it!

**Comment by jcsteh** [comment]
If we were to add an action for this, I'd do it separately from #851.

I'm not convinced this needs an action. You can already do this pretty quickly by moving to an envelope point, opening the context menu, pressing s twice, enter, then selecting the shape. Sure, it's not a single key, but it's still a lot faster than using the dialog. There's also the added advantage of being able to press an access key to more quickly get to a particular shape; e.g. s will take you to square.

If we really did need an action for this, conflating it with another action depending on context would result in some pretty confusing action descriptions; just as an example, OSARA: Split items at time selection/cycle through envelope shapes (depending on focus).

All of that said, if this is desirable, it's certainly possible and not super hard.

**Comment by leejul** [comment]
=1, cela pourrait être fait en script lua je pense, faut voir.

**Comment by mattymc2** [comment]
+3 on this. That comes after 2 right?Sent from my iPhoneOn 30 Jan 2023, at 8:50 am, leejul ***@***.***> wrote:﻿
=1, cela pourrait être fait en script lua je pense, faut voir.

**Comment by ScottChesworth** [comment]
> conflating it with another action depending on context would result in some pretty confusing action descriptions;
> 
Agreed, not keen on that. IMO we need two keys. Hahaha, sure, those are easy to find.

**Comment by jcsteh** [comment]
Also, should this operate on the last navigated/focused/current envelope point or selected envelope points? Most REAPER actions operate on selected envelope points.

**Comment by jcsteh** [comment]
When you say two keys, do you mean you want both a forward and a backward action? Is that really worth the squeeze?

**Comment by ranetto** [comment]
Hi all, honestly I have mapped an action to change the steepness of the bezier of the selected point: however in my opinion, a key would be enough to change the shapes in a circular way since there are four or five

**Comment by ScottChesworth** [comment]
Replying to some specifics...

> You can already do this pretty quickly by moving to an envelope point, opening the context menu, pressing s twice, enter, then selecting the shape. Sure, it's not a single key, but it's still a lot faster than using the dialog.
> 
But an action-based approach could be bound to surfaces/controllers, IMO that's a big advantage.

> When you say two keys, do you mean you want both a forward and a backward action? Is that really worth the squeeze?
> 
Fair point. A single action that cycles would be fine.

> should this operate on the last navigated/focused/current envelope point or selected envelope points?
> 
Selected points for sure, in line with how we handle everything else around envelopes and how REAPER handles, er, most stuff around envelopes. :)

**Comment by Lo-lo78** [comment]
You could do a cycle action.
The problem that there would be no voice feedback.
If these actions could be enclosed in an OSARA action, the problem would be solved:
Description: Envelope: Set shape of selected points to bezier; Command ID: 40683
Description: Envelope: Set shape of selected points to fast end; Command ID: 40429
Description: Envelope: Set shape of selected points to fast start; Command ID: 40428
Description: Envelope: Set shape of selected points to linear; Command ID: 40189
Description: Envelope: Set shape of selected points to slow start/end; Command ID: 40424
Description: Envelope: Set shape of selected points to square; Command ID: 40190

Surely there is a better idea!
Greetings!
