### ISSUE TITLE
API: osara_outputMessage doesn't output !"§()?,-;^{[]}}\|_-'~

### ISSUE THREAD

**Issue by mespotine** [jcsteh/osara#860]
Some characters are not output by osara_outputMessage, at least when using on WIndows 7 with NVDA 2022.1

The characters are ! " § ( ) ? , - ; ^ { [ ] } } \ | _ - ' ~

They are output, when typing them into a window but when trying to output them via the api-function, it says nothing.

**Comment by mespotine** [comment]
Forgot to mention: I tested it under Lua. Didn't check, whether other languages, like spanish, etc have more characters not being read in the screenreader via this function.

**Comment by jcsteh** [comment]
Are you certain you have NVDA's punctuation level set to all? At lower punctuation levels (including the default of some), many symbols are intentionally not read to provide a more natural reading experience particularly for newer users. More experienced users will be aware of how to configure this to hear more symbols. You can find this in NVDA menu -> Preferences -> Settings -> Speech -> Punctuation/symbol level.

**Comment by mespotine** [comment]
Ah, ok. The problem for me is, that I try to code an inputfield, where I try to mimic behavior of other textfields. Means, if I hit the left/right arrowkeys, it reads the character at cursor offset. I would like to read them out, as all other editors do. Could you add a second function, that overrides the preference and reads all punctuation? That way, I could read out these as single characters too.

**Comment by jcsteh** [comment]
I can't. That's not something that can be overridden at this level. You'd need a direct interface to the specific screen reader's code to do something like that.

While I understand what you're trying to do, the approach you're using has significant problems including this one. For example, this won't work at all for braille users, who need to see the entire line of text along with the cursor. Things like this need to be made accessible with full accessibility APIs; e.g. the UI Automation text pattern for editable text support.

All of that said, I do appreciate your efforts to make things more accessible and I understand that there are constraints in ReaScript UI frameworks that make things like this really difficult.

**Comment by jcsteh** [comment]
What UI framework are you using? I wonder whether we need to try to advocate for implementing proper accessibility API support into at least one framework that can be used via ReaScript.

**Comment by ScottChesworth** [comment]
> I wonder whether we need to try to advocate for implementing proper accessibility API support into at least one framework that can be used via ReaScript.
> 
Point me at what would be the least amount of work in terms of the technical hurdles, I can slide into some inboxes and seem friendly.

**Comment by ScottChesworth** [comment]
Two questions:
1. Would it help if Cockos could provide more controls along the lines of reaper.GetUserInputs? I had reason to ask Justin about this fairly recently and didn't get an answer, but to be fair, that was in the middle of a thread with higher priority things happening. Can try again if it'd help.
2. Is there a comprehensive list of which open source UI frameworks are popular/usable among ReaScripters? Identifying which of those are under active development would surely be a useful place to start.

**Comment by jcsteh** [comment]
I think it'd be helpful to know what UI frameworks are being used (as you've asked) before diving into the technicalities of what needs to be implemented. The unfortunate reality is that doing a custom accessibility implementation is a decent amount of work, especially for something like editable text. There's a reason that even REAPER uses native widgets for things like editable text boxes; it's really hard to get all the things right if you roll your own, not least accessibility. Even Microsoft manage to egregiously screw up accessibility for custom editable text implementations on a regular basis and they're the ones who designed the accessibility frameworks they're using!

**Comment by mespotine** [comment]
I try to code my own, since the already existing weren't designed with screenreader-support in mind, so it's not possible to add it at all. I'm quite far and currently in the middle of the inputfield, which I would like to finish before giving you all a go on testing and feedbacking on it. Yeah, I thought there's something missing from reading a line. I once asked for a function to output via braille, would this be possible and help? In regards of not being possible to add punctuation, how do other programs like text-editors do it? Do they simply use the ui-elements of the os and therefore this runs just like that? Now that I think about it, I could output punctuation as, by not writing a , but "comma" instead to the outputMessage-function... -------- Ursprüngliche Nachricht --------Von: James Teh ***@***.***>Datum: So., 5. Feb. 2023, 07:31An: jcsteh/osara ***@***.***>Cc: Meo-Ada Mespotine ***@***.***>, Author ***@***.***>Betreff: Re: [jcsteh/osara] API: osara_outputMessage doesn't output !"§()?,-;^{[]}}\|_-'~ (Issue #860)
I think it'd be helpful to know what UI frameworks are being used (as you've asked) before diving into the technicalities of what needs to be implemented. The unfortunate reality is that doing a custom accessibility implementation is a decent amount of work, especially for something like editable text. There's a reason that even REAPER uses native widgets for things like editable text boxes; it's really hard to get all the things right if you roll your own, not least accessibility. Even Microsoft manage to egregiously screw up accessibility for custom editable text implementations on a regular basis and they're the ones who designed the accessibility frameworks they're using!

**Comment by mespotine** [comment]
I forgot: I write my gui-framework in Reaper's own Gfx-functions-set. So it doesn't need any additional extensions to work. -------- Ursprüngliche Nachricht --------Von: James Teh ***@***.***>Datum: So., 5. Feb. 2023, 07:31An: jcsteh/osara ***@***.***>Cc: Meo-Ada Mespotine ***@***.***>, Author ***@***.***>Betreff: Re: [jcsteh/osara] API: osara_outputMessage doesn't output !"§()?,-;^{[]}}\|_-'~ (Issue #860)
I think it'd be helpful to know what UI frameworks are being used (as you've asked) before diving into the technicalities of what needs to be implemented. The unfortunate reality is that doing a custom accessibility implementation is a decent amount of work, especially for something like editable text. There's a reason that even REAPER uses native widgets for things like editable text boxes; it's really hard to get all the things right if you roll your own, not least accessibility. Even Microsoft manage to egregiously screw up accessibility for custom editable text implementations on a regular basis and they're the ones who designed the accessibility frameworks they're using!

**Comment by jcsteh** [comment]
So the way that OSARA outputs messages is honestly a last resort. For most GUIs, it shouldn't be done just by outputting messages. However, the custom widgets in REAPER (track strips, envelopes, etc.) don't fit well into standard UI patterns, which is why we have to resort to outputting messages.

For more standard UIs, including much of REAPER itself, the controls are exposed via operating system accessibility APIs. They are structured into a tree, with each control providing its type/role (button, check box, etc.), name/label, etc.

For text, things are more complicated. The APIs allow a screen reader to query each character, word and line, as well as asking for the character at the cursor (from which the screen reader can expand to the surrounding word or line).

While this seems a lot more complicated - and it absolutely is - there are good reasons for doing it this way. First and foremost, outputting messages is very specific to speech, but it doesn't work very well for braille. Second, it provides for a more consistent user experience across apps, since the various screen readers determine how the information should be presented. Third, doing it this way allows the user to repeat information if they miss it or request extra information as needed.

REAPER's gfx functions don't provide access to any of this. There is effectively no way to make things fully accessible with them, which is something I've been concerned about for a while.

**Comment by mespotine** [comment]
Yeah, it would be awesome, if Reaper would give access to these accessibility APIs. My current version of my framework is designed for this to be added, if existing. I currently try to match the way TTS says things in Reaper's dialogs, so that it at least feels like consistency. As workaround, I could add features for helping contextualizing things. I already have added F1 for rereading out the current state of a checkbox or the text of a textlabel for instance, and could do stuff like that for the inputbox too. Like, F2 read entire text, F3 read the last 5 words from cursor, F4 read text selection, etcBut this isn't standardized and expected behavior at all and needs to be explained... But I'm not ready to give up on this, yet.

**Comment by jcsteh** [comment]
To answer your other question, having a function to output via braille wouldn't really be enough here, since it wouldn't be able to handle scrolling, routing the cursor (akin to clicking the mouse on a character to move the cursor there), etc.

I really appreciate and respect your commitment here. Unfortunately, you're working with a very limited framework as far as accessibility goes, so what you have is probably the best you can hope for at this point.

**Comment by mespotine** [comment]
Ok, so I need to find some workarounds that make it still useable to some extend....

In regarding of the other frameworks, the most promising is ReaImGui, which is a binding of DearImGui to Reaper. It seems like, they have accessibility on their roadmap sometime in the future. In parts, features are already implemented, like tabbing through UI-elements, but there's no binding to accessibility in regards of output of any kind as of yet.

I still hope, it will make it possible at some point in the future...

**Comment by mespotine** [comment]
Some more questions:Does GetUserInputs have braille-support? And where can I find about the API for Braille-support? Maybe it's possible for Justin to add this on a low-level.For mouse, there are so called gfx-variables, that have flagvalues about mouse-state and modifier-states.Maybe it's possible to have a gfx-variable to return the button-states of braille-displays. So I can get, which character has been selected. Additionally get/set-functions to get/set Braille-text. With that, I could try to recode it myself, but I need to have basic information about where to find the APIs for it, to formulate a proper feature request. And one last thing: is there something like a virtual braille-display? Something for developers, who get the contents displayed and all the buttons a braille-display has, to toy around? This would be awesome. Windows has a virtual keyboard as accessibility tool, that can be used with a mouse. I would hope for something like that but for Braille. Thnx. (hope it is ok, if I ask you thousands of questions...)

**Comment by jcsteh** [comment]
There's also https://github.com/accesskit/accesskit which aims to be a cross-platform library which implements all of the various accessibility APIs and simplifies the book keeping required by the UI toolkit. It's still under heavy early development, but it might be far enough along to be helpful for a simple UI.

**Comment by ScottChesworth** [comment]
> I've honestly never used GetUserInputs, but if it's consistent with the rest of REAPER, it would use standard widgets, so I think it would be accessible.
> 
GetUserInputs provides an edit box, and screen readers announce the title atribute you specify. If you do something like reaper.GetUserInputs(title, 3, "Planes,Trains,Batmobiles", the tab order automatically reflects that order.
Couple of things to be aware of:
1. Screen reader users will need to be running REAPER 6.74 or newer. There was a serious issue with speech feedback up until then (titles were reported for the wrong edit boxes).
2. I haven't explicitly checked that the title and content of the edit box get pushed to braille displays because I don't have one of those here at the moment, but I reckon it does happen, it's just a bog standard edit field.
3. I'm not aware of a way to make the edit box read-only.

**Comment by mespotine** [comment]
Thank you both, will have a closer look at these.

Sounds promising with GetUserInputs. I guess, I will use this as a workaround for textfields for the time being.
For more capable UI-stuff, I need to actually go deep into the accessibility-related APIs first, which I'll postpone for the moment.
I think, if I do go deeper, I would rather try to help CFillion to make ReaImgGui accessible. Have not much of an idea, how it's working internally, but I hope, it can be enhanced.

Will have to require Reaper 6.75 and higher for my gui-lib anyways, due some other serious issues with inputting text, so that should be fine.

**Comment by mespotine** [comment]
One more question about osara_OutputMessage(), is it somehow possible to stop the currently read line?
I'm currently trying to implement hovering with the mouse over an ui-element will read out the caption of the ui-element.
When doing that in any dialog of Reaper, hovering above an ui-element will read the caption but as soon as I move the mouse above another ui-element, the currently read text is interrupted and the caption of the new ui-element is read instead.
Now I tried to do the same, but when pushing text to TTS via osara_OutputMessage, it will be read fully before reading the next one.
So if I'm hovering above one ui element and TTS is reading the caption and I move the mouse to the next ui-element, the caption of the first ui-element is still read until it's complete, then the caption of the second one is read.
Would it be possible to have a function to interrupt output-messages somehow so I can push the next message to be read immediately?

Regarding GetUserInputs:
From what I could figure out with NVDA's Braille Viewer is that GetUserInputs outputs the title correctly, but neither TTS nor the Braille Viewer read out the caption.
So it seems to work but limited to some extend, as I need to set the content of the caption into the window-title or it's invisible to TTS and Braille.
