### ISSUE TITLE
Bug: "OSARA: Mute next message from OSARA" action doesn't appear in all of the sections it's supposed to

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#870]
We have existing code for this action to appear in the MIDI Event List and Media Explorer sections, but it doesn't seem to be working and I'm not sure why.

Here's the line that makes the action visible in the piano roll, which works:
{ MIDI_EDITOR_SECTION, {DEFACCEL, "OSARA: Mute next message from OSARA"}, "OSARA_MUTENEXTMESSAGE", cmdMuteNextMessage},

Now here are the lines which don't work (as in, they build fine, but the action isn't visible in either section of the actions list)::
{ MIDI_EVENT_LIST_SECTION, {DEFACCEL, "OSARA: Mute next message from OSARA"}, "OSARA_MUTENEXTMESSAGE", cmdMuteNextMessage},
{ MEDIA_EXPLORER_SECTION, {DEFACCEL, "OSARA: Mute next message from OSARA"}, "OSARA_MUTENEXTMESSAGE", cmdMuteNextMessage},

Anyone got ideas? I thought maybe MuteNextMessage isn't included in a header somewhere, but the event list doesn't have its own header and another OSARA action appears there just fine. Hmmm.

**Comment by jcsteh** [comment]
I wonder if REAPER needs a different string id when you bind an action in multiple sections. Does it work if you do, say, OSARA_MIDIEVT_MUTENEXTMESSAGE? That doesn't explain why it works fine in the piano roll, though. Hmm.

**Comment by ScottChesworth** [comment]
Odd one isn't it. I'll try that and report back.

**Comment by RDMurray** [comment]
I just tried changing the id string and it does work. strange that it works for the piano roll though. the docs say 
> custom_action_register_t allows you to register ("custom_action") an action into a keyboard section action list
> register("custom_action",ca) will return the command ID (instance-dependent but unique across all sections), or 0 if failed (e.g. dupe idStr)
which suggests that register should return 0 on subsequent calls with the same IdStr. SWS has different ids for the same command in different sections.
