### ISSUE TITLE
Can we report vertical zoom?

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#872]
A request for this to be reportable came in from @dgl1984 via the WhatsApp group. It would be useful when tutoring/presenting REAPER to an audience with usable vision, making screen caps, creating YouTube content etc. Likely also helpful when working alongside sighted peers.

I took a stab at it, but this API has more arguments than I'm used to, scons was like "ROFL, are you typing with your toes again"?
Here's some notes I was working from.

Reckon this is the relevant API:
void adjustZoom(double amt, int forceset, bool doupd, int centermode)
forceset=0,doupd=true,centermode=-1 for default

These actions seem like they'll be useful:
40111 View: Zoom in vertical
40112 View: Zoom out vertical
_SWS_VZOOMFIT SWS: Vertical zoom to selected tracks
_WOL_SETVZOOMC_TRACKCVIEW SWS/wol: Options - Set "Vertical zoom center" to "Track at center of view"
_WOL_SETVZOOMC_TOPVISTRACK SWS/wol: Options - Set "Vertical zoom center" to "Top visible track"
_WOL_SETVZOOMC_LASTSELTRACK SWS/wol: Options - Set "Vertical zoom center" to "Last selected track"

No idea what the API is gonna return, suspect some feedback is better than none though.

Thanks in advance to anyone who can take a run at this. I'm happy to do tedious stuff here if that helps at all.

**Comment by jcsteh** [comment]
Nope, adjustZoom doesn't return anything unfortunately. I think we're going to need to do this with get_config_var and [vzoom2](https://github.com/mespotine/ultraschall-and-reaper-docs/blob/c8b6843fd6325161d129d1b55c147f4194392bd4/Docs/Reaper-ConfigVariables-Documentation.txt#L6727). How ugly.

**Comment by jcsteh** [comment]
The SWS actions seem to zoom to specific points or change zoom configuration. I don't think there's anything we can really report here other than a message confirming the action. That could be done in POST_COMMAND_MESSAGES.

**Comment by jcsteh** [comment]
Regarding the zoom in/out actions:

> It would be useful when tutoring/presenting REAPER to an audience with usable vision, making screen caps, creating YouTube content etc.

I'm not convinced. Sure, we can report the zoom level or size, but how does that help a blind user? They still don't know which tracks are actually visible on screen or whatever.

**Comment by ScottChesworth** [comment]
> Sure, we can report the zoom level or size, but how does that help a blind user? They still don't know which tracks are actually visible on screen or whatever.
> 
Far from ideal I know, but I'm thinking that if this is relevant to a user, they can do some experimentation ahead of time to gauge some ballpark values. Likely an oversimplification, but something like x pixels means I've got Y amount of tracks visible. 
Will have a tinker with the PR, maybe I can adjust to common res/scaling settings and rustle up a cheat sheet of sorts.

**Comment by jcsteh** [comment]
Note that the PR does report REAPER's magic values (as shown in the combo box in Preferences for default track zoom, etc.): 0 minimum, 2 small, 6 medium, etc. However, anything in the middle is just a number.

**Comment by ScottChesworth** [comment]
Hey @Mespotine, if you have a spare 5 minutes, could you describe how each of the "Vertical zoom center" options in Editing Behavior work for sighted folks? I'm especially interested in the "Last selected track" Option, thinking perhaps that would be a good choice for screen reader users who are demonstrating REAPER on video. Does that option make zoom auto-follow the selected track? If so, what happens when multiple tracks are selected? Also, what would be the visual result if you had a block of adjacent tracks selected (let's say tracks 2 through 6) then a couple unselected (let's say 7-9) and track 10 also selected?

Thanks in advance if you've got enough time to explain this stuff, and no worries if you haven't.

**Comment by jcsteh** [comment]
Note that OSARA calls Track: Vertical scroll selected tracks into view when moving between tracks.

**Comment by ranetto** [comment]
I consider it very important, I always work with blind customers and I often find myself embarrassed because they do not see the trail of which I am talking to him: a nice goal has been achieved when we made our selection of the tracks is followed by the screen Visible, another very important result was to be able to minimize the window of the parameters, so when I regulate an effect or a synth, I do not close it but with Alt more tabs focusing reaper and then I put myself on the parameters of the synth or the effect I have Moved and minimized: this further action for the zoom would allow us to be able to show the blind what we see and we hear: if you have questions regarding the vision I can ask myself and answer I greets everyone and thanks.

**Comment by ranetto** [comment]
Sorry I wrote Nonventsi Alposto of blind

**Comment by mespotine** [comment]
It's always the last clicked/selected track. So if you select track 1 and 2 and 10 in that order, track 10 will be at the center of the zoom. If you select track 1 and 10 and 2 in that order, track 2 will be at the center of the zoom. Unfortunately, it will not follow a track-selection done by the function SetTrackSelected(), so if that's what you want to do before zooming, you need to ask Justin for an option/function to set the last touched track instead.

**Comment by ScottChesworth** [comment]
Gotcha, thanks for explaining.
