### ISSUE TITLE
In MIDI editor, running "View: Go to start of file" action doesn't play note preview even if there is data at that location

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#882]
This used to work, think we lost it when I asked for previews not to be repeated when navigating by chord at the beginning/end of the data. That was issue #830 and PR #835. Seems logical that this action should play a preview though if the cursor position has changed?
In MIDI Editor section:
- View: Go to start of file
- 40036

**Comment by jcsteh** [comment]
I can't reproduce this. If I hit control+home in the MIDI editor and there's a note at the start of the MIDI item, I get a preview. Of course, there might not necessarily be a note at the start of the MIDI item.

**Comment by ScottChesworth** [comment]
I can't reproduce it today either. I moved some stuff around to show that when I was demoing yesterday and probably didn't put stuff back to exactly 0% or something. Sorry about the false alarm.
