### ISSUE TITLE
Consider introducing an option in the "FX parameters" dialog to allow filtering out the nameless parameters

### ISSUE THREAD

**Issue by vick08** [jcsteh/osara#887]
There are quite a few instrument plugins out there that provide a massive FX parameter list with half or more of those parameters  being empty. Komplete Kontrol is one such instrument. This results in the "FX parameter" list being huge and very tedious to scroll through.
This is a proposal to add an option to the "FX parameter" dialog, possibly a checkbox, that would allow the user to filter out empty, i.e. with no names, parameters from the parameter menu. In doing so, the menu can be significantly reduced, thus reducing the number of keyboard presses and increasing the efficiency of browsing / discovering the parameters that actually do something.

**Comment by jcsteh** [comment]
We'd need to look at various plugins to define what "no name" means. For example, I'm pretty sure Komplete Kontrol does provide a name, but it's a simple "-" character. Obviously, we should exclude "-", but the question is whether there are any other versions of "meaningless" out there.

**Comment by leejul** [comment]
+1

**Comment by vick08** [comment]
Ah, didn't realize that KK provides a symbol instead of the "no name". I guess, I assumed there was no name since VOiceOver does not read anything.
In that case, it can get messy if we start filtering out random symbols.
Could we start perhaps with non-alphabetic use cases?

**Comment by jcsteh** [comment]
I'm really not intending to be pedantic here, but non-alphabetic is highly dependent on language. Unicode is very complicated. :)

I guess we just start with a small set of known cases for "nothing" and extend it over time. That seems like the simplest and most pragmatic approach. We can always tweak it later.

**Comment by ScottChesworth** [comment]
How about an invert filter check box (perhaps with a friendlier name)? That way people could zap superfluous params as needed without us trying to interpret what they'll encounter.

**Comment by leejul** [comment]
I don't know if this is doable from a code point of view but maybe just make the filter regette parameters whose name is 2 characters or less. Parameters that are not labeled and not functional always have more than 2 characters.
The shortest parameter name I know of is Dry.

**Comment by jcsteh** [comment]
I'm not convinced invert filter is particularly intuitive, even with a better name. Also, as Vic pointed out, some screen readers/configurations don't read symbols anyway (and even if they do, you might get the white space wrong).

Two characters is also not language aware. I'm pretty sure there are east Asian languages where a single pictographic character can be a meaningful word.

**Comment by vick08** [comment]
How likely is it for a valid plugin name to have non-alphabetic characters? Given that the majority of users probably use plugins with English names, perhaps it's worth trying this as an option?

**Comment by jcsteh** [comment]
I don't know how likely it is, but we also don't have any data at all. If plugins are localised, it's likely that the parameter names would get localised too. And even if we factor out pictographic languages, there are still characters in European languages which wouldn't get caught by the standard alpha checks. Honestly, I think it's just simpler to go with a predefined list of invalid names for now. We can always tweak it down the line.

**Comment by vick08** [comment]
Sounds great!
Where should we collect the patterns? Right here or there is a more suitable place? :)

**Comment by jcsteh** [comment]
Here is good.

**Comment by vick08** [comment]
Two patterns I have seen so far:
1. An already-discussed pattern in Complete Control where, according to Jamie, the parameter label contains some symbol that screen readers do not voice, and the parameter value seems to be empty.
2. A pattern, in plugins such as Guitar Rig Pro, where the parameter label contains a string formatted as P#, and the empty parameter value. Please note, there is an actual number after the letter "P".
3. A pattern, in some 3rd-party JS plugins, where the parameter label is an empty value (or perhaps an unspoken symbol), and the parameter value containing the number or a string.
#888

**Comment by jcsteh** [comment]
Yuck. Detecting some of those without breaking valid use cases is going to be difficult if not impossible.

**Comment by vick08** [comment]
Perhaps I am the only person suffering from this, but I would even be happy with a checkbox (unchecked by default) that allowed me to temporarily hide parameters with empty values, of course, assuming they are completely empty or non-[a-z][0-9] ones otherwise.
I do agree a proper solution to this issue  probably does not exist and unlikely ever will.
Feel free to make a call and close the issue if we are unlikely to do anything about this!

**Comment by vick08** [comment]
Just wanted to see if it is still feasible to pursue this? I feel that the use case is valid but realize that there is no clean fix. The feature will be experimental at best.
What do you think?
