### ISSUE TITLE
I want to read the snapshot name aloud when I switch snapshots

### ISSUE THREAD

**Issue by c469591** [jcsteh/osara#896]
Hello.
Currently in reaper, I can use
ctrl+alt+7, 9 to switch snapshots, but it doesn't broadcast which snapshot is currently switched to.
Could you please let me hear the name of the snapshot I've switched to in a future version of osara by pressing this quick key?
Thanks!

**Comment by jcsteh** [comment]
This has already been filed as #110. It's not currently possible because there is no way to get the current snapshot name.
