### ISSUE TITLE
mute speech

### ISSUE THREAD

**Issue by dgl1984** [jcsteh/osara#9]
I would like to be able to have a toggle which would allow the disabling of speech from osara.  This is useful when I'm scrubbing or doing other edits where speech may not be necessary, or could be a distraction.

**Comment by jcsteh** [comment]
I can understand the need for this for specific commands like scrubbing. 
However, if you want a general mute, why not just use your screen 
reader's functionality for muting speech? That should give you the same 
practical benefit with greater consistency.

**Comment by dgl1984** [comment]
While that would, of course, suppress the messages from osara, I need to unmute before I do anything else. Anything saving mear seconds adds up when I'm doing projects with hundreds or even thousands of tiney little edits.
example of a common sequence.
Set ripple mode as needed, mute nvda, turn on numlock so that numpad 4 and 6 can move an item, turn off numlock, unmute speech, continue.

  

 


  ----- Original Message -----

**Comment by jcsteh** [comment]
Sorry, but I'm still not following why a separate command to mute OSARA 
would make this any easier. Using your example, you'd still have the 
following scenario:
Set ripple mode as needed, mute OSARA, turn on numlock so that numpad 4 
and 6 can move an item, turn off numlock, unmute OSARA, continue.

**Comment by dgl1984** [comment]
If osara were mutable, as such, no toggling from beeps back to speech 
would be necessary, and if the mute speech action were assigned to a 
function key, numlock wouldn't matter.
Again, its another time saver.

**Comment by jcsteh** [comment]
This argument doesn't hold. You can use the no beeps speech mode NVDA add-on and assign toggling of speech to whatever key you like. Implementing this would be akin to asking the developer of every application to provide a key to disable accessibility temporarily for that application, or to use a parallel for sighted users, a key to turn off the GUI temporarily. The correct place for silencing speech is the screen reader.

**Comment by jcsteh** [comment]
I introduced the ability to disable reporting of scrubbing using OSARA's new configuration dialog in 0d64c7b6.
