### ISSUE TITLE
Allow the Reporting Of changes made by control surfaces while in the FX window

### ISSUE THREAD

**Issue by onlineeaglewq** [jcsteh/osara#902]
When setting up Learn, it is possible to tell reaper to only make parameter changes by the control surface when the effect is being focused on. This means the same nobs can be assigned to multiple effects, and it is possible to control each effect separately without the nob changing all of the effects loaded. Unfortunately the option to report changes made by control surfaces only works when the track is in focus, and not when the FX window is open.

**Comment by jcsteh** [comment]
Reporting of surface changes was disabled in FX windows due to double speaking when changing the parameter from the keyboard. Unfortunately, there's no way to detect whether a surface parameter change was triggered by a surface itself or from the keyboard.

**Comment by jcsteh** [comment]
I just had a thought on this. Would it satisfy your request to have this reporting only work when the FX list itself is focused? At least that way, we wouldn't risk double speaking, but you'd still have a straightforward way to focus the plugin and have the learned parameters report.
