### ISSUE TITLE
Access request for translation

### ISSUE THREAD

**Issue by cankirca** [jcsteh/osara#910]
Hi,
 
Can you allow me to contribute translation via Crowdin please?
Username: cnkrc
Target language: Turkish
File name: Turkish.po
Regards.

**Comment by jcsteh** [comment]
Thanks for your interest in contributing. You noted that the target file would be Turkish.po. However, is there a REAPER language pack already? Is it named Turkish.ReaperLangPack?

**Comment by cankirca** [comment]
Hi,

TR pack is almost finished, it will be named as Turkish.ReaperLangPack.
I'd like to work on the Osara to save the time.
Best.

2023-06-09 13:52 GMT+03:00, James Teh ***@***.***>:
> Thanks for your interest in contributing. You noted that the target file
> would be Turkish.po. However, is there a REAPER language pack already? Is it
> named Turkish.ReaperLangPack?
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/jcsteh/osara/issues/910#issuecomment-1584381339
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
Can K.

**Comment by jcsteh** [comment]
Okay. You're good to go. Note that the file will be called tr_TR.po, but it will be loaded when the REAPER language pack is set to Turkish.ReaperLangpack.
