### ISSUE TITLE
Unable to display  OSARA's simplified parameters in an FX container window.

### ISSUE THREAD

**Issue by Aleskis** [jcsteh/osara#912]
1. Download the latest development version of REAPER from landoleed and install it.
2. In the FX Explorer, add the FX Container.
3. Tab over the FX container until you can add FX included in the container. Add an FX.
4. Return to the list of FX contained in the container and press Alt+P.
5. The window that opens shows the container parameters instead of the FX parameters in focus.

**Comment by jcsteh** [comment]
This also applies to support for things like control+b reporting the active/bypass state.

As I understand it, the API doesn't provide the info we need to do this properly. I've raised this with Cockos and we'll see what we get.

**Comment by jcsteh** [comment]
Sounds like exactly what we need, yeah.
