### ISSUE TITLE
Problems with downloading the Program File on Windows Desktop

### ISSUE THREAD

**Issue by Benni0816** [jcsteh/osara#916]
Hello, Ladies and Gentlemen,

I tried downloading the current Installation-File for Osara, but I am always stopped by Microsoft Defender Smartscreen Security.

Who and where can I change the Setting of the Defender, so the File can be downloaded?

Thanx for helping me with these Issue 

Note:

I am using Windows 11 profesional..

Kind Regards

Michael Stadler - Germany

**Comment by ScottChesworth** [comment]
Do you have another browser you can try? Download with Firefox seems to work fine here. If you have it, try that first.

**Comment by ElCrackLoko** [comment]
Hello, it is true that the latest build 1152 of Osara Windows Defender is detecting it as a threat. I imagine that it does not have a valid signature or something like that, or the signature was another of those that is usually always generated from Microsoft's white list. I'm not a programmer, but I know that there are files that are reported to antivirus companies to be whitelisted so they don't detect and delete them. Returning to the subject, this is solved with an update, it usually happens in very few versions of Osara, but when they update the file again it is fine as always.
@Benni0816, just disable antivirus temporarily, download Osara, install it, go to antivirus, add the file to exceptions (temporarily too) enable antivirus and for safety when Osara is updated again, remove the file from exceptions and work as always. It is not going to be that you come across a Malware that has the same denomination that is detected in the Osara Exe file and then you do have a bad time... Greetings to Germany from Ecuador, South America.

**Comment by Benni0816** [comment]
Thanx, I will try aniway, when I finished my Work today. 

 

Von: ScottChesworth ***@***.***> 
Gesendet: Freitag, 14. Juli 2023 18:26
An: jcsteh/osara ***@***.***>
Cc: Benni0816 ***@***.***>; Author ***@***.***>
Betreff: Re: [jcsteh/osara] Problems with downloading the Program File on Windows Desktop (Issue #916)

 

Do you have another browser you can try? Download with Firefox seems to work fine here. If you have it, try that first.

**Comment by jcsteh** [comment]
Closing as a duplicate of #387.
