### ISSUE TITLE
The option to report the name of the notes in the Midi editor does not work, Alt + 0.

### ISSUE THREAD

**Issue by ElCrackLoko** [jcsteh/osara#917]
Hello. In the Midi editor, by pressing the Alt + 9 command we activate and deactivate that Osara informs us of the velocity number of the Midi note when we pass through it. But, not so with the name option with Alt + 0. When we activate or deactivate it, Osara pays attention to the configuration that we have in the Osara configuration dialog with Control + F12. I mean, if we have this new option, I think that setting could already be removed from that group of options, right?

**Comment by jcsteh** [comment]
There's a distinction between note names (as in notes that have been given custom names) and reporting notes in general. The setting in the OSARA Configuration dialog is for reporting notes in general. I vaguely recall there was some talk about ignoring custom names if the REAPER setting is disabled, but I don't recall where that landed.

**Comment by ElCrackLoko** [comment]
I understand. I didn't know that you could add notes with personalized names, it seems very strange to me that someone knowing that it is a C5 (Do 5), in Spanish, would like to put an A#/A sharp  (La sostenido 5) on it. I still think that the Alt + 0 command would be more useful to activate and deactivate the report of Midi notes in general

**Comment by jcsteh** [comment]
The use case is MIDI instruments which trigger things other than pitched notes; e.g. drum kits, samples, etc.

**Comment by ElCrackLoko** [comment]
Oh, it's true. What a fool I am, wow, how the understanding between languages changes. I interpreted a personalized note as giving it a different name than the one it already had. But yes, it's true, Osara also reads you the Samples that you have loaded with ReaSamplomatic in the Midi editor as a Midi note. Anyway, I still think that if it could, these options to activate and deactivate are unified with Alt + 0 for the Osara de Samples report and the original Midi Notes. I seem to recall that you were in favor of shortening Osara's settings menu to Control + F12 is a good way to do it.

**Comment by ScottChesworth** [comment]
When a user has imported a custom named notes file though, they might want to control that reporting separately. If that doesn't suit you, make a custom action to control multiple report toggles when you hit Alt+0. Search the MIDI Editor section of the actions list for "OSARA report", you'll find a couple of useful toggle actions we've provided.

**Comment by jcsteh** [comment]
Reporting of notes isn't just note names. It includes lengths, mute, etc. as well. With this disabled, you're relying entirely on note preview. Also, REAPER visually allows you to turn off custom note names without turning off anything else, so tying all note reporting to this setting doesn't quite fit.

**Comment by ElCrackLoko** [comment]
Well. Although I don't fully understand this about the lengths and rests, in these about the names of notes, I leave it for peace since you are the connoisseurs here. I wish you health and prosperity, brothers. I close this useless thread then hehe.
