### ISSUE TITLE
Poedit says that a translation string is corrupted

### ISSUE THREAD

**Issue by ElCrackLoko** [jcsteh/osara#918]
Hello.
In the new strings that have been added, there is one that Poedit marks with a strange message and marks it as corrupted or translations with errors.
It is about the Piano roll view (Vista a Piano roll) in Spanish, come on, since we started translating with the PMA team, I always made sure that the characters were well written, capital letters, symbols, that there are no spaces at the end in my string, so our translation is pretty much perfect; All this with the exception of the last recently added chain, at least, Poedit marks it for me with a message that in Spanish is not clear but says something like:
duplicate message definition...
And it says that in all the other translations of the other languages, so we can rule out some single mistake in our translation only. I've tried translating it in different ways, adding more words, changing capitalization, etc., but nothing seems to work. It always says the same thing, even when the translation is correct.
All the best.

**Comment by jcsteh** [comment]
I suspect this was due to an empty translatable string that crept into the code in #913. I've fixed that now, so hopefully, that fixes the problem.

**Comment by ScottChesworth** [comment]
Oops, didn't realise an empty string would cause problems for translators. Sorry about that.

**Comment by jcsteh** [comment]
The build will now barf if someone accidentally does this, so it shouldn't happen again. I also updated the comments and code for toggle messages to make it clear that nullptr should be used instead of an empty string and to behave better when nullptr is encountered for an off message.

**Comment by ScottChesworth** [comment]
Saving me from myself. I could get used to That. :)

**Comment by jcsteh** [comment]
If a mistake happens once, it's likely it wasn't clear in the first place and could happen again, whether that's you, me or someone else. If we can make the machine protect us from such things easily enough, we should. :)
