### ISSUE TITLE
Vocalization request for 2 SWS actions

### ISSUE THREAD

**Issue by leejul** [jcsteh/osara#925]
I can't find a link to make a feature request for OSARA so sorry for using the wrong place.
Would it be possible to vocalize the following 2 SWS actions:
Tempo: Decrease current project tempo 01 BPM
Tempo: Increase current project tempo 01 BPM
Thanks.

**Comment by jcsteh** [comment]
This is the correct place for OSARA feature requests. Whether or not this can be implemented is an open question. I assume project tempo is exposed somewhere by the API, but I don't know where off the top of my head.

**Comment by ScottChesworth** [comment]
We already provide feedback for the actions you've pasted. They're not from SWS.

**Comment by leejul** [comment]
Oh, problem, I didn't know this action was vocalized. I set Reaper in English and indeed, it is vocalized. So it doesn't work with a LangPack.

**Comment by ScottChesworth** [comment]
Hmm, do we need new translation strings Jamie?

**Comment by leejul** [comment]
French Canada.

**Comment by jcsteh** [comment]
Does the screen reader just stay silent for you? It works for me and I also can't see anything in the fr_CA localisation that should cause problems here.

**Comment by leejul** [comment]
Ok, indeed, it works well on my other machines. The problem is only on one of my machines. Sorry for the inconvenience, I should have done tests on my other machines before making this post. I'll try to find why it doesn't work on this machine.

**Comment by ScottChesworth** [comment]
Closing this for now then just to keep the place tidy. If you figure anything else out that we should know about, feel free to reopen.
