### ISSUE TITLE
Is it possible to create an OSARA action to get the CPU percentage of a trace? For slow computers.

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#926]
Hello unfortunately when the computer has the CPU at 95% it is not possible to know how much an FX chain weighs. The computer is completely frozen. Knowing how CPU intensive a track is can help you freeze the track before it blows up your computer.
I have to use some tricks to be able to compose and mix. It takes hours to do a simple 10-minute operation.
Thank you!
🤞

**Comment by jcsteh** [comment]
Is this information available visually? If so, it might be possible. If not, then no, it's not possible.

**Comment by ranetto** [comment]
they are visible at the bottom of the window, somewhat as if they were a status bar of that window

**Comment by Lo-lo78** [comment]
@jcsteh 
Yes it is visible. I do not know from the TCP if it is possible to know this information. Perhaps the FX chain window should already be open. I do not know!
If you create a track and then press F to enter the FX chain and with the NVDA object navigator press NVDA+8 on the numeric keypad and then press NVDA+6 on the numeric keypad three times you get the information on how much the FX chain consumes .
The FX chain info string is organized like this:
0.03c/0.24c 2048/3584 spls
Il primo gruppo è quanta CPU consuma il singolo FX e poi quanto consuma l'intera catena FX.
0.03c/0.24 CPU. 0.24 is 24% CPU.
So the useful information in the first group is 0.24 CPU and in the second group are the latency samples.
The second group consists of:
2048/3584 spls
2048 is the selected FX and 3584 is the whole chain. That is how long it takes to go into play.
The useful information could be the entire FX chain:
0.24 CPU 3584 spls.
It would be very helpful if this could be known without going into the FX chain. From the TCP. If I select a track it could be useful with a shortcut connected to an action to know immediately how much CPU it consumes.
The spls are not needed but if you want to work on those too you could create a second dedicated action.
Or even a single action where if you double-press the shortcut first it gives you CPU and double-press gives you spls.
The information in a single string could be too long. Maybe with a punctuation you can separate the CPU from the spls. So you can put everything in one string.
Thank you!

**Comment by ScottChesworth** [comment]
I've had eyes confirm that it's possible to have the performance meter, tracks and the FX window all visible at once. However, this configuration would be difficult/impractical to set up with a screen reader, and it seems likely floating windows could cause other focus issues. assuming for a second that it's possible to obtain the relevant information, I think there is a valid case for OSARA actions reporting performance statistics on demand.
Hmm, not seeing any obvious APIs around collecting that info though. Do we need to request something from Cockos?

**Comment by jcsteh** [comment]
To clarify, the CPU usage is not visible from the TCP, right? Sighted users have to open the FX chain to get that info.

This is probably a case where it might be kinda sorta reasonable for the screen reader UX to deviate from the visual UX, given the difficulty of dealing with floating windows for screen reader users. However, as you say, I don't see any way to get this info from the API, so I think we're out of luck without help from Cockos. I don't really know what info is provided visually, so I couldn't tell you what to ask for.

**Comment by ranetto** [comment]
only the total CPU reaper percentage and the ram used by the project are visible from the TCP

**Comment by ranetto** [comment]
I think it's a tip that appears on hover

**Comment by Lo-lo78** [comment]
@jcsteh 
@ScottChesworth 
@ranetto 
If we don't have an API, it's unlikely that it will work 100%.
Let's wait for Cockos to give us an answer on this.
Thank you!

**Comment by ScottChesworth** [comment]
Seems like the best way forward yeah, that way we can provide the same amount of access on Mac. I've written to Cockos and asked about it, will bump the thread when I hear back.
