### ISSUE TITLE
Would it be possible for OSARA to report MIDI notes when pressing keys in the Virtual MIDI Keyboard?

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#930]
This has just been requested on RWP by someone who's struggling to learn the layout. I think there's a valid use case because we don't have any other form of landmarking available, said I'd ask if there was any way it could be done.

**Comment by jcsteh** [comment]
Would this actually help, given that you can hear the notes you're playing? It might help if we could support this in shortcut help - i.e. without actually sending the note and supporting the keys which change ranges - but I don't think we can.

**Comment by ScottChesworth** [comment]
Love the idea of speaking notes via Shortcut Help! Hearing the actual notes you're playing is probably fine if you've either 1) got absolute pitch, or 2) got a musical reference of some kind imported and enough ear-training to use that, but those things aren't always in play when someone's finding their feet. If there's no way OSARA can support it or if the juice wouldn't be worth the squeeze, I can make a tutorial on the VMK easy enough. Shortcut Help providing this would be a nifty feature though man.

**Comment by jcsteh** [comment]
Oh durp, I confess I was unconsciously assuming absolute pitch. That's not cool. Sorry.

The code for speaking notes on input is more or less already done; see #829, though it would need a bit of tweaking to do what we want here. I'm not sure about restricting to the virtual keyboard, but it might be possible. I don't think shortcut help is going to be feasible though, at least not in a cross-platform way.
