### ISSUE TITLE
File overwrite message which is no longer spoken by OSARA

### ISSUE THREAD

**Issue by leejul** [jcsteh/osara#931]
When saving a preset in the FX window and a preset has the same name, the alert message is no longer spoken by OSARA.
Is it normal?

**Comment by ScottChesworth** [comment]
We don't do anything there. If it's changed, that's REAPER handling the situation differently.

**Comment by leejul** [comment]
I just noticed that we have the same behavior with the delete take confirmation request.

**Comment by ScottChesworth** [comment]
I just ran "Take: Delete active take from items (prompt to confirm)". An accessible window with a title of "REAPER Query  dialog" came up, asking "Delete active take of selected items?" There were two buttons, OK and Cancel. All seems the same as ever here man. Is this perhaps a langpack issue?

**Comment by leejul** [comment]
Sorry, I restarted NVDA and no more problems. It's still the memory dedicated to 32 bits that makes NVDA buggy. I'm so looking forward to the day NVDA is released in 64-bit. Maybe when I'm old!
Sorry for inconvenience guys.

**Comment by jcsteh** [comment]
32 bit has absolutely nothing to do with any of this. But sure, feel free to spread unfounded FUD.

**Comment by leejul** [comment]
Spread unfounded FUD !
If you used Toontrack EZDrummer, you would understand. But rather than trying to find out more about the problem that is recognized even by NVAccess, you told me this.
It's your choice my friend.

**Comment by ScottChesworth** [comment]
Are you referring to this issue that @leonardder fixed over a year ago? https://github.com/nvaccess/nvda/pull/13271

**Comment by jcsteh** [comment]
There are absolutely edge cases, particularly in SysListView32 and SysTreeView32 controls, where 32 bit is problematic because NVDA actually reads remote process memory directly. But those cases are very specific and are the exception rather than the rule. Most of the time, NVDA doesn't read remote process memory directly. It either uses cross-process APIs or in-process code, both of which are not impacted by 32 vs 64 bit issues.

Assuming that an unrelated problem is due to a particular technical problem without sufficient technical analysis and then stating that publicly definitely qualifies as spreading unfounded FUD.

**Comment by leejul** [comment]
I don't know if this post refers to the bug concerning NVDA and EZDrummer but I can confirm that it is still not resolved.
And if we are talking about the same problem, it is certainly not part of an extremely rare case.
We have found that if there is a single track in Reaper with EZDrummer inserted on that track, the problem does not occur often.
But if we add 2 or 3 other tracks, the problem appears systematically.
Furthermore, this bug does not only affect EZDrummer, it also applies globally in Windows.
If 2 or 3 applications as well as 2 or 3 folders are open at the same time, for some reason NVDA no longer pronounces the selected elements.
But this behavior happens randomly.
Sometimes it is enough to simply restart NVDA, sometimes that is not enough, you have to restart the machine.
I have also noticed that when this behavior appears, simply do not use the machine for 3, 4, 5, 6, and sometimes even up to 10 minutes and the problem disappears.
And this also applies with EZDrummer in Reaper.
So, here's the $100 question, what caused this problem taking into account the fact that if I don't touch the machine for a while, the problem disappears?
I'm not a specialist like you but I have my own idea.
But it seems that it is not suggested to give a probable lead here, for fear of being insulted.
No offense Jamie, I know myself very well, I can sometimes push people around.
But if I may, responding with technical explanations is much more constructive.
After several email exchanges with Quentin Christensen, I understood that several dev seem to have tried to find a solution but I have not seen any change since the beginning.
As for the fact that NVDA is only offered in 32 bits, this is incomprehensible.
Especially since the reason I am given is that NVDA must be compatible on all systems.
I'm not a professional dev like you, but I know enough to say that it's nonsense.
Do you know a lot of software available only in 32 bit in 2023? Not me.
But hey, NVDA is an extra ordinary project and I'm not going to spit in the soup.
So, this leads me to say that this is why I made a connection with the problem encountered with the deletion of take whose message was not pronounced by NVDA.
Maybe this is unrelated but how can we be sure while the problem I'm referring to has not been resolved.
So when you say spread unfounded FUD, that suggests that I'm having fun saying stupid things.
If my theory, may be completely wrong or correct, seems stupid to you, then explain to me why we have this behavior with NVDA.
Thanks my friend.
