### ISSUE TITLE
I can't get the OSARA action to work: Report track/item/time selection to create custom action

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#934]
Hi I'm creating a custom action to move the track up or down with feedback.
The idea was:
1.
Script: X-Raym_Move selected tracks up on visible track list.lua
OSARA: Report track/item/time selection
2.
Script: X-Raym_Move selected tracks down on visible track list.lua
OSARA: Report track/item/time selection
But when I execute the custom action the OSARA action opens the window as if I had typed ctrl+shift+space twice.
There is a solution?
Mi piacerebbe che quando muovo la traccia su o giù ci fosse un feedback vocale. L'unico modo per fare la custom action è usare OSARA ma non funziona.
Thank you!

**Comment by ScottChesworth** [comment]
The window will open if that OSARA action is run twice within our timer that captures a double-tap. That could happen if 1) you have more than one instance of the action in the chain, or 2) you move tracks fast enough to beat the timer.
Before anyone asks, it's unlikely we'll be tweaking the timing of how double-taps are registered. That's a delicate balance. An easier solution could perhaps be to modify those scripts. I'll have a quick look into that.

**Comment by Lo-lo78** [comment]
I closed this issue because on RWP
Scott and Robbie suggested a solution that works.
Thank you!
