### ISSUE TITLE
Can OSARA report when Reaper itself stops transport?

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#936]
At the moment, we report changes of transport state when they're initiated by the User pressing play, pause or stop. However, there are preferences a user can check that cause Reaper itself to stop transport, changes of transport state aren't reported in those cases. Ideally they would be, seeing as there are clear visual indicators that transport has stopped.
Here are two preferences for testing, both in the Playback category:
- Stop/repeat playback at end of project
- Stop playback at end of loop if repeat is disabled

Is there anything we can do to report this? If it's easily done, feel free to just nudge me in a direction...

**Comment by jcsteh** [comment]
This should already be working when control surface reporting is enabled. OSARA uses the surface to get notified about transport changes in this case. We could de-couple this feedback from surface reporting if you like. That should be fairly straightforward.

I think we've actually discussed this exact change before, but i don't recall where.
