### ISSUE TITLE
These two actions do not work in Reaper 7's piano roll

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#942]
I wanted to point out that in the piano roll these two actions do not work: 

CC: Next CC lane 
CC: Previous CC lane 

The screen reader vocalizes -1 nonsense but doesn't change the CC.

**Comment by jcsteh** [comment]
This looks like a bug in REAPER 7, which I will report. That said, are these actions actually useful right now given #730?

**Comment by Lo-lo78** [comment]
I figured it was a Reaper problem.
But the problem
#730
it's more complex.
we also talk about lanes.
If Reaper has a bug on this it could be interesting.
Being able to move towards the next or previous cc with the same parameter is very convenient.
I hope Cockos fixes the problem.
We will probably have two more actions in the piano roll.

**Comment by jcsteh** [comment]
This is fixed in REAPER 7.02.
