### ISSUE TITLE
Bug: Could it be Osara? Error focusing FX in FX list when pressing F6

### ISSUE THREAD

**Issue by ElCrackLoko** [jcsteh/osara#951]
Hello guys, this comes from the Accessible Music Production community report, since this is something that affects many of us, not just me, and many colleagues have been reporting the same thing to me for days, now weeks, but the work This is what has not allowed me to come here to communicate this.
It happens that before when one loaded a Plugin (Let's say Nexus from ReFX or any VST3 that has parameters in its window) one would scroll through the buttons and options of the Plugin, in the FX view by pressing F6, or by clicking Shift Tab 3 times from the effect to the active FX box and then a down arrow. In any case, it was always better to press F6 to enter the FX window, and you could navigate perfectly with Tab, Shift+Tab and if there was a button that you wanted to activate, you pressed NVDA+Enter. Now, I don't know since when, or since what version of Reaper, or Osara, it can no longer be done this way, and now you have to press Control+Tab to move between the FX buttons and options, and if you want to go back , Control+Shift+Tab, because if you press Tab, the FX window blurs and places you on the Insert button, typical of Reaper. This is quite uncomfortable, I don't know if I should report it to Cockos, or to you, I even wanted to report it to ReFX, because maybe they broke accessibility or I don't know, but the same thing also happens with Swam Plugins, or iZotope Plugins, for example. What I already saw is not their thing. I don't know if I explain myself.
Could it be fixed from Osara if it was a mistake?
Please help.

**Comment by jcsteh** [comment]
Did you instruct REAPER to pass keyboard input to the plugin?

**Comment by ElCrackLoko** [comment]
@jcsteh If you mean Midi inputs, yes, that's all fine. The problem is NVDA's focus when interacting with a VST3 that contains a window within itself, such as Nexus, Swam Plugins or EzKeys. Hitting F6 in Reaper's effects chain focuses, but pressing Tab once, boom, goodbye to focus within the Plugin. The FX buttons can only be navigated with Control+Tab forward and Control+Shift+Tab back. I don't know how long this has been happening, but it's been a while and I'm not used to working like this, especially with Nexus 4, where from the Plugin itself you can move between the expansions, the banks and the instruments or Presets of the banks. Imagine having to press Control+Shift+Tab to go back or Control+Tab to go forward. When before only Tab and Shift+Tab was all that was good.

**Comment by jcsteh** [comment]
I mean REAPER's "Send all keyboard input to plug-in" option, which ensures that all key presses go to the plugin when the plugin is focused.

**Comment by ScottChesworth** [comment]
Passing keyboard input makes no difference. I reckon it's a JUCE regression.

**Comment by ScottChesworth** [comment]
Oh wait, if you're experiencing this in iZotope plugs, then I guess it's not exclusive to JUCE GUIs. Which iZotope products should I check?

**Comment by ElCrackLoko** [comment]
Hello. If you tell me this, then it means that what happens to us does not happen to you. But yes, I have also tried leaving that option activated, even though I had never had to activate it, I'm talking about before when everything worked well. It's strange, I even tried with previous versions of Reaper without touching anything, just installing to install and nothing, then I reset my Reaper, uninstalled it, installed it, configured it again. I've done so much that I just need to format, and I don't do it because members of the PMA community are experiencing the same thing. I even thought it was Windows 11, but no, there is another colleague who reports the same thing with Windows 10. Or maybe this error only happens to us Spanish speakers? Will it have to do with the language? Wow, I haven't tried Reaper in the original language. I just need that and continue speculating what else it could be.

**Comment by ElCrackLoko** [comment]
Sorry, I talked too much and with iZotope everything works fine. I just tried Nectar and VocalSynth. It's what you say, that thing about Juce GUIs. How do we fix this? Nexus, Swam and EzKeys.

**Comment by leejul** [comment]
I have the same problem with Kontakt 7 which does not react in the same way as Kontakt 6.
With Kontakt 6, F6 and up, in the plugin window.
With Kontakt 7, F6 just doesn't work.
You have to do Tab to the plugin, Space, up arrow and down arrow and there we are in the plugin.
I did some tests with Swam and indeed, it no longer works the same way.
Here the sequence is:
F6, up Arrow and you are in the plugin.
Now you can use Tab or Shift+Tab.
Why the sequence changed, computer mystery.
But no need to search, rather find the sequence and spread it.
Generally it's easy to find.
In very rare cases, you have to bring the mouse into the plugin window and use Tab and Shift+Tab afterwards.

**Comment by ElCrackLoko** [comment]
@Leejul
So you use Kontakt 7? How do you do if you want to change SnapShots? I know that with LBL you can at least change the NKIs, but modern libraries already only carry a couple of NKIs associated with a lot of NKS. Returning to the topic, I am talking about Swam AudioModeling, but in its latest version, 3.7.2. What version of Swam did you use in your test?
About the Juce GUIs, can someone tell me what that is? I'm curious if it was Cockos that moved something or maybe Osara. Because the Plugins, as long as the option is not configured, should not auto-update...

**Comment by leejul** [comment]
My version of Swam is 3.0.1 (4665).
For Kontakt this is not the subject here so I invite you to contact me personally.
reaperaccessible@gmail.com
Thanks.

**Comment by ScottChesworth** [comment]
> About the Juce GUIs, can someone tell me what that is?
> 
JUCE is a development framework that all of the plug-ins exhibiting this issue are built on, apart from Kontakt. Native Instruments are using multiple frameworks throughout the Kontakt 7 Gui at the moment, JUCE isn't anywhere in that equation, so although the issue is similar on the front-end, I'm pretty sure the solution will be different in their case.

**Comment by ScottChesworth** [comment]
Tested Nexus and SWAM instruments latest releases, same Issue with and without OSARA running, so it's not us.
I guess the next step is to try hitting the JUCE folks up about it. I can do that.

@jcsteh , might the NVDA log tell us anything useful? Any thoughts on what I should be looking for?

**Comment by jcsteh** [comment]
Can we double check this is definitely not some issue in a recent build of REAPER? I doubt it, but probably worth a check.

I don't think NVDA is going to be able to tell you anything you don't already know. It doesn't have any visibility into keyboard tab handling or anything like that; that's all handled within the plugin or its UI framework.

**Comment by ScottChesworth** [comment]
I just reproduced this in 6.44 (our minimum supportede version) with and without OSARA again.
While I'm chasing JUCE here, does anyone have access to these plug-ins on Mac to tell us what the situation with the tab order is there? How about a different DAW they can test the tab order in?
Do we know of a free plug-in or instrument where this happens? That would make it easier for more people to check more environments.

**Comment by pitermach** [comment]
Looks like this issue is restricted to Windows. I just did some testing with Nexus, which on my Windows PC was by now very out of date at version 4.5.3, with all the accessibility and tabbing toggles turned on it worked normally and I could tab to everything. Updated to the latest version - 4.13.3, and it started behaving how both of you said. On Mac, again with all the accessibility turned on with the latest version, I can still tab through every control (this is on Sonoma and Reaper 6.82) though on Mac it's better to navigate the UI with VO because it's nicely grouped.

Sadly I didn't have much luck finding a free plugin that exhibits this behavior - the ones I thought of trying either work fine - like the most recent snapshot of surge, or are built with Juce 6 still (like ChowTape)

**Comment by ScottChesworth** [comment]
Thanks, that helps to narrow it down a little more.

**Comment by ElCrackLoko** [comment]
Hello, I'm back here. I break the silence to see if a solution can be found, on Nexus, I use version 4.5.13, which came out in July of this year 2023 and I did not have that problem with the JUCE gui, that is why it seems a bit strange to me that now overnight I have this error with accessibility. UNLESS the GUI has been updated without permission, but it is very strange that only the JUCE GUI is updated. Maybe someone could report to them...

**Comment by ScottChesworth** [comment]
> Maybe someone could report to them...
> 
Already done.

**Comment by ElCrackLoko** [comment]
But doesn't it seem strange to you that with the same version 4.5.13 that didn't cause problems before, now it does? It's very strange, that's why I thought it was Reaper but some people already tried it and said it's not Reaper. Maybe by installing Reaper 6.44 and installing everything from 0 you can try it, as soon as I have a little free time I will do it

**Comment by ScottChesworth** [comment]
Again, already done. See this comment from four days ago:
> I just reproduced this in 6.44 (our minimum supportede version) with and without OSARA.
> 
Seems this isn't being caused by OSARA, so I dunno how much more we can do here.

**Comment by ElCrackLoko** [comment]
Well, then nothing else can be done. Thank you very much anyway, really. I close this then

**Comment by ScottChesworth** [comment]
FYI I'm gonna be at a conference with the JUCE dev team later this month, so I'll keep chasing this and update the thread whenever I find out any news. If you discover any new details, please report those here too.
