### ISSUE TITLE
Track spacers

### ISSUE THREAD

**Issue by mattymc2** [jcsteh/osara#953]
Hey guys.
I know there's loads of development going on at the moment but just thought I'd throw this into the ring. Would there be any value in supporting track spacers in reaper seven? I think it could be a nice way of grouping tracks that doesn't evolve using folders. Sort of like a heading type thing. Going further with this it would be cool to have next and previous spacer commands. kind of like the jump to next heading or previous heading command in a web browser. Keep in mind I haven't actually ever seen or used these spacers yet so not sure if this would be feasible But it struck me as something that could be really helpful navigating huge projects.
Cheers
Matt

**Comment by jcsteh** [comment]
I'm curious as to how this is better or more efficient for screen reader users than folders. Sighted users can skim the screen, but for screen reader users, being able to collapse things is generally going to be more efficient.

That said, if we did want to support this, an open question is how we indicate the presence of a spacer. I don't think you can select spacers, so I don't think up and down arrows are going to be able to stop on them. The best we could do is announce the spacer as part of the announcement when navigating to the first track below it:

> Jamie's crappy vocals spacer, 1 muted lead vocal

We could support next/previous spacer I think though, again moving to the first track below it.

**Comment by jcsteh** [comment]
Wait, can you name spacers?

**Comment by jcsteh** [comment]
I don't think you can.

**Comment by ScottChesworth** [comment]
Spacers don't have names. I'm not seeing an advantage over folders yet here.
