### ISSUE TITLE
Change keyboard shortcut to focus a container's FX list

### ISSUE THREAD

**Issue by leejul** [jcsteh/osara#954]
Since the arrival of containers in Reaper, I think it would be good to think about another design of the menu "View FX parameters for current track/take (depending on focus)".
Jamie has already accessed and fixed all the bugs when we are directly in the FX window.
But, personally, I would use a keyboard shortcut other than F6 which would be dedicated to the container.
This is how I see it:
Shortcut in the FX window:
Shift+Right Arrow - If container is selected, moves focus in its FX list, otherwise states, no container is selected
Shift+Left Arrow - Moves focus to the previous container, otherwise states, you are not in a container.
Should this be a loop, maybe yes, maybe no, personally a loop would be fine for me but some users might find it a bit confusing.
So for these users a stopper would be better for them.
If this is feasible, navigation would be extremely fast in the FX window.
Otherwise for the rest of the work already done in the FX window is very good, it is very responsive.

**Comment by jcsteh** [comment]
For what it's worth, sighted users can't do this either without clicking in the top FX list. Also, I think this would effectively require OSARA to focus the FX list and select a different container anyway, so I don't think it's going to be feasible or particularly efficient. Still, I don't know for certain.

**Comment by jcsteh** [comment]
Just to clarify, when you say shift+leftArrow to move to the previous container, I assume you mean the outer container? That is, if you're in a top level container, shift+leftArrow would take you to the main FX list?

**Comment by jcsteh** [comment]
If you meant outer rather than previous, that's probably more doable. IMO, it's still inconsistent with the way we focus other plugin windows though, which doesn't seem ideal or intuitive to me.

**Comment by jcsteh** [comment]
Got it. That seems feasible to implement. The keystrokes are an open question at this point given the inconsistency this would create between containers and other effects, though.

**Comment by leejul** [comment]
The keystrokes are an open question at this point given the inconsistency this would create between containers and other effects, though.

I don't understand what you mean. The proposed shortcuts are not used as far as I know. But maybe there's something I'm missing.

**Comment by ScottChesworth** [comment]
> The proposed shortcuts are not used as far as I know. But maybe there's something I'm missing.
> 
The keystrokes are available, yes, however we also need to ask whether those keystrokes are intuitive? Everywhere else I can think of in REAPER with the OSARA key map, Shift+Arrows adds to selection, hence those same keystrokes serving a different purpose just in this one scenario seems like a disparity. If I was poking around and trying to find how to move productively, I probably wouldn't think about Shift+Arrows, as it's not a keyboard convention I've encountered anywhere else for moving between groups/sections/structures. That doesn't mean we can't introduce it as a concept, but ideally there needs to be some logic or link back to concepts people are already familiar with. Taking F6 as an example, that was chosen because it's been a long-standing keyboard convention to jump through sections of a GUI on Windows. There's no similar concept around F6 on the Mac, but then, our focus hack doesn't work on Mac anyway, so we didn't worry about that not being a cross platform standard.
Hopefully that explains some of the thinking that goes into choosing keystrokes round these parts. As I said above, it doesn't mean we definitely can't or won't use Shift+Arrows. Explain why those are the most intuitive choices and sure, maybe those will be what gets chosen.

**Comment by leejul** [comment]
Ok, but as for intuitiveness with OSARA...
F5 - Track: Mute/unmute tracks
F6 - Track: Solo/unsolo tracks
F7 - Track: Toggle record arming for current/last touched track
F8 - Track: Cycle track record monitor
I don't see what is intuitive about the keymap proposed by OSARA.
I don't see any other option than to memorize them.
But whatever the shortcut, it's a detail for me.

**Comment by ScottChesworth** [comment]
I don't like those shortcuts either. They were chosen by the developer of ReaAccess, then carried over to OSARA initially for convenience, just to ease the transition. Then there was a period of time where Captain was AWOL, busying himself with a real life disaster. By the time I got back, everyone was familiar with those keystrokes and there were a bunch of people teaching them on courses at the time, so they stayed.

**Comment by leejul** [comment]
Oh, ok, I didn't know the story of OSARA.
But nothing stops you from offering a KeyMap completely redone from scratch.
Users could use the old one which would no longer be supported or the new one.
That's how IT is, people have to get used to it, it evolves over time, conservatism certainly has no place in this field.
Apple did not ask anyone for permission regarding changes to its processors.
With alternative KeyMaps, I think this would be a good opportunity.
This allows for a smooth transition.

**Comment by ScottChesworth** [comment]
> But nothing stops you from offering a KeyMap completely redone from scratch.
> 
Well, it would drastically increase the effort required to support OSARA for an unknown length of time, cut into adoption, cause fragmentation and/or invalidation of resources that I've busted a gut to create. Just a couple of small concerns there...

> conservatism certainly has no place in this field.
> 
Progress is good, but remember, you've seen it yourself that sometimes change can be impactful in all the wrong ways if it's not handled carefully. Have you already forgotten how pissed you were when NI released Kontakt 7, for example?

> With alternative KeyMaps, I think this would be a good opportunity.
> 
It's definitely a good reason to revamp/rethink some stuff around mapping, yep. We'll get into it soon. There are more pressing issues that need to be squared away first though.

**Comment by leejul** [comment]
Yes, indeed, sometimes it can be very frustrating when we lose our accessibility.
But we have changed our strategy in this regard.
Lots of great things for the future.
For KeyMaps, it would be a lot of work but once it's done, it's done for years.

**Comment by jcsteh** [comment]
In REAPER 7.03:

>   + FX containers: improve accessibility for nested containers by allowing left/right arrows in chain list to navigate up/down hierarchy
