### ISSUE TITLE
In the FX container the SWS actions to move the FX up or down do not work

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#956]
Hi the SWS actions to move an FX up or down don't work in the FX container:
SWS/S&M: Move selected FX up in chain for selected tracks
SWS/S&M: Move selected FX down in chain for selected tracks
they don't work in the container's FX chain.
With cut copy and paste everything works.
It's not super important but what's important is that you know.
Maybe Reaper or SWS should do the actions for the FX container.
Greetings!

**Comment by ScottChesworth** [comment]
Those are SWS actions, so you need to request updates on their GitHub: https://github.com/reaper-oss/sws

**Comment by Lo-lo78** [comment]
@ScottChesworth 
Hi I created a new issue on SWS:
https://github.com/reaper-oss/sws/issues/1788
Ciao!

**Comment by Lo-lo78** [comment]
@ScottChesworth 
I also opened this issue for the items:
https://github.com/reaper-oss/sws/issues/1790

**Comment by Lo-lo78** [comment]
I also proposed these actions:
https://github.com/reaper-oss/sws/issues/1794
Ciao!

**Comment by Lo-lo78** [comment]
Here are the two actions to move takes up or down:
https://github.com/Buy-One/REAPER-scripts/commit/1e13abf5c8495b9cf8ca645beed1ec99d1e58b07
https://github.com/Buy-One/REAPER-scripts/commit/e2183c4555894d2447ee41ed27283005abdeb30a

I made two custom actions that contain both SWS and BuyOne.
They don't conflict and I always use the same 2 shortcuts and not four shortcuts.
When I move a plugin in the FX chain of the track the actions to move the plugins in the FX chain of the take do not work and therefore when I move the plugins in the FX chain of the take the FX chain of the track does not work. Perfect!

**Comment by ScottChesworth** [comment]
Nice! We don't bundle scripts with OSARA, but I'll save your suggestion in the Dropbox text tutorials folder.

**Comment by Lo-lo78** [comment]
@ScottChesworth 
For updates to its scripts BuyOne moved me to its repository:
https://github.com/Buy-One/REAPER-scripts/issues/3

https://github.com/Buy-One/REAPER-scripts

**Comment by Lo-lo78** [comment]
Unfortunately I wasn't able to use two shortcuts for the track and the takes with the custom actions.
As was obvious, it moves both the fx chain of the track and the item.
Maybe something can be done with Cycle Actions.
