### ISSUE TITLE
On Windows, speech interrupt when reporting active/bypassed in FX containers makes it difficult to navigate with slower speech rates

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#957]
On Windows, OSARA appends either "active" or "bypassed" to entries in the FX chain list. This seems to be on some sort of timer. When moving through FX within a container (reaper 7.0 or newer), we now have reports that are a number being appended after the expected active/bypassed state. The number "3" is spoken after the first effect in the container, "5" after the second, "7" after the third etc. As both of these reports interrupt speech, when users have NVDA speaking relatively slowly, the name of the selected effect gets interrupted, and the ends of options within the context menu for each effect get obscured, making it difficult to know whether options are checked or unchecked.

To reproduce this, make a container, put some FX inside it, explore the list box and context menu for an effect. Set your speech rate slow, for example Espeak at 30.

If needed, I can make a recording of the UX here. Labelling it P1 as it's really quite difficult to work around.

Thanks in advance for any tightening that can happen, and of course, shout if I can do anything useful from here!

**Comment by jcsteh** [comment]
Oops. That's debugging code I uh... forgot to remove.
