### ISSUE TITLE
Help wanted to debug an SCons error and a question about GitLab for a new contributor

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#958]
@JennyKBrennan has been doing Mac key map stuff whenever we that for quite a while, and wants to get a local environment going on Windows too (a more powerful machine) so she can also start helping with reports for toggle actions etc.
Trying to build on Windows, we get this error from SCons:
> scons: *** Two environments with different actions were specified for the same target: reaper_osara.o
(action 1: windres --include-dir src -i reaper_osara.cpp -o reaper_osara.o)
(action 2: g++ -o reaper_osara.o -c /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /W3 /WX /clang:-Wno-unused-function reaper_osara.cpp)
File "E:\Code\osara\src\archBuild_sconscript", line 135, in <module>
> 
I don't know diddly about troubleshooting SCons beyond clearing its cache, which didn't work.

Also, when we cloned the repo recursively, it wanted her to log in to GitLab. Is that a new requirement that needs to be added to the ReadMe?

Not urgent, just whenever anyone's got a spare minute, ideas would be appreciated. TIA!

**Comment by jcsteh** [comment]
> > scons: *** Two environments with different actions were specified for the same target: reaper_osara.o
> > (action 1: windres --include-dir src -i reaper_osara.cpp -o reaper_osara.o)
> > (action 2: g++ -o reaper_osara.o -c /clang:-std=c++20 /EHsc /clang:-Wno-missing-braces /W3 /WX /clang:-Wno-unused-function reaper_osara.cpp)
> > File "E:\Code\osara\src\archBuild_sconscript", line 135, in

Hmm. Someone else had that issue in #905. My best guess is that SCons can't find Visual Studio for some reason, but I don't know why that would be. What version/edition of Visual Studio does @jennykbrennan have installed?

> Also, when we cloned the repo recursively, it wanted her to log in to GitLab. Is that a new requirement that needs to be added to the ReadMe?

GitLab? That's... bizarre. OSARA doesn't reference any submodules that are hosted on GitLab. Everything is hosted on GitHub, and even there, we don't reference any private repositories or reference via ssh, so it should never require authentication unless you try to push.

**Comment by jcsteh** [comment]
Oh, also, what version of SCons?

**Comment by jcsteh** [comment]
And was SCons installed using `py -3 -m pip install scons` or some other way?

**Comment by ScottChesworth** [comment]
I did pip install scons on her machine yeah.
Jen, when you wake up, do scons --version on a command prompt and paste that in here. Also pop into Control Panel, Programs and Features, let us know the exact version of Visual Studio Build Tools 2022 that you've got installed there.

**Comment by jcsteh** [comment]
Visual Studio Build Tools 2022 is sufficient; the precise minor version number probably isn't going to tell me anything useful. If you did pip install scons, that should be fine. Hmm. Curious.

I'd still like to see the full output from scons --version because it also includes the SCons installation path. I'm wondering whether there's something weird about the Python installation.

**Comment by jennykbrennan** [comment]
Gents
scons --version
        SCons: v4.5.2.120fd4f633e9ef3cafbc0fec35306d7555ffd1db, Tue, 21 Mar 2023 12:11:27 -0400, by bdbaddog on M1DOG2021
        SCons path: ['C:\\Users\\Jenny\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\SCons']

I know less than nothing about this and am surprised that I have had anything running at all. 
With that said: Anything VS rlated entries I find are 
Microsoft Visual Studio Code (User); Publisher: Microsoft Corporation; Installed On: 10/12/2023; Size: 357 MB; Version: 1.83.1  74 of 139
and 
Visual Studio Community 2022; Publisher: Microsoft Corporation; Installed On: 7/28/2022; Version: 17.2.6  126 of 139
No mention of *Build Tools* I'm missing something, I'm sure. Or I'm looking in the wrong place.

**Comment by ScottChesworth** [comment]
Ah that's probably my bad, thought you would've had build tools because that's how I've got my machine configured, but community should also be fine

**Comment by jcsteh** [comment]
Can you please try running scons with the SCONS_MSCOMMON_DEBUG environment variable set? For example:

1. Run cmd.exe to get to a command prompt.
2. Change to the osara source directory where you'd normally run scons.
3. Run this command:
    `set SCONS_MSCOMMON_DEBUG=vs.log`
4. Run scons.

Then, attach the log file this creates (vs.log in this example) here.

**Comment by ScottChesworth** [comment]
Sure, might be good for @Timtam to do that too right? Toni, see the comment above this one.

**Comment by Timtam** [comment]
Yeah, I attached mine. The log doesn't tell me anything useful though.
[vs.log](https://github.com/jcsteh/osara/files/13224858/vs.log)

**Comment by jcsteh** [comment]
Thanks. Looks like Visual Studio's vswhere.exe tool isn't finding Visual Studio, which is rather self-defeating. Can I confirm that you both have all the Visual Studio components installed as specified in the readme; i.e. Desktop Development with C++, etc.? Also, if you run the Visual Studio command prompt, does the cl command run if you just run it with no arguments?

**Comment by Timtam** [comment]
Yes to both. I just worked through the README again, updated VS2022 and made sure that everything is set up as described. Maybe the latest VS2022 isn't properly supported anymore and i'll just have a try with the build tools only.

**Comment by jcsteh** [comment]
Can you please run the following command in a command prompt and provide the output?
`"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -products * -version (17.0,18.0] -prerelease`

**Comment by jcsteh** [comment]
Btw, I'm not drip-feeding these suggestions to be difficult. On the contrary, I'm trying to figure it out as we go, including reading bits of the SCons source code. :)

**Comment by ScottChesworth** [comment]
No logs from Jen posted here yet because we found a problem with her installation of VS Community. Redownloading a bunch of components and will see where that leaves us.

**Comment by jcsteh** [comment]
Thanks Timtam. From that, it looks like you have a preview edition of Visual Studio Community 2022. By default, vswhere.exe doesn't include preview releases unless you use the -preview command line argument and it seems SCons doesn't pass that argument. I guess that makes some sense sometimes, but it's annoying that it's not configurable.

What's curious is that you said you updated Visual Studio, but obviously, it doesn't switch channels when you do that. Maybe there are still preview builds of Visual Studio updates even after the official release?

For now, you can work around this as follows:

1. Locate your SCons directory. scons --version should help.
2. In that directory, open the file Tool\MSCommon\vc.py in a text editor.
3. Find this line, around line 250:
    `        ["-version", "[17.0, 18.0)"],  # default: Enterprise, Professional, Community  (order unpredictable?)`
4. Change it to this:
    `        ["-version", "[17.0, 18.0)", "-preview"],  # default: Enterprise, Professional, Community  (order unpredictable?)`

**Comment by jcsteh** [comment]
@Timtam Urgh, I'm sorry. It should be -prerelease, not -preview. So:
`        ["-version", "[17.0, 18.0)", "-prerelease"],  # default: Enterprise, Professional, Community  (order unpredictable?)`

**Comment by jcsteh** [comment]
@ScottChesworth That was helpful, thanks. Please try again with latest master.

**Comment by ScottChesworth** [comment]
Different but not quite fixed:
> Submodule path 'include/tinygettext': checked out '1d57c99d5ae86155ec61e3dbcd1c9f421069f293'
fatal: No url found for submodule path 'include/tinygettext/external/cmake-modules' in .gitmodules
fatal: Failed to recurse into submodule path 'include/tinygettext'
>

**Comment by jcsteh** [comment]
I'm doing well today aren't I?

**Comment by jcsteh** [comment]
Okay, try now.

**Comment by jennykbrennan** [comment]
Yay. As far as I could tell it works as it should and scons gives me no problems. All is well in the world again. Thanks people.
Now, it remains to be seen if anything useful will come from another Cody pretender. Scott is teaching me everything he knows. It should go... well.Surely. :D

**Comment by Timtam** [comment]
Sorry, forgot to report back: You were right, changing the line made VSwhere find my preview version and the build ran through. I however decided to uninstall everything (including VS Installer because that version was only offering me to install preview versions) and opted to install the full version. Now everything works fine from scratch. Maybe that is something to note in the README though so that we don't run into a similar problem in the future again?
