### ISSUE TITLE
API: osara_outputMessage doesn't interrupt current read message

### ISSUE THREAD

**Issue by mespotine** [jcsteh/osara#961]
I'm currently in the development of my accessible gui-lib and I'm quite far with it. One of the things I try to implement is, that hovering above a ui-element reads out the text of the ui-element the mouse is currently hovering above, just as TTS is doing it on every other app.

This works fine, except of one tiny detail: a previously read message, read by osara_outputMessage(), can not be interrupted with a new message.
Means: all messages need to be read in full before the next one is read. So if I hover quickly over a number of ui-elements, they will be read one after another by Osara. And if the text of a ui-element is longer, it takes some time until all messages of displayed texts are read out and the stack of messages is empty. What I want to do instead is to read out the text of the next ui-element directly, interrupting any previously read out text immediately, as in every other app.

So, I would like to propose a change in how Osara treats the priorities of messages(and I hope, this works technically).

As far as I understood, new messages will be sent with the highest priority in Osara. But since a new message is also the same priority, it cannot "overwrite" the old message, so they will be read one after another.
I propose to do it like this: When a message is sent via osara_outputMessage, Osara sends out first an empty-message of highest priority and then send the actual messages with a priority less than highest.
That would mean, that messages can always be interrupted, since they aren't highest priority anymore. And they will be interrupted by the empty message sent to Osara as highest priority which takes no time to do, since the message is empty.

At least I hope it's possible to send empty messages to the system with highest priority.

I also implemented successfully keyboard-navigation, which works fine with interruptions of the currently read message, since sending keystrokes to the gfx-window seems to interrupt messages as well, so this is working.
But for the hovering of the mouse, I need such a change.

I have tested it under Windows 7, Reaper 7.01, Osara and NVDA 2022.1

**Comment by jcsteh** [comment]
Thanks for your efforts to make your GUI library accessible.

osara_outputMessage does interrupt. Unfortunately, it can only do this on Windows 10 Fall Creators Update or above (where we can use UI Automation notification events) or MacOS. There's nothing we can do to fix this, as it is a limitation of the available APIs in earlier versions of Windows.

**Comment by jcsteh** [comment]
Btw, the reason this works for mouse tracking in other apps is that mouse tracking in those apps is a function of the screen reader itself, so it chooses to interrupt in that code. In contrast, we're relying on other events here which weren't really designed for mouse tracking.

**Comment by mespotine** [comment]
Ah ok.

And my proposed workaround wouldn't work for older Windows-APIs either? I mean, it would be worth a shot...

**Comment by jcsteh** [comment]
The older APIs don't have a way to specify priority. It's just text. The older implementation is actually a total hack: we fudge the name of the focused control.
