### ISSUE TITLE
alt key maps suggestions

### ISSUE THREAD

**Issue by jprykiel** [jcsteh/osara#964]
Hello Jamie.
I don't know what you're up to with alternative key maps, but I just noticed that all upper row keys combined with ctrl alt shift are available for the moment, and quite a few alt upper row keys are free to.
There is still the Windows key to, but I heard its usage was banded, strangely Windows key works well on my machine under Windows 10, and in fact I use it for most of my custom hotkeys as a way of recognizing them.
Cheers,
JPR

**Comment by jcsteh** [comment]
I tend to stay out of the key map and leave that to @ScottChesworth and others. :)

**Comment by ScottChesworth** [comment]
Control+Alt+Shift can't be the modifier combination for switching, instant blocker for folks who don't have the usage of all 10 fingers and pianist dexxterity. I don't love the number row for this either, it's not mnemonic and you wouldn't be able to use that concept to access all layers without supporting multi-press, which is messy.

Dunno what we're doing design-wise yet, but it's not that.

**Comment by jprykiel** [comment]
Sorry @ScottChesworth, I know it's not perfect, but I honestly thought it was a good idea.
I can hold the alt key with my left index and control and shift together with my left middle finger? But I know I'm lucky to have all my fingers and not everyone has. On the other hand, nothing is going to fit everyone's disabilities  , and if we have 16 layers, how then? Is multi-press going to be supported by Osara?
 Numpad keys are also used, F keys to, maybe a keystroke that would bring up a combo list, but that would be a little slower. I'm just trying to think as a user. How about a little brainstorming on RWP?
Cheers,
JPR

**Comment by jcsteh** [comment]
I'm not quite sure what is meant by multi-press here, but if you mean pressing two keys to temporarily switch to a specific section, that's already possible with clever use of the override actions. For example, you could have a key in the main section to temporarily switch to alt-1 and a key in alt-1 to temporarily switch to alt-10.

That said, I don't see a world where we will end up using more than a couple of alt sections in the official key map. It just seems like overkill and it seems like we should leave at least some of these sections for user specific customisation.

Anyway, I'm going to close this to get it off the board, since it's not actionable at the moment. I'm happy for discussion to continue here though.

**Comment by ScottChesworth** [comment]
> nothing is going to fit everyone's disabilities,
> 
That's not a getout clause to roll with an idea knowing it would put barriers in place. I already know of a bunch of people who have struggled with the current key map, so at the very least I want to make sure those struggles are closely examined and accounted for in the next iteration. While it's true that we can't accommodate every person under the sun in one shot, we can improve the amount of thought and make sure we're consulting a wider spread of users during the early stages. Previously, we only had input from a handful of power users and productivity chasers, I'm sure we can do better than that next time.

> if we have 16 layers, how then?
> 
I don't know how yet. There's stuff to be sorted out before OSARA can go all in on layers anyway, providing dynamic feedback now that they're renamable being next on my list of things to figure out. Remember that we ship 11 languages and counting nowadays, so the feedback around switching layers also needs to be translatable.

> Is multi-press going to be supported by Osara?
> 
It already is in a couple of cases, compare single press versus double-tapping Control+Shift+J and Control+Shift+Space.

> How about a little brainstorming on RWP?
> 
Too soon for that IMO, but if you want to start it now, please make sure you're keeping notes and/or stashing replies that contain strong ideas along the way. Those long threads can be a time suck to sift through retroactively.
