### ISSUE TITLE
Ctrl+Shift+Space does not work anymore

### ISSUE THREAD

**Issue by leejul** [jcsteh/osara#966]
The number of tracks is no longer stated from 3 tracks with a LangPack. The only thing that is stated is "to".
Thanks.

**Comment by ScottChesworth** [comment]
Need more detailed repro steps please, ideally in the top comment next time.

**Comment by leejul** [comment]
If I select 3 or more tracks with Shift+Down Arrow or Up Arrow, when pressing Ctrl+Shift+Space to speak the number of tracks selected, NVDA only says the word "jusqu'à" which is equivalent to the word "to" in English.
You have changed the way OSARA speaks selected tracks.
Previously, OSARA spoke all the selected track names.
Now track names are only spoken if 2 tracks are selected.
from 3 or more consecutive tracks, OSARA says track xx to xx.
The bug currently is that NVDA only speaks the word "to" when 3 consecutive track is selected when a LangPack is used.

**Comment by ScottChesworth** [comment]
Gotcha, much better! Thanks for following up.

**Comment by ScottChesworth** [comment]
The English report for selecting three tracks contiguously is "1 through 3". Is this one of our reports that's constructed from fragments? Maybe something isn't properly tagged for translation yet, the numbers?

**Comment by RDMurray** [comment]
this looks like an error in the file `locale\fr_CA.po`:
```
msgid "{start} through {end}"
msgstr "jusqu'à"
```

Which should be 

```
msgid "{start} through {end}"
msgstr "{start} jusqu'à {end}"
```

The text in braces must exist in the translated string. It refers to variables that are replaced by the track information at runtime.

I think it would have to be fixed on Croudin.

**Comment by jcsteh** [comment]
@rdmurray LOL, you and I were both typing pretty much exactly the same reply at the same time. You beat me by 10 seconds.

**Comment by jcsteh** [comment]
Note that the translator comments explain what the variables are for and provide examples:

```
#. Used when reporting a range of tracks. {start} will be
#. replaced with the first track. {end} will be replaced with the last track
#. in the range. For example: "1 drums through 5 piano"
msgid "{start} through {end}"
```

If you can't see those, we should discuss that. How you see them depends on the editor you're using.

**Comment by leejul** [comment]
Is it just me who's having issues with Croudin now?
For quite a while now, there have been many buttons that are no longer labeled.
I must admit that navigating this website is really difficult.
At first everything was perfect, I don't know if it's me who isn't doing things right.
I tried with Firefox and Chrome, same result.

**Comment by leejul** [comment]
It's fixed on Croudin, thanks.

**Comment by jcsteh** [comment]
Urgh. I haven't looked at the Crowdin interface in a while, but if you're saying buttons are now unlabelled that were labelled before, I guess they broke some things for accessibility. That's super annoying.
