### ISSUE TITLE
Add 2 new actions to set the state of surface feedback

### ISSUE THREAD

**Issue by leejul** [jcsteh/osara#979]
Hi guys, 
Happy new year to all OSARA developers.
I would like to take this opportunity to say my annual thank you.
Keep going, you guys are the best.
So, would it be possible to add the following 2 actions, this would be very useful in CSI and for scripting in Reaper.
OSARA: Enable Report changes made via control surfaces
OSARA: Disable Report changes made via control surfaces
Big thanks again.

**Comment by ScottChesworth** [comment]
Which sections would you need these actions to be available in?

**Comment by leejul** [comment]
In the main section.

**Comment by jcsteh** [comment]
If we're going to do this, I wonder whether it's worth adding enable and disable actions for all the OSARA settings. On one hand, that adds a whole bunch of new actions most people will never use. On the other hand, it's a very common pattern in REAPER to have all three actions: enable, disable and toggle. The settings framework should make this fairly easy to implement without any special casing.

**Comment by leejul** [comment]
Personally I don't think it would be useful, it's a lot of work for actions that no one is going to use.
However, I have an action list to offer you if you are interested. If so, I'll make another post.
But thank you very much for adding these 2 actions, it will really advance the CSI project with OSARA.

**Comment by ScottChesworth** [comment]
I reckon do this one seeing as we already know CSI will use it, then we've got boilerplate in place for me or the other rookie to extend to others if anyone wants it done.

**Comment by leejul** [comment]
I feel stupid specifying this detail because you have probably already thought about it but I prefer to mention it just in case.
OSARA must not say anything when the 2 actions are triggered otherwise the 2 actions will be of no use.

**Comment by ScottChesworth** [comment]
That would be a super unusual UX from OSARA though. One solution is we report as all of our other actions usually do, if you want to silence that report, you can call our mute next message action in your script. Its ID is _OSARA_MUTENEXTMESSAGE

**Comment by leejul** [comment]
Yes I know this action, I will try this solution as soon as it is implemented. Great, thanks.
