### ISSUE TITLE
reaper 7: next/previous take no longer announced

### ISSUE THREAD

**Issue by insomnimus** [jcsteh/osara#982]
I've updated reaper to v7 after a few months of not using it. It seems they added comping support, which is great.
Along with that, I've updated Osara,.
However now Osara doesn't report when i switch takes with the action `move comp area to mouse down, or switch items to next take`.

Note, I'm using NVDA 2023.2 and Windows 10. I've not updated Osara keybinds while installing the Osara update, as  I have changes I don't wish to reconfigure.

Is there something I'm missing?

**Comment by ScottChesworth** [comment]
We don't have reporting for the actions around comping yet. Binding these two actions to T and Shift+T on your key map will get the behaviour you're used to from REAPER 6:
Take: Switch items to next take
Take: Switch items to previous take

**Comment by insomnimus** [comment]
Ah, yup this fixed the problem! Thank you for your time - closing as resolved.
