### ISSUE TITLE
Is it possible to insert buttons for ReaXcomp in the OSARA FX Parameters window?

### ISSUE THREAD

**Issue by Lo-lo78** [jcsteh/osara#983]
Hi I'm using ReaXcomp and unfortunately it is not possible to use the buttons conveniently from the plugin interface.
I'm referring to the buttons:
Solo current band button,
Auto makeup gain button,
Feedback detector button,
Program dependent release button.
I think the general gain of ReaXcomp is a Reaper problem. In the past Reaeq did not have gain among the parameters. As for the gain, I think you need to hear what Cockos thinks.
Thanks for everything you do!

**Comment by jcsteh** [comment]
> unfortunately it is not possible to use the buttons conveniently from the plugin interface.

Can you elaborate on this? Do you mean just because you have to tab to get to them or some other reason?

In any case, there's no way to do these things via the API currently. I don't know if Cockos would be willing to do that or not.

**Comment by Lo-lo78** [comment]
Yes, James, it is inconvenient to use ReaXcomp with the button "Solo current band".
When using a multi band it is often customary to solo the band
That's why I thought placing buttons in OSARA's FX parameters window would be faster for working with plugins that have buttons.
Obviously the representation in the OSARA window for the ReaXcomp buttons would simply be on off.
I understand that this cannot be done.
Let's wait what Cockos thinks.
_In my opinion Cockos should start thinking about putting shortcuts on ReaPlugs. This way reaper vst would be super accessible.

**Comment by Lo-lo78** [comment]
It's not important.
