### ISSUE TITLE
The filter for unnamed parameters does not seem to trigger for VST3 plugins

### ISSUE THREAD

**Issue by vick08** [jcsteh/osara#987]
This is a follow-up to issue #887 which was fixed some time ago.
As I started using more and more of VST3 plugins, I noticed that the current filter for unnamed parameters in the "parameter display" dialog does not seem to work.
Is there a limit on the number of parameters that get enumerated?
Because of a huge number of additional parameters in VST3 standard, the actual number is now quite larger. Because of this the dropdown menu gets very sluggish, so excluding unnamed parameters here would be very very useful!

**Comment by jcsteh** [comment]
I can't think of any reason VST3 should be an exception. Are you sure it's a parameter name covered by the list we discussed? In particular, I've noticed that Komplete Kontrol exposes parameters named "-" which isn't in the original list we discussed.

**Comment by vick08** [comment]
Hmmm, if I look at the regex, it seems like it's already scanning for the presence of a single hyphen in unnamed parameters, unless I misread the expression.
The pattern seems to parse just fine in VST plugins but not in VST3I ones.
My test is pretty simple though: I just toggle my punctuation verbosity to "all".

**Comment by jcsteh** [comment]
You're right. Sorry; I thought i hadn't added "-" yet for some reason. And I can confirm that doesn't work here with KK, but I have no idea why yet. Intriguing.

**Comment by jcsteh** [comment]
Aha, I see the problem with KK at least. The empty parameter names aren't a single "-". They take the form "5 -", where 5 is any number. So I guess we need to add that pattern too.

**Comment by jcsteh** [comment]
I fixed this for the above case. If there are others that aren't working for you, I'll need specific examples of the exact parameter names. Thanks.

**Comment by vick08** [comment]
Thanks!
