### ISSUE TITLE
Can't easily open properties for an item or navigate items after selecting an envelope

### ISSUE THREAD

**Issue by jcsteh** [jcsteh/osara#993]
STR:

1. Create a new project containing a single track with two items.
2. Press down arrow to select the track, control+home to go to start, then control+rightArrow to select the first item.
3. Press control+alt+p to show the pan envelope for the item.
4. Press alt+l to select the pan envelope.
5. Press shift+f2 to open the item properties.
    - Observe: Nothing happens.
6. Press control+rightArrow to move to the second item.
    - Observe: Nothing happens.

The reason for this is that once you select an envelope, item commands begin to target automation items. This is necessary and fits with the pattern of context sensitivity seen elsewhere with REAPER + OSARA. Unfortunately, it does make it rather annoying to mess with pitch envelopes, for example, where you sometimes need to change the pitch shift algorithm, etc. in item properties. It also makes it difficult to faff with envelopes across multiple items on a single track.

Here's what I tried next:

7. Press shift+a to select the item under the cursor.
8. Press shift+f2 to open the item properties.
    - Expected: The item properties should open.
    - Actual: Nothing happens.
9. Press control+rightArrow to move to the second item.
    - Expected: OSARA should report the second item.
    - Actual: Nothing happens.

When you press shift+a, that seems to me to be a logical indicator that the user intended to operate on a media item, not an automation item. The question is: does this make sense to everyone else? And would we ever want shift+a to context sensitively focus the automation item under the cursor or something like that if an envelope is selected? Oof.

Without this, you have to bounce to another track and back again, then potentially select the item you were working on to re-focus it, which... really grinds my gears.

@ScottChesworth, what do you think?

**Comment by Lo-lo78** [comment]
@jcsteh 
@ScottChesworth 
👍 
Indeed, when you have complex projects these are small slowdowns that can make you nervous and make the work worse.

**Comment by ScottChesworth** [comment]
When working on track envelopes, hitting hit Shift+A switches fake focus to items. Seems logical to me that it would also do the same when working with other focuses. Sure, I guess technically automation items are still a type of item, but the action we're running doesn't mention automation items specifically so it doesn't feel like a reach to bring the user back from working with those.
Does make me wonder whether we're switching to navigating automation items a bit more readily than is intuitive though.

Is it possible to have multiple fake focus states active at one time? If so, would there be any drawbacks to item commands moving through automation items as they do now but also media items after step 4?

**Comment by jcsteh** [comment]
> would there be any drawbacks to item commands moving through automation items as they do now but also media items after step 4?

I assume you mean they would move through only media items after step 4? The problem with that is that you might select an automation item, then move through some envelope points, then hit shift+f2. That should open properties for the automation item, not the media item. Similarly, item navigation commands should move through automation items. This is why we switch item commands (navigation and properties) to work with automation items as soon as an envelope is selected.

**Comment by jcsteh** [comment]
Oh interesting. It turns out that you actually [can't have automation items on take envelopes at the moment](https://forum.cockos.com/showthread.php?t=237649). Today I learned.
