### ISSUE TITLE
Where do we obtain reaper_plugin.h and reaper_plugin_functions.h files from?

### ISSUE THREAD

**Issue by ScottChesworth** [jcsteh/osara#995]
I'm working on a set of OSARA actions to adjust track volume in 1dB increments, idea being to have those working on the master track, which the current SWS actions we use do not. But, the setTrackUIVolume API I want to use was introduced in REAPER 6.71, which means a version bump. I don't know how to obtain the h files for that version, and update them in the OSARA repo.

Any advice appreciated.

CC @Timtam who is helping me when I inevitably get confused/stuck/upset.

**Comment by jcsteh** [comment]
reaper_plugin.h is very rarely updated. You get that from the REAPER SDK, but the version we have has some extra stuff in it taken from SWS and other places, so I wouldn't replace that one. I doubt there's anything you're missing there.

reaper_plugin_functions.h should be generated by REAPER itself using the `[developer] Write C++ API functions header` action. It's okay to just get this from the latest version of REAPER. It won't push us to REAPER 7+ unless you use a function which is only available in REAPER 7+.

**Comment by ScottChesworth** [comment]
Aha thanks! The action was what I couldn't find. Think I can get this done now.
