### ISSUE TITLE
MIDI editor: Change hotkey for dotted grid

### ISSUE THREAD

**Issue by MatejGolian** [jcsteh/osara#996]
Currently . is mapped to action 41005 - Set grid type to dotted. If I'm not mistaken however, there currently isn't any shortcut for setting the grid back to straight notes. So we should either map a shortcut to Grid: Set grid type to straight, or remap the . key to SWS/NF: Toggle dotted grid. I would personally prefer the second option, but either solution is fine.

**Comment by MatejGolian** [comment]
Thanks in advance. 🙂

**Comment by RDMurray** [comment]
The grid returns to straight if you set it with any of the "set grid size to ..." actions, so I haven't found this to be a problem in practice.

On a similar note, the action "Set length for next inserted note: dotted preserving division length" isn't assigned. I suggest Control+. for consistency with the other note length actions.

It would also be nice to have "Grid: Set grid type to triplet" and "Set length for next inserted note: triplet preserving division length" for completeness. Not sure about shortcuts for these, T and Control+T would make sense but T is already taken by "transpose notes..."

**Comment by ScottChesworth** [comment]
> It would also be nice to have "Grid: Set grid type to triplet" and "Set length for next inserted note: triplet preserving division length" for completeness.
>
Control+Shift+T and Control+T respectively for those? It's in line with the grid assignments from Main section.

**Comment by ScottChesworth** [comment]
Just curious, who here sets the grid with Control+Shift+Numbers carrying it over from Main, and who switches to unmodified numbers when they're in the MIDI Editor? That amount of duplication seems insane to me.

**Comment by MatejGolian** [comment]
I personally always use the modifier variants.
If we're going to use Control+Period for "Set length for next inserted note: dotted preserving division length", IMO it would make more sense to use Control+Shift+Period when setting the grid to dotted instead of just Period on its own.

**Comment by ScottChesworth** [comment]
Went with stock REAPER actions because had a brain block on how to get those SWS toggles talking in the MIDI Editor. As Robbie says, the grid type and length revert when you change them anyway, hopefully that's good enough for the time being. I want to rethink some of the grid-based mapping at some point soon anyways, it's taking up an insane amount of space.
